(** Generated by [scripts/generate_ckpath_certificates.py].
    Only the block output is transparent.  Selected base clauses,
    producer imports, replay records, and the transient database
    all remain underneath the opaque soundness theorem. *)

From Stdlib Require Import List.
From Digraph Require Import ckpath_cnf ckpath_drup_microblock ckpath_cert_k7_c12_low3_reduction ckpath_cert_k7_c12_low3_mask02_block00 ckpath_cert_k7_c12_low3_mask02_block01 ckpath_cert_k7_c12_low3_mask02_block02 ckpath_cert_k7_c12_low3_mask02_block03 ckpath_cert_k7_c12_low3_mask02_block04 ckpath_cert_k7_c12_low3_mask02_block07 ckpath_cert_k7_c12_low3_mask02_block08 ckpath_cert_k7_c12_low3_mask02_block11 ckpath_cert_k7_c12_low3_mask02_block12 ckpath_cert_k7_c12_low3_mask02_block13 ckpath_cert_k7_c12_low3_mask02_block14 ckpath_cert_k7_c12_low3_mask02_block15 ckpath_cert_k7_c12_low3_mask02_block16.
Import ListNotations.
Set Warnings "-abstract-large-number".

(** Original retained additions [425, 450); 272 selected base clauses and 43 imported consequences from 13 producer blocks. *)
Definition c12_k7_low3_mask02_block17_output : cnf :=
  [
  [(31,false);(117,true);(126,false);(139,true)];
  [(114,true);(117,true);(111,true);(139,true);(135,false)];
  [(112,false);(26,true);(31,true);(138,false);(135,false)];
  [(117,true);(126,false);(139,true);(135,false)];
  [(113,false);(114,false);(126,false);(139,true);(135,false)];
  [(114,false);(126,false);(139,true);(135,false)];
  [(112,true);(64,true);(56,true);(111,true);(114,true);(139,true)];
  [(126,false);(139,true);(135,false)];
  [(112,false);(139,true);(135,false)];
  [(102,true);(110,true);(100,true);(139,true);(135,false)];
  [(110,true);(100,true);(139,true);(135,false)];
  [(123,true);(131,true);(139,true);(135,false)];
  [(110,false);(139,true);(135,false)];
  [(139,true);(135,false)];
  [(75,true);(126,true);(123,true);(135,false)];
  [(75,false);(142,false);(110,true);(135,false)];
  [(75,true);(131,true);(123,true);(135,false)];
  [(75,false);(123,true);(110,true);(135,false)];
  [(26,true);(31,true);(142,false);(126,false);(75,true);(135,false)];
  [(26,false);(142,false);(100,true);(75,true);(67,true);(110,true);(139,false)];
  [(142,false);(123,true);(110,true);(135,false)];
  [(123,true);(110,true);(135,false)];
  [(142,true);(22,true);(135,false)];
  [(110,true);(135,false)];
  [(140,true);(123,false);(135,false)]
].

Theorem c12_k7_low3_mask02_block17_sound :
  forall rho, satisfies_cnf rho (c12_k7_low3_instance [true; false; false; true; false; false; false; false; true; false; false; false]) ->
    satisfies_cnf rho c12_k7_low3_mask02_block17_output.
Proof.
intros rho Hbase.
pose (select_cnf c12_k7_low3_mask02_block00_output [0;1;2;3;4;5;6;7;8;9;10;11] : cnf)
  as imported_from_block00.
assert (Himported_from_block00 :
  satisfies_cnf rho imported_from_block00).
{
  unfold imported_from_block00.
  apply (satisfies_cnf_select rho c12_k7_low3_mask02_block00_output [0;1;2;3;4;5;6;7;8;9;10;11]).
  - exact (c12_k7_low3_mask02_block00_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask02_block01_output [17] : cnf)
  as imported_from_block01.
assert (Himported_from_block01 :
  satisfies_cnf rho imported_from_block01).
{
  unfold imported_from_block01.
  apply (satisfies_cnf_select rho c12_k7_low3_mask02_block01_output [17]).
  - exact (c12_k7_low3_mask02_block01_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask02_block02_output [7] : cnf)
  as imported_from_block02.
assert (Himported_from_block02 :
  satisfies_cnf rho imported_from_block02).
{
  unfold imported_from_block02.
  apply (satisfies_cnf_select rho c12_k7_low3_mask02_block02_output [7]).
  - exact (c12_k7_low3_mask02_block02_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask02_block03_output [15;9] : cnf)
  as imported_from_block03.
assert (Himported_from_block03 :
  satisfies_cnf rho imported_from_block03).
{
  unfold imported_from_block03.
  apply (satisfies_cnf_select rho c12_k7_low3_mask02_block03_output [15;9]).
  - exact (c12_k7_low3_mask02_block03_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask02_block04_output [9;24] : cnf)
  as imported_from_block04.
assert (Himported_from_block04 :
  satisfies_cnf rho imported_from_block04).
{
  unfold imported_from_block04.
  apply (satisfies_cnf_select rho c12_k7_low3_mask02_block04_output [9;24]).
  - exact (c12_k7_low3_mask02_block04_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask02_block07_output [14] : cnf)
  as imported_from_block07.
assert (Himported_from_block07 :
  satisfies_cnf rho imported_from_block07).
{
  unfold imported_from_block07.
  apply (satisfies_cnf_select rho c12_k7_low3_mask02_block07_output [14]).
  - exact (c12_k7_low3_mask02_block07_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask02_block08_output [12;15] : cnf)
  as imported_from_block08.
assert (Himported_from_block08 :
  satisfies_cnf rho imported_from_block08).
{
  unfold imported_from_block08.
  apply (satisfies_cnf_select rho c12_k7_low3_mask02_block08_output [12;15]).
  - exact (c12_k7_low3_mask02_block08_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask02_block11_output [1] : cnf)
  as imported_from_block11.
assert (Himported_from_block11 :
  satisfies_cnf rho imported_from_block11).
{
  unfold imported_from_block11.
  apply (satisfies_cnf_select rho c12_k7_low3_mask02_block11_output [1]).
  - exact (c12_k7_low3_mask02_block11_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask02_block12_output [7] : cnf)
  as imported_from_block12.
assert (Himported_from_block12 :
  satisfies_cnf rho imported_from_block12).
{
  unfold imported_from_block12.
  apply (satisfies_cnf_select rho c12_k7_low3_mask02_block12_output [7]).
  - exact (c12_k7_low3_mask02_block12_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask02_block13_output [6] : cnf)
  as imported_from_block13.
assert (Himported_from_block13 :
  satisfies_cnf rho imported_from_block13).
{
  unfold imported_from_block13.
  apply (satisfies_cnf_select rho c12_k7_low3_mask02_block13_output [6]).
  - exact (c12_k7_low3_mask02_block13_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask02_block14_output [4;7;22;12;14;20] : cnf)
  as imported_from_block14.
assert (Himported_from_block14 :
  satisfies_cnf rho imported_from_block14).
{
  unfold imported_from_block14.
  apply (satisfies_cnf_select rho c12_k7_low3_mask02_block14_output [4;7;22;12;14;20]).
  - exact (c12_k7_low3_mask02_block14_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask02_block15_output [14;5;19;15;18;23] : cnf)
  as imported_from_block15.
assert (Himported_from_block15 :
  satisfies_cnf rho imported_from_block15).
{
  unfold imported_from_block15.
  apply (satisfies_cnf_select rho c12_k7_low3_mask02_block15_output [14;5;19;15;18;23]).
  - exact (c12_k7_low3_mask02_block15_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask02_block16_output [16;14;11;19;24;22;20] : cnf)
  as imported_from_block16.
assert (Himported_from_block16 :
  satisfies_cnf rho imported_from_block16).
{
  unfold imported_from_block16.
  apply (satisfies_cnf_select rho c12_k7_low3_mask02_block16_output [16;14;11;19;24;22;20]).
  - exact (c12_k7_low3_mask02_block16_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (concat [imported_from_block00;imported_from_block01;imported_from_block02;imported_from_block03;imported_from_block04;imported_from_block07;imported_from_block08;imported_from_block11;imported_from_block12;imported_from_block13;imported_from_block14;imported_from_block15;imported_from_block16] : cnf) as imported.
assert (Himported : satisfies_cnf rho imported).
{
  unfold imported.
  apply satisfies_cnf_concat_intro.
  constructor.
  { exact Himported_from_block00. }
  constructor.
  { exact Himported_from_block01. }
  constructor.
  { exact Himported_from_block02. }
  constructor.
  { exact Himported_from_block03. }
  constructor.
  { exact Himported_from_block04. }
  constructor.
  { exact Himported_from_block07. }
  constructor.
  { exact Himported_from_block08. }
  constructor.
  { exact Himported_from_block11. }
  constructor.
  { exact Himported_from_block12. }
  constructor.
  { exact Himported_from_block13. }
  constructor.
  { exact Himported_from_block14. }
  constructor.
  { exact Himported_from_block15. }
  constructor.
  { exact Himported_from_block16. }
  constructor.
}
pose (
  [66;67;68;69;70;71;72;73;74;75;76;77;27;44;429;435;415;295;169;434;433;4157;1802;3166;3167;4155;1787;4153;1062;4152;3172;4159;3158;1811;4158;3149;1807;3553;3536;3556;3521;3557;3550;3189;3211;3212;3210;3213;3214;49;2128;28;3157;1813;58;3162;2762;19;1086;1088;1064;1077;1812;3156;1055;61;3163;43;3159;1434;1484;1503;1505;1500;1494;1;1065;23;1058;26;1061;3182;1063;25;1060;3181;24;3180;1059;2251;2254;2245;2215;36;1814;3516;3528;3531;3532;1806;1801;1786;2825;2881;2916;2911;2846;54;3161;1483;1433;1493;1502;1499;2164;2149;2161;2158;2165;2154;2794;2803;2799;2806;20;2810;2809;3515;3514;3518;3517;2256;2201;3520;3513;3519;3522;3523;2199;2196;2180;2190;18;1076;13;1048;3173;1804;1789;1816;1809;1090;1087;1078;1089;2826;2820;2796;2816;2823;2175;2178;2171;2181;2151;3218;3194;3221;3224;3223;1085;35;1810;1785;1800;1054;3147;1808;48;57;3153;3148;53;3176;3186;3170;55;3169;3208;3239;3244;3876;3844;3873;3878;3859;3879;64;1815;3164;3525;3524;3526;3527;8;3146;3279;3314;3313;3299;3309;4156;1793;1792;1080;3150;1795;1082;1794;3851;3882;3888;3866;3887;29;3165;50;62;3171;37;1817;59;2141;52;1791;2503;2473;1079;3188;173;419;440;2114;3089;2513;2519;2488;2179;22;1798;2510;2493;2514;2478;2507;3199;3233;3234;3228;3231;1797;1081;177;439;423;445;446;1083;2482;441;2489;2485] : list nat) as base_ids.
pose ([
  ([60;233;250;277],[0;1;2;3;4;5;6;7;8;9;10;11;272;273;274;275;276;277;278;279;280;281;282;283;288;296;297;12;13;14;15;16;17;18;19;20;21;22;23;24;25;26;27;28;29;30;31;32;33;34;35;36;37;38;39;40;41;42;43;44;45;46;47;48;49;50;51;52;53;54;55;56;57;58;59]);
  ([227;233;221;277;268],[0;1;2;3;4;5;6;7;8;9;10;11;272;273;274;275;276;277;278;279;280;281;282;283;288;296;297;14;15;16;18;19;20;27;21;25;29;31;37;38;39;40;41;42;34;49;51;52;53;54;55;57;58;59;60;61;62;63;64;65;66;67;68;285;286;302]);
  ([222;51;61;274;268],[0;1;2;3;4;5;6;7;8;9;10;11;272;273;274;275;276;277;278;279;280;281;282;283;288;296;297;57;60;61;69;70;71;25;27;72;73;74;75;76;77;78;79;80;81;51;82;83;84;85;86;87;88;89;90;91;92]);
  ([233;250;277;268],[0;1;2;3;4;5;6;7;8;9;10;11;272;273;274;275;276;277;278;279;280;281;282;283;288;296;297;13;315;14;15;16;18;19;20;27;21;22;24;25;26;29;31;33;34;36;316;93;94;317;308;95;96;97;98;67;99;100;101;51;52;53;49;54;55;65;66;102;103;104;105;106]);
  ([224;226;250;277;268],[0;1;2;3;4;5;6;7;8;9;10;11;272;273;274;275;276;277;278;279;280;281;282;283;288;296;297;51;93;13;318;14;15;16;18;19;20;27;107;108;21;22;24;25;26;29;31;33;52;53;32;94;34;36;285;286;302;284;317;109;110;111;112;72;113;114;115;116;117;303;118;119;120;121;122;123;124;125;126;77]);
  ([226;250;277;268],[0;1;2;3;4;5;6;7;8;9;10;11;272;273;274;275;276;277;278;279;280;281;282;283;288;296;297;93;319;13;318;14;15;16;18;19;20;27;107;108;21;22;24;25;26;29;31;33;32;94;34;36;317;127;128;129;130;49;67;99;100;101;65;66;54;55;131;132]);
  ([223;127;111;221;227;277],[0;1;2;3;4;5;6;7;8;9;10;11;272;273;274;275;276;277;278;279;280;281;282;283;288;296;297;14;15;16;17;18;19;20;21;25;27;316;29;31;133;134;135;136;137;34;107;49;51;52;53;67;68;99;100;101;54;55;65;66;131;132]);
  ([250;277;268],[0;1;2;3;4;5;6;7;8;9;10;11;272;273;274;275;276;277;278;279;280;281;282;283;288;296;297;13;318;320;14;15;16;18;19;20;27;107;108;21;22;24;25;26;29;31;33;34;36;321;57;60;61;58;64;62;63;59;287;132;138;139;140;141;118;302;298;299;142;143]);
  ([222;277;268],[0;1;2;3;4;5;6;7;8;9;10;11;272;273;274;275;276;277;278;279;280;281;282;283;288;296;297;57;60;14;15;16;18;19;20;322;27;21;58;25;61;29;64;31;62;63;34;59;302;298;299;144;145;146;147;148;149;53;150;309;151;152;76;153;154;155;156;102;157;158;159;140;160;161;162;163;164;48;165;166;167;168;169;54;170]);
  ([203;219;199;277;268],[0;1;2;3;4;5;6;7;8;9;10;11;272;273;274;275;276;277;278;279;280;281;282;283;288;296;297;14;15;16;18;19;20;322;323;27;21;25;29;31;34;48;165;166;167;168;169;171;172;35;173;174;142;175;82;176;177;178;179;180;310;109;110;111;112;72;113;124;151;152;76]);
  ([219;199;277;268],[0;1;2;3;4;5;6;7;8;9;10;11;272;273;274;275;276;277;278;279;280;281;282;283;288;296;297;324;14;15;16;18;19;20;322;323;27;12;181;150;21;25;29;31;34;302;285;286;124;309;294;182;183;184;85;185;55;180;291;186;187;188;189;190]);
  ([245;261;277;268],[0;1;2;3;4;5;6;7;8;9;10;11;272;273;274;275;276;277;278;279;280;281;282;283;288;296;297;14;15;16;18;19;20;322;323;27;21;309;191;192;193;194;195;196;25;29;31;34;295;182;183;298;184;85;185]);
  ([218;277;268],[0;1;2;3;4;5;6;7;8;9;10;11;272;273;274;275;276;277;278;279;280;281;282;283;288;296;297;197;14;15;16;18;19;20;322;323;27;326;21;25;29;31;34;99;124;151;198;199;152;76;153;154;200;201;202;203;302;298;299;135;128;107;108;49;50;54;56;65;66;144;145;146;147;148;149;53]);
  ([277;268],[0;1;2;3;4;5;6;7;8;9;10;11;272;273;274;275;276;277;278;279;280;281;282;283;288;296;297;14;15;16;18;19;20;322;323;327;27;21;25;29;31;34;325;204;154;205;326]);
  ([149;251;245;268],[0;1;2;3;4;5;6;7;8;9;10;11;272;273;274;275;276;277;278;279;280;281;282;283;288;296;297;311;309]);
  ([148;282;219;268],[0;1;2;3;4;5;6;7;8;9;10;11;272;273;274;275;276;277;278;279;280;281;282;283;288;296;297;182;85;180;34;27;328;206;207;208;209;210;190;211;212;213;214;142;82;176;177;178;215;12;150;172;154;36;205;284;109;111;112;72;113]);
  ([149;261;245;268],[0;1;2;3;4;5;6;7;8;9;10;11;272;273;274;275;276;277;278;279;280;281;282;283;288;296;297;311;329;326;27;13;24;216;211;312;186;217;218;219;220;221;222;223;224;149;225;226;227;228;229;230;23;231;72;74;70;71;69;73;313;51;82;86;87;88;77;78;232;79;80;75;83;84;233;234;304;300;235;236]);
  ([148;245;219;268],[0;1;2;3;4;5;6;7;8;9;10;11;272;273;274;275;276;277;278;279;280;281;282;283;288;296;297;182;292;85;180;330]);
  ([51;61;282;250;149;268],[0;1;2;3;4;5;6;7;8;9;10;11;272;273;274;275;276;277;278;279;280;281;282;283;288;296;297;34;36;13;322;216;311;27;211;312;24;186;217;218;313;233;237;234;238;289;239;240;241;29;25;26;31;33;200;201;202;203;293;135;128;107;108;49;242;54;243;65;77;78;93;51;52;53;244;245;246;235;114;247]);
  ([50;282;199;149;133;219;276],[0;1;2;3;4;5;6;7;8;9;10;11;272;273;274;275;276;277;278;279;280;281;282;283;288;296;297;248;249;172;34;211;250;251;252;244;253;254;255;256;257;48;258;259;233;237;234;238;86;260;186;217;218;107;261]);
  ([282;245;219;268],[0;1;2;3;4;5;6;7;8;9;10;11;272;273;274;275;276;277;278;279;280;281;282;283;288;296;297;34;330;331;329;27;328;311;312;205;13;216;211;24;186;217;218;334;333;313;12;28;23;35;233;237;234;238;48]);
  ([245;219;268],[0;1;2;3;4;5;6;7;8;9;10;11;272;273;274;275;276;277;278;279;280;281;282;283;288;296;297;332;331;329;335;27;328;311;312;13;216;262;263;264;265;305;306;211;24;186;217;218;29;307]);
  ([283;43;268],[0;1;2;3;4;5;6;7;8;9;10;11;272;273;274;275;276;277;278;279;280;281;282;283;288;296;297;262;20;266;263;264;265;305]);
  ([219;268],[0;1;2;3;4;5;6;7;8;9;10;11;272;273;274;275;276;277;278;279;280;281;282;283;288;296;297;336;27;328;124;76;267;211;337;34;330;154;311;312;334;198;199;186;217;218;313;233;237;234;238;289;239;240;241;29;299;25;153;31;314;200;201;202;203;246;253;236;268;135;128;107]);
  ([279;244;268],[0;1;2;3;4;5;6;7;8;9;10;11;272;273;274;275;276;277;278;279;280;281;282;283;288;296;297;269;239;14;240;241;263;124;76;267;27;338;198;199;29;299;211;25;153;31;151;34;154;301;197;99;59;246;270;253;236;271;268;290;135;128;200;202;203;107])
] : list (list nat * list nat)) as records.
assert (Hcheck :
  check_selected_microblock (c12_k7_low3_instance [true; false; false; true; false; false; false; false; true; false; false; false]) base_ids
    imported records c12_k7_low3_mask02_block17_output = true).
{ vm_compute. reflexivity. }
exact (check_selected_microblock_sound
  (c12_k7_low3_instance [true; false; false; true; false; false; false; false; true; false; false; false]) base_ids imported records c12_k7_low3_mask02_block17_output
  Hcheck rho Hbase Himported).
Qed.
