(** Generated by [scripts/generate_ckpath_certificates.py].
    Only the block output is transparent.  Selected base clauses,
    producer imports, replay records, and the transient database
    all remain underneath the opaque soundness theorem. *)

From Stdlib Require Import List.
From Digraph Require Import ckpath_cnf ckpath_drup_microblock ckpath_cert_k7_c12_low3_reduction ckpath_cert_k7_c12_low3_mask02_block00 ckpath_cert_k7_c12_low3_mask02_block01 ckpath_cert_k7_c12_low3_mask02_block02 ckpath_cert_k7_c12_low3_mask02_block03 ckpath_cert_k7_c12_low3_mask02_block04 ckpath_cert_k7_c12_low3_mask02_block05 ckpath_cert_k7_c12_low3_mask02_block06 ckpath_cert_k7_c12_low3_mask02_block07 ckpath_cert_k7_c12_low3_mask02_block08 ckpath_cert_k7_c12_low3_mask02_block09 ckpath_cert_k7_c12_low3_mask02_block10 ckpath_cert_k7_c12_low3_mask02_block11 ckpath_cert_k7_c12_low3_mask02_block12.
Import ListNotations.
Set Warnings "-abstract-large-number".

(** Original retained additions [325, 350); 329 selected base clauses and 65 imported consequences from 13 producer blocks. *)
Definition c12_k7_low3_mask02_block13_output : cnf :=
  [
  [(126,false);(134,false);(123,false);(26,true);(53,true);(137,false)];
  [(139,false);(123,false);(137,false)];
  [(123,false);(140,true);(53,true);(137,false)];
  [(126,false);(143,false);(138,false);(26,true);(53,true);(137,false)];
  [(46,false);(138,false);(134,false);(126,true);(144,false);(26,true);(123,true);(142,false);(135,false)];
  [(31,true);(27,true);(138,false);(126,true);(144,false);(26,true);(123,true);(140,true);(135,false)];
  [(31,false);(126,true);(144,false);(123,true);(142,false)];
  [(125,true);(138,false);(58,true);(134,false);(126,true);(144,false);(123,true)];
  [(124,false);(64,true);(143,false);(138,false);(58,true);(134,false);(31,true);(144,false);(26,true);(135,false)];
  [(64,true);(138,false);(134,false);(58,true);(126,true);(143,false);(144,false);(123,true);(26,true);(142,false);(135,false)];
  [(139,true);(144,false);(140,true);(53,true);(137,false)];
  [(144,false);(140,true);(53,true);(137,false)];
  [(140,true);(53,true);(137,false)];
  [(117,true);(112,true);(115,true);(143,false);(134,false);(138,false);(140,false);(82,true)];
  [(15,true);(112,true);(115,true);(144,true);(53,true);(137,false)];
  [(112,true);(115,true);(144,true);(53,true);(137,false)];
  [(15,false);(55,true);(53,true);(137,false)];
  [(112,false);(134,false);(53,true);(137,false)];
  [(144,true);(53,true);(137,false)];
  [(115,false);(55,true);(53,true);(137,false)];
  [(79,false);(55,true);(53,true);(137,false)];
  [(55,true);(53,true);(137,false)];
  [(26,true);(86,false);(53,true);(137,false)];
  [(86,false);(53,true);(137,false)];
  [(26,false);(53,true);(137,false)]
].

Theorem c12_k7_low3_mask02_block13_sound :
  forall rho, satisfies_cnf rho (c12_k7_low3_instance [true; false; false; true; false; false; false; false; true; false; false; false]) ->
    satisfies_cnf rho c12_k7_low3_mask02_block13_output.
Proof.
intros rho Hbase.
pose (select_cnf c12_k7_low3_mask02_block00_output [0;1;2;3;4;5;6;7;8;9;10;11;13] : cnf)
  as imported_from_block00.
assert (Himported_from_block00 :
  satisfies_cnf rho imported_from_block00).
{
  unfold imported_from_block00.
  apply (satisfies_cnf_select rho c12_k7_low3_mask02_block00_output [0;1;2;3;4;5;6;7;8;9;10;11;13]).
  - exact (c12_k7_low3_mask02_block00_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask02_block01_output [18] : cnf)
  as imported_from_block01.
assert (Himported_from_block01 :
  satisfies_cnf rho imported_from_block01).
{
  unfold imported_from_block01.
  apply (satisfies_cnf_select rho c12_k7_low3_mask02_block01_output [18]).
  - exact (c12_k7_low3_mask02_block01_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask02_block02_output [12;14;7] : cnf)
  as imported_from_block02.
assert (Himported_from_block02 :
  satisfies_cnf rho imported_from_block02).
{
  unfold imported_from_block02.
  apply (satisfies_cnf_select rho c12_k7_low3_mask02_block02_output [12;14;7]).
  - exact (c12_k7_low3_mask02_block02_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask02_block03_output [9;15] : cnf)
  as imported_from_block03.
assert (Himported_from_block03 :
  satisfies_cnf rho imported_from_block03).
{
  unfold imported_from_block03.
  apply (satisfies_cnf_select rho c12_k7_low3_mask02_block03_output [9;15]).
  - exact (c12_k7_low3_mask02_block03_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask02_block04_output [9;12;15;17;21;16;24] : cnf)
  as imported_from_block04.
assert (Himported_from_block04 :
  satisfies_cnf rho imported_from_block04).
{
  unfold imported_from_block04.
  apply (satisfies_cnf_select rho c12_k7_low3_mask02_block04_output [9;12;15;17;21;16;24]).
  - exact (c12_k7_low3_mask02_block04_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask02_block05_output [4;8;14;7;6] : cnf)
  as imported_from_block05.
assert (Himported_from_block05 :
  satisfies_cnf rho imported_from_block05).
{
  unfold imported_from_block05.
  apply (satisfies_cnf_select rho c12_k7_low3_mask02_block05_output [4;8;14;7;6]).
  - exact (c12_k7_low3_mask02_block05_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask02_block06_output [8;11] : cnf)
  as imported_from_block06.
assert (Himported_from_block06 :
  satisfies_cnf rho imported_from_block06).
{
  unfold imported_from_block06.
  apply (satisfies_cnf_select rho c12_k7_low3_mask02_block06_output [8;11]).
  - exact (c12_k7_low3_mask02_block06_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask02_block07_output [2;24;6] : cnf)
  as imported_from_block07.
assert (Himported_from_block07 :
  satisfies_cnf rho imported_from_block07).
{
  unfold imported_from_block07.
  apply (satisfies_cnf_select rho c12_k7_low3_mask02_block07_output [2;24;6]).
  - exact (c12_k7_low3_mask02_block07_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask02_block08_output [11;24;16] : cnf)
  as imported_from_block08.
assert (Himported_from_block08 :
  satisfies_cnf rho imported_from_block08).
{
  unfold imported_from_block08.
  apply (satisfies_cnf_select rho c12_k7_low3_mask02_block08_output [11;24;16]).
  - exact (c12_k7_low3_mask02_block08_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask02_block09_output [11;8] : cnf)
  as imported_from_block09.
assert (Himported_from_block09 :
  satisfies_cnf rho imported_from_block09).
{
  unfold imported_from_block09.
  apply (satisfies_cnf_select rho c12_k7_low3_mask02_block09_output [11;8]).
  - exact (c12_k7_low3_mask02_block09_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask02_block10_output [23] : cnf)
  as imported_from_block10.
assert (Himported_from_block10 :
  satisfies_cnf rho imported_from_block10).
{
  unfold imported_from_block10.
  apply (satisfies_cnf_select rho c12_k7_low3_mask02_block10_output [23]).
  - exact (c12_k7_low3_mask02_block10_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask02_block11_output [11;22;21;23;16;8;7;4] : cnf)
  as imported_from_block11.
assert (Himported_from_block11 :
  satisfies_cnf rho imported_from_block11).
{
  unfold imported_from_block11.
  apply (satisfies_cnf_select rho c12_k7_low3_mask02_block11_output [11;22;21;23;16;8;7;4]).
  - exact (c12_k7_low3_mask02_block11_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask02_block12_output [20;8;14;23;6;18;4;5;21;24;9;19;16;10;15] : cnf)
  as imported_from_block12.
assert (Himported_from_block12 :
  satisfies_cnf rho imported_from_block12).
{
  unfold imported_from_block12.
  apply (satisfies_cnf_select rho c12_k7_low3_mask02_block12_output [20;8;14;23;6;18;4;5;21;24;9;19;16;10;15]).
  - exact (c12_k7_low3_mask02_block12_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (concat [imported_from_block00;imported_from_block01;imported_from_block02;imported_from_block03;imported_from_block04;imported_from_block05;imported_from_block06;imported_from_block07;imported_from_block08;imported_from_block09;imported_from_block10;imported_from_block11;imported_from_block12] : cnf) as imported.
assert (Himported : satisfies_cnf rho imported).
{
  unfold imported.
  apply satisfies_cnf_concat_intro.
  constructor.
  { exact Himported_from_block00. }
  constructor.
  { exact Himported_from_block01. }
  constructor.
  { exact Himported_from_block02. }
  constructor.
  { exact Himported_from_block03. }
  constructor.
  { exact Himported_from_block04. }
  constructor.
  { exact Himported_from_block05. }
  constructor.
  { exact Himported_from_block06. }
  constructor.
  { exact Himported_from_block07. }
  constructor.
  { exact Himported_from_block08. }
  constructor.
  { exact Himported_from_block09. }
  constructor.
  { exact Himported_from_block10. }
  constructor.
  { exact Himported_from_block11. }
  constructor.
  { exact Himported_from_block12. }
  constructor.
}
pose (
  [66;67;68;69;70;71;72;73;74;75;76;77;44;1778;4152;20;4154;1863;1838;1872;1874;40;1067;1773;3184;1780;4158;1089;1066;3183;1058;1049;4156;1083;1072;4153;1065;2555;2532;2482;471;449;470;198;1815;3164;3167;4155;1078;4159;1090;1811;1787;1807;1779;41;1068;3185;43;1776;1070;2158;2164;2149;2161;2154;2165;3203;3190;3202;3195;3200;3201;46;2790;49;47;31;50;1077;1418;1480;1473;1483;1477;1484;13;3842;3843;3844;3841;3834;25;1060;3181;2779;59;62;64;3146;55;3169;37;3166;2860;18;1063;1;26;1061;24;3180;1059;28;29;1064;2234;2225;2231;2236;2215;1783;3095;1782;2782;1785;27;3149;3855;3857;3859;3856;3858;1816;3165;3170;3171;3286;3288;3289;3283;3249;3214;1790;2180;2256;2251;2254;1434;1503;1494;1505;1500;3182;3179;2211;2204;2208;2214;1786;4;3871;3870;3872;3514;3577;3569;3574;3840;3155;2245;1076;469;23;2788;48;1075;1784;3152;3161;3175;1490;1487;1493;1423;3875;3876;3874;1877;1827;1894;1897;1898;3092;2542;2551;2554;5;32;52;1079;3188;3107;54;1081;1797;1082;1794;461;481;210;3575;3525;3597;3594;3598;3585;4157;3157;1813;9;58;3162;3160;61;3163;36;3158;1814;2875;204;477;455;57;1799;1084;3187;3177;1158;1093;1152;1157;3527;3587;3596;3599;1156;1148;12;1818;3172;2772;1054;1804;1809;1822;1884;1888;1887;1048;3173;1789;3;3576;19;1071;1055;1086;1088;1180;1111;1177;1161;1171;1181;17;1052;14;2785;3148;1777;1806;3159;1801;1909;1929;1944;1939;2913;2915;2906;2841;2896;22;16;1907;1937;1927;1803;1481;1430;1482;1472;1087;1417;1432;1431;1426;1422;1834;1859;1871;1849;1817;1810;1805;1914;1926;3934;3932;3893;3927;3930;1057;3178;2883;2902;2905;2828] : list nat) as base_ids.
pose ([
  ([250;266;244;51;105;272],[0;1;2;3;4;5;6;7;8;9;10;11;329;330;331;332;333;334;335;336;337;338;339;340;348;12;365;13;379;380;14;15;381;16;17;18;19;20;355;21;22;23;24;356;25;26;27;28;29;30;31;382]);
  ([276;244;272],[0;1;2;3;4;5;6;7;8;9;10;11;329;330;331;332;333;334;335;336;337;338;339;340;348;32;383;384;33;15;16;385;34;360;386;21;22;23;24;35;36;26;27;37;38;39]);
  ([244;279;105;272],[0;1;2;3;4;5;6;7;8;9;10;11;329;330;331;332;333;334;335;336;337;338;339;340;348;15;395;360;387;386;16;385;34;40;41;42;43;35;36;26;27;21;22;23;24;44;45;388;46;47;48;49;50;14;394]);
  ([250;284;274;51;105;272],[0;1;2;3;4;5;6;7;8;9;10;11;329;330;331;332;333;334;335;336;337;338;339;340;348;12;365;13;379;49;51;47;52;381;16;17;18;19;20;21;22;23;24;356;25;26;53;28;29;30;54;55;56;57;58;59;60;366;35;61;62;63;64;65;66;343;349;67;68;69;70;71;72;73;74;75;76;77;78;79;80;81;82;83;84;85;371]);
  ([90;274;266;251;286;51;245;282;268],[0;1;2;3;4;5;6;7;8;9;10;11;329;330;331;332;333;334;335;336;337;338;339;340;348;86;30;47;14;31;372;362;361;389;368;87;88;373;26;35;344;89;90;91;78;92;93;94;95;96;97;98;99;100;101;102;103;346;104;80;81;82;83;85;105;106]);
  ([61;53;274;251;286;51;245;279;268],[0;1;2;3;4;5;6;7;8;9;10;11;329;330;331;332;333;334;335;336;337;338;339;340;348;80;81;82;83;84;85;47;362;363;389;35;107;108;109;110;111;112;113;106;92;93;94;114;115;78;116;117;118;119;120;66;374;89;90;91;87;88;373;76;121;122;77;73;123;124;75;125]);
  ([60;251;286;245;282],[0;1;2;3;4;5;6;7;8;9;10;11;329;330;331;332;333;334;335;336;337;338;339;340;348;126;103;127;363;128;26;91;129;130;131;132;78;114;133;134;96;135;98;99;100;101;97;136;137;138;139;140;141;142]);
  ([249;274;115;266;251;286;245],[0;1;2;3;4;5;6;7;8;9;10;11;329;330;331;332;333;334;335;336;337;338;339;340;348;91;129;130;131;132;47;390;14;363;128;114;133;134;96;135;98;100;101;97;136;77;143;78;345;347;144;145;146;147;120]);
  ([246;127;284;274;115;266;61;286;51;268],[0;1;2;3;4;5;6;7;8;9;10;11;329;330;331;332;333;334;335;336;337;338;339;340;348;114;133;134;49;47;14;372;35;148;149;150;151;152;85;345;347;107;36;108;153;110;113;106;92;93;94;154;155;156;120;63;157;158;76;121;77;78;79;159;160;52;73;123;75;125;375;161;162;163;128;350;164;165;166;167]);
  ([127;274;266;115;251;284;286;245;51;282;268],[0;1;2;3;4;5;6;7;8;9;10;11;329;330;331;332;333;334;335;336;337;338;339;340;348;47;14;401;49;363;389;398;26;400;35;102;402;89;168;90;87;88;98;169;99;78;100;96;135;97;144;145;146;147;120;170;346;160;75;171]);
  ([277;286;279;105;272],[0;1;2;3;4;5;6;7;8;9;10;11;329;330;331;332;333;334;335;336;337;338;339;340;348;357;172;41;43;42;387;396;16;385;397;35;26;400;47;14;49;398;389;21;22;23;24;399;173;174;403;401;175;176;177;111;178;179;101;180;29;102;181;150;182;183;184;185;90;162;186;187;188;189;190;191;192;108;109;193;114]);
  ([286;279;105;272],[0;1;2;3;4;5;6;7;8;9;10;11;329;330;331;332;333;334;335;336;337;338;339;340;348;404;360;387;396;16;385;386;32;35;21;22;23;24;26;39;194;195;196;376;38;37;366;197;198;199;200;201;202;203;204;349;110;205;100;206;207;367;181;150;182;82;183;184;185;90;131;162;186;350;96;108;114]);
  ([279;105;272],[0;1;2;3;4;5;6;7;8;9;10;11;329;330;331;332;333;334;335;336;337;338;339;340;348;360;387;396;405;16;385;386;35;40;208;209;210;21;22;23;24;26;32;47;49;397;14;39;194;195;196;376;38;37;197;198;199;200;201;202;203;204;349;110;205;100;206;207;351]);
  ([233;223;229;284;266;274;278;163],[0;1;2;3;4;5;6;7;8;9;10;11;329;330;331;332;333;334;335;336;337;338;339;340;348;211;212;213;214;215;216;49;14;47;217;113;218;219;220;169;50;51;221;222;75;223;224;225;226;227;228;345;347;229]);
  ([29;223;229;287;105;272],[0;1;2;3;4;5;6;7;8;9;10;11;329;330;331;332;333;334;335;336;337;338;339;340;348;377;406;391;16;383;21;22;23;24;356;217;26;230;231;232;35;14;380;49;407;47;358;203;179;370;233;153;234;235;57;236;237;341;225;352;238;239;240;241;242;243;165;244;245;246;247;15;248;249;250;251;252;220;226;113;218]);
  ([223;229;287;105;272],[0;1;2;3;4;5;6;7;8;9;10;11;329;330;331;332;333;334;335;336;337;338;339;340;348;408;377;406;391;16;383;86;25;253;254;21;22;23;24;356;217;26;230;231;232;379;255;256;257;258;188;35;14;259;260;49;407;219;47;261;262;34;55;56;57;369;59;60;28;29;203;164;165;166;167;263;353]);
  ([28;109;105;272],[0;1;2;3;4;5;6;7;8;9;10;11;329;330;331;332;333;334;335;336;337;338;339;340;348;86;25;364;18;257]);
  ([222;266;105;272],[0;1;2;3;4;5;6;7;8;9;10;11;329;330;331;332;333;334;335;336;337;338;339;340;348;264;265;266;14;406;391;16;385;383;410;217;267;380;26;268;21;22;23;24;356;269;270;271;272;273;274;35;115;275;276;237;248;249;250;277;31;278;180;105;279;148;150;152;85;392]);
  ([287;105;272],[0;1;2;3;4;5;6;7;8;9;10;11;329;330;331;332;333;334;335;336;337;338;339;340;348;377;406;391;16;383;21;22;23;24;356;217;26;230;231;232;35;14;411;380;49;47;409;58;280;342;159;281;282;283;284;285;20;286;287;410;288;289;290;291;370;292;30;31;54;293;34;55;56]);
  ([228;109;105;272],[0;1;2;3;4;5;6;7;8;9;10;11;329;330;331;332;333;334;335;336;337;338;339;340;348;58;378;342;410;406;391;412;16;383;284;285;20;286;287;21;22;23;24;356;217;283;26;281;354;30;54;293;34;13;55;56]);
  ([156;109;105;272],[0;1;2;3;4;5;6;7;8;9;10;11;329;330;331;332;333;334;335;336;337;338;339;340;348;294;56;410;413;406;391;412;16;385;383;295;19;286;296;297;217;298;26;21;22;23;24;356;30;34;13;59;60;28;29;293;35;109;368;362;389;400;359;299;300;301;302;81]);
  ([109;105;272],[0;1;2;3;4;5;6;7;8;9;10;11;329;330;331;332;333;334;335;336;337;338;339;340;348;410;413;414;406;391;412;16;385;383;217;26;21;22;23;24;356;354;35;233;153;234;235;57;136;295;19;286;296;297;30;54;34;13;59;60;28;29;293;368;362;389]);
  ([51;170;105;272],[0;1;2;3;4;5;6;7;8;9;10;11;329;330;331;332;333;334;335;336;337;338;339;340;348;233;57;342;406;391;412;415;16;385;383;217;234;235;26;136;12;265;21;22;23;24;356;389;35;153;15;27;36;44;45;34;303;304;300;305;306;307;308;309;310;311;312;173;30]);
  ([170;105;272],[0;1;2;3;4;5;6;7;8;9;10;11;329;330;331;332;333;334;335;336;337;338;339;340;348;233;57;342;416;406;391;412;415;16;385;383;293;313;314;315;217;234;235;26;136;12;265;21;22;23;24;356;256;316;317;312;132;318;319;320;321;322;393]);
  ([50;105;272],[0;1;2;3;4;5;6;7;8;9;10;11;329;330;331;332;333;334;335;336;337;338;339;340;348;293;384;387;315;391;412;415;417;16;385;379;357;217;393;26;314;313;265;280;21;22;23;24;35;323;324;400;91;129;130;131;128;132;354;290;325;326;327;328;114;133;134;96])
] : list (list nat * list nat)) as records.
assert (Hcheck :
  check_selected_microblock (c12_k7_low3_instance [true; false; false; true; false; false; false; false; true; false; false; false]) base_ids
    imported records c12_k7_low3_mask02_block13_output = true).
{ vm_compute. reflexivity. }
exact (check_selected_microblock_sound
  (c12_k7_low3_instance [true; false; false; true; false; false; false; false; true; false; false; false]) base_ids imported records c12_k7_low3_mask02_block13_output
  Hcheck rho Hbase Himported).
Qed.
