(** Generated by [scripts/generate_ckpath_certificates.py].
    Only the block output is transparent.  Selected base clauses,
    producer imports, replay records, and the transient database
    all remain underneath the opaque soundness theorem. *)

From Stdlib Require Import List.
From Digraph Require Import ckpath_cnf ckpath_drup_microblock ckpath_cert_k7_c12_low3_reduction ckpath_cert_k7_c12_low3_mask04_block00 ckpath_cert_k7_c12_low3_mask04_block02 ckpath_cert_k7_c12_low3_mask04_block03 ckpath_cert_k7_c12_low3_mask04_block04 ckpath_cert_k7_c12_low3_mask04_block05 ckpath_cert_k7_c12_low3_mask04_block07 ckpath_cert_k7_c12_low3_mask04_block08 ckpath_cert_k7_c12_low3_mask04_block09 ckpath_cert_k7_c12_low3_mask04_block10 ckpath_cert_k7_c12_low3_mask04_block11 ckpath_cert_k7_c12_low3_mask04_block12 ckpath_cert_k7_c12_low3_mask04_block13 ckpath_cert_k7_c12_low3_mask04_block14.
Import ListNotations.
Set Warnings "-abstract-large-number".

(** Original retained additions [375, 400); 326 selected base clauses and 85 imported consequences from 13 producer blocks. *)
Definition c12_k7_low3_mask04_block15_output : cnf :=
  [
  [(40,true);(98,true);(39,true);(136,false)];
  [(91,true);(26,true);(93,true);(98,true);(136,false)];
  [(98,true);(39,true);(136,false)];
  [(39,true);(136,false)];
  [(136,false)];
  [(142,false);(141,false);(98,false)];
  [(141,false);(98,false)];
  [(113,false);(141,true)];
  [(98,false)];
  [(137,false);(144,false);(55,true);(99,true);(54,true);(51,true);(143,false)];
  [(144,false);(65,true);(62,true);(118,false);(54,true);(51,true);(111,false);(143,false)];
  [(119,true);(113,true);(112,true);(143,false)];
  [(144,true);(113,true);(112,true);(143,false)];
  [(118,true);(54,true);(51,true);(137,false);(113,true);(112,true);(143,false)];
  [(140,false);(141,false);(118,false);(54,true);(51,true);(137,false);(144,false);(113,true);(143,false)];
  [(141,false);(54,true);(51,true);(137,false);(113,true);(112,true);(143,false)];
  [(54,true);(51,true);(137,false);(113,true);(112,true);(143,false)];
  [(138,false);(66,true);(65,true);(62,true);(118,false)];
  [(54,false);(137,false);(113,true);(112,true);(143,false)];
  [(51,false);(113,true);(112,true);(143,false)];
  [(116,true);(113,true);(112,true);(143,false)];
  [(137,true);(113,true);(112,true);(143,false)];
  [(113,true);(112,true);(143,false)];
  [(138,false);(144,false);(51,true);(137,false);(113,false);(143,false)];
  [(144,false);(51,true);(137,false);(113,false);(143,false)]
].

Theorem c12_k7_low3_mask04_block15_sound :
  forall rho, satisfies_cnf rho (c12_k7_low3_instance [true; true; false; false; false; false; true; false; false; false; false; false]) ->
    satisfies_cnf rho c12_k7_low3_mask04_block15_output.
Proof.
intros rho Hbase.
pose (select_cnf c12_k7_low3_mask04_block00_output [0;1;2;3;4;5;6;7;8;9;10;11;19;22;21;12] : cnf)
  as imported_from_block00.
assert (Himported_from_block00 :
  satisfies_cnf rho imported_from_block00).
{
  unfold imported_from_block00.
  apply (satisfies_cnf_select rho c12_k7_low3_mask04_block00_output [0;1;2;3;4;5;6;7;8;9;10;11;19;22;21;12]).
  - exact (c12_k7_low3_mask04_block00_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask04_block02_output [12] : cnf)
  as imported_from_block02.
assert (Himported_from_block02 :
  satisfies_cnf rho imported_from_block02).
{
  unfold imported_from_block02.
  apply (satisfies_cnf_select rho c12_k7_low3_mask04_block02_output [12]).
  - exact (c12_k7_low3_mask04_block02_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask04_block03_output [4;16;15;12;17;13;21;20;23] : cnf)
  as imported_from_block03.
assert (Himported_from_block03 :
  satisfies_cnf rho imported_from_block03).
{
  unfold imported_from_block03.
  apply (satisfies_cnf_select rho c12_k7_low3_mask04_block03_output [4;16;15;12;17;13;21;20;23]).
  - exact (c12_k7_low3_mask04_block03_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask04_block04_output [18;11;6;17;3;16;2;1;4;0] : cnf)
  as imported_from_block04.
assert (Himported_from_block04 :
  satisfies_cnf rho imported_from_block04).
{
  unfold imported_from_block04.
  apply (satisfies_cnf_select rho c12_k7_low3_mask04_block04_output [18;11;6;17;3;16;2;1;4;0]).
  - exact (c12_k7_low3_mask04_block04_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask04_block05_output [2;9;5;1;23;20] : cnf)
  as imported_from_block05.
assert (Himported_from_block05 :
  satisfies_cnf rho imported_from_block05).
{
  unfold imported_from_block05.
  apply (satisfies_cnf_select rho c12_k7_low3_mask04_block05_output [2;9;5;1;23;20]).
  - exact (c12_k7_low3_mask04_block05_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask04_block07_output [11;23;13;9] : cnf)
  as imported_from_block07.
assert (Himported_from_block07 :
  satisfies_cnf rho imported_from_block07).
{
  unfold imported_from_block07.
  apply (satisfies_cnf_select rho c12_k7_low3_mask04_block07_output [11;23;13;9]).
  - exact (c12_k7_low3_mask04_block07_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask04_block08_output [19;14;20;22;17;11;7;5] : cnf)
  as imported_from_block08.
assert (Himported_from_block08 :
  satisfies_cnf rho imported_from_block08).
{
  unfold imported_from_block08.
  apply (satisfies_cnf_select rho c12_k7_low3_mask04_block08_output [19;14;20;22;17;11;7;5]).
  - exact (c12_k7_low3_mask04_block08_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask04_block09_output [19;18;17;13;21;12;3;5;24] : cnf)
  as imported_from_block09.
assert (Himported_from_block09 :
  satisfies_cnf rho imported_from_block09).
{
  unfold imported_from_block09.
  apply (satisfies_cnf_select rho c12_k7_low3_mask04_block09_output [19;18;17;13;21;12;3;5;24]).
  - exact (c12_k7_low3_mask04_block09_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask04_block10_output [23;6] : cnf)
  as imported_from_block10.
assert (Himported_from_block10 :
  satisfies_cnf rho imported_from_block10).
{
  unfold imported_from_block10.
  apply (satisfies_cnf_select rho c12_k7_low3_mask04_block10_output [23;6]).
  - exact (c12_k7_low3_mask04_block10_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask04_block11_output [10;8;22;24] : cnf)
  as imported_from_block11.
assert (Himported_from_block11 :
  satisfies_cnf rho imported_from_block11).
{
  unfold imported_from_block11.
  apply (satisfies_cnf_select rho c12_k7_low3_mask04_block11_output [10;8;22;24]).
  - exact (c12_k7_low3_mask04_block11_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask04_block12_output [16;18;20;0] : cnf)
  as imported_from_block12.
assert (Himported_from_block12 :
  satisfies_cnf rho imported_from_block12).
{
  unfold imported_from_block12.
  apply (satisfies_cnf_select rho c12_k7_low3_mask04_block12_output [16;18;20;0]).
  - exact (c12_k7_low3_mask04_block12_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask04_block13_output [21;20;24] : cnf)
  as imported_from_block13.
assert (Himported_from_block13 :
  satisfies_cnf rho imported_from_block13).
{
  unfold imported_from_block13.
  apply (satisfies_cnf_select rho c12_k7_low3_mask04_block13_output [21;20;24]).
  - exact (c12_k7_low3_mask04_block13_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask04_block14_output [24;22;7;21;23;6;1;4;0] : cnf)
  as imported_from_block14.
assert (Himported_from_block14 :
  satisfies_cnf rho imported_from_block14).
{
  unfold imported_from_block14.
  apply (satisfies_cnf_select rho c12_k7_low3_mask04_block14_output [24;22;7;21;23;6;1;4;0]).
  - exact (c12_k7_low3_mask04_block14_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (concat [imported_from_block00;imported_from_block02;imported_from_block03;imported_from_block04;imported_from_block05;imported_from_block07;imported_from_block08;imported_from_block09;imported_from_block10;imported_from_block11;imported_from_block12;imported_from_block13;imported_from_block14] : cnf) as imported.
assert (Himported : satisfies_cnf rho imported).
{
  unfold imported.
  apply satisfies_cnf_concat_intro.
  constructor.
  { exact Himported_from_block00. }
  constructor.
  { exact Himported_from_block02. }
  constructor.
  { exact Himported_from_block03. }
  constructor.
  { exact Himported_from_block04. }
  constructor.
  { exact Himported_from_block05. }
  constructor.
  { exact Himported_from_block07. }
  constructor.
  { exact Himported_from_block08. }
  constructor.
  { exact Himported_from_block09. }
  constructor.
  { exact Himported_from_block10. }
  constructor.
  { exact Himported_from_block11. }
  constructor.
  { exact Himported_from_block12. }
  constructor.
  { exact Himported_from_block13. }
  constructor.
  { exact Himported_from_block14. }
  constructor.
}
pose (
  [66;67;68;69;70;71;72;73;74;75;76;77;4153;36;1061;1138;4158;4155;242;151;278;281;34;2521;4154;4152;4156;4157;1614;1612;1572;1592;1537;37;35;1060;12;1141;1047;31;1056;1133;2549;2;1063;1140;3261;3260;3258;3257;3259;3201;2941;2948;2944;2946;2882;1828;1883;1889;1891;1890;41;2971;2984;2980;2906;2982;62;2517;17;1052;1165;2519;1073;1077;1067;47;2523;7;1083;1164;2518;52;2524;1234;1253;1257;1256;1244;1184;33;1058;1135;2530;2546;2513;2522;26;1137;1152;1145;1128;1157;2520;1237;1260;1259;1247;1187;1618;1619;1596;1541;1576;61;1162;2516;1081;3267;3269;8;1167;2526;1085;64;2525;3837;3264;48;2531;2529;53;2532;42;1615;1616;1593;1573;1538;1059;1136;3783;3784;3780;3728;4055;4044;4050;4053;2261;2264;2265;2242;2222;2187;32;1057;1134;2550;2151;2211;2213;2206;2212;50;3821;4;1076;1155;1072;1151;49;1074;1153;2880;2943;3268;3203;3262;3266;2939;2935;57;2507;172;201;95;207;187;1084;1166;4159;3584;3525;3589;3591;170;185;205;206;93;199;1051;46;2545;2551;2539;1071;1150;28;92;202;198;204;184;169;203;1130;1159;1154;1147;2535;1258;1278;1288;1296;1295;1223;3581;3526;3590;3588;3585;58;2508;9;1086;1169;2533;54;2538;43;18;1168;2527;1053;2232;2252;2197;2262;3841;3850;3856;3853;3857;44;1798;2273;2271;1950;1913;1951;1878;1943;1933;1066;1144;13;1149;1048;2543;1820;2542;55;162;79;168;2140;2201;2236;2256;2266;2536;2537;3580;3587;2937;1810;4065;4069;4070;1909;1929;1948;2456;85;183;91;1068;1146;3582;3577;3522;3583;40;3578;3586;3523;2544;3922;3923;3919;2272;3271;3206;3270;3265;2967;2898;2958;2964;2968;1163;1912;1949] : list nat) as base_ids.
pose ([
  ([79;195;77;270],[0;1;2;3;4;5;6;7;8;9;10;11;326;327;328;329;330;331;332;333;334;335;336;337;342;402;403;12;368;380;399;404;405;406;13;14;15;16;17;18;19;20;21;22;23;24;25;372;26;27;28;29;30;31;32;407;33;34;35;36;37;38;39;40;41;42;369;43;44;45;46;47;48;49;50;51;52;53;54;55;56;57;58;59;60;61;62]);
  ([181;51;185;195;270],[0;1;2;3;4;5;6;7;8;9;10;11;326;327;328;329;330;331;332;333;334;335;336;337;342;12;368;380;399;404;405;16;17;18;19;20;21;24;25;372;26;27;63;64;52;65;66;67;22;23;68;69;70;71;35;72;73;74;75;76;77;78;79;80;81;82;83;84;85;86;87;88;89;90;343;381]);
  ([195;77;270],[0;1;2;3;4;5;6;7;8;9;10;11;326;327;328;329;330;331;332;333;334;335;336;337;342;411;12;368;380;399;404;405;91;92;93;94;16;17;18;19;20;21;24;25;372;95;26;96;370;27;97;412;98;99;100;101;391;102;103;104;105;106;107;108;109;110;111;112;113;114;381]);
  ([77;270],[0;1;2;3;4;5;6;7;8;9;10;11;326;327;328;329;330;331;332;333;334;335;336;337;342;413;12;368;380;399;404;405;115;16;17;18;19;20;21;24;25;372;26;27;116;117;389;344;118;119;47;120;121;122;123;124;125;126;127;128;129;130;34;131;132;133;134;94;381;402;29;135;136;137;138;139;22;140;141;13;33;39;40;41;369;36;37;38;43;142;143;144;145;146;147;148;149;150;151;152;153;154;155;57;58;59]);
  ([270],[0;1;2;3;4;5;6;7;8;9;10;11;326;327;328;329;330;331;332;333;334;335;336;337;342;12;368;380;399;404;405;414;16;17;18;19;20;21;156;157;158;159;373;24;25;372;26;27;160;161;162;163;164;165;166;167;168;169;77;170;171;172;173;174;39;129;74;100;175;345;176;346;177;178;179;119;180;48;54;181;182;79;82;68;83;125;121;134;94;183;184;117]);
  ([282;280;194],[0;1;2;3;4;5;6;7;8;9;10;11;326;327;328;329;330;331;332;333;334;335;336;337;342;415;16;27;392;115;116;117;389;344;118;185;186;187;188;189;119;47;120;128;121;122;123;124;125;126;190;191;24;26;25;192;408;193;194;195;196]);
  ([280;194],[0;1;2;3;4;5;6;7;8;9;10;11;326;327;328;329;330;331;332;333;334;335;336;337;342;415;27;416;115;116;117;118;197;198;199;200;201;202;24;17;192;374;352;353;25;372;26;382;381;383;384;385;203;354;338;355;346;386;387;204;205;206;207;84;208;209;371;375;79;82;78;362]);
  ([224;281],[0;1;2;3;4;5;6;7;8;9;10;11;326;327;328;329;330;331;332;333;334;335;336;337;342;415;210;211;212;213;214;215;216;217;25;372;218;339;16;363;393;26;219;353;364;17;220;24;221;192;222;223;224;340;225;226;227;228;134;94;376]);
  ([194],[0;1;2;3;4;5;6;7;8;9;10;11;326;327;328;329;330;331;332;333;334;335;336;337;342;415;115;417;213;214;215;216;217;211;212;418;26;353;364;17;24;192;25;372;16;363;393;362;229;230;231;232;233;134;94;234;235;407;347;13;236;237;238;239;377;240;207;172;241;242;381;243;244;245;246;247;248;249;250;251;252;253;254;255;256;257;356;365;258;259;400]);
  ([272;286;109;197;107;101;284],[0;1;2;3;4;5;6;7;8;9;10;11;326;327;328;329;330;331;332;333;334;335;336;337;342;415;419;24;378;260;261;262;263;264;265;192;213;215;211;212;418;364;62;266;267;268;269;270;134]);
  ([286;129;123;234;107;101;220;284],[0;1;2;3;4;5;6;7;8;9;10;11;326;327;328;329;330;331;332;333;334;335;336;337;342;415;419;234;236;237;238;239;377;192;251;252;253;254;255;256;271;272;33;273;165;68;274;125;420;275;276;197;277;216;278;17;357;356;279;258;280;281;282;347]);
  ([237;225;223;284],[0;1;2;3;4;5;6;7;8;9;10;11;326;327;328;329;330;331;332;333;334;335;336;337;342;415;419;196;229;230;231;232;233;192;234;13;283;236;237;238;239;240;207;172;241;242;284;421;189;200;185;186;187;214;348;17;356;347;16;126;24;407;409;401;26;235;25;395;365;27;410]);
  ([287;225;223;284],[0;1;2;3;4;5;6;7;8;9;10;11;326;327;328;329;330;331;332;333;334;335;336;337;342;415;419;189;200;185;186;187;214;422;192;17;16;24;26;25;27;410;379;408;407;285;193;194;195;286;13;242;284;236;238;239;240;207;172;241;395;348;356;365;409;401;129;338;54;53;287;52;55;177;178;179;119;180;48;79;77;68;288;22;62;83;125;121;134;183;184;132;34;247;248;249;250;258;146;289;290;291;292;293;260;294]);
  ([235;107;101;272;225;223;284],[0;1;2;3;4;5;6;7;8;9;10;11;326;327;328;329;330;331;332;333;334;335;336;337;342;415;419;285;196;193;194;195;286;24;423;192;13;283;284;236;237;238;239;240;207;172;362;377;251;252;253;254;255;366;295;296;297;215;256;272;33;165;68;274;125;16;25;395;409;26;400;27;410;401;420]);
  ([278;280;234;107;101;272;286;225;284],[0;1;2;3;4;5;6;7;8;9;10;11;326;327;328;329;330;331;332;333;334;335;336;337;342;415;419;26;400;27;234;235;69;24;192;134;76;101;352;396;358;359;360]);
  ([280;107;101;272;225;223;284],[0;1;2;3;4;5;6;7;8;9;10;11;326;327;328;329;330;331;332;333;334;335;336;337;342;415;419;27;424;24;423;397;422;192;234;69;425;388;378;202;349;297;298;401;256;16;363;70;71;72;73;350]);
  ([107;101;272;225;223;284],[0;1;2;3;4;5;6;7;8;9;10;11;326;327;328;329;330;331;332;333;334;335;336;337;342;415;419;424;426;24;423;422;192;234;211;212;213;215;25;395;16;363;393;26;400;235;407;17;357;347;364;394;398;367;134]);
  ([274;131;129;123;234],[0;1;2;3;4;5;6;7;8;9;10;11;326;327;328;329;330;331;332;333;334;335;336;337;342;415;419;17;347;279;258]);
  ([106;272;225;223;284],[0;1;2;3;4;5;6;7;8;9;10;11;326;327;328;329;330;331;332;333;334;335;336;337;342;415;419;242;299;300;24;423;422;192;301;302;303;193;304;172;241;13;283;236;237;238;239;377;234;240;207;251;252;253;254;255;256;271;272;33;165;68;274;125;428;295;296;297;198;215;25;407]);
  ([100;225;223;284],[0;1;2;3;4;5;6;7;8;9;10;11;326;327;328;329;330;331;332;333;334;335;336;337;342;415;419;305;241;423;422;192;286;306;307;301;308;309;234;13;283;240;207;242;284;236;237;238;239;377;310;311;312;252]);
  ([231;225;223;284],[0;1;2;3;4;5;6;7;8;9;10;11;326;327;328;329;330;331;332;333;334;335;336;337;342;415;419;286;306;232;307;301;308;423;430;192;234;13;283;240;207;242;284;236;237;238;239;377;427;421;251;252;253;254;255;256;272;275;276;197;277;216;278;173;174;33;165;68;274;125;17;347;357;356;313;390;25;16;314;46;315;316;177;317;26;235;351]);
  ([273;225;223;284],[0;1;2;3;4;5;6;7;8;9;10;11;326;327;328;329;330;331;332;333;334;335;336;337;342;415;419;275;185;276;197;277;216;430;431;422;192;17;362;347;357;25;16;363;393;26;235;27;69;374;172;234;318;53;361;319;320;321;322;360]);
  ([225;223;284],[0;1;2;3;4;5;6;7;8;9;10;11;326;327;328;329;330;331;332;333;334;335;336;337;342;415;419;423;430;431;432;422;192;172;24;429;427]);
  ([274;286;101;272;224;284],[0;1;2;3;4;5;6;7;8;9;10;11;326;327;328;329;330;331;332;333;334;335;336;337;342;415;419;17;357;24;210;418;220;221;222;323;192;318;53;319;320;321;322;27;352;378;77;98;100;79;80;81;82;22;23;62;97;83;84;324;325]);
  ([286;101;272;224;284],[0;1;2;3;4;5;6;7;8;9;10;11;326;327;328;329;330;331;332;333;334;335;336;337;342;415;419;434;24;210;418;221;222;323;192;296;297;198;27;378;341;25;218;339;376;26;219;410;16;363;393;242;300;79;80;81;82;223;224])
] : list (list nat * list nat)) as records.
assert (Hcheck :
  check_selected_microblock (c12_k7_low3_instance [true; true; false; false; false; false; true; false; false; false; false; false]) base_ids
    imported records c12_k7_low3_mask04_block15_output = true).
{ vm_compute. reflexivity. }
exact (check_selected_microblock_sound
  (c12_k7_low3_instance [true; true; false; false; false; false; true; false; false; false; false; false]) base_ids imported records c12_k7_low3_mask04_block15_output
  Hcheck rho Hbase Himported).
Qed.
