(** Generated by [scripts/generate_ckpath_certificates.py].
    Only the block output is transparent.  Selected base clauses,
    producer imports, replay records, and the transient database
    all remain underneath the opaque soundness theorem. *)

From Stdlib Require Import List.
From Digraph Require Import ckpath_cnf ckpath_drup_microblock ckpath_cert_k7_c12_low3_reduction ckpath_cert_k7_c12_low3_mask16_block00 ckpath_cert_k7_c12_low3_mask16_block02 ckpath_cert_k7_c12_low3_mask16_block03 ckpath_cert_k7_c12_low3_mask16_block04 ckpath_cert_k7_c12_low3_mask16_block05 ckpath_cert_k7_c12_low3_mask16_block06 ckpath_cert_k7_c12_low3_mask16_block09 ckpath_cert_k7_c12_low3_mask16_block10.
Import ListNotations.
Set Warnings "-abstract-large-number".

(** Original retained additions [275, 289); 40 selected base clauses and 47 imported consequences from 8 producer blocks. *)
Definition c12_k7_low3_mask16_block11_output : cnf :=
  [
  [(107,false)];
  [(91,false)];
  [(90,false)];
  [(98,true)];
  [(93,false)];
  [(105,true)];
  [(106,true)];
  [(104,true)];
  [(101,true)];
  [(110,true)];
  [(100,true)];
  [(51,true)];
  [(95,true)];
  []
].

Theorem c12_k7_low3_mask16_block11_sound :
  forall rho, satisfies_cnf rho (c12_k7_low3_instance [true; true; false; true; false; false; false; false; false; false; false; false]) ->
    satisfies_cnf rho c12_k7_low3_mask16_block11_output.
Proof.
intros rho Hbase.
pose (select_cnf c12_k7_low3_mask16_block00_output [0;1;2;3;4;5;6;7;8;9;10;11;13] : cnf)
  as imported_from_block00.
assert (Himported_from_block00 :
  satisfies_cnf rho imported_from_block00).
{
  unfold imported_from_block00.
  apply (satisfies_cnf_select rho c12_k7_low3_mask16_block00_output [0;1;2;3;4;5;6;7;8;9;10;11;13]).
  - exact (c12_k7_low3_mask16_block00_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask16_block02_output [24] : cnf)
  as imported_from_block02.
assert (Himported_from_block02 :
  satisfies_cnf rho imported_from_block02).
{
  unfold imported_from_block02.
  apply (satisfies_cnf_select rho c12_k7_low3_mask16_block02_output [24]).
  - exact (c12_k7_low3_mask16_block02_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask16_block03_output [18;22;17] : cnf)
  as imported_from_block03.
assert (Himported_from_block03 :
  satisfies_cnf rho imported_from_block03).
{
  unfold imported_from_block03.
  apply (satisfies_cnf_select rho c12_k7_low3_mask16_block03_output [18;22;17]).
  - exact (c12_k7_low3_mask16_block03_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask16_block04_output [22;0] : cnf)
  as imported_from_block04.
assert (Himported_from_block04 :
  satisfies_cnf rho imported_from_block04).
{
  unfold imported_from_block04.
  apply (satisfies_cnf_select rho c12_k7_low3_mask16_block04_output [22;0]).
  - exact (c12_k7_low3_mask16_block04_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask16_block05_output [17] : cnf)
  as imported_from_block05.
assert (Himported_from_block05 :
  satisfies_cnf rho imported_from_block05).
{
  unfold imported_from_block05.
  apply (satisfies_cnf_select rho c12_k7_low3_mask16_block05_output [17]).
  - exact (c12_k7_low3_mask16_block05_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask16_block06_output [17;18;6] : cnf)
  as imported_from_block06.
assert (Himported_from_block06 :
  satisfies_cnf rho imported_from_block06).
{
  unfold imported_from_block06.
  apply (satisfies_cnf_select rho c12_k7_low3_mask16_block06_output [17;18;6]).
  - exact (c12_k7_low3_mask16_block06_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask16_block09_output [3;17;18;19;20;21;22;23;24] : cnf)
  as imported_from_block09.
assert (Himported_from_block09 :
  satisfies_cnf rho imported_from_block09).
{
  unfold imported_from_block09.
  apply (satisfies_cnf_select rho c12_k7_low3_mask16_block09_output [3;17;18;19;20;21;22;23;24]).
  - exact (c12_k7_low3_mask16_block09_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask16_block10_output [0;1;2;3;13;14;15;16;17;18;19;20;21;23;24] : cnf)
  as imported_from_block10.
assert (Himported_from_block10 :
  satisfies_cnf rho imported_from_block10).
{
  unfold imported_from_block10.
  apply (satisfies_cnf_select rho c12_k7_low3_mask16_block10_output [0;1;2;3;13;14;15;16;17;18;19;20;21;23;24]).
  - exact (c12_k7_low3_mask16_block10_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (concat [imported_from_block00;imported_from_block02;imported_from_block03;imported_from_block04;imported_from_block05;imported_from_block06;imported_from_block09;imported_from_block10] : cnf) as imported.
assert (Himported : satisfies_cnf rho imported).
{
  unfold imported.
  apply satisfies_cnf_concat_intro.
  constructor.
  { exact Himported_from_block00. }
  constructor.
  { exact Himported_from_block02. }
  constructor.
  { exact Himported_from_block03. }
  constructor.
  { exact Himported_from_block04. }
  constructor.
  { exact Himported_from_block05. }
  constructor.
  { exact Himported_from_block06. }
  constructor.
  { exact Himported_from_block09. }
  constructor.
  { exact Himported_from_block10. }
  constructor.
}
pose (
  [66;67;68;69;70;71;72;73;74;75;76;77;57;26;1151;17;1059;1052;1159;1565;1074;41;1555;3327;3267;3307;3241;3306;3268;3309;3248;3304;3303;3270;3269;3235;3310;3234;2911;2950] : list nat) as base_ids.
pose ([
  ([212],[0;1;2;3;4;5;6;7;8;9;10;11;40;41;42;43;44;45;46;47;48;49;50;51;53;60;61;63;64;65;66;67;68;69;70;71;72;73;74;75;76;77;78;79;80;81;82;83;84;85;86;12]);
  ([180],[0;1;2;3;4;5;6;7;8;9;10;11;40;41;42;43;44;45;46;47;48;49;50;51;53;60;61;63;64;65;66;67;68;69;70;71;72;73;74;75;76;77;78;79;80;81;82;83;84;85;86;87;13;59;14]);
  ([178],[0;1;2;3;4;5;6;7;8;9;10;11;40;41;42;43;44;45;46;47;48;49;50;51;53;60;61;63;64;65;66;67;68;69;70;71;72;73;74;75;76;77;78;79;80;81;82;83;84;85;86;87;88;15;16;17;54;18;19;20]);
  ([195],[0;1;2;3;4;5;6;7;8;9;10;11;40;41;42;43;44;45;46;47;48;49;50;51;53;60;61;63;64;65;66;67;68;69;70;71;72;73;74;75;76;77;78;79;80;81;82;83;84;85;86;87;88;89;52]);
  ([184],[0;1;2;3;4;5;6;7;8;9;10;11;40;41;42;43;44;45;46;47;48;49;50;51;53;60;61;63;64;65;66;67;68;69;70;71;72;73;74;75;76;77;78;79;80;81;82;83;84;85;86;87;88;89;90;21;22]);
  ([209],[0;1;2;3;4;5;6;7;8;9;10;11;40;41;42;43;44;45;46;47;48;49;50;51;53;60;61;63;64;65;66;67;68;69;70;71;72;73;74;75;76;77;78;79;80;81;82;83;84;85;86;87;88;89;90;91;23;24;25;26;27]);
  ([211],[0;1;2;3;4;5;6;7;8;9;10;11;40;41;42;43;44;45;46;47;48;49;50;51;53;60;61;63;64;65;66;67;68;69;70;71;72;73;74;75;76;77;78;79;80;81;82;83;84;85;86;87;88;89;90;91;92;28;29;57]);
  ([207],[0;1;2;3;4;5;6;7;8;9;10;11;40;41;42;43;44;45;46;47;48;49;50;51;53;60;61;63;64;65;66;67;68;69;70;71;72;73;74;75;76;77;78;79;80;81;82;83;84;85;86;87;88;89;90;91;92;93;62;30;31;32]);
  ([201],[0;1;2;3;4;5;6;7;8;9;10;11;40;41;42;43;44;45;46;47;48;49;50;51;53;60;61;63;64;65;66;67;68;69;70;71;72;73;74;75;76;77;78;79;80;81;82;83;84;85;86;87;88;89;90;91;92;93;94;33;34]);
  ([219],[0;1;2;3;4;5;6;7;8;9;10;11;40;41;42;43;44;45;46;47;48;49;50;51;53;60;61;63;64;65;66;67;68;69;70;71;72;73;74;75;76;77;78;79;80;81;82;83;84;85;86;87;88;89;90;91;92;93;94;95;35;36]);
  ([199],[0;1;2;3;4;5;6;7;8;9;10;11;40;41;42;43;44;45;46;47;48;49;50;51;53;60;61;63;64;65;66;67;68;69;70;71;72;73;74;75;76;77;78;79;80;81;82;83;84;85;86;87;88;89;90;91;92;93;94;95;96;37]);
  ([101],[0;1;2;3;4;5;6;7;8;9;10;11;40;41;42;43;44;45;46;47;48;49;50;51;53;60;61;63;64;65;66;67;68;69;70;71;72;73;74;75;76;77;78;79;80;81;82;83;84;85;86;87;88;89;90;91;92;93;94;95;96;97;55]);
  ([189],[0;1;2;3;4;5;6;7;8;9;10;11;40;41;42;43;44;45;46;47;48;49;50;51;53;60;61;63;64;65;66;67;68;69;70;71;72;73;74;75;76;77;78;79;80;81;82;83;84;85;86;87;88;89;90;91;92;93;94;95;96;97;98;56]);
  ([],[0;1;2;3;4;5;6;7;8;9;10;11;40;41;42;43;44;45;46;47;48;49;50;51;53;60;61;63;64;65;66;67;68;69;70;71;72;73;74;75;76;77;78;79;80;81;82;83;84;85;86;87;88;89;90;91;92;93;94;95;96;97;98;99;38;39;58])
] : list (list nat * list nat)) as records.
assert (Hcheck :
  check_selected_microblock (c12_k7_low3_instance [true; true; false; true; false; false; false; false; false; false; false; false]) base_ids
    imported records c12_k7_low3_mask16_block11_output = true).
{ vm_compute. reflexivity. }
exact (check_selected_microblock_sound
  (c12_k7_low3_instance [true; true; false; true; false; false; false; false; false; false; false; false]) base_ids imported records c12_k7_low3_mask16_block11_output
  Hcheck rho Hbase Himported).
Qed.
