(** Generated by [scripts/generate_ckpath_certificates.py].
    Only the block output is transparent.  Selected base clauses,
    producer imports, replay records, and the transient database
    all remain underneath the opaque soundness theorem. *)

From Stdlib Require Import List.
From Digraph Require Import ckpath_cnf ckpath_drup_microblock ckpath_cert_k7_base ckpath_cert_k7_c12_cover4_micro_block015 ckpath_cert_k7_c12_cover4_micro_block018 ckpath_cert_k7_c12_cover4_micro_block019 ckpath_cert_k7_c12_cover4_micro_block020 ckpath_cert_k7_c12_cover4_micro_block021 ckpath_cert_k7_c12_cover4_micro_block022.
Import ListNotations.
Set Warnings "-abstract-large-number".

(** Original retained additions [575, 600); 82 selected base clauses and 21 imported consequences from 6 producer blocks. *)
Definition c12_k7_cover4_micro_block023_output : cnf :=
  [
  [(137,false);(140,false);(139,false);(144,false)];
  [(141,false);(137,false);(139,false);(142,false)];
  [(141,false);(137,false);(139,false);(143,false)];
  [(141,false);(137,false);(139,false);(144,false)];
  [(142,false);(137,false);(139,false);(143,false)];
  [(142,false);(137,false);(139,false);(144,false)];
  [(143,false);(137,false);(139,false);(144,false)];
  [(137,false);(141,false);(140,false);(142,false)];
  [(137,false);(141,false);(140,false);(143,false)];
  [(137,false);(141,false);(140,false);(144,false)];
  [(137,false);(142,false);(140,false);(143,false)];
  [(137,false);(142,false);(140,false);(144,false)];
  [(137,false);(143,false);(140,false);(144,false)];
  [(137,false);(142,false);(141,false);(143,false)];
  [(137,false);(142,false);(141,false);(144,false)];
  [(137,false);(143,false);(141,false);(144,false)];
  [(137,false);(143,false);(142,false);(144,false)];
  [(140,false);(138,false);(139,false);(141,false)];
  [(140,false);(138,false);(139,false);(142,false)];
  [(140,false);(138,false);(139,false);(143,false)];
  [(140,false);(138,false);(139,false);(144,false)];
  [(141,false);(138,false);(139,false);(142,false)];
  [(141,false);(138,false);(139,false);(143,false)];
  [(141,false);(138,false);(139,false);(144,false)];
  [(142,false);(138,false);(139,false);(143,false)]
].

Theorem c12_k7_cover4_micro_block023_sound :
  forall rho, satisfies_cnf rho ((c12_k7_cover_base 4)) ->
    satisfies_cnf rho c12_k7_cover4_micro_block023_output.
Proof.
intros rho Hbase.
pose (select_cnf c12_k7_cover4_micro_block015_output [12;13;22] : cnf)
  as imported_from_block015.
assert (Himported_from_block015 :
  satisfies_cnf rho imported_from_block015).
{
  unfold imported_from_block015.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block015_output [12;13;22]).
  - exact (c12_k7_cover4_micro_block015_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block018_output [14;19] : cnf)
  as imported_from_block018.
assert (Himported_from_block018 :
  satisfies_cnf rho imported_from_block018).
{
  unfold imported_from_block018.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block018_output [14;19]).
  - exact (c12_k7_cover4_micro_block018_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block019_output [2] : cnf)
  as imported_from_block019.
assert (Himported_from_block019 :
  satisfies_cnf rho imported_from_block019).
{
  unfold imported_from_block019.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block019_output [2]).
  - exact (c12_k7_cover4_micro_block019_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block020_output [14] : cnf)
  as imported_from_block020.
assert (Himported_from_block020 :
  satisfies_cnf rho imported_from_block020).
{
  unfold imported_from_block020.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block020_output [14]).
  - exact (c12_k7_cover4_micro_block020_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block021_output [21;22;18] : cnf)
  as imported_from_block021.
assert (Himported_from_block021 :
  satisfies_cnf rho imported_from_block021).
{
  unfold imported_from_block021.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block021_output [21;22;18]).
  - exact (c12_k7_cover4_micro_block021_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block022_output [23;24;9;10;11;14;2;3;17;6;20] : cnf)
  as imported_from_block022.
assert (Himported_from_block022 :
  satisfies_cnf rho imported_from_block022).
{
  unfold imported_from_block022.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block022_output [23;24;9;10;11;14;2;3;17;6;20]).
  - exact (c12_k7_cover4_micro_block022_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (concat [imported_from_block015;imported_from_block018;imported_from_block019;imported_from_block020;imported_from_block021;imported_from_block022] : cnf) as imported.
assert (Himported : satisfies_cnf rho imported).
{
  unfold imported.
  apply satisfies_cnf_concat_intro.
  constructor.
  { exact Himported_from_block015. }
  constructor.
  { exact Himported_from_block018. }
  constructor.
  { exact Himported_from_block019. }
  constructor.
  { exact Himported_from_block020. }
  constructor.
  { exact Himported_from_block021. }
  constructor.
  { exact Himported_from_block022. }
  constructor.
}
pose (
  [66;67;68;69;70;71;72;73;74;75;76;77;2014;3223;368;4129;575;508;3827;452;576;4431;983;577;579;369;509;453;578;4733;592;600;916;370;580;917;581;5035;522;1043;582;567;377;583;584;410;457;585;564;374;458;586;587;1059;565;588;554;589;590;591;1053;538;3525;593;473;385;529;607;594;530;595;475;523;596;610;597;384;599;609;598;525;612] : list nat) as base_ids.
pose ([
  ([272;278;276;286],[0;1;2;3;4;5;6;7;8;9;10;11;12;13;14;15;16;17;92;93;18;94;19;20]);
  ([280;272;276;282],[0;1;2;3;4;5;6;7;8;9;10;11;12;21;22;85;23]);
  ([280;272;276;284],[0;1;2;3;4;5;6;7;8;9;10;11;12;21;92;24;13;104;18;25;26;95;27;28]);
  ([280;272;276;286],[0;1;2;3;4;5;6;7;8;9;10;11;12;21;92;24]);
  ([282;272;276;284],[0;1;2;3;4;5;6;7;8;9;10;11;12;29;89;30;31;93;32;13;104;18;33;34]);
  ([282;272;276;286],[0;1;2;3;4;5;6;7;8;9;10;11;12;29;90;96;93;35;13;104;107;18;33;36]);
  ([284;272;276;286],[0;1;2;3;4;5;6;7;8;9;10;11;12;37;82;38;86;39;40]);
  ([272;280;278;282],[0;1;2;3;4;5;6;7;8;9;10;11;12;13;21;41;42;43]);
  ([272;280;278;284],[0;1;2;3;4;5;6;7;8;9;10;11;12;13;21;110;15;44]);
  ([272;280;278;286],[0;1;2;3;4;5;6;7;8;9;10;11;12;13;21;110;111;15;88;45;92;46;97;47]);
  ([272;282;278;284],[0;1;2;3;4;5;6;7;8;9;10;11;12;13;29;98;48;110;15;93;49;50;51]);
  ([272;282;278;286],[0;1;2;3;4;5;6;7;8;9;10;11;12;13;29;99;48;110;113;15;93;49;50;52]);
  ([272;284;278;286],[0;1;2;3;4;5;6;7;8;9;10;11;12;13;114;37;82;38;86;53;54;55]);
  ([272;282;280;284],[0;1;2;3;4;5;6;7;8;9;10;11;12;13;29;56;100;21;110;42;57]);
  ([272;282;280;286],[0;1;2;3;4;5;6;7;8;9;10;11;12;13;29;101;100;116;21;110;42;85;23;58]);
  ([272;284;280;286],[0;1;2;3;4;5;6;7;8;9;10;11;12;13;117;37;82;38;86;28;59]);
  ([272;284;282;286],[0;1;2;3;4;5;6;7;8;9;10;11;12;13;37;82;38;86;60;51;30]);
  ([278;274;276;280],[0;1;2;3;4;5;6;7;8;9;10;11;12;15;61;62;63]);
  ([278;274;276;282],[0;1;2;3;4;5;6;7;8;9;10;11;12;15;62;64;65;66;48;31;67;68]);
  ([278;274;276;284],[0;1;2;3;4;5;6;7;8;9;10;11;12;15;62;87;69;83;94;70]);
  ([278;274;276;286],[0;1;2;3;4;5;6;7;8;9;10;11;12;15;62;71;83;94;72;120;121;122;18;73]);
  ([280;274;276;282],[0;1;2;3;4;5;6;7;8;9;10;11;12;21;91;84;74;75]);
  ([280;274;276;284],[0;1;2;3;4;5;6;7;8;9;10;11;12;21;76;77;78;79]);
  ([280;274;276;286],[0;1;2;3;4;5;6;7;8;9;10;11;12;21;76;77]);
  ([282;274;276;284],[0;1;2;3;4;5;6;7;8;9;10;11;12;29;80;102;81;78;65;31])
] : list (list nat * list nat)) as records.
assert (Hcheck :
  check_selected_microblock ((c12_k7_cover_base 4)) base_ids
    imported records c12_k7_cover4_micro_block023_output = true).
{ vm_compute. reflexivity. }
exact (check_selected_microblock_sound
  ((c12_k7_cover_base 4)) base_ids imported records c12_k7_cover4_micro_block023_output
  Hcheck rho Hbase Himported).
Qed.
