(** Generated by [scripts/generate_ckpath_certificates.py].
    Only the block output is transparent.  Selected base clauses,
    producer imports, replay records, and the transient database
    all remain underneath the opaque soundness theorem. *)

From Stdlib Require Import List.
From Digraph Require Import ckpath_cnf ckpath_drup_microblock ckpath_cert_k7_c12_low3_reduction ckpath_cert_k7_c12_low3_mask01_block00 ckpath_cert_k7_c12_low3_mask01_block02 ckpath_cert_k7_c12_low3_mask01_block03 ckpath_cert_k7_c12_low3_mask01_block04 ckpath_cert_k7_c12_low3_mask01_block05 ckpath_cert_k7_c12_low3_mask01_block06 ckpath_cert_k7_c12_low3_mask01_block07 ckpath_cert_k7_c12_low3_mask01_block09 ckpath_cert_k7_c12_low3_mask01_block10 ckpath_cert_k7_c12_low3_mask01_block11 ckpath_cert_k7_c12_low3_mask01_block13 ckpath_cert_k7_c12_low3_mask01_block14.
Import ListNotations.
Set Warnings "-abstract-large-number".

(** Original retained additions [375, 400); 252 selected base clauses and 40 imported consequences from 12 producer blocks. *)
Definition c12_k7_low3_mask01_block15_output : cnf :=
  [
  [(30,true);(26,true);(32,true);(135,false);(126,true);(123,true);(130,true)];
  [(144,true);(30,false);(101,false)];
  [(30,false);(123,true);(130,true);(126,true);(101,false)];
  [(144,false);(26,false);(123,true);(130,true);(126,true)];
  [(126,true);(123,true);(130,true);(101,false)];
  [(100,false);(101,false);(142,false)];
  [(103,true);(135,false);(123,false);(104,true);(142,false)];
  [(135,false);(123,false);(104,true);(142,false)];
  [(123,false);(104,true);(142,false)];
  [(135,true);(126,false);(101,false)];
  [(110,true);(135,false);(104,true);(142,false)];
  [(130,true);(104,true);(142,false)];
  [(126,false);(104,true);(142,false)];
  [(110,false);(104,true);(142,false)];
  [(104,true);(142,false)];
  [(135,true);(101,false);(53,true)];
  [(123,false);(98,true);(99,true);(141,false);(135,false);(32,true)];
  [(89,true);(141,false);(98,true);(99,true);(135,false);(32,true)];
  [(141,false);(143,false);(101,false);(135,false)];
  [(123,false);(143,false);(137,false);(54,true);(135,false);(53,true)];
  [(112,false);(137,false);(101,false);(53,true)];
  [(143,false);(101,false);(53,true)];
  [(45,false);(130,true);(101,false);(137,false)];
  [(45,true);(30,true);(101,false);(53,true)];
  [(130,false);(98,true);(141,false);(135,false);(32,true)]
].

Theorem c12_k7_low3_mask01_block15_sound :
  forall rho, satisfies_cnf rho (c12_k7_low3_instance [true; false; false; true; false; false; false; true; false; false; false; false]) ->
    satisfies_cnf rho c12_k7_low3_mask01_block15_output.
Proof.
intros rho Hbase.
pose (select_cnf c12_k7_low3_mask01_block00_output [0;1;2;3;4;5;6;7;8;9;10;11] : cnf)
  as imported_from_block00.
assert (Himported_from_block00 :
  satisfies_cnf rho imported_from_block00).
{
  unfold imported_from_block00.
  apply (satisfies_cnf_select rho c12_k7_low3_mask01_block00_output [0;1;2;3;4;5;6;7;8;9;10;11]).
  - exact (c12_k7_low3_mask01_block00_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask01_block02_output [2] : cnf)
  as imported_from_block02.
assert (Himported_from_block02 :
  satisfies_cnf rho imported_from_block02).
{
  unfold imported_from_block02.
  apply (satisfies_cnf_select rho c12_k7_low3_mask01_block02_output [2]).
  - exact (c12_k7_low3_mask01_block02_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask01_block03_output [11] : cnf)
  as imported_from_block03.
assert (Himported_from_block03 :
  satisfies_cnf rho imported_from_block03).
{
  unfold imported_from_block03.
  apply (satisfies_cnf_select rho c12_k7_low3_mask01_block03_output [11]).
  - exact (c12_k7_low3_mask01_block03_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask01_block04_output [6] : cnf)
  as imported_from_block04.
assert (Himported_from_block04 :
  satisfies_cnf rho imported_from_block04).
{
  unfold imported_from_block04.
  apply (satisfies_cnf_select rho c12_k7_low3_mask01_block04_output [6]).
  - exact (c12_k7_low3_mask01_block04_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask01_block05_output [18;21] : cnf)
  as imported_from_block05.
assert (Himported_from_block05 :
  satisfies_cnf rho imported_from_block05).
{
  unfold imported_from_block05.
  apply (satisfies_cnf_select rho c12_k7_low3_mask01_block05_output [18;21]).
  - exact (c12_k7_low3_mask01_block05_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask01_block06_output [10;5;2;12;14;13;23] : cnf)
  as imported_from_block06.
assert (Himported_from_block06 :
  satisfies_cnf rho imported_from_block06).
{
  unfold imported_from_block06.
  apply (satisfies_cnf_select rho c12_k7_low3_mask01_block06_output [10;5;2;12;14;13;23]).
  - exact (c12_k7_low3_mask01_block06_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask01_block07_output [18;24;19;0;22] : cnf)
  as imported_from_block07.
assert (Himported_from_block07 :
  satisfies_cnf rho imported_from_block07).
{
  unfold imported_from_block07.
  apply (satisfies_cnf_select rho c12_k7_low3_mask01_block07_output [18;24;19;0;22]).
  - exact (c12_k7_low3_mask01_block07_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask01_block09_output [19;9] : cnf)
  as imported_from_block09.
assert (Himported_from_block09 :
  satisfies_cnf rho imported_from_block09).
{
  unfold imported_from_block09.
  apply (satisfies_cnf_select rho c12_k7_low3_mask01_block09_output [19;9]).
  - exact (c12_k7_low3_mask01_block09_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask01_block10_output [11] : cnf)
  as imported_from_block10.
assert (Himported_from_block10 :
  satisfies_cnf rho imported_from_block10).
{
  unfold imported_from_block10.
  apply (satisfies_cnf_select rho c12_k7_low3_mask01_block10_output [11]).
  - exact (c12_k7_low3_mask01_block10_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask01_block11_output [24] : cnf)
  as imported_from_block11.
assert (Himported_from_block11 :
  satisfies_cnf rho imported_from_block11).
{
  unfold imported_from_block11.
  apply (satisfies_cnf_select rho c12_k7_low3_mask01_block11_output [24]).
  - exact (c12_k7_low3_mask01_block11_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask01_block13_output [14] : cnf)
  as imported_from_block13.
assert (Himported_from_block13 :
  satisfies_cnf rho imported_from_block13).
{
  unfold imported_from_block13.
  apply (satisfies_cnf_select rho c12_k7_low3_mask01_block13_output [14]).
  - exact (c12_k7_low3_mask01_block13_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask01_block14_output [13;24;20;23;16;22] : cnf)
  as imported_from_block14.
assert (Himported_from_block14 :
  satisfies_cnf rho imported_from_block14).
{
  unfold imported_from_block14.
  apply (satisfies_cnf_select rho c12_k7_low3_mask01_block14_output [13;24;20;23;16;22]).
  - exact (c12_k7_low3_mask01_block14_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (concat [imported_from_block00;imported_from_block02;imported_from_block03;imported_from_block04;imported_from_block05;imported_from_block06;imported_from_block07;imported_from_block09;imported_from_block10;imported_from_block11;imported_from_block13;imported_from_block14] : cnf) as imported.
assert (Himported : satisfies_cnf rho imported).
{
  unfold imported.
  apply satisfies_cnf_concat_intro.
  constructor.
  { exact Himported_from_block00. }
  constructor.
  { exact Himported_from_block02. }
  constructor.
  { exact Himported_from_block03. }
  constructor.
  { exact Himported_from_block04. }
  constructor.
  { exact Himported_from_block05. }
  constructor.
  { exact Himported_from_block06. }
  constructor.
  { exact Himported_from_block07. }
  constructor.
  { exact Himported_from_block09. }
  constructor.
  { exact Himported_from_block10. }
  constructor.
  { exact Himported_from_block11. }
  constructor.
  { exact Himported_from_block13. }
  constructor.
  { exact Himported_from_block14. }
  constructor.
}
pose (
  [66;67;68;69;70;71;72;73;74;75;76;77;1479;1489;4153;1500;1495;1429;1502;23;2860;1058;24;2861;1059;27;1062;25;2862;1;29;1064;3844;212;176;210;213;99;201;191;26;2842;1061;2825;2834;18;1804;2832;1076;1084;1070;1081;4158;4154;4157;4159;1063;4156;4155;2972;2936;2966;3876;3880;3878;3859;3873;2849;22;1813;1057;2859;1806;1801;1810;1795;1787;2946;2911;2982;2985;2986;17;1075;1080;1069;41;47;52;2248;2228;2255;2258;8;2831;1088;1803;20;1065;3231;3228;3229;3230;3213;64;1087;2830;48;2836;53;2837;57;2838;2833;175;209;190;200;1431;1468;1465;1462;1446;1456;1072;1086;1078;1083;1060;35;80;91;96;98;86;1089;2917;2921;2920;2901;3240;3243;3221;3242;2826;2828;2159;2193;97;44;2850;1775;1798;1784;1792;1807;1850;1869;1835;1870;1866;1860;3855;3889;3886;3890;3870;2848;55;2852;50;2851;62;3845;3877;3860;3879;3874;2822;37;59;2853;1538;2839;2835;2519;2497;2507;2516;2482;2513;1864;1833;1867;1848;1858;2174;2190;2196;2184;1082;1383;32;1696;2886;1467;1460;1454;1444;2824;1799;2823;7;1071;40;1067;1770;2864;1776;1068;2844;1066;2863;3527;3521;3516;3526;19;1939;1905;1940;1935;1925;1503;1483;208;173;188;198;61;3578;3576;3;211;2827;2913;2968;2987;2978;2948;2551;2480] : list nat) as base_ids.
pose ([
  ([59;51;63;268;251;245;259],[0;1;2;3;4;5;6;7;8;9;10;11;252;253;254;255;256;257;258;259;260;261;262;263;266;267;281;286;12;13;268;14;15;16;17;18;19;20;21;22;23;24;25;26;27;28;29;30;31;32;287]);
  ([287;58;200],[0;1;2;3;4;5;6;7;8;9;10;11;252;253;254;255;256;257;258;259;260;261;262;263;266;267;281;286;33;34;35;36;37;38;39;40;41;269;42;43;44;45;46;47;48;49;50;51;52;288;53;54;276;55;14;56;57;58;59;60;61]);
  ([58;245;259;251;200],[0;1;2;3;4;5;6;7;8;9;10;11;252;253;254;255;256;257;258;259;260;261;262;263;266;267;281;286;40;293;289;45;62;63;282;64;32;65;66;67]);
  ([286;50;245;259;251],[0;1;2;3;4;5;6;7;8;9;10;11;252;253;254;255;256;257;258;259;260;261;262;263;266;267;281;286;62;63;282;64;32;65;66;68;69]);
  ([251;245;259;200],[0;1;2;3;4;5;6;7;8;9;10;11;252;253;254;255;256;257;258;259;260;261;262;263;266;267;281;286;289;294;45;14;56;292;68;295;70;71;33;34;35;36;38;39;52;288;46;47;72;53;50;54;276;49;73;55;74;57;51;75;58;48;76;77;78;79;80;81;61;82;83;84;26;85;86;264;87;88;89;90;91;92]);
  ([198;200;282],[0;1;2;3;4;5;6;7;8;9;10;11;252;253;254;255;256;257;258;259;260;261;262;263;266;267;281;286;93;94;95;96;45;52;46;47;294;296]);
  ([205;268;244;207;282],[0;1;2;3;4;5;6;7;8;9;10;11;252;253;254;255;256;257;258;259;260;261;262;263;266;267;281;286;14;97;98;95;290;52;46;47;99;100;101;102;103;45;56;104;105;106;288;107;108;109;110;111;112;25;113;36;114;115;116;117;118;119;120;121;122;123;69;53;50;124;54;49;73;125;58;48;76;126;57;51;75;127;284;68;70;71;270;30;40;42;27;128]);
  ([268;244;207;282],[0;1;2;3;4;5;6;7;8;9;10;11;252;253;254;255;256;257;258;259;260;261;262;263;266;267;281;286;14;298;97;98;95;290;52;46;47;129;72;44;45;56;16;17]);
  ([244;207;282],[0;1;2;3;4;5;6;7;8;9;10;11;252;253;254;255;256;257;258;259;260;261;262;263;266;267;281;286;97;95;299;52;291;46;47;37;130;131;132;133;134;45;53;50;124;57;51;127;54;49;125;55;288;135;276;58;48;126;277;278;136;137;138;139;78;99;140;141;142;143;265;82;83;84;85;86;144;264;88;145;73;129;111;25;146;147]);
  ([269;250;200],[0;1;2;3;4;5;6;7;8;9;10;11;252;253;254;255;256;257;258;259;260;261;262;263;266;267;281;286;148;37;130;131;132;133;134;149;96;150;151;152;153;154;155;45;52;46;47;53;50;57;51;54;49;55;288;276;58;48;264;156;157;158;159;160;161;136]);
  ([219;268;207;282],[0;1;2;3;4;5;6;7;8;9;10;11;252;253;254;255;256;257;258;259;260;261;262;263;266;267;281;286;14;299;52;291;46;47;45;297;56;99;140;141;142;143;129;72;44;107;108;111;112;25;113;109;110;16;17;18;12;13;268;15]);
  ([259;207;282],[0;1;2;3;4;5;6;7;8;9;10;11;252;253;254;255;256;257;258;259;260;261;262;263;266;267;281;286;300;52;291;46;47;296;45;297;149;301;14;302;56;104;105;106;288;36;114;115;116;117;162;163;164;165;166;150;53;50;151;264;156;157;158;159;160;161;54;49;152;58;48;153;57;51;154;30;167;168;169;170;171]);
  ([250;207;282],[0;1;2;3;4;5;6;7;8;9;10;11;252;253;254;255;256;257;258;259;260;261;262;263;266;267;281;286;149;96;300;303;52;291;46;47;172;45;301;14;302;56;104;105;106;288;36;114;115;116;117;150;53;50;151;264;156;157;158;159;160;161;54;49;152;285;279;265;58;48;153;57;51;154;136]);
  ([218;207;282],[0;1;2;3;4;5;6;7;8;9;10;11;252;253;254;255;256;257;258;259;260;261;262;263;266;267;281;286;104;105;106;288;300;303;304;52;291;46;47;36;133;114;115;116;117;172;94;173;174;175;176;177;45;14;56;53;50;54;49;178;285;279;265;58;48;57;51;30;167;168;169;179;69;180;181;170;171;136;137;138;139;78;84;85;26;182]);
  ([207;282],[0;1;2;3;4;5;6;7;8;9;10;11;252;253;254;255;256;257;258;259;260;261;262;263;266;267;281;286;300;303;304;305;52;291;46;47;172;94;302;99;140;141;142;143;45;37;130;131;132;133;134;129;72;44;107;108;111;112;25;113;109;110;53;50;57;51;54;49;178;279;55;280;183;277]);
  ([269;200;105],[0;1;2;3;4;5;6;7;8;9;10;11;252;253;254;255;256;257;258;259;260;261;262;263;266;267;281;286;148;37;130;131;132;133;134;301;45;297;52;46;47;306;53;50;57;51;54;49;55;288;276;58;48;184;277;278;265;296;82;83;84;97;124;125;126;127;135;185;186;187;188;189;190;159;191;192;193;194;195;136;137;138;139;78;146;147;196;197;198;199;168;200;22;201;202;75;203;88]);
  ([244;195;197;280;268;63],[0;1;2;3;4;5;6;7;8;9;10;11;252;253;254;255;256;257;258;259;260;261;262;263;266;267;281;286;97;125;265;54;14;98;136;137;138;139;78;204;205;120;17;206;207;208;86;144;88;145;209;73]);
  ([177;280;195;197;268;63],[0;1;2;3;4;5;6;7;8;9;10;11;252;253;254;255;256;257;258;259;260;261;262;263;266;267;281;286;136;137;138;139;78;204;54;308;265;14;86;144;88;145;209;73;210;211;26;16;17;18;12;13;268;15]);
  ([280;284;200;268],[0;1;2;3;4;5;6;7;8;9;10;11;252;253;254;255;256;257;258;259;260;261;262;263;266;267;281;286;54;49;55;276;45;14;56;308;265;309;212;178;152;296]);
  ([244;284;272;107;268;105],[0;1;2;3;4;5;6;7;8;9;10;11;252;253;254;255;256;257;258;259;260;261;262;263;266;267;281;286;97;98;135;55;53;124;14;159;191;192;193;194;195;149;213;214;215;216;217;218;21;86;219;220;68;221;222;280;271;223;224;225;226]);
  ([222;272;200;105],[0;1;2;3;4;5;6;7;8;9;10;11;252;253;254;255;256;257;258;259;260;261;262;263;266;267;281;286;227;213;53;50;45;307;56;264;228;229;230;159;231;232;14;31;214;215;216;217;218;21;219;124;151;221;222;68;233;234]);
  ([284;200;105],[0;1;2;3;4;5;6;7;8;9;10;11;252;253;254;255;256;257;258;259;260;261;262;263;266;267;281;286;55;45;307;56;14;310;235;236;35;237;238;52;46;47;306;288;297;53;50;312;311;272;58;48;57;51;184;280;271;273;274;296;239;240;241;225]);
  ([88;259;200;272],[0;1;2;3;4;5;6;7;8;9;10;11;252;253;254;255;256;257;258;259;260;261;262;263;266;267;281;286;242;124;151;296]);
  ([89;59;200;105],[0;1;2;3;4;5;6;7;8;9;10;11;252;253;254;255;256;257;258;259;260;261;262;263;266;267;281;286;45;307;56;313;14;243;36;114;115;116;117;52;46;47;306;297;53;50;312;159;191;192;193;194;195;54;49;283;244;58;48;57;51;184;149;214;215;216;217;21;86;219;108;171;68;221;222;245;246;247;248;249;250;251;275]);
  ([258;195;280;268;63],[0;1;2;3;4;5;6;7;8;9;10;11;252;253;254;255;256;257;258;259;260;261;262;263;266;267;281;286;172;178;279;54;14;265;309])
] : list (list nat * list nat)) as records.
assert (Hcheck :
  check_selected_microblock (c12_k7_low3_instance [true; false; false; true; false; false; false; true; false; false; false; false]) base_ids
    imported records c12_k7_low3_mask01_block15_output = true).
{ vm_compute. reflexivity. }
exact (check_selected_microblock_sound
  (c12_k7_low3_instance [true; false; false; true; false; false; false; true; false; false; false; false]) base_ids imported records c12_k7_low3_mask01_block15_output
  Hcheck rho Hbase Himported).
Qed.
