(** Generated by [scripts/generate_ckpath_certificates.py].
    Only the block output is transparent.  Selected base clauses,
    producer imports, replay records, and the transient database
    all remain underneath the opaque soundness theorem. *)

From Stdlib Require Import List.
From Digraph Require Import ckpath_cnf ckpath_drup_microblock ckpath_cert_k7_base ckpath_cert_k7_c12_cover4_micro_block000 ckpath_cert_k7_c12_cover4_micro_block011 ckpath_cert_k7_c12_cover4_micro_block013 ckpath_cert_k7_c12_cover4_micro_block017 ckpath_cert_k7_c12_cover4_micro_block018 ckpath_cert_k7_c12_cover4_micro_block019 ckpath_cert_k7_c12_cover4_micro_block021 ckpath_cert_k7_c12_cover4_micro_block023 ckpath_cert_k7_c12_cover4_micro_block024 ckpath_cert_k7_c12_cover4_micro_block032 ckpath_cert_k7_c12_cover4_micro_block037 ckpath_cert_k7_c12_cover4_micro_block040 ckpath_cert_k7_c12_cover4_micro_block041 ckpath_cert_k7_c12_cover4_micro_block042 ckpath_cert_k7_c12_cover4_micro_block054 ckpath_cert_k7_c12_cover4_micro_block064 ckpath_cert_k7_c12_cover4_micro_block065 ckpath_cert_k7_c12_cover4_micro_block066 ckpath_cert_k7_c12_cover4_micro_block067.
Import ListNotations.
Set Warnings "-abstract-large-number".

(** Original retained additions [1700, 1725); 313 selected base clauses and 40 imported consequences from 19 producer blocks. *)
Definition c12_k7_cover4_micro_block068_output : cnf :=
  [
  [(38,false);(55,true);(46,true);(137,true);(149,true);(142,false);(139,false)];
  [(39,false);(135,false);(138,true);(149,true);(142,false);(139,false)];
  [(38,false);(126,true);(149,true);(142,false);(139,false);(145,true);(135,false);(151,true);(140,true);(154,true);(137,true)];
  [(46,true);(126,true);(142,false);(145,true);(139,false);(151,true);(154,true);(149,true);(137,true);(135,false);(140,true)];
  [(98,false);(126,true);(149,true);(142,false);(151,true);(135,false);(139,false);(145,true);(140,true)];
  [(126,true);(149,true);(135,false);(39,true);(154,true);(151,true);(142,false);(145,true);(140,true);(147,true);(137,true)];
  [(140,true);(144,true);(142,false);(136,true);(154,true);(150,false);(137,true);(134,true);(143,true)];
  [(38,false);(46,true);(137,true);(140,false);(149,true);(142,false);(139,false)];
  [(127,true);(42,true);(38,true);(149,true);(144,true);(126,true);(131,true)];
  [(127,false);(46,true);(137,true);(142,false);(145,true);(140,false);(139,false)];
  [(98,false);(38,true);(149,true);(126,true);(127,true);(142,false);(145,true)];
  [(46,true);(126,true);(140,false);(145,true);(142,false);(139,false);(154,true);(151,true);(137,true);(149,true)];
  [(98,false);(126,true);(139,false);(145,true);(16,true);(15,true);(142,false);(147,true)];
  [(125,false);(27,true);(140,false);(145,true);(142,false);(139,false)];
  [(131,true);(27,true);(26,true);(148,true);(126,true);(125,true);(144,true)];
  [(128,false);(66,true);(138,true);(140,false);(145,true);(139,false);(142,false)];
  [(126,true);(140,false);(145,true);(139,false);(142,false);(151,true);(154,true);(149,true);(147,true);(148,true);(137,true)];
  [(140,false);(151,true);(142,false);(136,true);(137,true);(154,true);(150,false)];
  [(38,false);(46,true);(137,true);(149,true);(144,false);(142,false);(139,false)];
  [(54,true);(51,true);(142,false);(148,true);(144,false);(31,true);(140,true);(46,true);(137,true)];
  [(54,false);(20,true);(139,false);(156,true);(144,false);(147,true);(119,true);(142,false)];
  [(98,false);(46,true);(148,true);(139,false);(153,true);(142,false);(144,false);(137,true);(156,true);(147,true)];
  [(54,true);(51,true);(141,true);(148,true);(144,false);(98,true);(137,true);(46,true);(142,false);(140,true)];
  [(26,false);(38,true);(136,true);(148,true);(139,false);(142,false)];
  [(31,true);(27,true);(142,false);(148,true);(144,false);(140,true);(26,true)]
].

Theorem c12_k7_cover4_micro_block068_sound :
  forall rho, satisfies_cnf rho ((c12_k7_cover_base 4)) ->
    satisfies_cnf rho c12_k7_cover4_micro_block068_output.
Proof.
intros rho Hbase.
pose (select_cnf c12_k7_cover4_micro_block000_output [3] : cnf)
  as imported_from_block000.
assert (Himported_from_block000 :
  satisfies_cnf rho imported_from_block000).
{
  unfold imported_from_block000.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block000_output [3]).
  - exact (c12_k7_cover4_micro_block000_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block011_output [15;17] : cnf)
  as imported_from_block011.
assert (Himported_from_block011 :
  satisfies_cnf rho imported_from_block011).
{
  unfold imported_from_block011.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block011_output [15;17]).
  - exact (c12_k7_cover4_micro_block011_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block013_output [3] : cnf)
  as imported_from_block013.
assert (Himported_from_block013 :
  satisfies_cnf rho imported_from_block013).
{
  unfold imported_from_block013.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block013_output [3]).
  - exact (c12_k7_cover4_micro_block013_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block017_output [11] : cnf)
  as imported_from_block017.
assert (Himported_from_block017 :
  satisfies_cnf rho imported_from_block017).
{
  unfold imported_from_block017.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block017_output [11]).
  - exact (c12_k7_cover4_micro_block017_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block018_output [7] : cnf)
  as imported_from_block018.
assert (Himported_from_block018 :
  satisfies_cnf rho imported_from_block018).
{
  unfold imported_from_block018.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block018_output [7]).
  - exact (c12_k7_cover4_micro_block018_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block019_output [11;17;18] : cnf)
  as imported_from_block019.
assert (Himported_from_block019 :
  satisfies_cnf rho imported_from_block019).
{
  unfold imported_from_block019.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block019_output [11;17;18]).
  - exact (c12_k7_cover4_micro_block019_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block021_output [22] : cnf)
  as imported_from_block021.
assert (Himported_from_block021 :
  satisfies_cnf rho imported_from_block021).
{
  unfold imported_from_block021.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block021_output [22]).
  - exact (c12_k7_cover4_micro_block021_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block023_output [5] : cnf)
  as imported_from_block023.
assert (Himported_from_block023 :
  satisfies_cnf rho imported_from_block023).
{
  unfold imported_from_block023.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block023_output [5]).
  - exact (c12_k7_cover4_micro_block023_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block024_output [15;12;21;19;0] : cnf)
  as imported_from_block024.
assert (Himported_from_block024 :
  satisfies_cnf rho imported_from_block024).
{
  unfold imported_from_block024.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block024_output [15;12;21;19;0]).
  - exact (c12_k7_cover4_micro_block024_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block032_output [8] : cnf)
  as imported_from_block032.
assert (Himported_from_block032 :
  satisfies_cnf rho imported_from_block032).
{
  unfold imported_from_block032.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block032_output [8]).
  - exact (c12_k7_cover4_micro_block032_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block037_output [8] : cnf)
  as imported_from_block037.
assert (Himported_from_block037 :
  satisfies_cnf rho imported_from_block037).
{
  unfold imported_from_block037.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block037_output [8]).
  - exact (c12_k7_cover4_micro_block037_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block040_output [3] : cnf)
  as imported_from_block040.
assert (Himported_from_block040 :
  satisfies_cnf rho imported_from_block040).
{
  unfold imported_from_block040.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block040_output [3]).
  - exact (c12_k7_cover4_micro_block040_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block041_output [13] : cnf)
  as imported_from_block041.
assert (Himported_from_block041 :
  satisfies_cnf rho imported_from_block041).
{
  unfold imported_from_block041.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block041_output [13]).
  - exact (c12_k7_cover4_micro_block041_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block042_output [24] : cnf)
  as imported_from_block042.
assert (Himported_from_block042 :
  satisfies_cnf rho imported_from_block042).
{
  unfold imported_from_block042.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block042_output [24]).
  - exact (c12_k7_cover4_micro_block042_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block054_output [2;5] : cnf)
  as imported_from_block054.
assert (Himported_from_block054 :
  satisfies_cnf rho imported_from_block054).
{
  unfold imported_from_block054.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block054_output [2;5]).
  - exact (c12_k7_cover4_micro_block054_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block064_output [7] : cnf)
  as imported_from_block064.
assert (Himported_from_block064 :
  satisfies_cnf rho imported_from_block064).
{
  unfold imported_from_block064.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block064_output [7]).
  - exact (c12_k7_cover4_micro_block064_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block065_output [10;23] : cnf)
  as imported_from_block065.
assert (Himported_from_block065 :
  satisfies_cnf rho imported_from_block065).
{
  unfold imported_from_block065.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block065_output [10;23]).
  - exact (c12_k7_cover4_micro_block065_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block066_output [13;24;12;9;22;23] : cnf)
  as imported_from_block066.
assert (Himported_from_block066 :
  satisfies_cnf rho imported_from_block066).
{
  unfold imported_from_block066.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block066_output [13;24;12;9;22;23]).
  - exact (c12_k7_cover4_micro_block066_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block067_output [12;24;11;20;21;22;5;23] : cnf)
  as imported_from_block067.
assert (Himported_from_block067 :
  satisfies_cnf rho imported_from_block067).
{
  unfold imported_from_block067.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block067_output [12;24;11;20;21;22;5;23]).
  - exact (c12_k7_cover4_micro_block067_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (concat [imported_from_block000;imported_from_block011;imported_from_block013;imported_from_block017;imported_from_block018;imported_from_block019;imported_from_block021;imported_from_block023;imported_from_block024;imported_from_block032;imported_from_block037;imported_from_block040;imported_from_block041;imported_from_block042;imported_from_block054;imported_from_block064;imported_from_block065;imported_from_block066;imported_from_block067] : cnf) as imported.
assert (Himported : satisfies_cnf rho imported).
{
  unfold imported.
  apply satisfies_cnf_concat_intro.
  constructor.
  { exact Himported_from_block000. }
  constructor.
  { exact Himported_from_block011. }
  constructor.
  { exact Himported_from_block013. }
  constructor.
  { exact Himported_from_block017. }
  constructor.
  { exact Himported_from_block018. }
  constructor.
  { exact Himported_from_block019. }
  constructor.
  { exact Himported_from_block021. }
  constructor.
  { exact Himported_from_block023. }
  constructor.
  { exact Himported_from_block024. }
  constructor.
  { exact Himported_from_block032. }
  constructor.
  { exact Himported_from_block037. }
  constructor.
  { exact Himported_from_block040. }
  constructor.
  { exact Himported_from_block041. }
  constructor.
  { exact Himported_from_block042. }
  constructor.
  { exact Himported_from_block054. }
  constructor.
  { exact Himported_from_block064. }
  constructor.
  { exact Himported_from_block065. }
  constructor.
  { exact Himported_from_block066. }
  constructor.
  { exact Himported_from_block067. }
  constructor.
}
pose (
  [66;67;68;69;70;71;72;73;74;75;76;77;2014;31;4126;5020;3310;32;2282;5021;4127;2867;2619;486;4733;490;3827;0;11;21;30;38;45;51;56;60;63;65;10;2015;3599;2281;2866;2921;61;5024;4998;5031;3525;4431;5337;2317;13;2264;41;4090;3014;3016;3013;3015;2943;2978;5398;5338;5394;5395;5396;5397;2285;2870;2287;2872;2284;5023;2869;2286;2;2288;255;1580;1724;1728;1685;1202;44;4111;4993;3036;3038;2960;3034;2995;35;37;4129;4425;617;483;399;539;3287;3237;3308;3306;5454;5453;5451;5412;5432;5377;62;59;55;29;20;2956;50;4112;4994;594;4407;3297;47;4091;4383;4992;4405;4110;3285;3305;3235;3295;3307;2702;2722;2732;2741;2743;2667;43;22;5013;2376;2387;2383;2321;2380;2386;15;2265;5010;4122;2270;17;2267;5012;12;5007;4119;5011;4109;2269;5363;5345;5347;5346;5348;574;5437;5435;5438;2280;2620;2621;2622;2623;2624;2625;4408;4113;4995;3608;3649;2273;3326;3271;3336;3345;3347;5434;5360;5433;3;2295;39;42;4997;4378;64;4403;4108;4990;2301;4409;4996;4404;4991;1795;4483;4486;4487;4467;4477;4452;2385;4406;3024;2969;3045;3043;3004;5611;406;5604;2678;2689;2682;2688;2685;24;2274;5605;5016;2279;5610;25;2275;5606;5017;28;2278;5609;1;26;2276;5018;5607;3891;4196;4134;5009;4985;5149;5158;5139;5159;5119;5084;36;4983;4104;54;4986;4107;4982;4103;58;4102;4981;4101;2316;2408;2428;5019;4989;5034;40;4106;4082;4121;4124;4251;4252;4241;4231;4211;4176;4075;2308;5634;2309;5635;33;4080;4079;4078;2310;5056;27;2277;5608;4444;4438;4433;4514;4445;4123;2272;5014;3026;3028;2950;2985] : list nat) as base_ids.
pose ([
  ([74;109;91;273;297;282;276],[0;1;2;3;4;5;6;7;8;9;10;11;12;13;339;14;340;15;16]);
  ([76;268;275;297;282;276],[0;1;2;3;4;5;6;7;8;9;10;11;12;17;18;19;20;21;22;319;320;23;318;317;316;24;25;26;27;28;29;30;31;32;33;34;35;36;37;38;39;40]);
  ([74;251;297;282;276;289;268;301;279;307;273],[0;1;2;3;4;5;6;7;8;9;10;11;12;13;41;339;14;340;15;353;42;43;24;25;26;22;320;23;316;354;27;28;29;31;32;33;34;35;36;37;38;39;345;346]);
  ([91;251;282;289;276;301;307;297;273;268;279],[0;1;2;3;4;5;6;7;8;9;10;11;12;345;346]);
  ([194;251;297;282;301;268;276;289;279],[0;1;2;3;4;5;6;7;8;9;10;11;12;44;45;46;47;43;24;25;48;22;320;23;318;316;354;26;27;28;29;30;31;32;33;34;35;36;37;38;39;347]);
  ([251;297;268;77;307;301;282;289;279;293;273],[0;1;2;3;4;5;6;7;8;9;10;11;12;43;22;49;48;24;50;51;27;28;29;30;31;32;33;34;35;36;37;38;39;341;337;357;320;355;356;348;313;52;53;54;55;349;350;56;57;58;59;60;61;62;63;64;65;66;67;68;69;70;71;72;73;74;75;76;77]);
  ([279;287;282;271;307;298;273;267;285],[0;1;2;3;4;5;6;7;8;9;10;11;12;342;24;341;49;343;78;27;28;29;30;31;32;33;34;35;36;37;38;39;344;22;79;80;81;82;83;354;358;84;85;86;87;88;59;89;90;91;92;68;45;69;93;70;71;13;41;14;340;15;353]);
  ([74;91;273;278;297;282;276],[0;1;2;3;4;5;6;7;8;9;10;11;12;13;339;14;340;15;353;94;95;334;324;96;97;98;325;99;24;26;27;28;29;30;31;32;33;34;35;36;37;38;39;100;101;102;103]);
  ([253;83;75;297;287;251;261],[0;1;2;3;4;5;6;7;8;9;10;11;12;43;104;105;106;107;108;109;27;28;29;30;31;32;33;34;35;36;37;38;39;110;111;112;113;93;114;77;115]);
  ([252;91;273;282;289;278;276],[0;1;2;3;4;5;6;7;8;9;10;11;12;116;117;118;24;50;94;324;119;97;98;325;99;120;26;27;28;29;30;31;32;33;34;35;36;37;38;39;100;101;121;102;103]);
  ([194;75;297;251;253;282;289],[0;1;2;3;4;5;6;7;8;9;10;11;12;44;45;46;43;24;50;27;28;29;30;31;32;33;34;35;36;37;38;39;361]);
  ([91;251;278;289;282;276;307;301;273;297],[0;1;2;3;4;5;6;7;8;9;10;11;12;362;94;324;119;96;97;98;325;99;24;26;360;27;28;29;30;31;32;33;34;35;36;37;38;39;363;351;352;122;123;124;93;125;126;127;103;128;129;130;131;132;133;134;135;136;137;138;139;140]);
  ([194;251;276;289;31;29;282;293],[0;1;2;3;4;5;6;7;8;9;10;11;12;44;46;26;50;24;51;141;27;28;29;30;31;32;33;34;35;36;37;38;39;142;143;144;145;146;147;148;149;150;151;114;152;153;154;155;156;157;158;159;160;161;109;162;163;164;165;166]);
  ([248;53;278;289;282;276],[0;1;2;3;4;5;6;7;8;9;10;11;12;93;125;126;127;94;324;119;96;97;98;325;99;167;24;26;27;28;29;30;31;32;33;34;35;36;37;38;39;133;134]);
  ([261;53;51;295;251;249;287],[0;1;2;3;4;5;6;7;8;9;10;11;12;22;108;162;168;169;62;170;27;28;29;30;31;32;33;34;35;36;37;38;39;116;114;171;111;112;113;110;172;173;174;175;176;177]);
  ([254;131;275;278;289;276;282],[0;1;2;3;4;5;6;7;8;9;10;11;12;112;94;324;96;97;98;325;99;167;178;26;179;24;180;27;28;29;30;31;32;33;34;35;36;37;38;39;181;182]);
  ([251;278;289;276;282;301;307;297;293;295;273],[0;1;2;3;4;5;6;7;8;9;10;11;12;364;94;324;119;96;97;98;325;99;26;24;183;27;28;29;30;31;32;33;34;35;36;37;38;39;52;53;41;366;365;352;116;120;117;118;368;184;185;186;187;188;189;169;190;191;65;140;192;193;194;195;110;196;197;198;114;171;199;200;201;202;77;111;203;204;113;205;160;206;207;314;208;209;210;211;212;213;143;214]);
  ([278;301;282;271;273;307;298],[0;1;2;3;4;5;6;7;8;9;10;11;12;94;48;24;337;338;49;336;330;331;333;332;27;28;29;30;31;32;33;34;35;36;37;38;39;329;96;97;98;369;84;85;86;215;216;217;218;219;220;90;13;41;14;340;15;360]);
  ([74;91;273;297;286;282;276],[0;1;2;3;4;5;6;7;8;9;10;11;12;13;339;14;340;15;360;353;43;50;221;335;321;326;327;222;24;26;27;28;29;30;31;32;33;34;35;36;37;38;39;194;103;100;101]);
  ([107;101;282;295;286;61;279;91;273],[0;1;2;3;4;5;6;7;8;9;10;11;12;103;100;101;121;102;16;24;22;223;50;27;28;29;30;31;32;33;34;35;36;37;38;39;54;140;192;194;195;84;224;225;226;227;175;228;229;230;231;232;113;233;234;235;236;237;238;239;240;241;242;171;243;244;245;246;247;248;249]);
  ([106;39;276;311;286;293;237;282],[0;1;2;3;4;5;6;7;8;9;10;11;12;139;250;251;26;96;328;326;327;222;322;50;321;323;24;27;28;29;30;31;32;33;34;35;36;37;38;39;252;253;254;255;256;257;258;259;260;261;262;263;264;265;266;267;268;152;269;270;271;272]);
  ([194;91;295;276;305;282;286;273;311;293],[0;1;2;3;4;5;6;7;8;9;10;11;12;44;141;273;274;22;26;96;328;326;327;222;322;275;24;50;27;28;29;30;31;32;33;34;35;37;38;39;373;372;276;277;278;279;280;281;282;283;284;285;286;266;287;288;289;245;155;111;290;291;292;293;294;295;296;297]);
  ([107;101;281;295;286;195;273;91;282;279],[0;1;2;3;4;5;6;7;8;9;10;11;12;16;372;103;100;101;121;102;22;50;24;27;28;29;30;31;32;33;34;35;36;37;38;39;84;298;299;315;300;54;140;192;223;194;195;301;302;303;304;305]);
  ([50;75;271;295;276;282],[0;1;2;3;4;5;6;7;8;9;10;11;12;140;306;307;308;309;310;311;216;312]);
  ([61;53;282;295;286;279;51],[0;1;2;3;4;5;6;7;8;9;10;11;12;24;22;50;224;225;226;227;175;228;27;28;29;30;31;32;33;34;35;36;37;38;39;229;230;231;232;113;233;234;235;236;237;238;239;240;241;242;171;243;244;245;246;248;249])
] : list (list nat * list nat)) as records.
assert (Hcheck :
  check_selected_microblock ((c12_k7_cover_base 4)) base_ids
    imported records c12_k7_cover4_micro_block068_output = true).
{ vm_compute. reflexivity. }
exact (check_selected_microblock_sound
  ((c12_k7_cover_base 4)) base_ids imported records c12_k7_cover4_micro_block068_output
  Hcheck rho Hbase Himported).
Qed.
