(** Generated by [scripts/generate_ckpath_certificates.py].
    Only the block output is transparent.  Selected base clauses,
    producer imports, replay records, and the transient database
    all remain underneath the opaque soundness theorem. *)

From Stdlib Require Import List.
From Digraph Require Import ckpath_cnf ckpath_drup_microblock ckpath_cert_k7_base ckpath_cert_k7_c12_cover4_micro_block000 ckpath_cert_k7_c12_cover4_micro_block011 ckpath_cert_k7_c12_cover4_micro_block012 ckpath_cert_k7_c12_cover4_micro_block013 ckpath_cert_k7_c12_cover4_micro_block015 ckpath_cert_k7_c12_cover4_micro_block016 ckpath_cert_k7_c12_cover4_micro_block017 ckpath_cert_k7_c12_cover4_micro_block018 ckpath_cert_k7_c12_cover4_micro_block019 ckpath_cert_k7_c12_cover4_micro_block020 ckpath_cert_k7_c12_cover4_micro_block023 ckpath_cert_k7_c12_cover4_micro_block024 ckpath_cert_k7_c12_cover4_micro_block025 ckpath_cert_k7_c12_cover4_micro_block030 ckpath_cert_k7_c12_cover4_micro_block048 ckpath_cert_k7_c12_cover4_micro_block049.
Import ListNotations.
Set Warnings "-abstract-large-number".

(** Original retained additions [1250, 1275); 236 selected base clauses and 41 imported consequences from 16 producer blocks. *)
Definition c12_k7_cover4_micro_block050_output : cnf :=
  [
  [(40,false);(142,false);(143,false);(149,true);(139,true);(140,false)];
  [(39,false);(62,true);(138,true);(64,true);(140,false);(149,true)];
  [(142,false);(143,false);(154,true);(140,false);(149,true);(38,true);(64,true);(139,true);(151,true)];
  [(90,false);(135,false);(149,true);(140,false);(39,true);(38,true);(152,true)];
  [(135,false);(98,true);(143,false);(144,true);(142,true);(151,true);(62,true);(64,true);(140,false);(154,true);(149,true);(38,true);(152,true)];
  [(90,false);(134,false);(149,true);(143,false);(39,true);(38,true);(152,true)];
  [(98,true);(144,true);(38,true);(151,true);(143,false);(62,true);(64,true);(140,false);(154,true);(149,true);(152,true);(137,true)];
  [(40,false);(75,true);(139,true);(143,false);(149,true);(135,false)];
  [(135,false);(101,true);(154,true);(143,false);(149,true);(39,true);(38,true);(140,false);(110,true);(142,true);(152,true)];
  [(144,true);(62,true);(149,true);(38,true);(154,true);(137,true);(140,false);(152,true);(151,true);(143,false);(64,true)];
  [(40,false);(144,false);(143,false);(149,true);(140,false);(139,true)];
  [(62,true);(143,false);(149,true);(38,true);(140,false);(154,true);(137,true);(152,true);(151,true);(64,true)];
  [(143,false);(64,true);(137,true);(140,false);(149,true);(38,true);(154,true);(152,true);(151,true)];
  [(40,false);(135,false);(142,false);(149,true);(140,false);(139,true)];
  [(135,false);(39,true);(154,true);(142,false);(149,true);(140,false);(38,true);(152,true)];
  [(40,false);(134,false);(142,false);(149,true);(140,false);(139,true)];
  [(134,false);(39,true);(142,false);(149,true);(141,true);(38,true);(140,false);(139,true)];
  [(40,false);(144,false);(142,false);(149,true);(140,false);(139,true)];
  [(39,true);(142,false);(154,true);(140,false);(149,true);(38,true);(137,true);(138,true);(143,true);(152,true)];
  [(142,false);(64,true);(138,true);(149,true);(140,false);(154,true);(38,true);(137,true);(143,true);(152,true)];
  [(40,false);(135,false);(140,false);(149,true);(139,true);(134,false)];
  [(144,true);(39,true);(154,true);(149,true);(140,false);(38,true);(152,true);(143,true);(137,true);(138,true);(142,true)];
  [(40,false);(135,false);(140,false);(149,true);(139,true);(144,false)];
  [(135,false);(144,false);(154,true);(149,true);(140,false);(39,true);(38,true);(152,true)];
  [(40,false);(134,false);(140,false);(149,true);(139,true);(144,false)]
].

Theorem c12_k7_cover4_micro_block050_sound :
  forall rho, satisfies_cnf rho ((c12_k7_cover_base 4)) ->
    satisfies_cnf rho c12_k7_cover4_micro_block050_output.
Proof.
intros rho Hbase.
pose (select_cnf c12_k7_cover4_micro_block000_output [3] : cnf)
  as imported_from_block000.
assert (Himported_from_block000 :
  satisfies_cnf rho imported_from_block000).
{
  unfold imported_from_block000.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block000_output [3]).
  - exact (c12_k7_cover4_micro_block000_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block011_output [15] : cnf)
  as imported_from_block011.
assert (Himported_from_block011 :
  satisfies_cnf rho imported_from_block011).
{
  unfold imported_from_block011.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block011_output [15]).
  - exact (c12_k7_cover4_micro_block011_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block012_output [22] : cnf)
  as imported_from_block012.
assert (Himported_from_block012 :
  satisfies_cnf rho imported_from_block012).
{
  unfold imported_from_block012.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block012_output [22]).
  - exact (c12_k7_cover4_micro_block012_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block013_output [8;6;9] : cnf)
  as imported_from_block013.
assert (Himported_from_block013 :
  satisfies_cnf rho imported_from_block013).
{
  unfold imported_from_block013.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block013_output [8;6;9]).
  - exact (c12_k7_cover4_micro_block013_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block015_output [4;6] : cnf)
  as imported_from_block015.
assert (Himported_from_block015 :
  satisfies_cnf rho imported_from_block015).
{
  unfold imported_from_block015.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block015_output [4;6]).
  - exact (c12_k7_cover4_micro_block015_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block016_output [17;16;14] : cnf)
  as imported_from_block016.
assert (Himported_from_block016 :
  satisfies_cnf rho imported_from_block016).
{
  unfold imported_from_block016.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block016_output [17;16;14]).
  - exact (c12_k7_cover4_micro_block016_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block017_output [16;15;17] : cnf)
  as imported_from_block017.
assert (Himported_from_block017 :
  satisfies_cnf rho imported_from_block017).
{
  unfold imported_from_block017.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block017_output [16;15;17]).
  - exact (c12_k7_cover4_micro_block017_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block018_output [12;11;13] : cnf)
  as imported_from_block018.
assert (Himported_from_block018 :
  satisfies_cnf rho imported_from_block018).
{
  unfold imported_from_block018.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block018_output [12;11;13]).
  - exact (c12_k7_cover4_micro_block018_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block019_output [23;24;1;11;3;22;13] : cnf)
  as imported_from_block019.
assert (Himported_from_block019 :
  satisfies_cnf rho imported_from_block019).
{
  unfold imported_from_block019.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block019_output [23;24;1;11;3;22;13]).
  - exact (c12_k7_cover4_micro_block019_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block020_output [0] : cnf)
  as imported_from_block020.
assert (Himported_from_block020 :
  satisfies_cnf rho imported_from_block020).
{
  unfold imported_from_block020.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block020_output [0]).
  - exact (c12_k7_cover4_micro_block020_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block023_output [12;11] : cnf)
  as imported_from_block023.
assert (Himported_from_block023 :
  satisfies_cnf rho imported_from_block023).
{
  unfold imported_from_block023.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block023_output [12;11]).
  - exact (c12_k7_cover4_micro_block023_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block024_output [5;22;7;24;23] : cnf)
  as imported_from_block024.
assert (Himported_from_block024 :
  satisfies_cnf rho imported_from_block024).
{
  unfold imported_from_block024.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block024_output [5;22;7;24;23]).
  - exact (c12_k7_cover4_micro_block024_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block025_output [0] : cnf)
  as imported_from_block025.
assert (Himported_from_block025 :
  satisfies_cnf rho imported_from_block025).
{
  unfold imported_from_block025.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block025_output [0]).
  - exact (c12_k7_cover4_micro_block025_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block030_output [10] : cnf)
  as imported_from_block030.
assert (Himported_from_block030 :
  satisfies_cnf rho imported_from_block030).
{
  unfold imported_from_block030.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block030_output [10]).
  - exact (c12_k7_cover4_micro_block030_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block048_output [22;20;12;5;3;1] : cnf)
  as imported_from_block048.
assert (Himported_from_block048 :
  satisfies_cnf rho imported_from_block048).
{
  unfold imported_from_block048.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block048_output [22;20;12;5;3;1]).
  - exact (c12_k7_cover4_micro_block048_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block049_output [13] : cnf)
  as imported_from_block049.
assert (Himported_from_block049 :
  satisfies_cnf rho imported_from_block049).
{
  unfold imported_from_block049.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block049_output [13]).
  - exact (c12_k7_cover4_micro_block049_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (concat [imported_from_block000;imported_from_block011;imported_from_block012;imported_from_block013;imported_from_block015;imported_from_block016;imported_from_block017;imported_from_block018;imported_from_block019;imported_from_block020;imported_from_block023;imported_from_block024;imported_from_block025;imported_from_block030;imported_from_block048;imported_from_block049] : cnf) as imported.
assert (Himported : satisfies_cnf rho imported).
{
  unfold imported.
  apply satisfies_cnf_concat_intro.
  constructor.
  { exact Himported_from_block000. }
  constructor.
  { exact Himported_from_block011. }
  constructor.
  { exact Himported_from_block012. }
  constructor.
  { exact Himported_from_block013. }
  constructor.
  { exact Himported_from_block015. }
  constructor.
  { exact Himported_from_block016. }
  constructor.
  { exact Himported_from_block017. }
  constructor.
  { exact Himported_from_block018. }
  constructor.
  { exact Himported_from_block019. }
  constructor.
  { exact Himported_from_block020. }
  constructor.
  { exact Himported_from_block023. }
  constructor.
  { exact Himported_from_block024. }
  constructor.
  { exact Himported_from_block025. }
  constructor.
  { exact Himported_from_block030. }
  constructor.
  { exact Himported_from_block048. }
  constructor.
  { exact Himported_from_block049. }
  constructor.
}
pose (
  [66;67;68;69;70;71;72;73;74;75;76;77;2014;33;2283;4427;5022;4733;586;551;5035;411;5318;4129;0;11;21;30;38;45;51;56;60;63;65;10;2015;3904;3894;3910;3844;3917;32;4426;2282;2921;3637;3647;3572;3648;3627;3607;3014;3016;2978;3015;3013;2943;35;2285;5320;5024;37;2287;12;36;2286;5321;34;2284;4382;5319;5023;2;2288;4521;4522;4502;4518;17;2619;3021;3827;2303;3017;3020;2945;2980;2872;2868;3899;3916;3893;3903;484;474;326;493;49;2299;5330;4;2301;2890;50;2300;2889;23;2892;14;2891;4744;4808;4813;4814;4794;5339;5364;5367;5365;5359;5366;8;42;53;57;27;29;55;5287;59;44;62;4387;4378;2317;2576;2577;2579;2581;2582;2580;3918;3907;3913;3847;3897;3525;4431;250;2594;2596;2595;2597;4739;4803;4798;4804;5351;5349;5352;5344;5350;4811;48;2870;2874;2869;4391;4506;61;5336;2311;2609;4801;5337;5613;553;3911;3905;3895;3845;626;5615;5617;5616;5614;46;2296;2591;4430;5327;413;492;325;3869;3945;495;4508;4512;4441;4505;353;408;389;3915;2578;4510;4491;552;607;251;5021;3592;3601;3613;327;308;3886;3885;283;292;4432;4489;4490;4492;4488;3835;4440;4439;4438;355;391;3839;3831;3830] : list nat) as base_ids.
pose ([
  ([78;282;284;297;277;278],[0;1;2;3;4;5;6;7;8;9;10;11;12;13;14;15;16;17;18;19;20;253;21;263;22;268;264;23;24;25;26;27;28;29;30;31;32;33;34;35;36;37;38;39;40;41]);
  ([76;123;275;127;278;297],[0;1;2;3;4;5;6;7;8;9;10;11;12;42;43;44;23;45;24;25;26;27;28;29;30;31;32;33;34;35;36;46;47;48;49;50;51]);
  ([282;284;307;278;297;75;127;277;301],[0;1;2;3;4;5;6;7;8;9;10;11;12;17;18;19;277;20;253;21;263;268;264;23;270;24;25;26;27;28;29;30;31;32;33;34;35;36;278;52;53;54;55;56;57;58;59;60;61;62;63;64;65;66;67;68;69;70;71;72;73;74;276;237;75;76;77;78]);
  ([178;268;297;278;77;75;303],[0;1;2;3;4;5;6;7;8;9;10;11;12;79;59;80;236;45;23;81;82;83;24;25;26;27;28;29;30;31;32;33;34;35;36;52;84;85;86;87;62;63;88;13;14;15;89;68;69;66;73;74;64;90;91;92;93]);
  ([268;195;284;287;283;301;123;127;278;307;297;75;303],[0;1;2;3;4;5;6;7;8;9;10;11;12;80;20;94;250;247;95;96;97;271;278;23;24;25;26;27;28;29;30;31;32;33;34;35;36;236;280;276;47;48;49;50;51;98;99;100;272;101;102;103;104;105;106;107;108;109;110;111;112;113;114;115;116;117;118;119;120;121;122;123;124;125;126;127;128;129;130;131;132;133;134;269]);
  ([178;266;297;284;77;75;303],[0;1;2;3;4;5;6;7;8;9;10;11;12;79;59;83;135;45;20;82;24;25;26;27;28;29;30;31;32;33;34;35;36;52;84;85;86;87;81;13;14;22;136;68;69;71;137;65;66;67;138;73;74;139;64;140;62;63;141;91;142;143;144;145;146]);
  ([195;287;75;301;284;123;127;278;307;297;303;273],[0;1;2;3;4;5;6;7;8;9;10;11;12;147;20;278;23;148;45;82;24;25;26;27;28;29;30;31;32;33;34;35;36;279;271;281;149;135;282;276;47;48;49;50;51;98;99;100;272;150;101;102;151;104;105;152;107;109;153;154;155;156;115;157;158;159;160;116;161;162;122;124;123;58;125;132;133;134;128;129;62;131;130;52;84;85;86;87;81]);
  ([78;149;277;284;297;268],[0;1;2;3;4;5;6;7;8;9;10;11;12;13;14;22;20;45;80;89;24;25;26;27;28;29;30;31;32;33;34;35;36;91;142;143]);
  ([268;201;307;284;297;77;75;278;219;283;303],[0;1;2;3;4;5;6;7;8;9;10;11;12;80;94;247;148;20;236;23;280;96;250;260;95;24;25;26;27;28;29;30;31;32;33;34;35;36;111;112;113;114;115;163;122;123;124;125;126;164;284;52;53;54;55;56;57;165;60;62;63;88;64;166;69;167;71;70;168;74;169]);
  ([287;123;297;75;307;273;278;303;301;284;127],[0;1;2;3;4;5;6;7;8;9;10;11;12;45;148;23;82;147;283;20;24;25;26;27;28;29;30;31;32;33;34;35;36;279;278;170;171;172;271;285;149;135;282;173;155;156;115;157;174;154;124;123;58;125;122;52;84;85;86;87;81;13;14;22;15;136;68;69;71;70;168;137;65;73;74;139;64;140;62;63;141;91]);
  ([78;286;284;297;278;277],[0;1;2;3;4;5;6;7;8;9;10;11;12;13;14;22;15;277;175;176;265;244;266;177;261;20;23;260;24;25;26;27;28;29;30;31;32;33;34;35;36;178;41;179;91;180;181]);
  ([123;284;297;75;278;307;273;303;301;127],[0;1;2;3;4;5;6;7;8;9;10;11;12;286;20;45;23;260;148;82;147;24;25;26;27;28;29;30;31;32;33;34;35;36;175;182;244;287;278;271;52;53;54;55;56;57;58;59;60;183;62;63;184;64;65;66;67;185;68;69;71;70;186;73;74;111]);
  ([284;127;273;278;297;75;307;303;301],[0;1;2;3;4;5;6;7;8;9;10;11;12;20;288;23;45;148;82;147;24;25;26;27;28;29;30;31;32;33;34;35;36;187;188;270;273;189;274;190;191;178;271;135;239;192;275;180]);
  ([78;268;282;297;278;277],[0;1;2;3;4;5;6;7;8;9;10;11;12;13;14;15;80;89;17;277;254;251;248;193;255;194;16;23;24;25;26;27;28;29;30;31;32;33;34;35;36;39;195;196;179;37]);
  ([268;77;307;282;297;278;75;303],[0;1;2;3;4;5;6;7;8;9;10;11;12;80;280;236;148;17;254;251;256;248;197;255;194;23;24;25;26;27;28;29;30;31;32;33;34;35;36;290;52;53;54;55;56;57;165;61;62;63;88;64;166;66;69;70;72;167;74;198;199;200;201]);
  ([78;266;282;297;278;277],[0;1;2;3;4;5;6;7;8;9;10;11;12;13;14;15;277;16;135;202;203;204;242;136;17;194;245;23;24;25;26;27;28;29;30;31;32;33;34;35;36;39;37;205;41;38]);
  ([266;77;282;297;281;75;278;277],[0;1;2;3;4;5;6;7;8;9;10;11;12;135;202;204;242;292;17;194;21;245;23;24;25;26;27;28;29;30;31;32;33;34;35;36;52;53;54;55;56;57;58;59;61;206;62;63;141;64;140;65;66;138;68;69;72;137;73;74;139;207;208]);
  ([78;286;282;297;278;277],[0;1;2;3;4;5;6;7;8;9;10;11;12;13;14;15;277;16;292;175;254;176;262;209;17;267;210;23;24;25;26;27;28;29;30;31;32;33;34;35;36;39;37;205;41;38;40]);
  ([77;282;307;278;297;75;273;275;285;303],[0;1;2;3;4;5;6;7;8;9;10;11;12;17;148;291;23;45;82;24;25;26;27;28;29;30;31;32;33;34;35;36;293;211;175;294;52;53;54;55;56;57;58;59;61;183;62;63;184;64;65;66;185;68;69;72;186;70;73;74;207;208;276;200]);
  ([282;127;275;297;278;307;75;273;285;303],[0;1;2;3;4;5;6;7;8;9;10;11;12;17;295;45;23;148;82;24;25;26;27;28;29;30;31;32;33;34;35;36;42;43;44;278;212;213;214;215]);
  ([78;268;278;297;277;266],[0;1;2;3;4;5;6;7;8;9;10;11;12;13;14;15;80;290;89;240;238;216;217;239;23;45;135;136;24;25;26;27;28;29;30;31;32;33;34;35;36;90;218;179;37;219]);
  ([287;77;307;297;278;75;303;285;273;275;283],[0;1;2;3;4;5;6;7;8;9;10;11;12;148;45;23;82;220;221;24;25;26;27;28;29;30;31;32;33;34;35;36;135;80;297;280;236;52;53;54;55;56;57;165;206;62;63;88;141;64;166;140;66;138;69;70;137;167;74;139;208;222;223;224;225;226]);
  ([78;268;278;297;277;286],[0;1;2;3;4;5;6;7;8;9;10;11;12;13;14;15;89;80;290;252;257;258;297;23;45;175;287;176;24;25;26;27;28;29;30;31;32;33;34;35;36;90;93;179;37;219;227]);
  ([268;286;307;297;278;77;75;303],[0;1;2;3;4;5;6;7;8;9;10;11;12;80;252;257;258;291;175;259;260;241;249;23;280;236;24;25;26;27;28;29;30;31;32;33;34;35;36;299;52;53;54;55;56;57;165;183;62;63;88;184;64;166;66;185;69;70;167;186;74;200;228;229;230]);
  ([78;266;278;297;277;286],[0;1;2;3;4;5;6;7;8;9;10;11;12;13;14;15;287;176;135;231;232;243;292;246;297;136;23;175;24;25;26;27;28;29;30;31;32;33;34;35;36;233;40;181;234;235])
] : list (list nat * list nat)) as records.
assert (Hcheck :
  check_selected_microblock ((c12_k7_cover_base 4)) base_ids
    imported records c12_k7_cover4_micro_block050_output = true).
{ vm_compute. reflexivity. }
exact (check_selected_microblock_sound
  ((c12_k7_cover_base 4)) base_ids imported records c12_k7_cover4_micro_block050_output
  Hcheck rho Hbase Himported).
Qed.
