(** Generated by [scripts/generate_ckpath_certificates.py].
    Only the block output is transparent.  Selected base clauses,
    producer imports, replay records, and the transient database
    all remain underneath the opaque soundness theorem. *)

From Stdlib Require Import List.
From Digraph Require Import ckpath_cnf ckpath_drup_microblock ckpath_cert_k7_c12_low3_reduction ckpath_cert_k7_c12_low3_mask00_block00 ckpath_cert_k7_c12_low3_mask00_block01 ckpath_cert_k7_c12_low3_mask00_block02 ckpath_cert_k7_c12_low3_mask00_block03 ckpath_cert_k7_c12_low3_mask00_block05 ckpath_cert_k7_c12_low3_mask00_block06 ckpath_cert_k7_c12_low3_mask00_block07 ckpath_cert_k7_c12_low3_mask00_block08 ckpath_cert_k7_c12_low3_mask00_block09 ckpath_cert_k7_c12_low3_mask00_block10 ckpath_cert_k7_c12_low3_mask00_block11.
Import ListNotations.
Set Warnings "-abstract-large-number".

(** Original retained additions [300, 325); 292 selected base clauses and 46 imported consequences from 11 producer blocks. *)
Definition c12_k7_low3_mask00_block12_output : cnf :=
  [
  [(139,true);(81,true);(144,false);(125,true);(140,false);(134,true);(57,true)];
  [(40,false);(144,false);(134,true);(136,false)];
  [(127,false);(114,true);(112,true);(64,true);(79,true);(86,true);(134,true);(140,false);(57,true)];
  [(144,false);(134,true);(136,false)];
  [(83,false);(64,true);(138,false);(57,true)];
  [(79,true);(39,false);(134,true);(136,false)];
  [(39,false);(134,true);(136,false)];
  [(134,true);(136,false)];
  [(140,false);(39,true);(136,false)];
  [(138,true);(39,true);(136,false)];
  [(83,false);(39,true);(136,false)];
  [(144,false);(127,true);(20,false);(125,true)];
  [(143,false);(20,false);(116,true);(114,true);(112,true)];
  [(143,true);(125,true);(68,true);(75,true);(35,false);(140,true)];
  [(116,false);(39,true);(136,false)];
  [(39,true);(136,false)];
  [(143,false);(140,true);(125,true);(68,true);(75,true);(20,false);(112,true);(116,true);(70,true)];
  [(140,true);(125,true);(68,true);(75,true);(20,false);(112,true);(116,true);(70,true)];
  [(144,false);(140,false);(125,true);(79,true);(86,true);(20,false)];
  [(127,false);(144,true);(140,false);(68,true);(75,true);(86,true);(79,true);(136,false)];
  [(139,false);(140,false);(144,true);(125,true);(86,true);(79,true);(75,true);(68,true);(112,true);(14,true);(116,true);(136,false)];
  [(125,true);(86,true);(79,true);(20,false);(75,true);(68,true);(112,true);(14,true);(116,true);(136,false)];
  [(140,false);(86,true);(79,true);(75,true);(143,true);(81,true);(136,false)];
  [(16,true);(15,true);(14,true);(116,true);(136,false)];
  [(68,false);(15,true);(14,true);(134,false)]
].

Theorem c12_k7_low3_mask00_block12_sound :
  forall rho, satisfies_cnf rho (c12_k7_low3_instance [true; false; false; false; true; false; false; false; true; false; false; false]) ->
    satisfies_cnf rho c12_k7_low3_mask00_block12_output.
Proof.
intros rho Hbase.
pose (select_cnf c12_k7_low3_mask00_block00_output [0;1;2;3;4;5;6;7;8;9;10;11;14] : cnf)
  as imported_from_block00.
assert (Himported_from_block00 :
  satisfies_cnf rho imported_from_block00).
{
  unfold imported_from_block00.
  apply (satisfies_cnf_select rho c12_k7_low3_mask00_block00_output [0;1;2;3;4;5;6;7;8;9;10;11;14]).
  - exact (c12_k7_low3_mask00_block00_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask00_block01_output [19] : cnf)
  as imported_from_block01.
assert (Himported_from_block01 :
  satisfies_cnf rho imported_from_block01).
{
  unfold imported_from_block01.
  apply (satisfies_cnf_select rho c12_k7_low3_mask00_block01_output [19]).
  - exact (c12_k7_low3_mask00_block01_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask00_block02_output [12;14] : cnf)
  as imported_from_block02.
assert (Himported_from_block02 :
  satisfies_cnf rho imported_from_block02).
{
  unfold imported_from_block02.
  apply (satisfies_cnf_select rho c12_k7_low3_mask00_block02_output [12;14]).
  - exact (c12_k7_low3_mask00_block02_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask00_block03_output [5;1] : cnf)
  as imported_from_block03.
assert (Himported_from_block03 :
  satisfies_cnf rho imported_from_block03).
{
  unfold imported_from_block03.
  apply (satisfies_cnf_select rho c12_k7_low3_mask00_block03_output [5;1]).
  - exact (c12_k7_low3_mask00_block03_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask00_block05_output [16;19] : cnf)
  as imported_from_block05.
assert (Himported_from_block05 :
  satisfies_cnf rho imported_from_block05).
{
  unfold imported_from_block05.
  apply (satisfies_cnf_select rho c12_k7_low3_mask00_block05_output [16;19]).
  - exact (c12_k7_low3_mask00_block05_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask00_block06_output [9] : cnf)
  as imported_from_block06.
assert (Himported_from_block06 :
  satisfies_cnf rho imported_from_block06).
{
  unfold imported_from_block06.
  apply (satisfies_cnf_select rho c12_k7_low3_mask00_block06_output [9]).
  - exact (c12_k7_low3_mask00_block06_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask00_block07_output [13;14] : cnf)
  as imported_from_block07.
assert (Himported_from_block07 :
  satisfies_cnf rho imported_from_block07).
{
  unfold imported_from_block07.
  apply (satisfies_cnf_select rho c12_k7_low3_mask00_block07_output [13;14]).
  - exact (c12_k7_low3_mask00_block07_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask00_block08_output [13;8;21] : cnf)
  as imported_from_block08.
assert (Himported_from_block08 :
  satisfies_cnf rho imported_from_block08).
{
  unfold imported_from_block08.
  apply (satisfies_cnf_select rho c12_k7_low3_mask00_block08_output [13;8;21]).
  - exact (c12_k7_low3_mask00_block08_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask00_block09_output [1;17;2;15] : cnf)
  as imported_from_block09.
assert (Himported_from_block09 :
  satisfies_cnf rho imported_from_block09).
{
  unfold imported_from_block09.
  apply (satisfies_cnf_select rho c12_k7_low3_mask00_block09_output [1;17;2;15]).
  - exact (c12_k7_low3_mask00_block09_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask00_block10_output [2;6;24;4;5] : cnf)
  as imported_from_block10.
assert (Himported_from_block10 :
  satisfies_cnf rho imported_from_block10).
{
  unfold imported_from_block10.
  apply (satisfies_cnf_select rho c12_k7_low3_mask00_block10_output [2;6;24;4;5]).
  - exact (c12_k7_low3_mask00_block10_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask00_block11_output [13;21;24;22;20;15;23;16;19;14;18] : cnf)
  as imported_from_block11.
assert (Himported_from_block11 :
  satisfies_cnf rho imported_from_block11).
{
  unfold imported_from_block11.
  apply (satisfies_cnf_select rho c12_k7_low3_mask00_block11_output [13;21;24;22;20;15;23;16;19;14;18]).
  - exact (c12_k7_low3_mask00_block11_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (concat [imported_from_block00;imported_from_block01;imported_from_block02;imported_from_block03;imported_from_block05;imported_from_block06;imported_from_block07;imported_from_block08;imported_from_block09;imported_from_block10;imported_from_block11] : cnf) as imported.
assert (Himported : satisfies_cnf rho imported).
{
  unfold imported.
  apply satisfies_cnf_concat_intro.
  constructor.
  { exact Himported_from_block00. }
  constructor.
  { exact Himported_from_block01. }
  constructor.
  { exact Himported_from_block02. }
  constructor.
  { exact Himported_from_block03. }
  constructor.
  { exact Himported_from_block05. }
  constructor.
  { exact Himported_from_block06. }
  constructor.
  { exact Himported_from_block07. }
  constructor.
  { exact Himported_from_block08. }
  constructor.
  { exact Himported_from_block09. }
  constructor.
  { exact Himported_from_block10. }
  constructor.
  { exact Himported_from_block11. }
  constructor.
}
pose (
  [66;67;68;69;70;71;72;73;74;75;76;77;219;237;113;238;169;4157;4155;4158;4153;4159;4154;1072;50;2122;2116;3164;2099;2158;2144;2149;2159;2153;2156;1;2793;2826;2828;2827;2808;2822;48;1076;2096;3180;3165;3148;3157;3176;2101;49;1077;1074;3183;1075;33;1068;3181;37;4156;22;1057;44;249;3811;228;1807;1742;1797;1804;36;1071;2;32;34;1069;3182;2108;2789;2805;2798;2804;2794;25;2118;59;2115;40;58;2114;1086;46;3587;2224;251;122;193;1801;1766;1843;1831;1840;12;3860;3859;3834;3861;3854;3862;3166;55;29;3161;2133;1391;62;64;2855;2876;2871;2874;6;1522;353;2095;2185;2240;2220;1067;250;123;229;239;2851;2801;2873;2867;2861;1087;3527;3600;3593;3577;3598;1844;16;2117;1769;1847;1846;1061;1080;1419;2227;2204;2214;2154;2226;2504;2539;1762;1837;1838;1834;2865;2858;2864;2844;4152;1048;1092;1095;1093;1096;1097;1094;518;377;502;512;3821;3171;1053;3144;1498;1473;1479;496;484;495;349;494;2210;2200;2221;2222;2150;1115;1098;3518;3586;3568;3582;3588;3153;514;505;516;244;370;440;2098;2229;2225;2219;2228;3081;9;2127;3151;54;28;2129;43;61;18;3154;3513;3576;3572;3578;3159;245;515;371;506;441;2542;2543;2522;2536;2472;1808;3088;2106;3820;52;2104;24;2110;39;5;3833;3835;3838;3836;3837;501;355;490;2438;1082;4077;4066;4041;4076;365;511;354;489;500;3883;3879;3845;3882;3870;15;3172;1054;17;3173;1773;1849;1485;1486;1482;1475;1420;3100;1051;1100] : list nat) as base_ids.
pose ([
  ([277;161;286;249;278;267;113],[0;1;2;3;4;5;6;7;8;9;10;11;292;293;294;295;296;297;298;299;300;301;302;303;306;310;313;318;327;12;13;14;15;16;322;17;328;18;19;329;20;21;330;22;23;24;25;26;27;28;312;319;29;30;31;32;33;34;35;36;37;38;39;40;41;42;43;44;45;46;47;48;49;50;51;52;53;54;55]);
  ([78;286;267;270],[0;1;2;3;4;5;6;7;8;9;10;11;292;293;294;295;296;297;298;299;300;301;302;303;306;310;313;318;327;56;57;58;322;331;328;22;332;17;59;23;338;333;334;60;320;20;335;61;62;63;64;65;66;67;68;69;70;19;329;18;71;72;73;74;45;75;76;77;24;25;26;27;28;78;336]);
  ([252;227;223;127;157;171;267;278;113],[0;1;2;3;4;5;6;7;8;9;10;11;292;293;294;295;296;297;298;299;300;301;302;303;306;310;313;318;327;24;26;79;80;81;82;321;83;17;84;85;86;87;88;89;90;91;92;56;93;94;95;96;15;64;97;66]);
  ([286;267;270],[0;1;2;3;4;5;6;7;8;9;10;11;292;293;294;295;296;297;298;299;300;301;302;303;306;310;313;318;327;322;339;328;331;22;332;98;99;100;101;102;59;23;17;103;73;71;72;74;45;75;76;77;336;340;104;105;106;107;108;109;86;110;111;112;113;114;115;116;63;117;118;119;120;80;121;84;89;90;304;88;122;92;123;124;323]);
  ([164;127;274;113],[0;1;2;3;4;5;6;7;8;9;10;11;292;293;294;295;296;297;298;299;300;301;302;303;306;310;313;318;327;92;314;18;125;126;127;128]);
  ([157;76;267;270],[0;1;2;3;4;5;6;7;8;9;10;11;292;293;294;295;296;297;298;299;300;301;302;303;306;310;313;318;327;74;129;45;331;341;22;17;130;131;132;133;95;19;20;18;342;60;324;21;134;121;135;321;136;137;138;84;85;86;139;87;122;89;90;91;304;88;56;140;141;142;143;144;93;311;98;145;99;100;102;337]);
  ([76;267;270],[0;1;2;3;4;5;6;7;8;9;10;11;292;293;294;295;296;297;298;299;300;301;302;303;306;310;313;318;327;74;129;45;343;331;341;22;146;147;76;17;130;131;132;133;95;148;70;149;102;150;19;20;151;18;342;55;60;324;152;21;73;103;62;59;23;56;57;58;71;72;153;154;128;155;156;157;158;159;160]);
  ([267;270],[0;1;2;3;4;5;6;7;8;9;10;11;292;293;294;295;296;297;298;299;300;301;302;303;306;310;313;318;327;331;341;344;22;332;17;130;131;132;133;95;307;69;161;101;162;163;164;19;20;18;60;21;103;62;73;56;58;71;72;59;23;75;76;77;165;83;166;167;168;336]);
  ([278;77;270],[0;1;2;3;4;5;6;7;8;9;10;11;292;293;294;295;296;297;298;299;300;301;302;303;306;310;313;318;327;17;307;69;161;101;162;163;164;22;332;345;103;73;56;58;71;72;59;23;75;76;77;169;170;165;83;166;167;168;138;86;87;122;26;88;89;90;84;85;92;104;93;171;172;173;174;175;176;177;178;179;180;181;182;183;184;19;311;304;20;62;185;186;187]);
  ([275;77;270],[0;1;2;3;4;5;6;7;8;9;10;11;292;293;294;295;296;297;298;299;300;301;302;303;306;310;313;318;327;307;69;161;101;162;163;164;346;22;332;345;103;73;56;58;71;72;59;23;75;76;77;188;189;190;191;192;169;170;322;335]);
  ([164;77;270],[0;1;2;3;4;5;6;7;8;9;10;11;292;293;294;295;296;297;298;299;300;301;302;303;306;310;313;318;327;92;307;69;161;101;162;163;164;346;347;22;332;345;103;73;56;58;71;72;59;23;75;76;77;18;342;125;193;194;195;169;170;42;43;44;182;196;197;50;51;198;199;171]);
  ([286;253;38;249],[0;1;2;3;4;5;6;7;8;9;10;11;292;293;294;295;296;297;298;299;300;301;302;303;306;310;313;318;327;322;104;105;106;107;108;109;113]);
  ([284;38;231;227;223],[0;1;2;3;4;5;6;7;8;9;10;11;292;293;294;295;296;297;298;299;300;301;302;303;306;310;313;318;327;21;200;201;202;203;204;205]);
  ([285;249;135;149;68;279],[0;1;2;3;4;5;6;7;8;9;10;11;292;293;294;295;296;297;298;299;300;301;302;303;306;310;313;318;327;206;207;208;209;210;211;190;334;103;19;60;320;322;169;170;20;62]);
  ([230;77;270],[0;1;2;3;4;5;6;7;8;9;10;11;292;293;294;295;296;297;298;299;300;301;302;303;306;310;313;318;327;51;307;69;161;101;162;163;164;346;347;348;22;332;345;103;73;56;58;71;72;59;23;75;76;77;18;308;212;305;169;170;171;173;174;175;176;172;351;315;213;214;215;32;216;182]);
  ([77;270],[0;1;2;3;4;5;6;7;8;9;10;11;292;293;294;295;296;297;298;299;300;301;302;303;306;310;313;318;327;307;69;161;101;162;163;164;346;347;348;352;22;332;345;103;73;56;58;71;72;59;23;75;76;77;18;169;170;351;21;200;201;202;203;204;217;93;350;218;219;330;220;221;48;222;223;224;225;89;172]);
  ([284;279;249;135;149;38;223;231;139],[0;1;2;3;4;5;6;7;8;9;10;11;292;293;294;295;296;297;298;299;300;301;302;303;306;310;313;318;327;21;226;350;205;71;227;228;143;229;230;231;218;219;330;220;89;221;48;224;225;232;233;188;234;235;236;309;237;238]);
  ([279;249;135;149;38;223;231;139],[0;1;2;3;4;5;6;7;8;9;10;11;292;293;294;295;296;297;298;299;300;301;302;303;306;310;313;318;327;354;226;206;207;208;209;210;211;190;351;19;184;60;320;238;334;324;239;160;240;241;242;322;113;349;169;183;20;22;332;353;18;243;98;67;68;70;63;244;221;245;61;111;246;247;152;248;249;250;251;252;78]);
  ([286;278;249;157;171;38],[0;1;2;3;4;5;6;7;8;9;10;11;292;293;294;295;296;297;298;299;300;301;302;303;306;310;313;318;327;322;113;349;17;226;253;254;255;256;257;24;26;27;321;63;111;46;117;86;110;116;79;80]);
  ([252;287;278;135;149;171;157;270],[0;1;2;3;4;5;6;7;8;9;10;11;292;293;294;295;296;297;298;299;300;301;302;303;306;310;313;318;327;24;26;321;17;22;332;345;353;79;80;81;82;83;92;169;74;45;84;85;86;139;87;88;89;90;91;56;342;98;145;99;100;102;258;259;260;261;179;103;170;62;59;73;71;75;19;25;304;311;20;187]);
  ([276;278;287;249;171;157;149;135;223;27;231;270],[0;1;2;3;4;5;6;7;8;9;10;11;292;293;294;295;296;297;298;299;300;301;302;303;306;310;313;318;327;60;17;357;22;332;345;353;169;74;45;238;239;160;240;241;242;221;262;245;111;247;248;249;250;251;252;138;134;121;135;136;137;56;84;86;122;89;88;98;145;99;100;102;263;264;265;266;144;170;73;71;75;117;304;63;112;116;179;177]);
  ([249;171;157;38;149;135;223;27;231;270],[0;1;2;3;4;5;6;7;8;9;10;11;292;293;294;295;296;297;298;299;300;301;302;303;306;310;313;318;327;226;22;332;345;353;169;183;74;45;355;17;356;358;357;267;260;268;180;20;18;342;19;184;21;350;205;138;134;121;135;136;137;71;227;228;143;229;230;231;56;84;85;86;122;89]);
  ([278;171;157;149;285;161;270],[0;1;2;3;4;5;6;7;8;9;10;11;292;293;294;295;296;297;298;299;300;301;302;303;306;310;313;318;327;17;165;83;166;167;168;138;22;332;345;353;86;139;87;122;26;88;89;90;91;84;85;92;169;74;45;342;261;179;269;270;271;322;325;272;273;274;275;276;326]);
  ([31;29;27;231;270],[0;1;2;3;4;5;6;7;8;9;10;11;292;293;294;295;296;297;298;299;300;301;302;303;306;310;313;318;327;22;332;345;353;169;316;171;173;174;175;176;172;74;45;277;146;278;279;280;281;359;59;145;243;282;283;149;56;73;71;75;350;360;208;190;206;210;207;322;113;18;342;19;184;20;62;60;238;239;160;240;241;242;317;187;284;285;286;287;288;221;245;111;246;247;289;249]);
  ([134;29;27;266],[0;1;2;3;4;5;6;7;8;9;10;11;292;293;294;295;296;297;298;299;300;301;302;303;306;310;313;318;327;277;290;169;316;291;199])
] : list (list nat * list nat)) as records.
assert (Hcheck :
  check_selected_microblock (c12_k7_low3_instance [true; false; false; false; true; false; false; false; true; false; false; false]) base_ids
    imported records c12_k7_low3_mask00_block12_output = true).
{ vm_compute. reflexivity. }
exact (check_selected_microblock_sound
  (c12_k7_low3_instance [true; false; false; false; true; false; false; false; true; false; false; false]) base_ids imported records c12_k7_low3_mask00_block12_output
  Hcheck rho Hbase Himported).
Qed.
