(** Generated by [scripts/generate_ckpath_certificates.py].
    Only the block output is transparent.  Selected base clauses,
    producer imports, replay records, and the transient database
    all remain underneath the opaque soundness theorem. *)

From Stdlib Require Import List.
From Digraph Require Import ckpath_cnf ckpath_drup_microblock ckpath_cert_k7_base ckpath_cert_k7_c12_cover4_micro_block012 ckpath_cert_k7_c12_cover4_micro_block013 ckpath_cert_k7_c12_cover4_micro_block014.
Import ListNotations.
Set Warnings "-abstract-large-number".

(** Original retained additions [375, 400); 93 selected base clauses and 11 imported consequences from 3 producer blocks. *)
Definition c12_k7_cover4_micro_block015_output : cnf :=
  [
  [(139,false);(134,false);(137,false);(142,false)];
  [(139,false);(134,false);(137,false);(143,false)];
  [(144,false);(134,false);(137,false);(139,false)];
  [(140,false);(134,false);(137,false);(141,false)];
  [(140,false);(134,false);(137,false);(142,false)];
  [(140,false);(134,false);(137,false);(143,false)];
  [(134,false);(137,false);(140,false);(144,false)];
  [(141,false);(134,false);(137,false);(142,false)];
  [(141,false);(134,false);(137,false);(143,false)];
  [(141,false);(134,false);(137,false);(144,false)];
  [(142,false);(134,false);(137,false);(143,false)];
  [(142,false);(134,false);(137,false);(144,false)];
  [(143,false);(134,false);(137,false);(144,false)];
  [(139,false);(134,false);(138,false);(140,false)];
  [(139,false);(134,false);(138,false);(141,false)];
  [(139,false);(134,false);(138,false);(142,false)];
  [(139,false);(134,false);(138,false);(143,false)];
  [(144,false);(138,false);(134,false);(139,false)];
  [(140,false);(134,false);(138,false);(141,false)];
  [(140,false);(134,false);(138,false);(142,false)];
  [(140,false);(134,false);(138,false);(143,false)];
  [(134,false);(138,false);(140,false);(144,false)];
  [(141,false);(134,false);(138,false);(142,false)];
  [(141,false);(134,false);(138,false);(143,false)];
  [(141,false);(134,false);(138,false);(144,false)]
].

Theorem c12_k7_cover4_micro_block015_sound :
  forall rho, satisfies_cnf rho ((c12_k7_cover_base 4)) ->
    satisfies_cnf rho c12_k7_cover4_micro_block015_output.
Proof.
intros rho Hbase.
pose (select_cnf c12_k7_cover4_micro_block012_output [16;21;22] : cnf)
  as imported_from_block012.
assert (Himported_from_block012 :
  satisfies_cnf rho imported_from_block012).
{
  unfold imported_from_block012.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block012_output [16;21;22]).
  - exact (c12_k7_cover4_micro_block012_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block013_output [17;18;23] : cnf)
  as imported_from_block013.
assert (Himported_from_block013 :
  satisfies_cnf rho imported_from_block013).
{
  unfold imported_from_block013.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block013_output [17;18;23]).
  - exact (c12_k7_cover4_micro_block013_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block014_output [17;23;24;18;22] : cnf)
  as imported_from_block014.
assert (Himported_from_block014 :
  satisfies_cnf rho imported_from_block014).
{
  unfold imported_from_block014.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block014_output [17;23;24;18;22]).
  - exact (c12_k7_cover4_micro_block014_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (concat [imported_from_block012;imported_from_block013;imported_from_block014] : cnf) as imported.
assert (Himported : satisfies_cnf rho imported).
{
  unfold imported.
  apply satisfies_cnf_concat_intro.
  constructor.
  { exact Himported_from_block012. }
  constructor.
  { exact Himported_from_block013. }
  constructor.
  { exact Himported_from_block014. }
  constructor.
}
pose (
  [66;67;68;69;70;71;72;73;74;75;76;77;2014;3827;406;405;2317;3223;370;372;371;5337;340;323;387;4129;408;409;410;373;411;412;374;413;375;376;4431;309;727;777;787;414;415;377;728;778;788;416;378;729;779;789;379;4733;310;730;780;790;796;381;380;731;781;791;797;5035;333;382;383;402;403;404;3525;341;384;385;386;346;388;389;391;390;742;315;364;807;392;743;808;393;744;809;394] : list nat) as base_ids.
pose ([
  ([276;266;272;282],[0;1;2;3;4;5;6;7;8;9;10;11;12;13;14;15;99;16;100;101;17;96;18]);
  ([276;266;272;284],[0;1;2;3;4;5;6;7;8;9;10;11;12;13;99;16;100;101;104;17;96;19;20]);
  ([286;266;272;276],[0;1;2;3;4;5;6;7;8;9;10;11;12;21;22;23;24;19]);
  ([278;266;272;280],[0;1;2;3;4;5;6;7;8;9;10;11;12;25;93;26;27;28;102;16;100;17;97;29]);
  ([278;266;272;282],[0;1;2;3;4;5;6;7;8;9;10;11;12;25;93;30;31;102;16;100;107;17;97;32]);
  ([278;266;272;284],[0;1;2;3;4;5;6;7;8;9;10;11;12;25;93;33;102;16;100;107;108;17;97;34]);
  ([266;272;278;286],[0;1;2;3;4;5;6;7;8;9;10;11;12;16;103;100;107;108;17;97;35]);
  ([280;266;272;282],[0;1;2;3;4;5;6;7;8;9;10;11;12;36;37;38;39;40;41;42;16;107;17;43]);
  ([280;266;272;284],[0;1;2;3;4;5;6;7;8;9;10;11;12;36;37;44;45;46;47;16;107;111;17;48]);
  ([280;266;272;286],[0;1;2;3;4;5;6;7;8;9;10;11;12;36;37;49;50;51;16;107;111;112;17;52]);
  ([282;266;272;284],[0;1;2;3;4;5;6;7;8;9;10;11;12;53;54;55;56;57;58;59;16;111;17;60]);
  ([282;266;272;286],[0;1;2;3;4;5;6;7;8;9;10;11;12;53;54;61;62;63;64;59]);
  ([284;266;272;286],[0;1;2;3;4;5;6;7;8;9;10;11;12;65;66;67]);
  ([276;266;274;278],[0;1;2;3;4;5;6;7;8;9;10;11;12;13;68]);
  ([276;266;274;280],[0;1;2;3;4;5;6;7;8;9;10;11;12;13;69;70;71;16;117;72;99;94;73;74]);
  ([276;266;274;282],[0;1;2;3;4;5;6;7;8;9;10;11;12;13;14;15;16;117;118;72;99;94;73;75]);
  ([276;266;274;284],[0;1;2;3;4;5;6;7;8;9;10;11;12;13;16;117;118;119;72;99;94;73;24;76]);
  ([286;274;266;276],[0;1;2;3;4;5;6;7;8;9;10;11;12;21;77;23;24]);
  ([278;266;274;280],[0;1;2;3;4;5;6;7;8;9;10;11;12;25;95;29;26;27;28;16;117;72;98;78]);
  ([278;266;274;282],[0;1;2;3;4;5;6;7;8;9;10;11;12;25;95;30;31;16;117;122;72;102;98;79]);
  ([278;266;274;284],[0;1;2;3;4;5;6;7;8;9;10;11;12;25;95;16;117;122;123;72;102;80;98;81]);
  ([266;274;278;286],[0;1;2;3;4;5;6;7;8;9;10;11;12;16;117;122;123;72;102;80]);
  ([280;266;274;282],[0;1;2;3;4;5;6;7;8;9;10;11;12;36;82;83;84;85;41;42;16;122;72;86]);
  ([280;266;274;284],[0;1;2;3;4;5;6;7;8;9;10;11;12;36;87;83;84;88;16;122;126;72;89]);
  ([280;266;274;286],[0;1;2;3;4;5;6;7;8;9;10;11;12;36;90;83;84;91;16;122;126;127;72;92])
] : list (list nat * list nat)) as records.
assert (Hcheck :
  check_selected_microblock ((c12_k7_cover_base 4)) base_ids
    imported records c12_k7_cover4_micro_block015_output = true).
{ vm_compute. reflexivity. }
exact (check_selected_microblock_sound
  ((c12_k7_cover_base 4)) base_ids imported records c12_k7_cover4_micro_block015_output
  Hcheck rho Hbase Himported).
Qed.
