(** Generated by [scripts/generate_ckpath_certificates.py].
    Only the block output is transparent.  Selected base clauses,
    producer imports, replay records, and the transient database
    all remain underneath the opaque soundness theorem. *)

From Stdlib Require Import List.
From Digraph Require Import ckpath_cnf ckpath_drup_microblock ckpath_cert_k7_c12_low3_reduction ckpath_cert_k7_c12_low3_mask09_block00 ckpath_cert_k7_c12_low3_mask09_block02 ckpath_cert_k7_c12_low3_mask09_block03 ckpath_cert_k7_c12_low3_mask09_block04 ckpath_cert_k7_c12_low3_mask09_block05 ckpath_cert_k7_c12_low3_mask09_block06 ckpath_cert_k7_c12_low3_mask09_block07.
Import ListNotations.
Set Warnings "-abstract-large-number".

(** Original retained additions [200, 225); 266 selected base clauses and 33 imported consequences from 7 producer blocks. *)
Definition c12_k7_low3_mask09_block08_output : cnf :=
  [
  [(135,false);(124,false);(79,false)];
  [(117,false);(139,false);(141,false);(89,true);(142,false)];
  [(99,false);(143,false);(111,true);(117,true);(141,false)];
  [(137,true);(135,true);(124,false)];
  [(137,false);(52,true);(50,true);(69,false);(124,false)];
  [(135,false);(139,false);(76,true);(124,false)];
  [(75,true);(139,false);(76,true);(124,false)];
  [(52,false);(95,true);(90,true);(91,true);(137,false);(124,false)];
  [(141,false);(91,true);(90,true);(95,true);(124,false)];
  [(50,true);(137,false);(52,true);(74,true);(139,false);(124,false)];
  [(50,false);(79,true);(75,false);(139,false);(124,false)];
  [(52,true);(50,true);(137,false);(139,false);(124,false)];
  [(91,false);(50,true);(137,false);(45,true);(139,false);(67,true)];
  [(50,true);(137,false);(139,false);(124,false)];
  [(95,false);(71,true);(139,false);(67,true)];
  [(75,true);(137,false);(139,false);(124,false)];
  [(137,false);(139,false);(124,false)];
  [(139,false);(124,false)];
  [(99,true);(140,false);(79,true);(78,true);(141,false);(111,true);(89,true);(143,false);(33,true)];
  [(140,false);(79,true);(78,true);(141,false);(111,true);(89,true);(143,false);(33,true)];
  [(137,true);(124,false)];
  [(140,false);(143,false);(79,true);(141,false);(124,false)];
  [(99,false);(143,false);(111,true);(141,false)];
  [(112,true);(117,true);(111,true);(140,true);(143,false);(141,false)];
  [(112,false);(99,true);(142,false);(141,false);(124,false)]
].

Theorem c12_k7_low3_mask09_block08_sound :
  forall rho, satisfies_cnf rho (c12_k7_low3_instance [true; true; false; false; false; true; false; false; false; false; false; false]) ->
    satisfies_cnf rho c12_k7_low3_mask09_block08_output.
Proof.
intros rho Hbase.
pose (select_cnf c12_k7_low3_mask09_block00_output [0;1;2;3;4;5;6;7;8;9;10;11] : cnf)
  as imported_from_block00.
assert (Himported_from_block00 :
  satisfies_cnf rho imported_from_block00).
{
  unfold imported_from_block00.
  apply (satisfies_cnf_select rho c12_k7_low3_mask09_block00_output [0;1;2;3;4;5;6;7;8;9;10;11]).
  - exact (c12_k7_low3_mask09_block00_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask09_block02_output [14] : cnf)
  as imported_from_block02.
assert (Himported_from_block02 :
  satisfies_cnf rho imported_from_block02).
{
  unfold imported_from_block02.
  apply (satisfies_cnf_select rho c12_k7_low3_mask09_block02_output [14]).
  - exact (c12_k7_low3_mask09_block02_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask09_block03_output [0;21;13;18] : cnf)
  as imported_from_block03.
assert (Himported_from_block03 :
  satisfies_cnf rho imported_from_block03).
{
  unfold imported_from_block03.
  apply (satisfies_cnf_select rho c12_k7_low3_mask09_block03_output [0;21;13;18]).
  - exact (c12_k7_low3_mask09_block03_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask09_block04_output [15;5;2;21;22;16;17;14] : cnf)
  as imported_from_block04.
assert (Himported_from_block04 :
  satisfies_cnf rho imported_from_block04).
{
  unfold imported_from_block04.
  apply (satisfies_cnf_select rho c12_k7_low3_mask09_block04_output [15;5;2;21;22;16;17;14]).
  - exact (c12_k7_low3_mask09_block04_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask09_block05_output [2;24] : cnf)
  as imported_from_block05.
assert (Himported_from_block05 :
  satisfies_cnf rho imported_from_block05).
{
  unfold imported_from_block05.
  apply (satisfies_cnf_select rho c12_k7_low3_mask09_block05_output [2;24]).
  - exact (c12_k7_low3_mask09_block05_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask09_block06_output [0;18;8] : cnf)
  as imported_from_block06.
assert (Himported_from_block06 :
  satisfies_cnf rho imported_from_block06).
{
  unfold imported_from_block06.
  apply (satisfies_cnf_select rho c12_k7_low3_mask09_block06_output [0;18;8]).
  - exact (c12_k7_low3_mask09_block06_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask09_block07_output [20;24;18] : cnf)
  as imported_from_block07.
assert (Himported_from_block07 :
  satisfies_cnf rho imported_from_block07).
{
  unfold imported_from_block07.
  apply (satisfies_cnf_select rho c12_k7_low3_mask09_block07_output [20;24;18]).
  - exact (c12_k7_low3_mask09_block07_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (concat [imported_from_block00;imported_from_block02;imported_from_block03;imported_from_block04;imported_from_block05;imported_from_block06;imported_from_block07] : cnf) as imported.
assert (Himported : satisfies_cnf rho imported).
{
  unfold imported.
  apply satisfies_cnf_concat_intro.
  constructor.
  { exact Himported_from_block00. }
  constructor.
  { exact Himported_from_block02. }
  constructor.
  { exact Himported_from_block03. }
  constructor.
  { exact Himported_from_block04. }
  constructor.
  { exact Himported_from_block05. }
  constructor.
  { exact Himported_from_block06. }
  constructor.
  { exact Himported_from_block07. }
  constructor.
}
pose (
  [66;67;68;69;70;71;72;73;74;75;76;77;4152;1051;1130;29;16;1224;1212;1218;1223;1202;22;1047;2226;4159;1167;2218;28;1053;1128;1049;1124;25;1050;1052;1127;1048;2227;3523;3545;3548;3547;3546;3544;19;1168;2216;49;61;58;54;43;1882;4157;1162;2205;2952;2950;2895;2886;4155;2184;2201;2933;2927;2937;62;1081;1161;3526;110;108;107;111;109;78;106;1153;4156;1158;2222;4158;1165;4153;1139;1074;1078;1083;1062;2610;2591;2601;2612;2576;2607;46;2199;1149;1135;33;2197;1077;1156;2192;40;2198;4154;1147;1859;1865;1864;1863;24;1142;2281;2262;2284;2272;2278;2247;52;1071;2187;55;1152;32;39;1154;2186;1862;1829;1844;1860;1861;44;13;42;1067;1144;41;1068;1145;2894;1066;1143;2944;2882;2897;2900;2951;2885;1845;1830;2255;2251;2231;1148;2260;2261;2259;1065;53;1072;1150;2182;2196;2572;2573;2574;2564;2568;2276;2277;2265;2240;57;59;2193;1157;3272;137;269;1069;1146;2233;2229;2230;2234;2232;26;1866;1867;1846;1831;2903;2909;2910;2911;2908;2883;34;1080;1160;2200;47;17;1163;2203;2275;2269;2244;2282;3592;2189;15;2330;2279;2310;2266;1073;1151;2183;1064;1141;2256;2241;2207;2935;2934;2922;2928;2912;1876;1853;1838;1870;1869;136;87;138;2220;1159;2195;2214;227;230;224;231;165;218;162;220;222;219;221;3541;3531;3542;3535;3538;2902;2917;2936;2206;2204] : list nat) as base_ids.
pose ([
  ([268;246;156],[0;1;2;3;4;5;6;7;8;9;10;11;266;267;268;269;270;271;272;273;274;275;276;277;279;12;13;14;296;15;297;16;283;17;18;19;20;21;22;23;24;25;26;27;28;29;30;31;32;33;34;35;36;37;38;39;40;41;42;43;44;45;46;47;48;49;50;51;52;53;291;54;55;56;57;58;59;60]);
  ([232;276;280;177;282],[0;1;2;3;4;5;6;7;8;9;10;11;266;267;268;269;270;271;272;273;274;275;276;277;279;51;284;61;62;54;63;64;65;66;285]);
  ([196;284;221;233;280],[0;1;2;3;4;5;6;7;8;9;10;11;266;267;268;269;270;271;272;273;274;275;276;277;279;67;68;69;25;280;281;70]);
  ([273;269;246],[0;1;2;3;4;5;6;7;8;9;10;11;266;267;268;269;270;271;272;273;274;275;276;277;279;71;72;73;74;75;76;77;15;78;25;26;54;55;79;80;81;82;83;300;84;85;61;301;286;287;45;46;47;86;87;88;89;90;91;92;93;94;95;282;293;96;97;33;98;99;100;101;50;102;103;104;16;105;106;64;65;66;285]);
  ([272;103;99;136;246],[0;1;2;3;4;5;6;7;8;9;10;11;266;267;268;269;270;271;272;273;274;275;276;277;279;107;108;109;110;111;112;113;114]);
  ([268;276;151;246],[0;1;2;3;4;5;6;7;8;9;10;11;266;267;268;269;270;271;272;273;274;275;276;277;279;12;14;61;15;299;78;283;288]);
  ([149;276;151;246],[0;1;2;3;4;5;6;7;8;9;10;11;266;267;268;269;270;271;272;273;274;275;276;277;279;61;304;15;78;302;115;116;117;118;119;120;107;108;121;122;98;113;114;123;124;86;125;62;126;127;128;129;294;130;131;132;133;109;134;54;55;135;136;22;137;138;139;140;52;141;142;143]);
  ([102;189;179;181;272;246],[0;1;2;3;4;5;6;7;8;9;10;11;266;267;268;269;270;271;272;273;274;275;276;277;279;140;144;145;107;108;15;146;294]);
  ([280;181;179;189;246],[0;1;2;3;4;5;6;7;8;9;10;11;266;267;268;269;270;271;272;273;274;275;276;277;279;54;55;147;148;149;150;151]);
  ([99;272;103;147;276;246],[0;1;2;3;4;5;6;7;8;9;10;11;266;267;268;269;270;271;272;273;274;275;276;277;279;107;108;303;152;153;111;61;78;15;109;110;112;154;155;156;22;136;157;52;141;142;158;159;160;105;161]);
  ([98;157;148;276;246],[0;1;2;3;4;5;6;7;8;9;10;11;266;267;268;269;270;271;272;273;274;275;276;277;279;127;162;163;164;165;61;78;15;307;289;294;79;80;97;33;166;98;167;168;169;170;171;172;173;154;174;175;176;50;102;103;177;87;178;179;290;100;101;105;106;124;295;128;129;180;181;182]);
  ([103;99;272;276;246],[0;1;2;3;4;5;6;7;8;9;10;11;266;267;268;269;270;271;272;273;274;275;276;277;279;303;107;108;308;61;78;15;109;110;112;152;153;111;121;122;98;105;161;135;183;184;137;138;139;22;136;157;52;141;142;294;185;186;187;188;189;307]);
  ([180;99;272;89;276;133],[0;1;2;3;4;5;6;7;8;9;10;11;266;267;268;269;270;271;272;273;274;275;276;277;279;190;164;139;107;61;133;191;112;192;193;194;105;161;114;52;141;142;140;144;145;135;183;184;22;136;157;156;185;186;187;188;189]);
  ([99;272;276;246],[0;1;2;3;4;5;6;7;8;9;10;11;266;267;268;269;270;271;272;273;274;275;276;277;279;107;108;61;78;15;310;311;140;144;145;294;54;55;195;196;197;198;199;200;201;56;121;165;49;202;203;204;67;68;69;63;205;206;207;208;138;209;210;211;160;115;212;213;298;133;191;192;193;194;214;215;161]);
  ([188;141;276;133],[0;1;2;3;4;5;6;7;8;9;10;11;266;267;268;269;270;271;272;273;274;275;276;277;279;121;165;216;119;217;218;219;209]);
  ([149;272;276;246],[0;1;2;3;4;5;6;7;8;9;10;11;266;267;268;269;270;271;272;273;274;275;276;277;279;305;107;108;312;61;78;15;51;220;221;222;127;223;224;298;225;217;226;219;209;313;113;114;123;124;86;125;128;129;126;122;98;294;54;55;227;228;229;230;231;148;232;67;49;201;140;206;138;190;213;233;234;235;236;237]);
  ([272;276;246],[0;1;2;3;4;5;6;7;8;9;10;11;266;267;268;269;270;271;272;273;274;275;276;277;279;107;108;312;314;61;78;15;127;223;224;162;163;164;165;309;306;307;16;122;299;297;289;172;173;154;174;175;238;239;240;25;26;241;79;80;97;242;243;51;220;221;124;86;125;113;114;123;126;82;83;244;298]);
  ([276;246],[0;1;2;3;4;5;6;7;8;9;10;11;266;267;268;269;270;271;272;273;274;275;276;277;279;61;78;315;15;302;12;14;304;299;283;51;220;221;222;298;245;246;247;248;249;54;55;25;26;79;80;81;84;85;301;287;286;45;46;47;86;87;89;94]);
  ([197;278;157;155;280;221;177;284;65],[0;1;2;3;4;5;6;7;8;9;10;11;266;267;268;269;270;271;272;273;274;275;276;277;279;287;286;79;54;25;45;46;47;87;94]);
  ([278;157;155;280;221;177;284;65],[0;1;2;3;4;5;6;7;8;9;10;11;266;267;268;269;270;271;272;273;274;275;276;277;279;79;317;54;25;67;68;69;63;301]);
  ([273;246],[0;1;2;3;4;5;6;7;8;9;10;11;266;267;268;269;270;271;272;273;274;275;276;277;279;302;15;316;12;14;299;250;251;252;253;254;255;283;79;80;84;85;82;83;81;54;55;25;26;318]);
  ([278;284;157;280;246],[0;1;2;3;4;5;6;7;8;9;10;11;266;267;268;269;270;271;272;273;274;275;276;277;279;79;80;25;26;54;55;15;316;319;318]);
  ([196;284;221;280],[0;1;2;3;4;5;6;7;8;9;10;11;266;267;268;269;270;271;272;273;274;275;276;277;279;67;68;69;63;301]);
  ([223;233;221;279;284;280],[0;1;2;3;4;5;6;7;8;9;10;11;266;267;268;269;270;271;272;273;274;275;276;277;279;290;256;257;70;258;259;260;301;292]);
  ([222;197;282;280;246],[0;1;2;3;4;5;6;7;8;9;10;11;266;267;268;269;270;271;272;273;274;275;276;277;279;45;88;82;83;54;55;15;316;319;282;107;108;183;64;65;66;261;262;263;140;264;201;56;121;206;207;208;138;190;265;205;227;278;110])
] : list (list nat * list nat)) as records.
assert (Hcheck :
  check_selected_microblock (c12_k7_low3_instance [true; true; false; false; false; true; false; false; false; false; false; false]) base_ids
    imported records c12_k7_low3_mask09_block08_output = true).
{ vm_compute. reflexivity. }
exact (check_selected_microblock_sound
  (c12_k7_low3_instance [true; true; false; false; false; true; false; false; false; false; false; false]) base_ids imported records c12_k7_low3_mask09_block08_output
  Hcheck rho Hbase Himported).
Qed.
