(** Generated by [scripts/generate_ckpath_certificates.py].
    Only the block output is transparent.  Selected base clauses,
    producer imports, replay records, and the transient database
    all remain underneath the opaque soundness theorem. *)

From Stdlib Require Import List.
From Digraph Require Import ckpath_cnf ckpath_drup_microblock ckpath_cert_k7_base ckpath_cert_k7_c12_cover4_micro_block016 ckpath_cert_k7_c12_cover4_micro_block019 ckpath_cert_k7_c12_cover4_micro_block021 ckpath_cert_k7_c12_cover4_micro_block023 ckpath_cert_k7_c12_cover4_micro_block024 ckpath_cert_k7_c12_cover4_micro_block030 ckpath_cert_k7_c12_cover4_micro_block031 ckpath_cert_k7_c12_cover4_micro_block032 ckpath_cert_k7_c12_cover4_micro_block033 ckpath_cert_k7_c12_cover4_micro_block038 ckpath_cert_k7_c12_cover4_micro_block040 ckpath_cert_k7_c12_cover4_micro_block041 ckpath_cert_k7_c12_cover4_micro_block042 ckpath_cert_k7_c12_cover4_micro_block043 ckpath_cert_k7_c12_cover4_micro_block051 ckpath_cert_k7_c12_cover4_micro_block068 ckpath_cert_k7_c12_cover4_micro_block078 ckpath_cert_k7_c12_cover4_micro_block081 ckpath_cert_k7_c12_cover4_micro_block082 ckpath_cert_k7_c12_cover4_micro_block083 ckpath_cert_k7_c12_cover4_micro_block097 ckpath_cert_k7_c12_cover4_micro_block103 ckpath_cert_k7_c12_cover4_micro_block107 ckpath_cert_k7_c12_cover4_micro_block112 ckpath_cert_k7_c12_cover4_micro_block113 ckpath_cert_k7_c12_cover4_micro_block118 ckpath_cert_k7_c12_cover4_micro_block124 ckpath_cert_k7_c12_cover4_micro_block127 ckpath_cert_k7_c12_cover4_micro_block128 ckpath_cert_k7_c12_cover4_micro_block129 ckpath_cert_k7_c12_cover4_micro_block130 ckpath_cert_k7_c12_cover4_micro_block137 ckpath_cert_k7_c12_cover4_micro_block138 ckpath_cert_k7_c12_cover4_micro_block139 ckpath_cert_k7_c12_cover4_micro_block140 ckpath_cert_k7_c12_cover4_micro_block141 ckpath_cert_k7_c12_cover4_micro_block142.
Import ListNotations.
Set Warnings "-abstract-large-number".

(** Original retained additions [3575, 3600); 303 selected base clauses and 70 imported consequences from 37 producer blocks. *)
Definition c12_k7_cover4_micro_block143_output : cnf :=
  [
  [(44,false);(130,true);(129,true);(143,false);(145,true)];
  [(125,false);(30,true);(135,true);(143,false);(145,true);(141,false);(139,false)];
  [(88,false);(143,false);(139,false);(141,false);(144,true);(135,true);(137,true)];
  [(41,false);(81,true);(88,true);(140,true);(149,true);(141,false)];
  [(38,false);(149,true);(139,false);(137,true);(143,false);(141,false)];
  [(40,false);(149,true);(88,true);(140,true);(142,true);(139,false);(143,false);(38,true);(141,false)];
  [(149,true);(88,true);(139,false);(142,true);(140,true);(141,false);(143,false);(137,true)];
  [(40,false);(153,true);(139,false);(143,false);(88,true);(155,true)];
  [(101,true);(129,true);(144,true);(126,true);(155,true);(103,true);(104,true)];
  [(101,false);(15,true);(14,true);(147,true)];
  [(44,true);(38,true);(155,true);(147,true);(141,false);(145,true);(139,false);(40,true);(136,true)];
  [(129,true);(125,true);(139,false);(145,true);(141,false);(151,true);(126,true)];
  [(104,true);(14,true);(15,true);(139,false);(155,true);(143,false);(147,true);(101,true);(100,true)];
  [(101,true);(26,true);(141,false);(155,true);(139,false);(100,true);(144,true);(125,true);(126,true);(148,true);(137,true);(143,false);(15,true);(147,true);(38,true);(40,true);(136,true)];
  [(38,true);(147,true);(139,false);(148,true);(151,true);(141,false);(155,true);(137,true);(143,false);(40,true);(136,true);(145,true)];
  [(27,false);(143,false);(137,true);(148,true);(139,false);(141,false)];
  [(125,false);(27,true);(135,true);(143,false);(145,true);(141,false);(139,false)];
  [(100,false);(129,true);(144,true);(125,true);(141,false);(155,true)];
  [(28,false);(59,true);(143,false);(148,true);(141,false);(139,false)];
  [(129,true);(148,true);(28,true);(27,true);(40,true);(136,true);(143,false);(145,true);(141,false);(139,false);(151,true)];
  [(26,true);(126,true);(144,true);(125,true);(148,true);(28,true);(27,true)];
  [(26,false);(40,true);(136,true);(148,true);(143,false);(141,false)];
  [(144,true);(111,true);(141,false);(139,false);(135,true);(136,true);(137,true);(142,true);(140,true)];
  [(43,true);(149,true);(140,true);(144,false);(141,false);(38,true);(39,true)];
  [(144,false);(141,false);(140,true);(136,true);(139,false);(156,false)]
].

Theorem c12_k7_cover4_micro_block143_sound :
  forall rho, satisfies_cnf rho ((c12_k7_cover_base 4)) ->
    satisfies_cnf rho c12_k7_cover4_micro_block143_output.
Proof.
intros rho Hbase.
pose (select_cnf c12_k7_cover4_micro_block016_output [8] : cnf)
  as imported_from_block016.
assert (Himported_from_block016 :
  satisfies_cnf rho imported_from_block016).
{
  unfold imported_from_block016.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block016_output [8]).
  - exact (c12_k7_cover4_micro_block016_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block019_output [15;16] : cnf)
  as imported_from_block019.
assert (Himported_from_block019 :
  satisfies_cnf rho imported_from_block019).
{
  unfold imported_from_block019.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block019_output [15;16]).
  - exact (c12_k7_cover4_micro_block019_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block021_output [19] : cnf)
  as imported_from_block021.
assert (Himported_from_block021 :
  satisfies_cnf rho imported_from_block021).
{
  unfold imported_from_block021.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block021_output [19]).
  - exact (c12_k7_cover4_micro_block021_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block023_output [2;3] : cnf)
  as imported_from_block023.
assert (Himported_from_block023 :
  satisfies_cnf rho imported_from_block023).
{
  unfold imported_from_block023.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block023_output [2;3]).
  - exact (c12_k7_cover4_micro_block023_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block024_output [13;19] : cnf)
  as imported_from_block024.
assert (Himported_from_block024 :
  satisfies_cnf rho imported_from_block024).
{
  unfold imported_from_block024.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block024_output [13;19]).
  - exact (c12_k7_cover4_micro_block024_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block030_output [6] : cnf)
  as imported_from_block030.
assert (Himported_from_block030 :
  satisfies_cnf rho imported_from_block030).
{
  unfold imported_from_block030.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block030_output [6]).
  - exact (c12_k7_cover4_micro_block030_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block031_output [16] : cnf)
  as imported_from_block031.
assert (Himported_from_block031 :
  satisfies_cnf rho imported_from_block031).
{
  unfold imported_from_block031.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block031_output [16]).
  - exact (c12_k7_cover4_micro_block031_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block032_output [11] : cnf)
  as imported_from_block032.
assert (Himported_from_block032 :
  satisfies_cnf rho imported_from_block032).
{
  unfold imported_from_block032.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block032_output [11]).
  - exact (c12_k7_cover4_micro_block032_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block033_output [5;3] : cnf)
  as imported_from_block033.
assert (Himported_from_block033 :
  satisfies_cnf rho imported_from_block033).
{
  unfold imported_from_block033.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block033_output [5;3]).
  - exact (c12_k7_cover4_micro_block033_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block038_output [3] : cnf)
  as imported_from_block038.
assert (Himported_from_block038 :
  satisfies_cnf rho imported_from_block038).
{
  unfold imported_from_block038.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block038_output [3]).
  - exact (c12_k7_cover4_micro_block038_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block040_output [23] : cnf)
  as imported_from_block040.
assert (Himported_from_block040 :
  satisfies_cnf rho imported_from_block040).
{
  unfold imported_from_block040.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block040_output [23]).
  - exact (c12_k7_cover4_micro_block040_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block041_output [16;0] : cnf)
  as imported_from_block041.
assert (Himported_from_block041 :
  satisfies_cnf rho imported_from_block041).
{
  unfold imported_from_block041.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block041_output [16;0]).
  - exact (c12_k7_cover4_micro_block041_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block042_output [8;10;23] : cnf)
  as imported_from_block042.
assert (Himported_from_block042 :
  satisfies_cnf rho imported_from_block042).
{
  unfold imported_from_block042.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block042_output [8;10;23]).
  - exact (c12_k7_cover4_micro_block042_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block043_output [0;7] : cnf)
  as imported_from_block043.
assert (Himported_from_block043 :
  satisfies_cnf rho imported_from_block043).
{
  unfold imported_from_block043.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block043_output [0;7]).
  - exact (c12_k7_cover4_micro_block043_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block051_output [3] : cnf)
  as imported_from_block051.
assert (Himported_from_block051 :
  satisfies_cnf rho imported_from_block051).
{
  unfold imported_from_block051.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block051_output [3]).
  - exact (c12_k7_cover4_micro_block051_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block068_output [14] : cnf)
  as imported_from_block068.
assert (Himported_from_block068 :
  satisfies_cnf rho imported_from_block068).
{
  unfold imported_from_block068.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block068_output [14]).
  - exact (c12_k7_cover4_micro_block068_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block078_output [16;23;19] : cnf)
  as imported_from_block078.
assert (Himported_from_block078 :
  satisfies_cnf rho imported_from_block078).
{
  unfold imported_from_block078.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block078_output [16;23;19]).
  - exact (c12_k7_cover4_micro_block078_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block081_output [3] : cnf)
  as imported_from_block081.
assert (Himported_from_block081 :
  satisfies_cnf rho imported_from_block081).
{
  unfold imported_from_block081.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block081_output [3]).
  - exact (c12_k7_cover4_micro_block081_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block082_output [5;2] : cnf)
  as imported_from_block082.
assert (Himported_from_block082 :
  satisfies_cnf rho imported_from_block082).
{
  unfold imported_from_block082.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block082_output [5;2]).
  - exact (c12_k7_cover4_micro_block082_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block083_output [18] : cnf)
  as imported_from_block083.
assert (Himported_from_block083 :
  satisfies_cnf rho imported_from_block083).
{
  unfold imported_from_block083.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block083_output [18]).
  - exact (c12_k7_cover4_micro_block083_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block097_output [10] : cnf)
  as imported_from_block097.
assert (Himported_from_block097 :
  satisfies_cnf rho imported_from_block097).
{
  unfold imported_from_block097.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block097_output [10]).
  - exact (c12_k7_cover4_micro_block097_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block103_output [21] : cnf)
  as imported_from_block103.
assert (Himported_from_block103 :
  satisfies_cnf rho imported_from_block103).
{
  unfold imported_from_block103.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block103_output [21]).
  - exact (c12_k7_cover4_micro_block103_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block107_output [16] : cnf)
  as imported_from_block107.
assert (Himported_from_block107 :
  satisfies_cnf rho imported_from_block107).
{
  unfold imported_from_block107.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block107_output [16]).
  - exact (c12_k7_cover4_micro_block107_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block112_output [18;19] : cnf)
  as imported_from_block112.
assert (Himported_from_block112 :
  satisfies_cnf rho imported_from_block112).
{
  unfold imported_from_block112.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block112_output [18;19]).
  - exact (c12_k7_cover4_micro_block112_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block113_output [1] : cnf)
  as imported_from_block113.
assert (Himported_from_block113 :
  satisfies_cnf rho imported_from_block113).
{
  unfold imported_from_block113.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block113_output [1]).
  - exact (c12_k7_cover4_micro_block113_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block118_output [11] : cnf)
  as imported_from_block118.
assert (Himported_from_block118 :
  satisfies_cnf rho imported_from_block118).
{
  unfold imported_from_block118.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block118_output [11]).
  - exact (c12_k7_cover4_micro_block118_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block124_output [10] : cnf)
  as imported_from_block124.
assert (Himported_from_block124 :
  satisfies_cnf rho imported_from_block124).
{
  unfold imported_from_block124.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block124_output [10]).
  - exact (c12_k7_cover4_micro_block124_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block127_output [19] : cnf)
  as imported_from_block127.
assert (Himported_from_block127 :
  satisfies_cnf rho imported_from_block127).
{
  unfold imported_from_block127.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block127_output [19]).
  - exact (c12_k7_cover4_micro_block127_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block128_output [0] : cnf)
  as imported_from_block128.
assert (Himported_from_block128 :
  satisfies_cnf rho imported_from_block128).
{
  unfold imported_from_block128.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block128_output [0]).
  - exact (c12_k7_cover4_micro_block128_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block129_output [10] : cnf)
  as imported_from_block129.
assert (Himported_from_block129 :
  satisfies_cnf rho imported_from_block129).
{
  unfold imported_from_block129.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block129_output [10]).
  - exact (c12_k7_cover4_micro_block129_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block130_output [18;22;5;15] : cnf)
  as imported_from_block130.
assert (Himported_from_block130 :
  satisfies_cnf rho imported_from_block130).
{
  unfold imported_from_block130.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block130_output [18;22;5;15]).
  - exact (c12_k7_cover4_micro_block130_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block137_output [15;18;13] : cnf)
  as imported_from_block137.
assert (Himported_from_block137 :
  satisfies_cnf rho imported_from_block137).
{
  unfold imported_from_block137.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block137_output [15;18;13]).
  - exact (c12_k7_cover4_micro_block137_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block138_output [5;10;17;0;13] : cnf)
  as imported_from_block138.
assert (Himported_from_block138 :
  satisfies_cnf rho imported_from_block138).
{
  unfold imported_from_block138.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block138_output [5;10;17;0;13]).
  - exact (c12_k7_cover4_micro_block138_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block139_output [14;18;3;24;22] : cnf)
  as imported_from_block139.
assert (Himported_from_block139 :
  satisfies_cnf rho imported_from_block139).
{
  unfold imported_from_block139.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block139_output [14;18;3;24;22]).
  - exact (c12_k7_cover4_micro_block139_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block140_output [10;18;8;0;3] : cnf)
  as imported_from_block140.
assert (Himported_from_block140 :
  satisfies_cnf rho imported_from_block140).
{
  unfold imported_from_block140.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block140_output [10;18;8;0;3]).
  - exact (c12_k7_cover4_micro_block140_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block141_output [0] : cnf)
  as imported_from_block141.
assert (Himported_from_block141 :
  satisfies_cnf rho imported_from_block141).
{
  unfold imported_from_block141.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block141_output [0]).
  - exact (c12_k7_cover4_micro_block141_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block142_output [22;23;24;18;16] : cnf)
  as imported_from_block142.
assert (Himported_from_block142 :
  satisfies_cnf rho imported_from_block142).
{
  unfold imported_from_block142.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block142_output [22;23;24;18;16]).
  - exact (c12_k7_cover4_micro_block142_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (concat [imported_from_block016;imported_from_block019;imported_from_block021;imported_from_block023;imported_from_block024;imported_from_block030;imported_from_block031;imported_from_block032;imported_from_block033;imported_from_block038;imported_from_block040;imported_from_block041;imported_from_block042;imported_from_block043;imported_from_block051;imported_from_block068;imported_from_block078;imported_from_block081;imported_from_block082;imported_from_block083;imported_from_block097;imported_from_block103;imported_from_block107;imported_from_block112;imported_from_block113;imported_from_block118;imported_from_block124;imported_from_block127;imported_from_block128;imported_from_block129;imported_from_block130;imported_from_block137;imported_from_block138;imported_from_block139;imported_from_block140;imported_from_block141;imported_from_block142] : cnf) as imported.
assert (Himported : satisfies_cnf rho imported).
{
  unfold imported.
  apply satisfies_cnf_concat_intro.
  constructor.
  { exact Himported_from_block016. }
  constructor.
  { exact Himported_from_block019. }
  constructor.
  { exact Himported_from_block021. }
  constructor.
  { exact Himported_from_block023. }
  constructor.
  { exact Himported_from_block024. }
  constructor.
  { exact Himported_from_block030. }
  constructor.
  { exact Himported_from_block031. }
  constructor.
  { exact Himported_from_block032. }
  constructor.
  { exact Himported_from_block033. }
  constructor.
  { exact Himported_from_block038. }
  constructor.
  { exact Himported_from_block040. }
  constructor.
  { exact Himported_from_block041. }
  constructor.
  { exact Himported_from_block042. }
  constructor.
  { exact Himported_from_block043. }
  constructor.
  { exact Himported_from_block051. }
  constructor.
  { exact Himported_from_block068. }
  constructor.
  { exact Himported_from_block078. }
  constructor.
  { exact Himported_from_block081. }
  constructor.
  { exact Himported_from_block082. }
  constructor.
  { exact Himported_from_block083. }
  constructor.
  { exact Himported_from_block097. }
  constructor.
  { exact Himported_from_block103. }
  constructor.
  { exact Himported_from_block107. }
  constructor.
  { exact Himported_from_block112. }
  constructor.
  { exact Himported_from_block113. }
  constructor.
  { exact Himported_from_block118. }
  constructor.
  { exact Himported_from_block124. }
  constructor.
  { exact Himported_from_block127. }
  constructor.
  { exact Himported_from_block128. }
  constructor.
  { exact Himported_from_block129. }
  constructor.
  { exact Himported_from_block130. }
  constructor.
  { exact Himported_from_block137. }
  constructor.
  { exact Himported_from_block138. }
  constructor.
  { exact Himported_from_block139. }
  constructor.
  { exact Himported_from_block140. }
  constructor.
  { exact Himported_from_block141. }
  constructor.
  { exact Himported_from_block142. }
  constructor.
}
pose (
  [66;67;68;69;70;71;72;73;74;75;76;77;2014;37;5035;5285;5337;0;11;21;30;38;45;51;56;60;63;65;10;2015;5448;5445;5442;5371;5406;5436;4699;5284;4110;4431;3827;619;2745;2742;59;543;403;5328;1637;1707;5324;5306;5289;2309;4076;5313;31;64;5290;4679;55;4702;5287;4113;4701;5286;4112;20;4697;2301;4108;2280;2295;2310;29;4698;4109;4700;3646;34;2921;2284;4726;58;40;4199;4140;4207;4209;2281;4723;33;2283;4725;5318;578;621;487;3019;3017;3018;2944;2979;2287;35;2285;5320;36;2286;5321;2;2288;12;4808;4811;4813;4794;4814;4744;42;4683;48;27;57;8;1803;1676;4250;4245;4229;4174;4248;4075;3016;2978;2943;3014;3015;3013;4149;4218;53;1296;4129;4081;4733;4098;4204;4169;4243;4224;4246;16;4078;2307;5334;4077;46;4082;25;2308;5335;4820;4805;4807;4740;4806;4790;2314;2315;5382;18;2269;2317;2336;3025;3027;3028;2986;2951;4713;32;4703;4094;5437;5430;5433;5396;5361;62;4704;50;3650;4747;4745;4746;4735;4748;4097;4099;4100;4096;4093;5308;2329;2330;2319;2324;2331;3023;3026;2984;2949;5288;4739;4751;4753;4754;4681;2689;2688;2682;2619;5309;5302;4680;4095;2299;2278;2293;2396;2386;2402;2405;2408;4712;4119;5301;23;4719;2273;5310;2730;2725;5446;5443;5372;24;2274;4125;4720;5311;44;3037;3044;3046;3007;2972;2263;2272;2678;2676;2677;2680;2679;2620;2277;4682;5314;2275;5312;4080;4721;26;2276;4722;2279;28;5315;1;4734;5345;5344;5338;22;4718;3010;3008;2996;3020;3022;2981;2946;5615;5613;5617;404;1168;5616;5614;3021;2980;2945] : list nat) as base_ids.
pose ([
  ([86;259;257;284;289],[0;1;2;3;4;5;6;7;8;9;10;11;12;341;13;14;15;16;17;18;19;20;21;22;23;24;25;26;27;28;29;30;31;32;33;34;35]);
  ([248;59;269;284;289;280;276],[0;1;2;3;4;5;6;7;8;9;10;11;12;341;13;36;37;38;14;16;39;303;307;306;40;41;309;17;18;19;20;21;22;23;24;25;26;27;28;29;42;43]);
  ([174;284;276;280;287;269;273],[0;1;2;3;4;5;6;7;8;9;10;11;12;341;44;368;14;40;45;46;41;309;39;352;17;18;19;20;21;22;23;24;25;26;27;28;29;369;47;318;48;312;320;49;321;50;51;52;53;54;55;373;370;374;56;30;31;32;33;34;35;57;58;59;60;61;62;63;64;65;66;67;68;69;70;71;72;73;74;75;76;77;78;344;345]);
  ([80;161;175;279;297;280],[0;1;2;3;4;5;6;7;8;9;10;11;12;341;79;353;354;362;357;355;80;363;81;82;39;17;18;19;20;21;22;23;24;25;26;27;28;29;83;84;356;85;86;87;88]);
  ([74;297;276;273;284;280],[0;1;2;3;4;5;6;7;8;9;10;11;12;341;56;327;331;330;328;89;90;332]);
  ([78;297;175;279;283;276;284;75;280],[0;1;2;3;4;5;6;7;8;9;10;11;12;341;91;92;93;94;80;40;46;95;96;97;358;349;39;17;18;19;20;21;22;23;24;25;26;27;28;29;376;356;98;99;100;101;102;13;103;104;105;106;107;108;109;110;111;112;113;114;115;116;117;118;119;120;121;122;123;124;125;319;323;126;314;127;88;128;129;130;131;132]);
  ([297;175;276;283;279;280;284;273],[0;1;2;3;4;5;6;7;8;9;10;11;12;341;80;377;378;40;46;96;97;358;39;349;352;17;18;19;20;21;22;23;24;25;26;27;28;29;133;134;135;325;136;137;138;13;103;112;110;111;121;104;105;106;107;108;109;79;353;376;81;82;357;113;115;116;117;118;83;350;85;139;140;84;119;120;141;122;124;316;142;322;317;324]);
  ([78;305;276;284;175;309],[0;1;2;3;4;5;6;7;8;9;10;11;12;341;91;143;367;364;144;40;14;145;146;17;18;19;20;21;22;23;24;25;26;27;28;29;334;147;128;148;149;150;151;152;153;123;154;155;73;156;157;158;159;83;350;160;161;162]);
  ([201;257;287;251;309;205;207],[0;1;2;3;4;5;6;7;8;9;10;11;12;341;145;17;18;19;20;21;22;23;24;25;26;27;28;29;113;163;164;165;166;167;57;168;121;123;124;169;141;122;170]);
  ([200;29;27;293],[0;1;2;3;4;5;6;7;8;9;10;11;12;341;171;172;173;17;18;19;20;21;22;23;24;25;26;27;28;29;174]);
  ([87;75;309;293;280;289;276;79;271],[0;1;2;3;4;5;6;7;8;9;10;11;12;341;175;176;177;178;179;145;173;180;39;120;16;77;40;133;17;18;19;20;21;22;23;24;25;26;27;28;29;79;104;107;112;110;382;181;381;337;113;163;164;166;167;44;182;183]);
  ([257;249;276;289;280;301;251],[0;1;2;3;4;5;6;7;8;9;10;11;12;341;40;16;39;17;18;19;20;21;22;23;24;25;26;27;28;29;35;184;185;186;187;188;189;190;57;191;64;66;60;61;63;74;75;76;67;68;69;70;346;344;192;347;348;343]);
  ([207;27;29;276;309;284;293;201;199],[0;1;2;3;4;5;6;7;8;9;10;11;12;341;40;145;14;173;165;193;194;195;196;17;18;19;20;21;22;23;24;25;26;27;28;29;197;104;198;123;121;199;141;200;122;201;57;168;202;203;204;205;206;207;208]);
  ([201;51;280;309;276;199;287;249;251;295;273;284;29;293;75;79;271],[0;1;2;3;4;5;6;7;8;9;10;11;12;341;39;304;309;46;337;145;40;352;14;176;136;209;210;211;212;17;18;19;20;21;22;23;24;25;26;27;28;29;375;181;349;79;107;112;110;318;312;320;385;351;384;119;182;156;213;335;329;326;57;58;214;215;216;217;118;122;201;218;121;199;200;123;132;198;219;220;221]);
  ([75;293;276;295;301;280;309;273;284;79;271;289],[0;1;2;3;4;5;6;7;8;9;10;11;12;341;173;40;222;39;96;309;145;14;383;17;18;19;20;21;22;23;24;25;26;27;28;29;375;13;223;224;15;379;384;318;320;182;183;156;213;386;171;172;382;225;226;227;228;229;160;230;231;232;233;234;112;235;236;237;333]);
  ([52;284;273;295;276;280],[0;1;2;3;4;5;6;7;8;9;10;11;12;341;238;239;240;241;329]);
  ([248;53;269;284;289;280;276],[0;1;2;3;4;5;6;7;8;9;10;11;12;341;13;36;37;38;374;14;41;16;39;95;309;46;306;40;17;18;19;20;21;22;23;24;25;26;27;28;29;242;243]);
  ([198;257;287;249;280;309],[0;1;2;3;4;5;6;7;8;9;10;11;12;341;124;169;59;244;245;39;145;17;18;19;20;21;22;23;24;25;26;27;28;29;33;188;246]);
  ([54;117;284;295;280;276],[0;1;2;3;4;5;6;7;8;9;10;11;12;341;247;248;249;250;251;78;342;348]);
  ([257;295;55;53;79;271;284;289;280;276;301],[0;1;2;3;4;5;6;7;8;9;10;11;12;341;222;389;14;41;16;39;40;384;95;309;46;17;18;19;20;21;22;23;24;25;26;27;28;29;375;252;77;15;379;176;253;254;255;256;257;318;48;320;321;56;181;79;107;112;258;259;110;390;382;260;261;262;263;264;265;385;122;266;267;268;159;269;270;271;272;273;274;275;74;276;277;278;279;71;119;280]);
  ([51;251;287;249;295;55;53],[0;1;2;3;4;5;6;7;8;9;10;11;12;341;326;222;17;18;19;20;21;22;23;24;25;26;27;28;29;57;260;261;262;263;264;265;122;266;159;269;273;274;74;276;277;228;279;71;281;282;283]);
  ([50;79;271;295;284;280],[0;1;2;3;4;5;6;7;8;9;10;11;12;341;284;259;285;223;222;14;39;17;18;19;20;21;22;23;24;25;26;27;28;29;286;287;288;178;256]);
  ([287;221;280;276;269;271;273;283;279],[0;1;2;3;4;5;6;7;8;9;10;11;12;341;39;40;371;372;359;17;18;19;20;21;22;23;24;25;26;27;28;29;46;375;379;318;48;312;320;49;321;380;388;394;387;389;56;391;392;393;260;261;262;263;264;265;182;183;156;213;252;77;15;122;266;268;235;267;159;269;271;273;274;275;74;276;277;228;278;279;71;214]);
  ([85;297;279;286;280;75;77],[0;1;2;3;4;5;6;7;8;9;10;11;12;341;80;16;39;289;17;18;19;20;21;22;23;24;25;26;27;28;29;137;290;100;291;292;359;104;105;293;91;92;93;294;13;103;295;79;363;360]);
  ([286;280;279;271;276;310],[0;1;2;3;4;5;6;7;8;9;10;11;12;341;16;39;40;96;296;310;305;308;17;18;19;20;21;22;23;24;25;26;27;28;29;312;359;311;313;297;315;314;365;361;366;336;396;107;108;298;339;340;337;79;360;82;299;338;300;136;301;302;91])
] : list (list nat * list nat)) as records.
assert (Hcheck :
  check_selected_microblock ((c12_k7_cover_base 4)) base_ids
    imported records c12_k7_cover4_micro_block143_output = true).
{ vm_compute. reflexivity. }
exact (check_selected_microblock_sound
  ((c12_k7_cover_base 4)) base_ids imported records c12_k7_cover4_micro_block143_output
  Hcheck rho Hbase Himported).
Qed.
