(** Generated by [scripts/generate_ckpath_certificates.py].
    Only the block output is transparent.  Selected base clauses,
    producer imports, replay records, and the transient database
    all remain underneath the opaque soundness theorem. *)

From Stdlib Require Import List.
From Digraph Require Import ckpath_cnf ckpath_drup_microblock ckpath_cert_k7_c12_low3_reduction ckpath_cert_k7_c12_low3_mask04_block00 ckpath_cert_k7_c12_low3_mask04_block02 ckpath_cert_k7_c12_low3_mask04_block04 ckpath_cert_k7_c12_low3_mask04_block05 ckpath_cert_k7_c12_low3_mask04_block08 ckpath_cert_k7_c12_low3_mask04_block09 ckpath_cert_k7_c12_low3_mask04_block10 ckpath_cert_k7_c12_low3_mask04_block11 ckpath_cert_k7_c12_low3_mask04_block14 ckpath_cert_k7_c12_low3_mask04_block15.
Import ListNotations.
Set Warnings "-abstract-large-number".

(** Original retained additions [400, 425); 178 selected base clauses and 47 imported consequences from 10 producer blocks. *)
Definition c12_k7_low3_mask04_block16_output : cnf :=
  [
  [(51,true);(137,false);(113,false);(143,false)];
  [(137,false);(113,false);(143,false)];
  [(113,false);(143,false)];
  [(137,true);(143,false)];
  [(141,false);(135,false);(144,false);(143,false)];
  [(135,false);(144,false);(143,false)];
  [(144,false);(143,false)];
  [(143,false)];
  [(144,true)];
  [(141,true)];
  [(142,true)];
  [(138,true)];
  [(140,true)];
  [(135,true)];
  [(137,true)];
  [(28,false)];
  [(153,false)];
  [(154,false)];
  [(29,false)];
  [(150,false)];
  [(152,false)];
  [(147,false)];
  [(112,false)];
  [(149,false)];
  [(91,false)]
].

Theorem c12_k7_low3_mask04_block16_sound :
  forall rho, satisfies_cnf rho (c12_k7_low3_instance [true; true; false; false; false; false; true; false; false; false; false; false]) ->
    satisfies_cnf rho c12_k7_low3_mask04_block16_output.
Proof.
intros rho Hbase.
pose (select_cnf c12_k7_low3_mask04_block00_output [0;1;2;3;4;5;6;7;8;9;10;11;12;22;19] : cnf)
  as imported_from_block00.
assert (Himported_from_block00 :
  satisfies_cnf rho imported_from_block00).
{
  unfold imported_from_block00.
  apply (satisfies_cnf_select rho c12_k7_low3_mask04_block00_output [0;1;2;3;4;5;6;7;8;9;10;11;12;22;19]).
  - exact (c12_k7_low3_mask04_block00_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask04_block02_output [12] : cnf)
  as imported_from_block02.
assert (Himported_from_block02 :
  satisfies_cnf rho imported_from_block02).
{
  unfold imported_from_block02.
  apply (satisfies_cnf_select rho c12_k7_low3_mask04_block02_output [12]).
  - exact (c12_k7_low3_mask04_block02_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask04_block04_output [16;18;4] : cnf)
  as imported_from_block04.
assert (Himported_from_block04 :
  satisfies_cnf rho imported_from_block04).
{
  unfold imported_from_block04.
  apply (satisfies_cnf_select rho c12_k7_low3_mask04_block04_output [16;18;4]).
  - exact (c12_k7_low3_mask04_block04_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask04_block05_output [9;5] : cnf)
  as imported_from_block05.
assert (Himported_from_block05 :
  satisfies_cnf rho imported_from_block05).
{
  unfold imported_from_block05.
  apply (satisfies_cnf_select rho c12_k7_low3_mask04_block05_output [9;5]).
  - exact (c12_k7_low3_mask04_block05_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask04_block08_output [7;19;17;16;23;20] : cnf)
  as imported_from_block08.
assert (Himported_from_block08 :
  satisfies_cnf rho imported_from_block08).
{
  unfold imported_from_block08.
  apply (satisfies_cnf_select rho c12_k7_low3_mask04_block08_output [7;19;17;16;23;20]).
  - exact (c12_k7_low3_mask04_block08_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask04_block09_output [22;18] : cnf)
  as imported_from_block09.
assert (Himported_from_block09 :
  satisfies_cnf rho imported_from_block09).
{
  unfold imported_from_block09.
  apply (satisfies_cnf_select rho c12_k7_low3_mask04_block09_output [22;18]).
  - exact (c12_k7_low3_mask04_block09_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask04_block10_output [7;14;11;10] : cnf)
  as imported_from_block10.
assert (Himported_from_block10 :
  satisfies_cnf rho imported_from_block10).
{
  unfold imported_from_block10.
  apply (satisfies_cnf_select rho c12_k7_low3_mask04_block10_output [7;14;11;10]).
  - exact (c12_k7_low3_mask04_block10_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask04_block11_output [22;24;19;21;10] : cnf)
  as imported_from_block11.
assert (Himported_from_block11 :
  satisfies_cnf rho imported_from_block11).
{
  unfold imported_from_block11.
  apply (satisfies_cnf_select rho c12_k7_low3_mask04_block11_output [22;24;19;21;10]).
  - exact (c12_k7_low3_mask04_block11_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask04_block14_output [0;1;6] : cnf)
  as imported_from_block14.
assert (Himported_from_block14 :
  satisfies_cnf rho imported_from_block14).
{
  unfold imported_from_block14.
  apply (satisfies_cnf_select rho c12_k7_low3_mask04_block14_output [0;1;6]).
  - exact (c12_k7_low3_mask04_block14_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask04_block15_output [4;8;24;7;21;22] : cnf)
  as imported_from_block15.
assert (Himported_from_block15 :
  satisfies_cnf rho imported_from_block15).
{
  unfold imported_from_block15.
  apply (satisfies_cnf_select rho c12_k7_low3_mask04_block15_output [4;8;24;7;21;22]).
  - exact (c12_k7_low3_mask04_block15_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (concat [imported_from_block00;imported_from_block02;imported_from_block04;imported_from_block05;imported_from_block08;imported_from_block09;imported_from_block10;imported_from_block11;imported_from_block14;imported_from_block15] : cnf) as imported.
assert (Himported : satisfies_cnf rho imported).
{
  unfold imported.
  apply satisfies_cnf_concat_intro.
  constructor.
  { exact Himported_from_block00. }
  constructor.
  { exact Himported_from_block02. }
  constructor.
  { exact Himported_from_block04. }
  constructor.
  { exact Himported_from_block05. }
  constructor.
  { exact Himported_from_block08. }
  constructor.
  { exact Himported_from_block09. }
  constructor.
  { exact Himported_from_block10. }
  constructor.
  { exact Himported_from_block11. }
  constructor.
  { exact Himported_from_block14. }
  constructor.
  { exact Himported_from_block15. }
  constructor.
}
pose (
  [66;67;68;69;70;71;72;73;74;75;76;77;4154;28;1147;2535;1163;4159;187;206;201;95;4157;4155;1154;4158;1166;4156;1159;4152;1130;43;1146;7;1083;1164;2518;3271;3261;3206;3270;3268;3265;1258;1278;40;2538;2523;1065;1143;3001;2932;2997;2987;2967;3003;41;2522;34;2521;26;1145;17;1165;2519;52;2524;1915;1935;1880;1945;1952;13;22;3;39;1064;1142;1068;85;91;93;2151;162;172;79;170;168;1288;169;19;1170;2534;1075;1082;1054;1079;2988;2948;1069;24;1049;1125;2548;3841;3850;3856;3853;3857;3846;183;185;37;2542;2464;50;2544;55;64;2543;1811;1236;1277;1275;1201;1047;1052;1128;1051;1127;57;2507;35;8;53;48;42;1861;1926;1896;1932;202;198;184;92;2898;2958;2964;2968;47;2520;1152;1157;58;1078;1158;1482;2233;1912;1949;204;1084;207;203;205;186;200;297;94;171;25;2529;1050;1126;2512;1233;1273;1198] : list nat) as base_ids.
pose ([
  ([101;272;224;284],[0;1;2;3;4;5;6;7;8;9;10;11;178;179;180;181;182;183;184;185;186;187;188;189;193;219;220;221;12;13;222;14;15;16;17;18;19;20;21;22;199;190;23;24;200;25;26;27;28;216;29;30;191;201;31;32;33;34;35;36;202;37;38;39;40;41;42;217;218;43;44]);
  ([272;224;284],[0;1;2;3;4;5;6;7;8;9;10;11;178;179;180;181;182;183;184;185;186;187;188;189;193;219;220;12;225;13;222;14;15;16;17;45;46;47;48;49;22;50;51;52;53;54;55;56;57;33;34;35;36;58;59;60;61;62;63;64;65;66;67;68;69;70;71;72;73;191;74;75;76;77;31;78;32;79;80;81;21;82;203]);
  ([224;284],[0;1;2;3;4;5;6;7;8;9;10;11;178;179;180;181;182;183;184;185;186;187;188;189;193;219;220;13;222;15;16;226;17;22;83;84;85;86;87;23;24;194;204;197;211;29;30;191;88]);
  ([273;284],[0;1;2;3;4;5;6;7;8;9;10;11;178;179;180;181;182;183;184;185;186;187;188;189;193;219;220;83;84;85;86;87;89;17;227;23;194;204;197;211;29;25;27;22;223;207;208;205;90;91;92;93;94;95;96;192;209;97;98]);
  ([280;268;286;284],[0;1;2;3;4;5;6;7;8;9;10;11;178;179;180;181;182;183;184;185;186;187;188;189;193;219;220;22;29;17;227;228;224;12;99;90;91;92;94;95;201;190;205;33;34;35;36;100;101;102;103;204;104;105;106;107;108;109;110;111;112;113;114;115;116;117;118;119;120;27;216;96;25;44;121;122;123;124;212;199;37;38;39;40;41;42;218;73;125;126;127;128;129;31;130;131;132;133;134;135;136;137;68;138;139;140]);
  ([268;286;284],[0;1;2;3;4;5;6;7;8;9;10;11;178;179;180;181;182;183;184;185;186;187;188;189;193;219;220;29;229;17;227;228;141;142;143;198;224;12;99;25;197;27;211;96;200]);
  ([286;284],[0;1;2;3;4;5;6;7;8;9;10;11;178;179;180;181;182;183;184;185;186;187;188;189;193;219;220;230;17;227;228;79;144;80;81;224;12;99;23;194;195;93;22;27;211;96;25;197;90;91;92;94;54;98;145;146;147;148;196;149;47;60;150;151;152;33;34;35;36;58;56;57;65;66;153;131;154;155;213;156;157;199;158;159]);
  ([284],[0;1;2;3;4;5;6;7;8;9;10;11;178;179;180;181;182;183;184;185;186;187;188;189;193;219;220;17;227;228;231;224;12;99;18;19;20;21;160;90;91;92;94;23;93;25;161;27;96;200]);
  ([287],[0;1;2;3;4;5;6;7;8;9;10;11;178;179;180;181;182;183;184;185;186;187;188;189;193;219;220;232;18;19;84;20;21;162]);
  ([281],[0;1;2;3;4;5;6;7;8;9;10;11;178;179;180;181;182;183;184;185;186;187;188;189;193;219;220;232;233;144;141;222;142;143;89;163]);
  ([283],[0;1;2;3;4;5;6;7;8;9;10;11;178;179;180;181;182;183;184;185;186;187;188;189;193;219;220;232;233;234;86;111;164]);
  ([275],[0;1;2;3;4;5;6;7;8;9;10;11;178;179;180;181;182;183;184;185;186;187;188;189;193;219;220;232;233;234;235;79;110;165]);
  ([279],[0;1;2;3;4;5;6;7;8;9;10;11;178;179;180;181;182;183;184;185;186;187;188;189;193;219;220;232;233;234;235;236;87;166]);
  ([269],[0;1;2;3;4;5;6;7;8;9;10;11;178;179;180;181;182;183;184;185;186;187;188;189;193;219;220;232;233;234;235;236;237;167;168]);
  ([273],[0;1;2;3;4;5;6;7;8;9;10;11;178;179;180;181;182;183;184;185;186;187;188;189;193;219;220;232;233;234;235;236;237;238;169]);
  ([54],[0;1;2;3;4;5;6;7;8;9;10;11;178;179;180;181;182;183;184;185;186;187;188;189;193;219;220;232;233;234;235;236;237;238;239;100;101;102;103;204]);
  ([304],[0;1;2;3;4;5;6;7;8;9;10;11;178;179;180;181;182;183;184;185;186;187;188;189;193;219;220;232;233;234;235;236;237;238;239;240;22]);
  ([306],[0;1;2;3;4;5;6;7;8;9;10;11;178;179;180;181;182;183;184;185;186;187;188;189;193;219;220;232;233;234;235;236;237;238;239;240;241;25]);
  ([56],[0;1;2;3;4;5;6;7;8;9;10;11;178;179;180;181;182;183;184;185;186;187;188;189;193;219;220;232;233;234;235;236;237;238;239;240;241;242;170;171;59;172;173;174;214;210;211]);
  ([298],[0;1;2;3;4;5;6;7;8;9;10;11;178;179;180;181;182;183;184;185;186;187;188;189;193;219;220;232;233;234;235;236;237;238;239;240;241;242;243;23]);
  ([302],[0;1;2;3;4;5;6;7;8;9;10;11;178;179;180;181;182;183;184;185;186;187;188;189;193;219;220;232;233;234;235;236;237;238;239;240;241;242;243;244;27]);
  ([292],[0;1;2;3;4;5;6;7;8;9;10;11;178;179;180;181;182;183;184;185;186;187;188;189;193;219;220;232;233;234;235;236;237;238;239;240;241;242;243;244;245;29]);
  ([222],[0;1;2;3;4;5;6;7;8;9;10;11;178;179;180;181;182;183;184;185;186;187;188;189;193;219;220;232;233;234;235;236;237;238;239;240;241;242;243;244;245;246;90;94;161;93;96;200]);
  ([296],[0;1;2;3;4;5;6;7;8;9;10;11;178;179;180;181;182;183;184;185;186;187;188;189;193;219;220;232;233;234;235;236;237;238;239;240;241;242;243;244;245;246;247;12]);
  ([180],[0;1;2;3;4;5;6;7;8;9;10;11;178;179;180;181;182;183;184;185;186;187;188;189;193;219;220;232;233;234;235;236;237;238;239;240;241;242;243;244;245;246;247;248;60;61;150;151;152;206;175;176;177;215;127])
] : list (list nat * list nat)) as records.
assert (Hcheck :
  check_selected_microblock (c12_k7_low3_instance [true; true; false; false; false; false; true; false; false; false; false; false]) base_ids
    imported records c12_k7_low3_mask04_block16_output = true).
{ vm_compute. reflexivity. }
exact (check_selected_microblock_sound
  (c12_k7_low3_instance [true; true; false; false; false; false; true; false; false; false; false; false]) base_ids imported records c12_k7_low3_mask04_block16_output
  Hcheck rho Hbase Himported).
Qed.
