(** Generated by [scripts/generate_ckpath_certificates.py].
    Only the block output is transparent.  Selected base clauses,
    producer imports, replay records, and the transient database
    all remain underneath the opaque soundness theorem. *)

From Stdlib Require Import List.
From Digraph Require Import ckpath_cnf ckpath_drup_microblock ckpath_cert_k7_c12_low3_reduction ckpath_cert_k7_c12_low3_mask15_block00 ckpath_cert_k7_c12_low3_mask15_block01 ckpath_cert_k7_c12_low3_mask15_block02 ckpath_cert_k7_c12_low3_mask15_block03 ckpath_cert_k7_c12_low3_mask15_block04 ckpath_cert_k7_c12_low3_mask15_block05 ckpath_cert_k7_c12_low3_mask15_block06 ckpath_cert_k7_c12_low3_mask15_block07 ckpath_cert_k7_c12_low3_mask15_block08 ckpath_cert_k7_c12_low3_mask15_block09 ckpath_cert_k7_c12_low3_mask15_block10 ckpath_cert_k7_c12_low3_mask15_block11.
Import ListNotations.
Set Warnings "-abstract-large-number".

(** Original retained additions [300, 325); 257 selected base clauses and 48 imported consequences from 12 producer blocks. *)
Definition c12_k7_low3_mask15_block12_output : cnf :=
  [
  [(50,false);(98,true);(137,false)];
  [(91,false);(50,true);(137,false)];
  [(53,true);(124,true);(135,false);(50,true);(137,false)];
  [(124,true);(135,false);(98,true);(137,false)];
  [(135,false);(98,true);(137,false)];
  [(98,true);(137,false)];
  [(135,true);(137,false)];
  [(138,false);(137,false)];
  [(123,true);(137,false)];
  [(137,false)];
  [(136,true)];
  [(140,true)];
  [(143,true)];
  [(138,true)];
  [(135,true)];
  [(148,false)];
  [(152,false)];
  [(155,false)];
  [(150,false)];
  [(147,false)];
  [(26,true);(31,true);(27,true)];
  [(30,false);(58,true);(65,true)];
  [(30,true);(31,true);(27,true)];
  [(31,true);(27,true)];
  [(31,false)]
].

Theorem c12_k7_low3_mask15_block12_sound :
  forall rho, satisfies_cnf rho (c12_k7_low3_instance [true; true; false; false; false; false; false; false; false; true; false; false]) ->
    satisfies_cnf rho c12_k7_low3_mask15_block12_output.
Proof.
intros rho Hbase.
pose (select_cnf c12_k7_low3_mask15_block00_output [0;1;2;3;4;5;6;7;8;9;10;11] : cnf)
  as imported_from_block00.
assert (Himported_from_block00 :
  satisfies_cnf rho imported_from_block00).
{
  unfold imported_from_block00.
  apply (satisfies_cnf_select rho c12_k7_low3_mask15_block00_output [0;1;2;3;4;5;6;7;8;9;10;11]).
  - exact (c12_k7_low3_mask15_block00_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask15_block01_output [5] : cnf)
  as imported_from_block01.
assert (Himported_from_block01 :
  satisfies_cnf rho imported_from_block01).
{
  unfold imported_from_block01.
  apply (satisfies_cnf_select rho c12_k7_low3_mask15_block01_output [5]).
  - exact (c12_k7_low3_mask15_block01_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask15_block02_output [4;15;19;13;10;22] : cnf)
  as imported_from_block02.
assert (Himported_from_block02 :
  satisfies_cnf rho imported_from_block02).
{
  unfold imported_from_block02.
  apply (satisfies_cnf_select rho c12_k7_low3_mask15_block02_output [4;15;19;13;10;22]).
  - exact (c12_k7_low3_mask15_block02_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask15_block03_output [4] : cnf)
  as imported_from_block03.
assert (Himported_from_block03 :
  satisfies_cnf rho imported_from_block03).
{
  unfold imported_from_block03.
  apply (satisfies_cnf_select rho c12_k7_low3_mask15_block03_output [4]).
  - exact (c12_k7_low3_mask15_block03_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask15_block04_output [17] : cnf)
  as imported_from_block04.
assert (Himported_from_block04 :
  satisfies_cnf rho imported_from_block04).
{
  unfold imported_from_block04.
  apply (satisfies_cnf_select rho c12_k7_low3_mask15_block04_output [17]).
  - exact (c12_k7_low3_mask15_block04_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask15_block05_output [14;8;20] : cnf)
  as imported_from_block05.
assert (Himported_from_block05 :
  satisfies_cnf rho imported_from_block05).
{
  unfold imported_from_block05.
  apply (satisfies_cnf_select rho c12_k7_low3_mask15_block05_output [14;8;20]).
  - exact (c12_k7_low3_mask15_block05_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask15_block06_output [1;9;21] : cnf)
  as imported_from_block06.
assert (Himported_from_block06 :
  satisfies_cnf rho imported_from_block06).
{
  unfold imported_from_block06.
  apply (satisfies_cnf_select rho c12_k7_low3_mask15_block06_output [1;9;21]).
  - exact (c12_k7_low3_mask15_block06_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask15_block07_output [15;12] : cnf)
  as imported_from_block07.
assert (Himported_from_block07 :
  satisfies_cnf rho imported_from_block07).
{
  unfold imported_from_block07.
  apply (satisfies_cnf_select rho c12_k7_low3_mask15_block07_output [15;12]).
  - exact (c12_k7_low3_mask15_block07_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask15_block08_output [16] : cnf)
  as imported_from_block08.
assert (Himported_from_block08 :
  satisfies_cnf rho imported_from_block08).
{
  unfold imported_from_block08.
  apply (satisfies_cnf_select rho c12_k7_low3_mask15_block08_output [16]).
  - exact (c12_k7_low3_mask15_block08_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask15_block09_output [15] : cnf)
  as imported_from_block09.
assert (Himported_from_block09 :
  satisfies_cnf rho imported_from_block09).
{
  unfold imported_from_block09.
  apply (satisfies_cnf_select rho c12_k7_low3_mask15_block09_output [15]).
  - exact (c12_k7_low3_mask15_block09_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask15_block10_output [14] : cnf)
  as imported_from_block10.
assert (Himported_from_block10 :
  satisfies_cnf rho imported_from_block10).
{
  unfold imported_from_block10.
  apply (satisfies_cnf_select rho c12_k7_low3_mask15_block10_output [14]).
  - exact (c12_k7_low3_mask15_block10_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask15_block11_output [2;3;21;9;13;23;24;12;6;5;8;19;7;20;15;4] : cnf)
  as imported_from_block11.
assert (Himported_from_block11 :
  satisfies_cnf rho imported_from_block11).
{
  unfold imported_from_block11.
  apply (satisfies_cnf_select rho c12_k7_low3_mask15_block11_output [2;3;21;9;13;23;24;12;6;5;8;19;7;20;15;4]).
  - exact (c12_k7_low3_mask15_block11_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (concat [imported_from_block00;imported_from_block01;imported_from_block02;imported_from_block03;imported_from_block04;imported_from_block05;imported_from_block06;imported_from_block07;imported_from_block08;imported_from_block09;imported_from_block10;imported_from_block11] : cnf) as imported.
assert (Himported : satisfies_cnf rho imported).
{
  unfold imported.
  apply satisfies_cnf_concat_intro.
  constructor.
  { exact Himported_from_block00. }
  constructor.
  { exact Himported_from_block01. }
  constructor.
  { exact Himported_from_block02. }
  constructor.
  { exact Himported_from_block03. }
  constructor.
  { exact Himported_from_block04. }
  constructor.
  { exact Himported_from_block05. }
  constructor.
  { exact Himported_from_block06. }
  constructor.
  { exact Himported_from_block07. }
  constructor.
  { exact Himported_from_block08. }
  constructor.
  { exact Himported_from_block09. }
  constructor.
  { exact Himported_from_block10. }
  constructor.
  { exact Himported_from_block11. }
  constructor.
}
pose (
  [66;67;68;69;70;71;72;73;74;75;76;77;39;1064;1145;3505;4154;26;1148;4157;1166;4155;2224;2169;2228;2235;2233;2231;1071;1153;1155;40;1065;1146;3506;1956;1957;1934;1879;1914;149;205;43;1068;1149;3489;3500;44;1069;1150;22;3;1070;1151;13;1152;4152;1131;4153;1140;3849;3841;260;42;1067;3184;3191;3193;3195;3129;34;47;2787;52;62;1087;1172;7;3855;3851;3853;3844;3848;3839;64;55;3490;59;3488;50;37;3487;2756;2704;2750;2754;1958;29;3486;1134;1173;1169;1207;1210;1212;1203;1213;1183;3160;3153;3158;3156;3149;1881;1880;1861;1846;25;2785;3498;1051;27;1052;129;93;4159;1473;1928;143;61;3493;1086;1171;3508;3504;3511;3514;3499;49;185;3852;3840;3845;3854;2484;3185;3192;3194;3130;3189;3492;3491;2782;2863;2932;2898;2918;2928;2933;1633;1619;1564;1635;20;1177;3485;1089;1063;1085;1055;1088;1885;1892;1891;1854;1869;1205;1208;1211;1181;1201;3127;3126;3125;3128;199;296;170;276;234;240;220;114;1246;1247;1243;1240;1236;28;1053;1132;3478;1054;1;1130;3497;1050;1129;1049;1128;3496;3837;3835;3836;2874;2867;1285;1286;1279;1273;3494;1047;2878;2876;2812;2871;46;33;41;1084;1168;57;1082;6;1592;1594;1583;1573;1523;1596;3838;3843;3850;3847;3188;2150;2290;2219;2284;2288;2254;2274;1629;1599;48;4;31] : list nat) as base_ids.
pose ([
  ([98;195;272],[0;1;2;3;4;5;6;7;8;9;10;11;257;258;259;260;261;262;263;264;265;266;267;268;270;281;288;289;290;12;13;14;15;291;16;292;293;294;17;18;295;19;20;21;22;23;24;25;26;27;28;29;30]);
  ([180;99;272],[0;1;2;3;4;5;6;7;8;9;10;11;257;258;259;260;261;262;263;264;265;266;267;268;270;281;288;289;290;17;18;295;284;296;16;292;21;30;31;32;33;34;19;20;269;35;36;37;38;39;40;41;42;43;44;45;46;47;48;49;50;51;52;53;54;55;56;278;57;297;58;59;60;61]);
  ([105;247;268;99;272],[0;1;2;3;4;5;6;7;8;9;10;11;257;258;259;260;261;262;263;264;265;266;267;268;270;281;288;289;290;56;284;296;306;16;292;31;32;33;34;19;269;35;36;37;38;39;278;62;41;42;43;44;45;46;47;48;49;50;51;52;54;55;21;58;60;61]);
  ([247;268;195;272],[0;1;2;3;4;5;6;7;8;9;10;11;257;258;259;260;261;262;263;264;265;266;267;268;270;281;288;289;290;56;305;16;292;293;284;306;307;278;19;31;32;33;34;63;64;282;65;66;67;68;69;285;70;71;72;73;74;75;76;77;78;79;80;81;82;83;84;85;86;87;47;88;89;45;90;91;92;93;94;95;276;96]);
  ([268;195;272],[0;1;2;3;4;5;6;7;8;9;10;11;257;258;259;260;261;262;263;264;265;266;267;268;270;281;288;289;290;56;308;305;16;292;293;97;98;99;100;53;101;284;306;278;19;102;286;103;104;105;106;107;69;108;109;110;111;112;38;113;114;115;116;31;32;34;117;118;119;120;121;122]);
  ([195;272],[0;1;2;3;4;5;6;7;8;9;10;11;257;258;259;260;261;262;263;264;265;266;267;268;270;281;288;289;290;305;309;16;292;293;284;306;123;124;40;19;31;32;33;34;21;298;58;125;269;63;64;65;66;67;68;69;285;70;126;71;72;73;74;75;76;77;100;78;79;80;81;82;83;279;84;85;86;87;47;88;89;90;91;114;127;96]);
  ([269;272],[0;1;2;3;4;5;6;7;8;9;10;11;257;258;259;260;261;262;263;264;265;266;267;268;270;281;288;289;290;123;128;124;40;16;292;310;21;19;58;125;129;130;131;132;133;134;135;136;269;12;13;14;15;22;23;24;25;26]);
  ([274;272],[0;1;2;3;4;5;6;7;8;9;10;11;257;258;259;260;261;262;263;264;265;266;267;268;270;281;288;289;290;21;16;292;293;310;311;19;129;130;131;132;133;135;136;56;278;137;299;300;301;307;138;86;15]);
  ([245;272],[0;1;2;3;4;5;6;7;8;9;10;11;257;258;259;260;261;262;263;264;265;266;267;268;270;281;288;289;290;16;292;293;310;311;312;19;129;130;131;132;133;136;56;278;137;299;139;62;295;300;58;134;125;269;302;78;140;141;142;60;143;303;12;13;15;144;145;146;147;148;149;150;85;90;91;283;47;88;89;45;87;151;70;71;73;77;152;153;154;155;156;157;158;159;160;161;162]);
  ([272],[0;1;2;3;4;5;6;7;8;9;10;11;257;258;259;260;261;262;263;264;265;266;267;268;270;281;288;289;290;16;292;293;310;311;312;313;19;129;130;131;132;133;136;56;278;137;299;139;62;295;163;164;165;52;166;167;168;169;170;300;58;134;125;269;302;171;172;173;174;175;286;176;104;177;178;179;180;12;13;15;148;181;182;183;184;31;32;34;72;47;48;49;280;42;45;46;279]);
  ([271],[0;1;2;3;4;5;6;7;8;9;10;11;257;258;259;260;261;262;263;264;265;266;267;268;270;281;288;289;290;314;185;41;186;187]);
  ([279],[0;1;2;3;4;5;6;7;8;9;10;11;257;258;259;260;261;262;263;264;265;266;267;268;270;281;288;289;290;314;315;188;189]);
  ([285],[0;1;2;3;4;5;6;7;8;9;10;11;257;258;259;260;261;262;263;264;265;266;267;268;270;281;288;289;290;314;315;316;40;62;190]);
  ([275],[0;1;2;3;4;5;6;7;8;9;10;11;257;258;259;260;261;262;263;264;265;266;267;268;270;281;288;289;290;314;315;316;317;191]);
  ([269],[0;1;2;3;4;5;6;7;8;9;10;11;257;258;259;260;261;262;263;264;265;266;267;268;270;281;288;289;290;314;315;316;317;318;192]);
  ([294],[0;1;2;3;4;5;6;7;8;9;10;11;257;258;259;260;261;262;263;264;265;266;267;268;270;281;288;289;290;314;315;316;317;318;319;58]);
  ([302],[0;1;2;3;4;5;6;7;8;9;10;11;257;258;259;260;261;262;263;264;265;266;267;268;270;281;288;289;290;314;315;316;317;318;319;320;19]);
  ([308],[0;1;2;3;4;5;6;7;8;9;10;11;257;258;259;260;261;262;263;264;265;266;267;268;270;281;288;289;290;314;315;316;317;318;319;320;321;125]);
  ([298],[0;1;2;3;4;5;6;7;8;9;10;11;257;258;259;260;261;262;263;264;265;266;267;268;270;281;288;289;290;314;315;316;317;318;319;320;321;322;21]);
  ([292],[0;1;2;3;4;5;6;7;8;9;10;11;257;258;259;260;261;262;263;264;265;266;267;268;270;281;288;289;290;314;315;316;317;318;319;320;321;322;323;56]);
  ([51;61;53],[0;1;2;3;4;5;6;7;8;9;10;11;257;258;259;260;261;262;263;264;265;266;267;268;270;281;288;289;290;314;315;316;317;318;319;320;321;322;323;324;193;194;179;195;196;197;300;198;199;200;91;201;202;203;169;17;119;120;204;205;206;207;208;209;210;211;212;83;213;271]);
  ([58;115;129],[0;1;2;3;4;5;6;7;8;9;10;11;257;258;259;260;261;262;263;264;265;266;267;268;270;281;288;289;290;314;315;316;317;318;319;320;321;322;323;324;17;119;120;204;214;215;304;277]);
  ([59;61;53],[0;1;2;3;4;5;6;7;8;9;10;11;257;258;259;260;261;262;263;264;265;266;267;268;270;281;288;289;290;314;315;316;317;318;319;320;321;322;323;324;216;217;195;218;219;177;272;273;274;198;199;200;91;201;202;50;220;221;117;205;206;207;208;203;169;275]);
  ([61;53],[0;1;2;3;4;5;6;7;8;9;10;11;257;258;259;260;261;262;263;264;265;266;267;268;270;281;288;289;290;314;315;316;317;318;319;320;321;322;323;324;300;325;327;50;220;221;17;119;120;204;214;215;304;222;223;224;225;226;227;228;87;229;230;231;232;136;233;168;31;234;235;236;237;238;239;287;240;241;242;80;243;279;65;66;67;68;69;143;70]);
  ([60],[0;1;2;3;4;5;6;7;8;9;10;11;257;258;259;260;261;262;263;264;265;266;267;268;270;281;288;289;290;314;315;316;317;318;319;320;321;322;323;324;121;122;57;137;244;65;66;67;68;69;285;228;70;71;73;74;75;76;77;100;78;79;80;81;82;83;279;84;85;86;87;151;152;47;88;89;245;90;91;246;247;248;249;250;251;159;160;161;162;252;253;254;255;256])
] : list (list nat * list nat)) as records.
assert (Hcheck :
  check_selected_microblock (c12_k7_low3_instance [true; true; false; false; false; false; false; false; false; true; false; false]) base_ids
    imported records c12_k7_low3_mask15_block12_output = true).
{ vm_compute. reflexivity. }
exact (check_selected_microblock_sound
  (c12_k7_low3_instance [true; true; false; false; false; false; false; false; false; true; false; false]) base_ids imported records c12_k7_low3_mask15_block12_output
  Hcheck rho Hbase Himported).
Qed.
