(** Generated by [scripts/generate_ckpath_certificates.py].
    Only the block output is transparent.  Selected base clauses,
    producer imports, replay records, and the transient database
    all remain underneath the opaque soundness theorem. *)

From Stdlib Require Import List.
From Digraph Require Import ckpath_cnf ckpath_drup_microblock ckpath_cert_k7_base ckpath_cert_k7_c12_cover4_micro_block004 ckpath_cert_k7_c12_cover4_micro_block013 ckpath_cert_k7_c12_cover4_micro_block014 ckpath_cert_k7_c12_cover4_micro_block017 ckpath_cert_k7_c12_cover4_micro_block031 ckpath_cert_k7_c12_cover4_micro_block035 ckpath_cert_k7_c12_cover4_micro_block036 ckpath_cert_k7_c12_cover4_micro_block038 ckpath_cert_k7_c12_cover4_micro_block039 ckpath_cert_k7_c12_cover4_micro_block042 ckpath_cert_k7_c12_cover4_micro_block071 ckpath_cert_k7_c12_cover4_micro_block072 ckpath_cert_k7_c12_cover4_micro_block073 ckpath_cert_k7_c12_cover4_micro_block083 ckpath_cert_k7_c12_cover4_micro_block087 ckpath_cert_k7_c12_cover4_micro_block091 ckpath_cert_k7_c12_cover4_micro_block092 ckpath_cert_k7_c12_cover4_micro_block093 ckpath_cert_k7_c12_cover4_micro_block094 ckpath_cert_k7_c12_cover4_micro_block097 ckpath_cert_k7_c12_cover4_micro_block109 ckpath_cert_k7_c12_cover4_micro_block110 ckpath_cert_k7_c12_cover4_micro_block124 ckpath_cert_k7_c12_cover4_micro_block125 ckpath_cert_k7_c12_cover4_micro_block127 ckpath_cert_k7_c12_cover4_micro_block128 ckpath_cert_k7_c12_cover4_micro_block129 ckpath_cert_k7_c12_cover4_micro_block130 ckpath_cert_k7_c12_cover4_micro_block136 ckpath_cert_k7_c12_cover4_micro_block154 ckpath_cert_k7_c12_cover4_micro_block164 ckpath_cert_k7_c12_cover4_micro_block166 ckpath_cert_k7_c12_cover4_micro_block168 ckpath_cert_k7_c12_cover4_micro_block169 ckpath_cert_k7_c12_cover4_micro_block170 ckpath_cert_k7_c12_cover4_micro_block173 ckpath_cert_k7_c12_cover4_micro_block175 ckpath_cert_k7_c12_cover4_micro_block176 ckpath_cert_k7_c12_cover4_micro_block177 ckpath_cert_k7_c12_cover4_micro_block178.
Import ListNotations.
Set Warnings "-abstract-large-number".

(** Original retained additions [4475, 4500); 236 selected base clauses and 92 imported consequences from 40 producer blocks. *)
Definition c12_k7_cover4_micro_block179_output : cnf :=
  [
  [(150,false);(141,true);(140,true)];
  [(148,false);(141,true);(140,true)];
  [(156,false);(141,true);(140,true)];
  [(64,false);(139,true);(140,true);(141,true);(151,true)];
  [(63,true);(145,true);(148,true);(152,true);(140,true);(151,true);(64,true)];
  [(134,false);(152,true);(151,true);(148,true);(140,true);(64,true);(154,false)];
  [(152,true);(151,true);(140,true);(141,true)];
  [(27,false);(62,true);(142,false);(150,true);(63,true);(148,true);(139,false)];
  [(28,false);(62,true);(63,true);(148,true);(142,false)];
  [(62,true);(111,true);(148,true);(136,false);(156,true);(30,true);(139,false);(153,true);(63,true);(142,false);(150,true)];
  [(27,true);(117,true);(111,true);(136,false);(156,true);(28,true);(30,true);(148,true);(139,false);(153,true)];
  [(64,false);(139,false);(142,false);(148,true);(136,false);(156,true);(153,true);(150,true);(144,true);(141,true);(151,true)];
  [(63,true);(62,true);(139,false);(156,true);(153,true);(136,false);(151,true);(142,false);(150,true);(148,true);(64,true)];
  [(63,false);(151,true);(140,true);(141,true)];
  [(27,false);(50,true);(137,true);(148,true);(142,false);(139,false)];
  [(151,true);(141,true);(140,true)];
  [(141,true);(140,true)];
  [(26,false);(63,true);(62,true);(136,false);(151,true);(141,false);(153,true);(147,true)];
  [(63,true);(156,true);(62,true);(148,true);(150,true);(151,true);(153,true);(147,true)];
  [(63,false);(151,true);(140,true)];
  [(153,false);(156,true);(148,true);(28,true);(140,true);(150,true);(151,true)];
  [(156,true);(62,true);(148,true);(140,true);(151,true);(150,true)];
  [(62,true);(151,true);(150,true);(140,true);(148,true)];
  [(151,true);(150,true);(140,true);(148,true)];
  [(27,false);(52,true);(137,true);(148,true);(142,false);(141,false)]
].

Theorem c12_k7_cover4_micro_block179_sound :
  forall rho, satisfies_cnf rho ((c12_k7_cover_base 4)) ->
    satisfies_cnf rho c12_k7_cover4_micro_block179_output.
Proof.
intros rho Hbase.
pose (select_cnf c12_k7_cover4_micro_block004_output [10] : cnf)
  as imported_from_block004.
assert (Himported_from_block004 :
  satisfies_cnf rho imported_from_block004).
{
  unfold imported_from_block004.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block004_output [10]).
  - exact (c12_k7_cover4_micro_block004_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block013_output [20] : cnf)
  as imported_from_block013.
assert (Himported_from_block013 :
  satisfies_cnf rho imported_from_block013).
{
  unfold imported_from_block013.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block013_output [20]).
  - exact (c12_k7_cover4_micro_block013_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block014_output [4] : cnf)
  as imported_from_block014.
assert (Himported_from_block014 :
  satisfies_cnf rho imported_from_block014).
{
  unfold imported_from_block014.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block014_output [4]).
  - exact (c12_k7_cover4_micro_block014_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block017_output [11;18] : cnf)
  as imported_from_block017.
assert (Himported_from_block017 :
  satisfies_cnf rho imported_from_block017).
{
  unfold imported_from_block017.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block017_output [11;18]).
  - exact (c12_k7_cover4_micro_block017_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block031_output [21;15;9] : cnf)
  as imported_from_block031.
assert (Himported_from_block031 :
  satisfies_cnf rho imported_from_block031).
{
  unfold imported_from_block031.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block031_output [21;15;9]).
  - exact (c12_k7_cover4_micro_block031_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block035_output [24] : cnf)
  as imported_from_block035.
assert (Himported_from_block035 :
  satisfies_cnf rho imported_from_block035).
{
  unfold imported_from_block035.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block035_output [24]).
  - exact (c12_k7_cover4_micro_block035_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block036_output [21;18;15;9] : cnf)
  as imported_from_block036.
assert (Himported_from_block036 :
  satisfies_cnf rho imported_from_block036).
{
  unfold imported_from_block036.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block036_output [21;18;15;9]).
  - exact (c12_k7_cover4_micro_block036_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block038_output [10] : cnf)
  as imported_from_block038.
assert (Himported_from_block038 :
  satisfies_cnf rho imported_from_block038).
{
  unfold imported_from_block038.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block038_output [10]).
  - exact (c12_k7_cover4_micro_block038_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block039_output [10;4;16] : cnf)
  as imported_from_block039.
assert (Himported_from_block039 :
  satisfies_cnf rho imported_from_block039).
{
  unfold imported_from_block039.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block039_output [10;4;16]).
  - exact (c12_k7_cover4_micro_block039_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block042_output [6;11;10;0] : cnf)
  as imported_from_block042.
assert (Himported_from_block042 :
  satisfies_cnf rho imported_from_block042).
{
  unfold imported_from_block042.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block042_output [6;11;10;0]).
  - exact (c12_k7_cover4_micro_block042_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block071_output [22] : cnf)
  as imported_from_block071.
assert (Himported_from_block071 :
  satisfies_cnf rho imported_from_block071).
{
  unfold imported_from_block071.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block071_output [22]).
  - exact (c12_k7_cover4_micro_block071_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block072_output [17] : cnf)
  as imported_from_block072.
assert (Himported_from_block072 :
  satisfies_cnf rho imported_from_block072).
{
  unfold imported_from_block072.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block072_output [17]).
  - exact (c12_k7_cover4_micro_block072_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block073_output [9] : cnf)
  as imported_from_block073.
assert (Himported_from_block073 :
  satisfies_cnf rho imported_from_block073).
{
  unfold imported_from_block073.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block073_output [9]).
  - exact (c12_k7_cover4_micro_block073_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block083_output [17] : cnf)
  as imported_from_block083.
assert (Himported_from_block083 :
  satisfies_cnf rho imported_from_block083).
{
  unfold imported_from_block083.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block083_output [17]).
  - exact (c12_k7_cover4_micro_block083_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block087_output [9] : cnf)
  as imported_from_block087.
assert (Himported_from_block087 :
  satisfies_cnf rho imported_from_block087).
{
  unfold imported_from_block087.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block087_output [9]).
  - exact (c12_k7_cover4_micro_block087_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block091_output [14;23;15] : cnf)
  as imported_from_block091.
assert (Himported_from_block091 :
  satisfies_cnf rho imported_from_block091).
{
  unfold imported_from_block091.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block091_output [14;23;15]).
  - exact (c12_k7_cover4_micro_block091_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block092_output [24] : cnf)
  as imported_from_block092.
assert (Himported_from_block092 :
  satisfies_cnf rho imported_from_block092).
{
  unfold imported_from_block092.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block092_output [24]).
  - exact (c12_k7_cover4_micro_block092_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block093_output [10;11;2;16] : cnf)
  as imported_from_block093.
assert (Himported_from_block093 :
  satisfies_cnf rho imported_from_block093).
{
  unfold imported_from_block093.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block093_output [10;11;2;16]).
  - exact (c12_k7_cover4_micro_block093_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block094_output [11;10;14] : cnf)
  as imported_from_block094.
assert (Himported_from_block094 :
  satisfies_cnf rho imported_from_block094).
{
  unfold imported_from_block094.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block094_output [11;10;14]).
  - exact (c12_k7_cover4_micro_block094_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block097_output [10;24] : cnf)
  as imported_from_block097.
assert (Himported_from_block097 :
  satisfies_cnf rho imported_from_block097).
{
  unfold imported_from_block097.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block097_output [10;24]).
  - exact (c12_k7_cover4_micro_block097_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block109_output [5;21] : cnf)
  as imported_from_block109.
assert (Himported_from_block109 :
  satisfies_cnf rho imported_from_block109).
{
  unfold imported_from_block109.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block109_output [5;21]).
  - exact (c12_k7_cover4_micro_block109_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block110_output [8] : cnf)
  as imported_from_block110.
assert (Himported_from_block110 :
  satisfies_cnf rho imported_from_block110).
{
  unfold imported_from_block110.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block110_output [8]).
  - exact (c12_k7_cover4_micro_block110_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block124_output [10] : cnf)
  as imported_from_block124.
assert (Himported_from_block124 :
  satisfies_cnf rho imported_from_block124).
{
  unfold imported_from_block124.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block124_output [10]).
  - exact (c12_k7_cover4_micro_block124_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block125_output [7] : cnf)
  as imported_from_block125.
assert (Himported_from_block125 :
  satisfies_cnf rho imported_from_block125).
{
  unfold imported_from_block125.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block125_output [7]).
  - exact (c12_k7_cover4_micro_block125_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block127_output [21;2;15] : cnf)
  as imported_from_block127.
assert (Himported_from_block127 :
  satisfies_cnf rho imported_from_block127).
{
  unfold imported_from_block127.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block127_output [21;2;15]).
  - exact (c12_k7_cover4_micro_block127_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block128_output [11;21] : cnf)
  as imported_from_block128.
assert (Himported_from_block128 :
  satisfies_cnf rho imported_from_block128).
{
  unfold imported_from_block128.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block128_output [11;21]).
  - exact (c12_k7_cover4_micro_block128_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block129_output [6;16;7] : cnf)
  as imported_from_block129.
assert (Himported_from_block129 :
  satisfies_cnf rho imported_from_block129).
{
  unfold imported_from_block129.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block129_output [6;16;7]).
  - exact (c12_k7_cover4_micro_block129_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block130_output [1;21;22;11;2;3;12;13] : cnf)
  as imported_from_block130.
assert (Himported_from_block130 :
  satisfies_cnf rho imported_from_block130).
{
  unfold imported_from_block130.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block130_output [1;21;22;11;2;3;12;13]).
  - exact (c12_k7_cover4_micro_block130_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block136_output [12] : cnf)
  as imported_from_block136.
assert (Himported_from_block136 :
  satisfies_cnf rho imported_from_block136).
{
  unfold imported_from_block136.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block136_output [12]).
  - exact (c12_k7_cover4_micro_block136_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block154_output [1] : cnf)
  as imported_from_block154.
assert (Himported_from_block154 :
  satisfies_cnf rho imported_from_block154).
{
  unfold imported_from_block154.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block154_output [1]).
  - exact (c12_k7_cover4_micro_block154_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block164_output [20] : cnf)
  as imported_from_block164.
assert (Himported_from_block164 :
  satisfies_cnf rho imported_from_block164).
{
  unfold imported_from_block164.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block164_output [20]).
  - exact (c12_k7_cover4_micro_block164_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block166_output [20;21] : cnf)
  as imported_from_block166.
assert (Himported_from_block166 :
  satisfies_cnf rho imported_from_block166).
{
  unfold imported_from_block166.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block166_output [20;21]).
  - exact (c12_k7_cover4_micro_block166_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block168_output [6] : cnf)
  as imported_from_block168.
assert (Himported_from_block168 :
  satisfies_cnf rho imported_from_block168).
{
  unfold imported_from_block168.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block168_output [6]).
  - exact (c12_k7_cover4_micro_block168_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block169_output [2;7;14;8] : cnf)
  as imported_from_block169.
assert (Himported_from_block169 :
  satisfies_cnf rho imported_from_block169).
{
  unfold imported_from_block169.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block169_output [2;7;14;8]).
  - exact (c12_k7_cover4_micro_block169_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block170_output [0;12;19] : cnf)
  as imported_from_block170.
assert (Himported_from_block170 :
  satisfies_cnf rho imported_from_block170).
{
  unfold imported_from_block170.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block170_output [0;12;19]).
  - exact (c12_k7_cover4_micro_block170_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block173_output [13] : cnf)
  as imported_from_block173.
assert (Himported_from_block173 :
  satisfies_cnf rho imported_from_block173).
{
  unfold imported_from_block173.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block173_output [13]).
  - exact (c12_k7_cover4_micro_block173_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block175_output [8] : cnf)
  as imported_from_block175.
assert (Himported_from_block175 :
  satisfies_cnf rho imported_from_block175).
{
  unfold imported_from_block175.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block175_output [8]).
  - exact (c12_k7_cover4_micro_block175_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block176_output [23;10;20;6] : cnf)
  as imported_from_block176.
assert (Himported_from_block176 :
  satisfies_cnf rho imported_from_block176).
{
  unfold imported_from_block176.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block176_output [23;10;20;6]).
  - exact (c12_k7_cover4_micro_block176_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block177_output [2;7;4;5;0] : cnf)
  as imported_from_block177.
assert (Himported_from_block177 :
  satisfies_cnf rho imported_from_block177).
{
  unfold imported_from_block177.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block177_output [2;7;4;5;0]).
  - exact (c12_k7_cover4_micro_block177_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block178_output [19;12;22;20;8;24;23;0] : cnf)
  as imported_from_block178.
assert (Himported_from_block178 :
  satisfies_cnf rho imported_from_block178).
{
  unfold imported_from_block178.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block178_output [19;12;22;20;8;24;23;0]).
  - exact (c12_k7_cover4_micro_block178_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (concat [imported_from_block004;imported_from_block013;imported_from_block014;imported_from_block017;imported_from_block031;imported_from_block035;imported_from_block036;imported_from_block038;imported_from_block039;imported_from_block042;imported_from_block071;imported_from_block072;imported_from_block073;imported_from_block083;imported_from_block087;imported_from_block091;imported_from_block092;imported_from_block093;imported_from_block094;imported_from_block097;imported_from_block109;imported_from_block110;imported_from_block124;imported_from_block125;imported_from_block127;imported_from_block128;imported_from_block129;imported_from_block130;imported_from_block136;imported_from_block154;imported_from_block164;imported_from_block166;imported_from_block168;imported_from_block169;imported_from_block170;imported_from_block173;imported_from_block175;imported_from_block176;imported_from_block177;imported_from_block178] : cnf) as imported.
assert (Himported : satisfies_cnf rho imported).
{
  unfold imported.
  apply satisfies_cnf_concat_intro.
  constructor.
  { exact Himported_from_block004. }
  constructor.
  { exact Himported_from_block013. }
  constructor.
  { exact Himported_from_block014. }
  constructor.
  { exact Himported_from_block017. }
  constructor.
  { exact Himported_from_block031. }
  constructor.
  { exact Himported_from_block035. }
  constructor.
  { exact Himported_from_block036. }
  constructor.
  { exact Himported_from_block038. }
  constructor.
  { exact Himported_from_block039. }
  constructor.
  { exact Himported_from_block042. }
  constructor.
  { exact Himported_from_block071. }
  constructor.
  { exact Himported_from_block072. }
  constructor.
  { exact Himported_from_block073. }
  constructor.
  { exact Himported_from_block083. }
  constructor.
  { exact Himported_from_block087. }
  constructor.
  { exact Himported_from_block091. }
  constructor.
  { exact Himported_from_block092. }
  constructor.
  { exact Himported_from_block093. }
  constructor.
  { exact Himported_from_block094. }
  constructor.
  { exact Himported_from_block097. }
  constructor.
  { exact Himported_from_block109. }
  constructor.
  { exact Himported_from_block110. }
  constructor.
  { exact Himported_from_block124. }
  constructor.
  { exact Himported_from_block125. }
  constructor.
  { exact Himported_from_block127. }
  constructor.
  { exact Himported_from_block128. }
  constructor.
  { exact Himported_from_block129. }
  constructor.
  { exact Himported_from_block130. }
  constructor.
  { exact Himported_from_block136. }
  constructor.
  { exact Himported_from_block154. }
  constructor.
  { exact Himported_from_block164. }
  constructor.
  { exact Himported_from_block166. }
  constructor.
  { exact Himported_from_block168. }
  constructor.
  { exact Himported_from_block169. }
  constructor.
  { exact Himported_from_block170. }
  constructor.
  { exact Himported_from_block173. }
  constructor.
  { exact Himported_from_block175. }
  constructor.
  { exact Himported_from_block176. }
  constructor.
  { exact Himported_from_block177. }
  constructor.
  { exact Himported_from_block178. }
  constructor.
}
pose (
  [66;67;68;69;70;71;72;73;74;75;76;77;2014;0;11;21;30;38;45;51;56;60;63;65;10;2015;2921;4733;1688;1690;1685;1692;1556;1178;3827;2317;5337;422;47;3471;2297;3223;1192;1709;1570;2619;48;2298;3180;5031;4514;4445;4505;4518;4516;4495;7;5626;34;62;52;26;2593;23;3185;14;3184;49;2299;3181;4995;50;2300;3182;31;3186;2679;2678;2677;2676;2680;2620;359;356;1136;5030;3179;2592;4214;4193;5625;1261;4144;4136;4148;4131;4143;2273;5015;4124;3628;3629;3237;3308;3287;3297;3310;3306;4;2274;2289;24;5016;542;546;539;510;2716;2711;2715;2717;2642;28;2278;4983;5007;4992;25;2275;5017;4080;27;2277;5019;22;2272;5014;4123;29;2279;1;2280;5036;5035;4129;3216;3201;5059;5073;5044;5076;5080;5079;46;2296;3178;5029;4125;4128;4107;4113;4122;3280;3295;3298;4986;1778;4203;4216;57;3195;2307;5034;3200;33;59;2309;3197;6;2310;3198;3219;3222;3644;3621;3643;3601;3183;2301;3171;5028;5430;5359;1774;3639;3638;4431;555;4719;3292;39;4727;4731;4198;1639;4715;4702;4694;4718;3194;3317;3315;3316;3318;3245;3562;13;3175;2264;43;4994;4985;2293;3172;3170;2291;4729;1636;1781;4730;3841;3913;3912;3239;3313;3311] : list nat) as base_ids.
pose ([
  ([298;281;279],[0;1;2;3;4;5;6;7;8;9;10;11;12;278;320;298;311;13;14;15;16;17;18;19;20;21;22;23;24;25;26;27;315;28;29;30;31;249;32;33;273;321;34;322;35;36;323;324;37;325;38;39;40;326]);
  ([294;281;279],[0;1;2;3;4;5;6;7;8;9;10;11;12;278;312;328;298;13;14;15;16;17;18;19;20;21;22;23;24;25;27;315;41;26;273;250;251;42;43;44;252;34;322;36;35;279;266;267;265;236;268;261]);
  ([310;281;279],[0;1;2;3;4;5;6;7;8;9;10;11;12;278;328;329;298;311;13;14;15;16;17;18;19;20;21;22;23;24;25;41;45;26;27;315;273;253;245;241;254;255;35;36;34;322;279]);
  ([126;277;279;281;301],[0;1;2;3;4;5;6;7;8;9;10;11;12;278;46;47;298;311;328;329;330;13;14;15;16;17;18;19;20;21;22;23;24;25;316;26;48;27;315;49;45;273;50;51;52;53;54;55;38;56;57;58;59;60;61;62;279]);
  ([125;289;295;303;279;301;127],[0;1;2;3;4;5;6;7;8;9;10;11;12;278;36;45;34;322;298;311;288;285;289;290;291;13;14;15;16;17;18;19;20;21;22;23;24;25;317;280;26;27;315;63;64;65;66;67;68;69;70;71;72;73;74;75;318;76;77;78;79;80;81;327]);
  ([266;303;301;295;279;127;306],[0;1;2;3;4;5;6;7;8;9;10;11;12;278;35;34;322;45;298;311;13;14;15;16;17;18;19;20;21;22;23;24;25;317;26;237;82;83;262;27;244;245;84;246;332;263;38;40;326;85;86;87;264;88;89]);
  ([303;301;279;281],[0;1;2;3;4;5;6;7;8;9;10;11;12;278;34;322;298;311;328;329;330;13;14;15;16;17;18;19;20;21;22;23;24;25;331;317;26;27;315;41;45;273;333;279;36;306;90;270;271;272;91;84;38;40;85;86;92;93;94;95;96]);
  ([52;123;282;299;125;295;276],[0;1;2;3;4;5;6;7;8;9;10;11;12;278;63;97;98;27;41;45;34;99;13;14;15;16;17;18;19;20;21;22;23;24;25;286;288;281;283;100;101;102;103;104;105;106;107;273;258;74;46;108;65;109;110]);
  ([54;123;125;295;282],[0;1;2;3;4;5;6;7;8;9;10;11;12;278;111;109;112;317;310;299;45;27;13;14;15;16;17;18;19;20;21;22;23;24;25;287]);
  ([123;221;295;270;311;59;276;305;125;282;299],[0;1;2;3;4;5;6;7;8;9;10;11;12;278;336;45;26;238;315;113;114;115;34;116;27;335;13;14;15;16;17;18;19;20;21;22;23;24;25;273;117;118;119;301;120;121;256;242;247;122;123;124;125;126;127;128;129;130;131;132;133;134;135;136;137;138;139;140;141;75;142]);
  ([53;233;221;270;311;55;59;295;276;305],[0;1;2;3;4;5;6;7;8;9;10;11;12;278;301;26;143;45;34;144;13;14;15;16;17;18;19;20;21;22;23;24;25;134;313;145;146;135;137;147;117;118;119;120;121;311;148;149;150;151;152;122]);
  ([126;276;282;295;270;311;305;299;287;281;301],[0;1;2;3;4;5;6;7;8;9;10;11;12;278;46;324;48;34;239;27;238;315;115;26;47;49;13;14;15;16;17;18;19;20;21;22;23;24;25;273;51;52;53;54;55;50;242;247;56;58;59;60;61;38;260;337;153;154;155;156;157;158;159;160;161;338;63;97;98;99;307;102;162;163;164;105]);
  ([125;123;276;311;305;270;301;282;299;295;127],[0;1;2;3;4;5;6;7;8;9;10;11;12;278;336;335;34;239;143;144;26;325;27;238;113;114;288;285;289;290;291;280;13;14;15;16;17;18;19;20;21;22;23;24;25;301;273;64;65;110;66;67;68;69;165;71;72;73;74;75]);
  ([124;301;279;281],[0;1;2;3;4;5;6;7;8;9;10;11;12;278;38;40;326;334;298;311;328;329;330;13;14;15;16;17;18;19;20;21;22;23;24;25;153;39;26;86;27;315;85;45;273;166;88;89;167;168;96;242;247;169;170;171;172;257;127;87;173;174;146;175;176;177;178;179;180;51;52;53;54;55;50]);
  ([52;99;273;295;282;276],[0;1;2;3;4;5;6;7;8;9;10;11;12;278;63;97;98;99;277;307;258;274;273;45;27;34;13;14;15;16;17;18;19;20;21;22;23;24;25;102;162;163;164;105]);
  ([301;281;279],[0;1;2;3;4;5;6;7;8;9;10;11;12;278;334;341;328;329;330;298;311;13;14;15;16;17;18;19;20;21;22;23;24;25;41;45;143;26;27;273;166;242;247;36;35;279;339;340;153;154;155;156;157;158;159;160;161;342;301;134;145;146;135;137;136;75;181;182;259;282;183;184;185;186;308;108;187;188;71;72;73;64;67;68;69;65;66;189;319;190;191;192]);
  ([281;279],[0;1;2;3;4;5;6;7;8;9;10;11;12;278;328;329;330;343;298;311;13;14;15;16;17;18;19;20;21;22;23;24;25;41;45;143;26;27;273;193;243;248;256;36;35;34;279]);
  ([50;125;123;270;301;280;305;293],[0;1;2;3;4;5;6;7;8;9;10;11;12;278;134;146;75;182;194;284;195;26;196;302]);
  ([125;311;123;295;299;301;305;293],[0;1;2;3;4;5;6;7;8;9;10;11;12;278;143;45;41;144;35;13;14;15;16;17;18;19;20;21;22;23;24;25;273;298;311;344;26;345;27;113;197;336;300;63;97;98;277;198;288;281;283;292;293;286;199;200;201]);
  ([124;301;279],[0;1;2;3;4;5;6;7;8;9;10;11;12;278;38;40;326;341;298;311;13;14;15;16;17;18;19;20;21;22;23;24;25;153;39;196;83;240;303;202;26;86;27;113;315;85;203;88]);
  ([304;311;295;55;279;299;301],[0;1;2;3;4;5;6;7;8;9;10;11;12;278;143;45;298;311;344;41;347;13;14;15;16;17;18;19;20;21;22;23;24;25;26;27;113;197;196;83;166;204;91;296;322;332;46;48;47;49;201;205;206;207;277;297;134;75;182;135;145;136;208;209;181;162;210;211;212;213;214;215;286;294;295;284;216;217;218;219;220;221;222;223;269;224;225;304;226;275]);
  ([311;123;295;279;301;299],[0;1;2;3;4;5;6;7;8;9;10;11;12;278;143;45;298;311;344;347;41;13;14;15;16;17;18;19;20;21;22;23;24;25;26;27;113;197;196;83;336;348;346;227;84;296;332;46;48;47;49;201;206;207;277;297;134;75;135;145;136;208;209;181;146;162;210;211;212;213;214;215;286;294;295;284;216;217;219;220;221;222;223;269;224;225;304;226;275]);
  ([123;301;299;279;295],[0;1;2;3;4;5;6;7;8;9;10;11;12;278;349;347;41;298;311;344;45;13;14;15;16;17;18;19;20;21;22;23;24;25;336;273;26;27;113;315;197;83;241;245;228;254;332;345;205;296;46;48;47;49;201;206;327;277]);
  ([301;299;279;295],[0;1;2;3;4;5;6;7;8;9;10;11;12;278;347;350;41;298;311;344;45;13;14;15;16;17;18;19;20;21;22;23;24;25;153;154;322;155;156;309;229;314;305;273;26;27;113;276;304;230;231;232]);
  ([52;103;273;295;282;280],[0;1;2;3;4;5;6;7;8;9;10;11;12;278;63;97;98;277;198;233;234;235])
] : list (list nat * list nat)) as records.
assert (Hcheck :
  check_selected_microblock ((c12_k7_cover_base 4)) base_ids
    imported records c12_k7_cover4_micro_block179_output = true).
{ vm_compute. reflexivity. }
exact (check_selected_microblock_sound
  ((c12_k7_cover_base 4)) base_ids imported records c12_k7_cover4_micro_block179_output
  Hcheck rho Hbase Himported).
Qed.
