(** Generated by [scripts/generate_ckpath_certificates.py].
    Only the block output is transparent.  Selected base clauses,
    producer imports, replay records, and the transient database
    all remain underneath the opaque soundness theorem. *)

From Stdlib Require Import List.
From Digraph Require Import ckpath_cnf ckpath_drup_microblock ckpath_cert_k7_c12_low3_reduction ckpath_cert_k7_c12_low3_mask06_block00 ckpath_cert_k7_c12_low3_mask06_block01 ckpath_cert_k7_c12_low3_mask06_block02 ckpath_cert_k7_c12_low3_mask06_block03 ckpath_cert_k7_c12_low3_mask06_block04 ckpath_cert_k7_c12_low3_mask06_block05 ckpath_cert_k7_c12_low3_mask06_block06 ckpath_cert_k7_c12_low3_mask06_block07 ckpath_cert_k7_c12_low3_mask06_block08 ckpath_cert_k7_c12_low3_mask06_block09.
Import ListNotations.
Set Warnings "-abstract-large-number".

(** Original retained additions [250, 275); 315 selected base clauses and 60 imported consequences from 10 producer blocks. *)
Definition c12_k7_low3_mask06_block10_output : cnf :=
  [
  [(111,true);(51,true);(90,true);(137,false);(141,false);(112,true);(114,true);(143,false)];
  [(111,false);(134,false);(144,false);(137,false);(142,false);(110,true);(135,false);(143,false);(26,true)];
  [(114,true);(143,false);(62,true)];
  [(140,true);(90,false);(138,true);(143,false);(29,true);(26,true)];
  [(135,false);(144,false);(140,false);(90,false);(29,true);(26,true)];
  [(135,true);(18,true);(90,false);(138,true)];
  [(90,false);(138,true);(143,false);(29,true);(26,true)];
  [(52,false);(86,true);(137,false);(140,false)];
  [(53,true);(51,true);(86,true);(134,false);(135,false);(137,false);(140,false);(143,false);(29,true);(26,true)];
  [(46,false);(104,true);(93,true);(18,true);(141,false);(142,false);(135,false);(134,false);(90,true);(29,true);(26,true)];
  [(27,true);(93,true);(115,true);(112,true);(141,false);(135,false);(90,true);(143,false);(29,true);(26,true)];
  [(91,true);(112,true);(115,true);(93,true);(141,false);(90,true);(143,false)];
  [(51,true);(86,true);(142,false);(135,false);(141,false);(137,false);(134,false);(140,false);(90,true);(143,false);(29,true);(26,true)];
  [(86,true);(142,false);(135,false);(141,false);(137,false);(134,false);(140,false);(90,true);(143,false);(29,true);(26,true)];
  [(51,false);(141,false);(93,true);(135,false);(90,true);(29,true);(26,true)];
  [(91,true);(93,true);(141,false);(90,true);(143,false)];
  [(142,false);(135,false);(141,false);(137,false);(134,false);(140,false);(90,true);(143,false);(29,true);(26,true)];
  [(144,true);(140,false);(138,true);(143,false);(29,true);(26,true)];
  [(93,true);(144,false);(112,true);(135,false);(141,false);(90,true);(143,false);(29,true);(26,true)];
  [(30,true);(112,true);(138,false);(135,false);(141,false);(143,false);(29,true);(26,true)];
  [(138,false);(135,false);(140,false);(141,false);(90,true);(143,false);(29,true);(26,true)];
  [(79,true);(112,true);(86,true);(144,false);(135,false);(140,false);(143,false)];
  [(112,true);(144,false);(135,false);(140,false);(141,false);(143,false);(29,true);(26,true)];
  [(144,false);(135,false);(140,false);(141,false);(143,false);(29,true);(26,true)];
  [(135,false);(140,false);(141,false);(143,false);(29,true);(26,true)]
].

Theorem c12_k7_low3_mask06_block10_sound :
  forall rho, satisfies_cnf rho (c12_k7_low3_instance [true; false; false; true; false; false; true; false; false; false; false; false]) ->
    satisfies_cnf rho c12_k7_low3_mask06_block10_output.
Proof.
intros rho Hbase.
pose (select_cnf c12_k7_low3_mask06_block00_output [0;1;2;3;4;5;6;7;8;9;10;11;12;24] : cnf)
  as imported_from_block00.
assert (Himported_from_block00 :
  satisfies_cnf rho imported_from_block00).
{
  unfold imported_from_block00.
  apply (satisfies_cnf_select rho c12_k7_low3_mask06_block00_output [0;1;2;3;4;5;6;7;8;9;10;11;12;24]).
  - exact (c12_k7_low3_mask06_block00_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask06_block01_output [1;20] : cnf)
  as imported_from_block01.
assert (Himported_from_block01 :
  satisfies_cnf rho imported_from_block01).
{
  unfold imported_from_block01.
  apply (satisfies_cnf_select rho c12_k7_low3_mask06_block01_output [1;20]).
  - exact (c12_k7_low3_mask06_block01_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask06_block02_output [21;7] : cnf)
  as imported_from_block02.
assert (Himported_from_block02 :
  satisfies_cnf rho imported_from_block02).
{
  unfold imported_from_block02.
  apply (satisfies_cnf_select rho c12_k7_low3_mask06_block02_output [21;7]).
  - exact (c12_k7_low3_mask06_block02_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask06_block03_output [20;1;10;0;16;15;21;11] : cnf)
  as imported_from_block03.
assert (Himported_from_block03 :
  satisfies_cnf rho imported_from_block03).
{
  unfold imported_from_block03.
  apply (satisfies_cnf_select rho c12_k7_low3_mask06_block03_output [20;1;10;0;16;15;21;11]).
  - exact (c12_k7_low3_mask06_block03_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask06_block04_output [14;19;0] : cnf)
  as imported_from_block04.
assert (Himported_from_block04 :
  satisfies_cnf rho imported_from_block04).
{
  unfold imported_from_block04.
  apply (satisfies_cnf_select rho c12_k7_low3_mask06_block04_output [14;19;0]).
  - exact (c12_k7_low3_mask06_block04_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask06_block05_output [3;13;12;19;18] : cnf)
  as imported_from_block05.
assert (Himported_from_block05 :
  satisfies_cnf rho imported_from_block05).
{
  unfold imported_from_block05.
  apply (satisfies_cnf_select rho c12_k7_low3_mask06_block05_output [3;13;12;19;18]).
  - exact (c12_k7_low3_mask06_block05_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask06_block06_output [2;21;22;17;9] : cnf)
  as imported_from_block06.
assert (Himported_from_block06 :
  satisfies_cnf rho imported_from_block06).
{
  unfold imported_from_block06.
  apply (satisfies_cnf_select rho c12_k7_low3_mask06_block06_output [2;21;22;17;9]).
  - exact (c12_k7_low3_mask06_block06_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask06_block07_output [24;7;12] : cnf)
  as imported_from_block07.
assert (Himported_from_block07 :
  satisfies_cnf rho imported_from_block07).
{
  unfold imported_from_block07.
  apply (satisfies_cnf_select rho c12_k7_low3_mask06_block07_output [24;7;12]).
  - exact (c12_k7_low3_mask06_block07_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask06_block08_output [11;14;3;17;12;16] : cnf)
  as imported_from_block08.
assert (Himported_from_block08 :
  satisfies_cnf rho imported_from_block08).
{
  unfold imported_from_block08.
  apply (satisfies_cnf_select rho c12_k7_low3_mask06_block08_output [11;14;3;17;12;16]).
  - exact (c12_k7_low3_mask06_block08_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask06_block09_output [22;19;10;2;24;17;7;18;12;9;5;15] : cnf)
  as imported_from_block09.
assert (Himported_from_block09 :
  satisfies_cnf rho imported_from_block09).
{
  unfold imported_from_block09.
  apply (satisfies_cnf_select rho c12_k7_low3_mask06_block09_output [22;19;10;2;24;17;7;18;12;9;5;15]).
  - exact (c12_k7_low3_mask06_block09_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (concat [imported_from_block00;imported_from_block01;imported_from_block02;imported_from_block03;imported_from_block04;imported_from_block05;imported_from_block06;imported_from_block07;imported_from_block08;imported_from_block09] : cnf) as imported.
assert (Himported : satisfies_cnf rho imported).
{
  unfold imported.
  apply satisfies_cnf_concat_intro.
  constructor.
  { exact Himported_from_block00. }
  constructor.
  { exact Himported_from_block01. }
  constructor.
  { exact Himported_from_block02. }
  constructor.
  { exact Himported_from_block03. }
  constructor.
  { exact Himported_from_block04. }
  constructor.
  { exact Himported_from_block05. }
  constructor.
  { exact Himported_from_block06. }
  constructor.
  { exact Himported_from_block07. }
  constructor.
  { exact Himported_from_block08. }
  constructor.
  { exact Himported_from_block09. }
  constructor.
}
pose (
  [66;67;68;69;70;71;72;73;74;75;76;77;3525;3517;3523;3526;3527;3524;4154;1771;4157;1793;4159;54;2527;28;2523;1805;43;2525;58;61;49;1934;1897;1917;1927;1862;1935;452;183;309;450;2959;2890;2956;2940;2960;2950;41;9;2521;1088;1803;4152;3879;3880;3876;4158;4153;62;37;2530;29;2529;1808;50;2532;55;2533;18;1070;1063;1800;2515;1054;1474;1497;414;2526;1773;1049;39;2447;1072;1772;42;1069;17;449;1795;2507;1053;1062;1495;1483;1496;1473;1492;1423;24;1059;2540;1064;23;1058;2539;26;1061;1;1065;1883;1823;1873;1896;1895;1892;36;2445;2846;3518;3521;3519;3522;3520;1774;4156;1079;2626;2632;2629;2610;2620;2560;310;311;85;313;288;312;1170;1210;1211;1135;1190;1200;13;1048;2535;1801;1790;1796;19;20;14;2536;15;2537;455;187;457;418;1768;1068;2666;2656;2646;1932;1933;1912;1857;1922;1770;44;1071;1066;2541;1150;1153;1152;1151;1145;1090;1475;1467;1472;1412;1052;12;27;3581;3578;3580;3579;2501;59;2496;1055;3259;3196;3256;3258;3251;3257;2934;2931;2933;2926;2871;2932;64;1798;2513;8;1799;2514;48;2519;57;2504;3573;2505;47;2511;1083;1792;34;1797;2509;7;1085;1794;2506;52;2512;3599;3603;1002;1007;1769;1872;1882;1822;1893;1894;3;2457;1493;1482;1494;1422;40;1067;1767;2502;2663;2953;2952;2881;2951;2941;1084;1785;2508;3265;3199;3261;3254;3263;2518;35;53;4058;2944;4155;2199;2197;2198;2200;2192;2137;1779;1777;1074;1778;2510;1787;46;6;1082;1788;2217;2258;2237;1791;3530;3601;3873;1789;2498;2585;2591;2575;2594;2597;1081;1804;2522;1425;1086;3262;3200;3255;3264;1075] : list nat) as base_ids.
pose ([
  ([221;101;179;272;280;223;227;284],[0;1;2;3;4;5;6;7;8;9;10;11;315;316;317;318;319;320;321;322;323;324;325;326;331;12;13;14;15;16;17;18;19;20;21;22;23;24;25;26;27;28;29;363;30;31;32;33;354;364;34;35;36;37;38;39;40;41;42;43;44;45;46;47;48;49]);
  ([220;266;286;272;282;219;268;284;51],[0;1;2;3;4;5;6;7;8;9;10;11;315;316;317;318;319;320;321;322;323;324;325;326;331;50;51;52;53;54;55;355;344;357;56;57;18;58;358;59;22;60;61;62;63;64;65;66;67;68;69;70;71;72;73;74;75;76;77]);
  ([227;284;123],[0;1;2;3;4;5;6;7;8;9;10;11;315;316;317;318;319;320;321;322;323;324;325;326;331;365;22;354;366;364;367;368;20;39;40;78;41;42;54;18;59;58;359;376;12;13;14;15;16;17;23;25;26;27;28;29;19;30;31;32;79;369;345;34;35;36;37;38;360;361;33;333;327;375;63;80;81;82;83;84;85;86;87]);
  ([279;178;275;284;57;51],[0;1;2;3;4;5;6;7;8;9;10;11;315;316;317;318;319;320;321;322;323;324;325;326;331;88;89;39;40;78;41;42;22;20;90;91;54;92;18;87;59;93;58;94;95;96;97;98;99;25;72;100;101;102;63;103;104;105;106;107;108;109;110;377;344;111;112;113;114;115;116;117;118;119;120;121;122;123;124;82;85;125;19]);
  ([268;286;278;178;57;51],[0;1;2;3;4;5;6;7;8;9;10;11;315;316;317;318;319;320;321;322;323;324;325;326;331;59;93;126;346;127;88;94;95;96;97;98;99;328;25;72;100;101;102;63;103;104;105;106;107;108;109;110;341;342;128;129;130;131;132;133]);
  ([269;35;178;275],[0;1;2;3;4;5;6;7;8;9;10;11;315;316;317;318;319;320;321;322;323;324;325;326;331;134;135;136;137;138;88;356;139;41;20;90;91;58;54;92;140;141;142;143;144;145;18;87;332;22;126;346;127;362;146;147;148;27;329;65;149;125;150;151;152;75;153;154;155;156;157;111;112;113]);
  ([178;275;284;57;51],[0;1;2;3;4;5;6;7;8;9;10;11;315;316;317;318;319;320;321;322;323;324;325;326;331;88;22;378;126;346;127;328;380;59;93;379;94;95;96;97;98;99;158;159;160;161;25;72;100;101;102;63;103;104;105;106;107;108;109;110;20;90;91;54;92;140;141;142;143;144;145;58;18;87;332;364;111;112;113;114;115;116;128;129;130;131;132;133;147;148;149;125]);
  ([102;171;272;278],[0;1;2;3;4;5;6;7;8;9;10;11;315;316;317;318;319;320;321;322;323;324;325;326;331;49;162;163;18;126;346;164;165;166;128]);
  ([105;101;171;266;268;272;278;284;57;51],[0;1;2;3;4;5;6;7;8;9;10;11;315;316;317;318;319;320;321;322;323;324;325;326;331;382;54;59;18;126;346;22;167;168;116;169;170;171;328;28;71;172;173;174;146;80;81;105;84;82;175;176;370;177;178;179;180;181;182;76;183;184;185;97;186;117;88;187;156;188;25;63;100;107;189;109;128;129;130;131;132;133;190;191;192;193;120;194;195;196]);
  ([90;207;185;35;280;282;268;266;179;57;51],[0;1;2;3;4;5;6;7;8;9;10;11;315;316;317;318;319;320;321;322;323;324;325;326;331;146;81;105;20;58;59;54;345;177;178;179;180;181;182;76;183;184;185;97;186;187;153;197;75;156;157;188;25;63;100;107;189;109;198;199;200;201;202;203;204;205;206;207;208;209;210;211;212;213;214;215;216;217;218;219]);
  ([53;185;229;223;280;268;179;284;57;51],[0;1;2;3;4;5;6;7;8;9;10;11;315;316;317;318;319;320;321;322;323;324;325;326;331;76;183;184;185;97;186;20;59;22;25;72;63;100;101;102;107;108;189;109;110;220;190;191;192;193;120;204;205;206;207;208;209;117;31]);
  ([181;223;229;185;280;179;284],[0;1;2;3;4;5;6;7;8;9;10;11;315;316;317;318;319;320;321;322;323;324;325;326;331;204;205;206;207;208;209;20;22;60;221;368;349;222;223;31;219;224;225;226;227;228;229;230;231;232;233;234;235;236]);
  ([101;171;282;268;280;272;266;278;179;284;57;51],[0;1;2;3;4;5;6;7;8;9;10;11;315;316;317;318;319;320;321;322;323;324;325;326;331;383;382;58;59;20;18;237;238;54;126;346;22;86;239;328;384;240;241;242;243;244;125;82;175;176;245;84;85;28;71;174;377;385;386;117;104;246;107;247;248;249;98;250;25;100;63;189;109;190;191;192;193;120;198;199;200;201;202;203;31;32;221;212]);
  ([171;282;268;280;272;266;278;179;284;57;51],[0;1;2;3;4;5;6;7;8;9;10;11;315;316;317;318;319;320;321;322;323;324;325;326;331;382;387;58;59;20;18;237;238;54;126;346;22;251;223;252;253;155;217;106;79;254;328;164;165;166;128;255]);
  ([100;280;185;268;179;57;51],[0;1;2;3;4;5;6;7;8;9;10;11;315;316;317;318;319;320;321;322;323;324;325;326;331;251;223;106;20;59;256;257;205;258;259;260;76;183;184;185;97;186;60;261;21;221;31;219;224;225;107]);
  ([181;185;280;179;284],[0;1;2;3;4;5;6;7;8;9;10;11;315;316;317;318;319;320;321;322;323;324;325;326;331;204;205;206;207;208;209;20;22;60;261;21;221;222;223;31;219;224;225;226;227;228;229;230;231;232;233;234;55;386]);
  ([282;268;280;272;266;278;179;284;57;51],[0;1;2;3;4;5;6;7;8;9;10;11;315;316;317;318;319;320;321;322;323;324;325;326;331;58;388;59;20;18;237;238;54;126;346;22;218;262;390;389;107;151;263;247;185;248;249;98;250;345;25;72;104;105;100;102;63;103;189;109;110;264;265;266;377;201;267;268;210;211;212;213;214;215;216;117;118;86;269;172;332;225;270;271;272;190;191;192]);
  ([287;278;275;284;57;51],[0;1;2;3;4;5;6;7;8;9;10;11;315;316;317;318;319;320;321;322;323;324;325;326;331;158;159;137;160;161;126;346;381;22;20;54;59;391]);
  ([185;286;223;268;280;179;284;57;51],[0;1;2;3;4;5;6;7;8;9;10;11;315;316;317;318;319;320;321;322;323;324;325;326;331;390;389;59;20;22;107;151;263;247;185;248;249;98;250;25;72;104;105;100;101;102;63;189;109;110;342;377;344;117;118;120;121;122;123;124;28;29;21;30;32;31;23;256;273;45]);
  ([59;223;274;268;280;284;57;51],[0;1;2;3;4;5;6;7;8;9;10;11;315;316;317;318;319;320;321;322;323;324;325;326;331;247;185;248;249;98;250;274;59;20;22;25;72;104;105;106;100;101;102;63;189;93;109;110;342;275;276;277;334;278;279;280;377;32;281;222;282;283;216;284;386;190;191]);
  ([274;268;278;280;179;284;57;51],[0;1;2;3;4;5;6;7;8;9;10;11;315;316;317;318;319;320;321;322;323;324;325;326;331;274;335;59;126;346;20;22;394;107;108;390;49;262;285;284;328;128;129;130;131;132;133;251;282;195;371;286;196;287;150;288;289;290;291;292;293;117;336]);
  ([157;223;171;286;268;278;284],[0;1;2;3;4;5;6;7;8;9;10;11;315;316;317;318;319;320;321;322;323;324;325;326;331;362;59;126;346;22;328;128;129;130;131;132;133;251;194;195;371;286;196;287;150;294;288;289;290;341;343;117;235;236;295;192;296;336;337;379;55;56;297;57;63]);
  ([223;286;268;278;280;284;57;51],[0;1;2;3;4;5;6;7;8;9;10;11;315;316;317;318;319;320;321;322;323;324;325;326;331;59;126;346;20;22;379;393;395;49;262;285;396;328;298;299;108;330;247;185;248;249;98;109;110;25;72;104;105;106;100;101;102;63;189;377;341;344;117;118;300;301;302;303;304;120;121;122;123;124;150;195;286]);
  ([286;268;278;280;284;57;51],[0;1;2;3;4;5;6;7;8;9;10;11;315;316;317;318;319;320;321;322;323;324;325;326;331;397;59;126;346;20;22;379;152;335;372;305;306;307;103;373;261;338;117;347;348;350;339;351;369;249;96;308;352;340;58;309;374;100;118;104;105;106;25;72;107;189;109;110;66;222;310;311;312;313;353;128;129]);
  ([268;278;280;284;57;51],[0;1;2;3;4;5;6;7;8;9;10;11;315;316;317;318;319;320;321;322;323;324;325;326;331;59;398;126;346;20;22;392;274;335;395;394;88;93;90;91;127;314;107;108;94;95;96;97;99;328;128;129;130;131;132;133;25;72;100;101;102;63;104;105;106;109;110;194;282;195;371;286;196;150;290;277])
] : list (list nat * list nat)) as records.
assert (Hcheck :
  check_selected_microblock (c12_k7_low3_instance [true; false; false; true; false; false; true; false; false; false; false; false]) base_ids
    imported records c12_k7_low3_mask06_block10_output = true).
{ vm_compute. reflexivity. }
exact (check_selected_microblock_sound
  (c12_k7_low3_instance [true; false; false; true; false; false; true; false; false; false; false; false]) base_ids imported records c12_k7_low3_mask06_block10_output
  Hcheck rho Hbase Himported).
Qed.
