(** Generated by [scripts/generate_ckpath_certificates.py].
    Only the block output is transparent.  Selected base clauses,
    producer imports, replay records, and the transient database
    all remain underneath the opaque soundness theorem. *)

From Stdlib Require Import List.
From Digraph Require Import ckpath_cnf ckpath_drup_microblock ckpath_cert_k7_c12_low3_reduction ckpath_cert_k7_c12_low3_mask07_block00 ckpath_cert_k7_c12_low3_mask07_block01 ckpath_cert_k7_c12_low3_mask07_block02 ckpath_cert_k7_c12_low3_mask07_block03 ckpath_cert_k7_c12_low3_mask07_block04 ckpath_cert_k7_c12_low3_mask07_block05 ckpath_cert_k7_c12_low3_mask07_block07 ckpath_cert_k7_c12_low3_mask07_block08 ckpath_cert_k7_c12_low3_mask07_block09 ckpath_cert_k7_c12_low3_mask07_block12 ckpath_cert_k7_c12_low3_mask07_block13.
Import ListNotations.
Set Warnings "-abstract-large-number".

(** Original retained additions [350, 375); 199 selected base clauses and 43 imported consequences from 11 producer blocks. *)
Definition c12_k7_low3_mask07_block14_output : cnf :=
  [
  [(44,true);(114,true);(143,false);(139,false);(136,false);(39,true);(41,true)];
  [(42,false);(125,true);(143,false);(114,true);(144,false)];
  [(138,false);(140,false)];
  [(42,true);(39,true);(140,false)];
  [(39,true);(140,false)];
  [(114,false);(140,false)];
  [(43,true);(44,true);(140,false)];
  [(42,false);(43,false);(140,false)];
  [(44,true);(140,false)];
  [(40,false);(75,true);(140,false)];
  [(75,true);(140,false)];
  [(140,false)];
  [(136,true)];
  [(139,true)];
  [(138,true)];
  [(142,true)];
  [(144,true)];
  [(143,true)];
  [(134,true)];
  [(148,false)];
  [(151,false)];
  [(150,false)];
  [(57,true)];
  [(3,false)];
  [(154,false)]
].

Theorem c12_k7_low3_mask07_block14_sound :
  forall rho, satisfies_cnf rho (c12_k7_low3_instance [true; false; true; false; false; false; false; false; true; false; false; false]) ->
    satisfies_cnf rho c12_k7_low3_mask07_block14_output.
Proof.
intros rho Hbase.
pose (select_cnf c12_k7_low3_mask07_block00_output [0;1;2;3;4;5;6;7;8;9;10;11] : cnf)
  as imported_from_block00.
assert (Himported_from_block00 :
  satisfies_cnf rho imported_from_block00).
{
  unfold imported_from_block00.
  apply (satisfies_cnf_select rho c12_k7_low3_mask07_block00_output [0;1;2;3;4;5;6;7;8;9;10;11]).
  - exact (c12_k7_low3_mask07_block00_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask07_block01_output [11] : cnf)
  as imported_from_block01.
assert (Himported_from_block01 :
  satisfies_cnf rho imported_from_block01).
{
  unfold imported_from_block01.
  apply (satisfies_cnf_select rho c12_k7_low3_mask07_block01_output [11]).
  - exact (c12_k7_low3_mask07_block01_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask07_block02_output [14] : cnf)
  as imported_from_block02.
assert (Himported_from_block02 :
  satisfies_cnf rho imported_from_block02).
{
  unfold imported_from_block02.
  apply (satisfies_cnf_select rho c12_k7_low3_mask07_block02_output [14]).
  - exact (c12_k7_low3_mask07_block02_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask07_block03_output [14;5;9;15] : cnf)
  as imported_from_block03.
assert (Himported_from_block03 :
  satisfies_cnf rho imported_from_block03).
{
  unfold imported_from_block03.
  apply (satisfies_cnf_select rho c12_k7_low3_mask07_block03_output [14;5;9;15]).
  - exact (c12_k7_low3_mask07_block03_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask07_block04_output [15;18] : cnf)
  as imported_from_block04.
assert (Himported_from_block04 :
  satisfies_cnf rho imported_from_block04).
{
  unfold imported_from_block04.
  apply (satisfies_cnf_select rho c12_k7_low3_mask07_block04_output [15;18]).
  - exact (c12_k7_low3_mask07_block04_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask07_block05_output [17;19;2;16] : cnf)
  as imported_from_block05.
assert (Himported_from_block05 :
  satisfies_cnf rho imported_from_block05).
{
  unfold imported_from_block05.
  apply (satisfies_cnf_select rho c12_k7_low3_mask07_block05_output [17;19;2;16]).
  - exact (c12_k7_low3_mask07_block05_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask07_block07_output [23;16] : cnf)
  as imported_from_block07.
assert (Himported_from_block07 :
  satisfies_cnf rho imported_from_block07).
{
  unfold imported_from_block07.
  apply (satisfies_cnf_select rho c12_k7_low3_mask07_block07_output [23;16]).
  - exact (c12_k7_low3_mask07_block07_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask07_block08_output [24;22;23] : cnf)
  as imported_from_block08.
assert (Himported_from_block08 :
  satisfies_cnf rho imported_from_block08).
{
  unfold imported_from_block08.
  apply (satisfies_cnf_select rho c12_k7_low3_mask07_block08_output [24;22;23]).
  - exact (c12_k7_low3_mask07_block08_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask07_block09_output [0;19;3] : cnf)
  as imported_from_block09.
assert (Himported_from_block09 :
  satisfies_cnf rho imported_from_block09).
{
  unfold imported_from_block09.
  apply (satisfies_cnf_select rho c12_k7_low3_mask07_block09_output [0;19;3]).
  - exact (c12_k7_low3_mask07_block09_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask07_block12_output [9;5] : cnf)
  as imported_from_block12.
assert (Himported_from_block12 :
  satisfies_cnf rho imported_from_block12).
{
  unfold imported_from_block12.
  apply (satisfies_cnf_select rho c12_k7_low3_mask07_block12_output [9;5]).
  - exact (c12_k7_low3_mask07_block12_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask07_block13_output [0;1;24;21;22;17;23;16;18] : cnf)
  as imported_from_block13.
assert (Himported_from_block13 :
  satisfies_cnf rho imported_from_block13).
{
  unfold imported_from_block13.
  apply (satisfies_cnf_select rho c12_k7_low3_mask07_block13_output [0;1;24;21;22;17;23;16;18]).
  - exact (c12_k7_low3_mask07_block13_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (concat [imported_from_block00;imported_from_block01;imported_from_block02;imported_from_block03;imported_from_block04;imported_from_block05;imported_from_block07;imported_from_block08;imported_from_block09;imported_from_block12;imported_from_block13] : cnf) as imported.
assert (Himported : satisfies_cnf rho imported).
{
  unfold imported.
  apply satisfies_cnf_concat_intro.
  constructor.
  { exact Himported_from_block00. }
  constructor.
  { exact Himported_from_block01. }
  constructor.
  { exact Himported_from_block02. }
  constructor.
  { exact Himported_from_block03. }
  constructor.
  { exact Himported_from_block04. }
  constructor.
  { exact Himported_from_block05. }
  constructor.
  { exact Himported_from_block07. }
  constructor.
  { exact Himported_from_block08. }
  constructor.
  { exact Himported_from_block09. }
  constructor.
  { exact Himported_from_block12. }
  constructor.
  { exact Himported_from_block13. }
  constructor.
}
pose (
  [66;67;68;69;70;71;72;73;74;75;76;77;1611;1616;4159;4156;4153;1617;1595;1540;1575;33;1059;1451;3184;35;1061;1453;3163;1062;31;1057;3182;2;1064;12;2484;2534;2551;2548;2554;2555;3571;3521;3587;3588;3589;5;24;52;1078;3191;39;2127;54;3171;3586;28;1495;3161;49;3164;9;3159;1089;3165;58;3166;61;3167;3934;3860;4155;1474;4157;14;113;122;81;121;1058;4158;1573;1615;1609;1538;1593;1454;25;1396;55;29;2868;2804;2871;345;290;353;354;108;4152;1048;1457;1455;1105;1108;1109;1093;1098;1102;17;1052;3181;2125;2441;3154;3177;36;3162;1479;1489;1485;32;1450;3183;1587;1623;1621;1552;1607;1456;3266;3305;3231;3286;3307;3308;3248;3263;3198;3264;3265;37;1493;1551;1586;1606;1620;2468;16;1082;2443;1080;1478;2122;1599;1579;1544;1619;15;2865;2881;2884;2815;53;3157;3180;1079;1477;3174;3524;3593;3574;3595;3591;43;2465;2146;3870;3869;96;305;295;304;303;299;365;363;355;349;376;375;369;123;377;371;153;370;117] : list nat) as base_ids.
pose ([
  ([87;227;284;276;270;77;81],[0;1;2;3;4;5;6;7;8;9;10;11;199;200;201;202;203;204;205;206;207;208;209;210;212;233;234;12;13;14;15;16;235;17;18;19;20;21;22;23;24;25;26;27;28;29;30;31;32;33;34;35;36;37;38;39;40;41;213;42;43;44;45;46;47;48;49;50;51;52;53;54]);
  ([82;249;284;227;286],[0;1;2;3;4;5;6;7;8;9;10;11;199;200;201;202;203;204;205;206;207;208;209;210;212;233;234;25;28;14;55;42;56;43;44;45;46;57;58;59;60;61;62;63;64;214;225;54;65;66;67;68;69;70;71]);
  ([274;278],[0;1;2;3;4;5;6;7;8;9;10;11;199;200;201;202;203;204;205;206;207;208;209;210;212;233;234;72;217;73;236;237;74;238;75;76;77;78;219;79;15;14;16;239;228;80;81;215;235;242;243;240;82;83;84;85;86;29;87;21;22;23;24;34;30;31;32;220;36;37;38;39;40;41;213;221;88;89;47;48;49;50;51;231;52;53;54;90;60;91;92;93;94;229;226]);
  ([83;77;278],[0;1;2;3;4;5;6;7;8;9;10;11;199;200;201;202;203;204;205;206;207;208;209;210;212;233;234;74;238;244;95;96;97;98;99;15;16;239;228;82;13;83;84;85;86;235;81;215;14;100;241;101;35;102;103;29;87;21;22;23;24;34;30;31;32;240;104;105;106;107;108;109;220;36;37;38;39;40;41;213;221;110;111;112;113;114;88;47;48;49;231;52;54;90;60;91;92;93;94;229;226]);
  ([77;278],[0;1;2;3;4;5;6;7;8;9;10;11;199;200;201;202;203;204;205;206;207;208;209;210;212;233;234;245;74;238;244;25;55;95;96;97;98;99;15;16;239;228;235;26;27;81;215;115;14;28;100;241;116;243;240;117;103;216;222;227;118;119;120;17]);
  ([226;278],[0;1;2;3;4;5;6;7;8;9;10;11;199;200;201;202;203;204;205;206;207;208;209;210;212;233;234;117;121;237;74;238;246;95;96;97;98;99;122;123;124;15;119;16;239;228;80;103;125;126;127;128;129;81;115;120;14;28;118;100;116;35;102;25;55;26;27;21;22;24;34;130;31;32;131;132;133;134;135;136;106;107;108;109;104;105;36;37;38;39;40;41]);
  ([85;87;278],[0;1;2;3;4;5;6;7;8;9;10;11;199;200;201;202;203;204;205;206;207;208;209;210;212;233;234;74;238;244;246;247;95;96;97;98;99;122;123;124;15;16;239;228;80;125;126;127;128;129;81;115;14;28;100;116;35;102;25;55;26;27;243;21;22;24;34;130]);
  ([82;84;278],[0;1;2;3;4;5;6;7;8;9;10;11;199;200;201;202;203;204;205;206;207;208;209;210;212;233;234;25;117;74;238;244;246;55;95;96;97;98;99;122;123;124;15;16;239;228;80;26;27;29;81;115;14;28;243;100;116;232;230;137;138;131;139;140;141;42;56;43;44;45;46;142;130;143]);
  ([87;278],[0;1;2;3;4;5;6;7;8;9;10;11;199;200;201;202;203;204;205;206;207;208;209;210;212;233;234;248;74;238;244;246;247;249;95;96;97;98;99;122;123;124;15;16;239;228;80;29;87;81;14;100;144;145;146;147;232;230;33;34;130;35;101;31;21;22;213;221;240;106;107;108;109;104;105;36;37;38;39;40;41;60;91;148;220;113;149;110;112;47;48;49;231;52;54;90;88;92;93;94;226]);
  ([78;149;278],[0;1;2;3;4;5;6;7;8;9;10;11;199;200;201;202;203;204;205;206;207;208;209;210;212;233;234;21;74;238;244;246;247;250;95;96;97;98;99;122;123;124;142;15;16;239;228;80;22;81;14;100;243;240;36;37;38;39;40;41;223;213;220;47;150;48;49;50;51;231;52;151;54;152;153;90;154;60;61;88;221;92;93;94;226]);
  ([149;278],[0;1;2;3;4;5;6;7;8;9;10;11;199;200;201;202;203;204;205;206;207;208;209;210;212;233;234;251;74;238;244;246;247;250;95;96;97;98;99;122;123;124;142;15;16;239;228;80;81;14;100;243;240;155;156;157;158;31;32;35;102;101;34;29;87;106;107;108;109;104;105;159;149;110;112;36;37;38;39;40;41;213;160;161;162;163;226]);
  ([278],[0;1;2;3;4;5;6;7;8;9;10;11;199;200;201;202;203;204;205;206;207;208;209;210;212;233;234;74;238;244;246;247;250;252;95;96;97;98;99;122;123;124;142;164;165;166;167;168;67;24;169;15;16;239;228;80;81;14;100;243;240;170;171;172;173;45;174;155;156;157;158;62;63;64;214;225;54;57;58;211;68;69;175;176;177;60;61;31;102;101;29;87;70;218;178;179]);
  ([271],[0;1;2;3;4;5;6;7;8;9;10;11;199;200;201;202;203;204;205;206;207;208;209;210;212;233;234;253;180;181;182;183;184;96;185]);
  ([277],[0;1;2;3;4;5;6;7;8;9;10;11;199;200;201;202;203;204;205;206;207;208;209;210;212;233;234;253;254;224;186;187;95;76]);
  ([275],[0;1;2;3;4;5;6;7;8;9;10;11;199;200;201;202;203;204;205;206;207;208;209;210;212;233;234;253;254;255;188;97;98;99;189]);
  ([283],[0;1;2;3;4;5;6;7;8;9;10;11;199;200;201;202;203;204;205;206;207;208;209;210;212;233;234;253;254;255;256;79;190;191;192]);
  ([287],[0;1;2;3;4;5;6;7;8;9;10;11;199;200;201;202;203;204;205;206;207;208;209;210;212;233;234;253;254;255;256;257;193;194;195]);
  ([285],[0;1;2;3;4;5;6;7;8;9;10;11;199;200;201;202;203;204;205;206;207;208;209;210;212;233;234;253;254;255;256;257;258;196;197]);
  ([267],[0;1;2;3;4;5;6;7;8;9;10;11;199;200;201;202;203;204;205;206;207;208;209;210;212;233;234;253;254;255;256;257;258;259;198]);
  ([294],[0;1;2;3;4;5;6;7;8;9;10;11;199;200;201;202;203;204;205;206;207;208;209;210;212;233;234;253;254;255;256;257;258;259;260;16]);
  ([300],[0;1;2;3;4;5;6;7;8;9;10;11;199;200;201;202;203;204;205;206;207;208;209;210;212;233;234;253;254;255;256;257;258;259;260;261;15]);
  ([298],[0;1;2;3;4;5;6;7;8;9;10;11;199;200;201;202;203;204;205;206;207;208;209;210;212;233;234;253;254;255;256;257;258;259;260;261;262;72]);
  ([113],[0;1;2;3;4;5;6;7;8;9;10;11;199;200;201;202;203;204;205;206;207;208;209;210;212;233;234;253;254;255;256;257;258;259;260;261;262;263;217]);
  ([4],[0;1;2;3;4;5;6;7;8;9;10;11;199;200;201;202;203;204;205;206;207;208;209;210;212;233;234;253;254;255;256;257;258;259;260;261;262;263;264;33;102;73]);
  ([306],[0;1;2;3;4;5;6;7;8;9;10;11;199;200;201;202;203;204;205;206;207;208;209;210;212;233;234;253;254;255;256;257;258;259;260;261;262;263;264;265;81])
] : list (list nat * list nat)) as records.
assert (Hcheck :
  check_selected_microblock (c12_k7_low3_instance [true; false; true; false; false; false; false; false; true; false; false; false]) base_ids
    imported records c12_k7_low3_mask07_block14_output = true).
{ vm_compute. reflexivity. }
exact (check_selected_microblock_sound
  (c12_k7_low3_instance [true; false; true; false; false; false; false; false; true; false; false; false]) base_ids imported records c12_k7_low3_mask07_block14_output
  Hcheck rho Hbase Himported).
Qed.
