(** Generated by [scripts/generate_ckpath_certificates.py].
    Only the block output is transparent.  Selected base clauses,
    producer imports, replay records, and the transient database
    all remain underneath the opaque soundness theorem. *)

From Stdlib Require Import List.
From Digraph Require Import ckpath_cnf ckpath_drup_microblock ckpath_cert_k7_c12_low3_reduction ckpath_cert_k7_c12_low3_mask07_block00 ckpath_cert_k7_c12_low3_mask07_block02 ckpath_cert_k7_c12_low3_mask07_block03 ckpath_cert_k7_c12_low3_mask07_block04 ckpath_cert_k7_c12_low3_mask07_block05 ckpath_cert_k7_c12_low3_mask07_block06 ckpath_cert_k7_c12_low3_mask07_block07 ckpath_cert_k7_c12_low3_mask07_block08 ckpath_cert_k7_c12_low3_mask07_block09.
Import ListNotations.
Set Warnings "-abstract-large-number".

(** Original retained additions [250, 275); 282 selected base clauses and 49 imported consequences from 9 producer blocks. *)
Definition c12_k7_low3_mask07_block10_output : cnf :=
  [
  [(14,true);(139,false);(57,false);(144,false);(137,false)];
  [(139,false);(138,false);(144,false);(137,false)];
  [(126,true);(47,true);(123,true);(124,true);(50,true);(144,false);(137,false)];
  [(47,true);(123,true);(124,true);(50,true);(144,false);(137,false)];
  [(125,true);(55,true);(123,true);(124,true);(50,true);(144,false);(137,false)];
  [(55,true);(123,true);(124,true);(50,true);(144,false);(137,false)];
  [(123,true);(124,true);(50,true);(144,false);(137,false)];
  [(134,false);(14,true);(46,false);(22,true)];
  [(53,true);(123,false);(50,true);(137,false)];
  [(140,true);(112,true);(138,true);(123,false);(53,false)];
  [(142,false);(144,false);(134,false);(22,true);(53,false)];
  [(144,false);(139,false);(123,false);(50,true);(137,false)];
  [(139,false);(123,false);(50,true);(137,false)];
  [(134,false);(22,true);(53,false);(139,true)];
  [(123,false);(50,true);(137,false)];
  [(134,true);(139,true);(53,false);(50,true);(137,false)];
  [(100,true);(57,false);(142,false);(105,true);(134,false);(104,true)];
  [(101,false);(17,true);(16,true);(134,false)];
  [(57,false);(142,false);(105,true);(134,false);(16,true);(104,true)];
  [(142,false);(139,true);(53,false);(50,true);(137,false)];
  [(139,true);(53,false);(50,true);(137,false)];
  [(20,true);(57,false);(134,false);(53,false)];
  [(136,false);(57,false);(134,false);(139,false);(53,false)];
  [(57,false);(134,false);(139,false);(53,false)];
  [(136,true);(53,false);(50,true);(137,false)]
].

Theorem c12_k7_low3_mask07_block10_sound :
  forall rho, satisfies_cnf rho (c12_k7_low3_instance [true; false; true; false; false; false; false; false; true; false; false; false]) ->
    satisfies_cnf rho c12_k7_low3_mask07_block10_output.
Proof.
intros rho Hbase.
pose (select_cnf c12_k7_low3_mask07_block00_output [0;1;2;3;4;5;6;7;8;9;10;11] : cnf)
  as imported_from_block00.
assert (Himported_from_block00 :
  satisfies_cnf rho imported_from_block00).
{
  unfold imported_from_block00.
  apply (satisfies_cnf_select rho c12_k7_low3_mask07_block00_output [0;1;2;3;4;5;6;7;8;9;10;11]).
  - exact (c12_k7_low3_mask07_block00_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask07_block02_output [14;16] : cnf)
  as imported_from_block02.
assert (Himported_from_block02 :
  satisfies_cnf rho imported_from_block02).
{
  unfold imported_from_block02.
  apply (satisfies_cnf_select rho c12_k7_low3_mask07_block02_output [14;16]).
  - exact (c12_k7_low3_mask07_block02_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask07_block03_output [9;15] : cnf)
  as imported_from_block03.
assert (Himported_from_block03 :
  satisfies_cnf rho imported_from_block03).
{
  unfold imported_from_block03.
  apply (satisfies_cnf_select rho c12_k7_low3_mask07_block03_output [9;15]).
  - exact (c12_k7_low3_mask07_block03_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask07_block04_output [15;3;7;4] : cnf)
  as imported_from_block04.
assert (Himported_from_block04 :
  satisfies_cnf rho imported_from_block04).
{
  unfold imported_from_block04.
  apply (satisfies_cnf_select rho c12_k7_low3_mask07_block04_output [15;3;7;4]).
  - exact (c12_k7_low3_mask07_block04_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask07_block05_output [1;11] : cnf)
  as imported_from_block05.
assert (Himported_from_block05 :
  satisfies_cnf rho imported_from_block05).
{
  unfold imported_from_block05.
  apply (satisfies_cnf_select rho c12_k7_low3_mask07_block05_output [1;11]).
  - exact (c12_k7_low3_mask07_block05_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask07_block06_output [7;13;22;8;6] : cnf)
  as imported_from_block06.
assert (Himported_from_block06 :
  satisfies_cnf rho imported_from_block06).
{
  unfold imported_from_block06.
  apply (satisfies_cnf_select rho c12_k7_low3_mask07_block06_output [7;13;22;8;6]).
  - exact (c12_k7_low3_mask07_block06_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask07_block07_output [8;13;3;16;0;21;19;17;22;23] : cnf)
  as imported_from_block07.
assert (Himported_from_block07 :
  satisfies_cnf rho imported_from_block07).
{
  unfold imported_from_block07.
  apply (satisfies_cnf_select rho c12_k7_low3_mask07_block07_output [8;13;3;16;0;21;19;17;22;23]).
  - exact (c12_k7_low3_mask07_block07_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask07_block08_output [10;5;3;8;6;14;20] : cnf)
  as imported_from_block08.
assert (Himported_from_block08 :
  satisfies_cnf rho imported_from_block08).
{
  unfold imported_from_block08.
  apply (satisfies_cnf_select rho c12_k7_low3_mask07_block08_output [10;5;3;8;6;14;20]).
  - exact (c12_k7_low3_mask07_block08_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask07_block09_output [21;24;4;1;0] : cnf)
  as imported_from_block09.
assert (Himported_from_block09 :
  satisfies_cnf rho imported_from_block09).
{
  unfold imported_from_block09.
  apply (satisfies_cnf_select rho c12_k7_low3_mask07_block09_output [21;24;4;1;0]).
  - exact (c12_k7_low3_mask07_block09_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (concat [imported_from_block00;imported_from_block02;imported_from_block03;imported_from_block04;imported_from_block05;imported_from_block06;imported_from_block07;imported_from_block08;imported_from_block09] : cnf) as imported.
assert (Himported : satisfies_cnf rho imported).
{
  unfold imported.
  apply satisfies_cnf_concat_intro.
  constructor.
  { exact Himported_from_block00. }
  constructor.
  { exact Himported_from_block02. }
  constructor.
  { exact Himported_from_block03. }
  constructor.
  { exact Himported_from_block04. }
  constructor.
  { exact Himported_from_block05. }
  constructor.
  { exact Himported_from_block06. }
  constructor.
  { exact Himported_from_block07. }
  constructor.
  { exact Himported_from_block08. }
  constructor.
  { exact Himported_from_block09. }
  constructor.
}
pose (
  [66;67;68;69;70;71;72;73;74;75;76;77;4156;14;1065;4154;4152;1050;18;1053;3169;1111;1090;1115;1112;1114;1051;3180;13;3177;20;3181;4155;1474;12;1497;3176;1475;1467;1482;37;1465;1480;1473;1850;1848;1852;1851;1849;1827;42;1068;1462;3172;40;1066;1460;3187;44;3835;3842;3845;3841;3843;3844;3170;55;3173;64;50;59;3174;62;3175;3171;1887;1921;1926;1924;1927;1466;41;1067;1461;3188;3;43;1069;1463;2868;3849;3846;3863;3862;3836;3840;3837;3838;3839;22;1947;1945;1906;1942;1871;2875;2555;3099;379;324;142;400;399;2787;3066;3068;3018;3054;4153;1058;1057;1049;1148;1095;1837;1866;1869;1872;3847;3848;389;409;334;152;1070;1464;1870;1864;1867;1835;1456;1109;1071;154;132;153;349;391;314;390;3168;1496;3182;1064;1082;4158;3155;4159;3164;1089;3178;3203;3228;3240;3238;3239;3218;3532;3517;3531;3522;3530;3526;1080;1054;1062;35;3153;1489;15;3179;1491;3151;1087;53;57;1492;2457;1124;395;318;4157;1086;1200;1195;1198;1159;32;1450;2473;1495;397;396;320;1088;2465;61;3167;28;3161;58;3166;36;3162;1455;1485;385;383;310;384;148;146;128;92;147;1077;2205;2202;2196;2208;2186;1084;1612;1615;29;1576;1596;3156;1113;1188;8;3150;1490;3263;3275;3253;3274;3273;3152;3157;1093;1120;1123;1117;1055;406;405;328;1189;1182;1185;17;1570;1577;1501;1563;1556;1498;1557;1555;1554;1558;2;1453;3185;1059;1451;3184;1146;1147;1149;319] : list nat) as base_ids.
pose ([
  ([27;276;112;286;272],[0;1;2;3;4;5;6;7;8;9;10;11;282;283;284;285;286;287;288;289;290;291;292;293;294;12;13;14;15;309;16;302;326;310;17;18;19;20;21;22;23;24;319;25;320;26;27;28;29;30;31;327]);
  ([276;274;286;272],[0;1;2;3;4;5;6;7;8;9;10;11;282;283;284;285;286;287;288;289;290;291;292;293;294;12;32;298;33;15;13;14;331;309;34;35;36;37;38;39;16;302;17;319;321;30;303;40;41;42;43;44;45;46;47;48;49;50;51;52;53;54;55;56;57;311;304;58]);
  ([251;93;245;247;99;286;272],[0;1;2;3;4;5;6;7;8;9;10;11;282;283;284;285;286;287;288;289;290;291;292;293;294;59;60;61;62;63;64;15;40;65;41;66;67;68;69;53;70;71;72;73;44]);
  ([93;245;247;99;286;272],[0;1;2;3;4;5;6;7;8;9;10;11;282;283;284;285;286;287;288;289;290;291;292;293;294;333;15;58;74;75;76;77;78;46;79;28;80;54;55;56;57;50;51;52;53;81;82;83;84;85;41;86;87;88;89;295;90;91;92;93;94]);
  ([249;109;245;247;99;286;272],[0;1;2;3;4;5;6;7;8;9;10;11;282;283;284;285;286;287;288;289;290;291;292;293;294;59;95;96;97;94;98;334;15;74;68;66;67;70;71;69;53;72;73;99;38;100;101;102;103;104;86;87;88;81;82;83;28;80;54;55;56;85;105;106;107;108;109;110;111;112;113;114;115;116;117;32;298;118;119;120;16;310;17;121;122;123;22]);
  ([109;245;247;99;286;272],[0;1;2;3;4;5;6;7;8;9;10;11;282;283;284;285;286;287;288;289;290;291;292;293;294;335;334;15;40;65;41;99;38;124;104;125;126;127;28;80;50;51;52;53;54;55;56;57;81;82;83;84;86;87;88;62;90;91;128;129;89;328;74;68;66;67;70;72;130;131;112;132;133;106]);
  ([245;247;99;286;272],[0;1;2;3;4;5;6;7;8;9;10;11;282;283;284;285;286;287;288;289;290;291;292;293;294;334;336;15;99;38;58;134;135;59;60;61;62;63;64;40;65;41;66;67;68;69;53;70;71;72;73;136;137;138;139;86;87;88;54;55;56;311;81;82;83;28;80;89;108;109;110;111;112;113;107;32;298;43;118;119;120;140;16;310;17;121;122;123;22]);
  ([266;27;90;43],[0;1;2;3;4;5;6;7;8;9;10;11;282;283;284;285;286;287;288;289;290;291;292;293;294;16;121;28;141;321;123]);
  ([105;244;99;272],[0;1;2;3;4;5;6;7;8;9;10;11;282;283;284;285;286;287;288;289;290;291;292;293;294;30;142;15;104;44;136;137;138;139;58;134;135;99;38;86;87;88;54;55;56;57;81;82;83;84;28;80;338;89;143;110;133;144;145;309]);
  ([279;223;275;244;104],[0;1;2;3;4;5;6;7;8;9;10;11;282;283;284;285;286;287;288;289;290;291;292;293;294;146;147;148;108;130;149;144;30;142;50;51;52;53;15;150;151;299;118;152;153;12;154;155;156;300;157;158;159;16;160;161;162;163;164;165;166;167;168;169;170;171;172;321;18;87;173;174;175;176;329;177;68;178]);
  ([282;286;266;43;104],[0;1;2;3;4;5;6;7;8;9;10;11;282;283;284;285;286;287;288;289;290;291;292;293;294;155;156;16;160;50;53;321;300;179;17;180;161;162;163;164;165;166;298;18;181;182;174;176;177;68;183;178;184;185;186;187;188]);
  ([286;276;244;99;272],[0;1;2;3;4;5;6;7;8;9;10;11;282;283;284;285;286;287;288;289;290;291;292;293;294;12;332;309;302;154;30;142;339;150;151;15;51;52;16;160;341;340;50;53;321;189;190;191;192;330;179;17;180;157;158;159;305;306;118;152;153;188;193;194;195;196;167;168;169;170;171;172;81;82;83;84;197;198;199;34;35;36;38;39;200]);
  ([276;244;99;272],[0;1;2;3;4;5;6;7;8;9;10;11;282;283;284;285;286;287;288;289;290;291;292;293;294;12;309;302;154;342;30;142;339;15;51;52;16;160;50;321;179;17;180;298;340;201;202;203;191;192;157;158;159;306;155;156;204;307;118;152;153;167;168;169;170;171;172;197;198;205;161;162;163;164;165;166;308;206;207;208;200;209;210;211;212;135;213;214;215;178]);
  ([266;43;104;277],[0;1;2;3;4;5;6;7;8;9;10;11;282;283;284;285;286;287;288;289;290;291;292;293;294;16;160;50;312;321;15;51;52;179;17;180;298;216;108;217;218;219;341]);
  ([244;99;272],[0;1;2;3;4;5;6;7;8;9;10;11;282;283;284;285;286;287;288;289;290;291;292;293;294;30;142;339;343;15;51;52;344;50;110;220;221;222;223;224;191;192;53;150;151;155;156;204;32;298;225;301;118;152;153;157;158;159;296;161;162;163;164;165;166;13;119;226;227;228;229;230;313;18;87;231;175;176;177;329;68;183;178;184;185;186;232;233;306]);
  ([267;277;104;99;272],[0;1;2;3;4;5;6;7;8;9;10;11;282;283;284;285;286;287;288;289;290;291;292;293;294;110;220;221;222;223;224;50;345;15;51;52;191;53;155;156;300;32;298;33;301;118;152;157;158;296;337;161;162;163;164;165;166;13;119;313;234;35;20;182;87;231;175;176;177;329;68;183;178;184;185;232;233;235;236]);
  ([199;112;282;209;266;207],[0;1;2;3;4;5;6;7;8;9;10;11;282;283;284;285;286;287;288;289;290;291;292;293;294;161;162;163;164;165;166;13;155;16;310;17;174;18;181;182;176;177;68;183;178;184;237;185;186;319;321;21;238]);
  ([200;33;31;266],[0;1;2;3;4;5;6;7;8;9;10;11;282;283;284;285;286;287;288;289;290;291;292;293;294;18;314;315;319;321;122;16;174;238;322;239]);
  ([112;282;209;266;31;207],[0;1;2;3;4;5;6;7;8;9;10;11;282;283;284;285;286;287;288;289;290;291;292;293;294;347;155;16;310;17;240;204;241;242;314;319;321;348;243;244;245;246;247;176;177;178;186;248;185;249;237;250;251;252;253;326]);
  ([282;277;104;99;272],[0;1;2;3;4;5;6;7;8;9;10;11;282;283;284;285;286;287;288;289;290;291;292;293;294;155;156;346;50;344;345;15;51;52;16;160;349;254;298;216;108;218;219;53;337;191;118;152;157;158;296;330;300;234;35;161;162;163;164;165;166;250;251;252;253;238;181;182;174]);
  ([277;104;99;272],[0;1;2;3;4;5;6;7;8;9;10;11;282;283;284;285;286;287;288;289;290;291;292;293;294;346;350;50;344;345;15;51;52;16;160;255;112;217;256;257;254;53;337;191;32;298;33;157;158;330;118;152;234;35;310;17;119;326]);
  ([39;112;266;104],[0;1;2;3;4;5;6;7;8;9;10;11;282;283;284;285;286;287;288;289;290;291;292;293;294;13;310;17;326;16;50;258;314;319;348;239;259;260;122;322;36;30;26;27;261;31;28;29;118;152;119;262;263;264;265;266]);
  ([270;112;266;276;104],[0;1;2;3;4;5;6;7;8;9;10;11;282;283;284;285;286;287;288;289;290;291;292;293;294;118;152;119;13;310;17;352;16;12;302;50;316;297;267;266;268;269;270;271;319;321;348;19;272;153;140;176;273;29;274;275;276;277;328;278;279;280;22;317;318]);
  ([112;266;276;104],[0;1;2;3;4;5;6;7;8;9;10;11;282;283;284;285;286;287;288;289;290;291;292;293;294;13;310;17;352;353;16;12;302;50;319;321;348;19;323;30;191;324;22;21;24;25;325;28;29;26;27;31]);
  ([271;104;99;272],[0;1;2;3;4;5;6;7;8;9;10;11;282;283;284;285;286;287;288;289;290;291;292;293;294;50;345;351;15;51;52;12;309;302;16;160;354;298;190;281;203;148;155;156;296;307;157;158;305;53;341;337;191;308;81;83])
] : list (list nat * list nat)) as records.
assert (Hcheck :
  check_selected_microblock (c12_k7_low3_instance [true; false; true; false; false; false; false; false; true; false; false; false]) base_ids
    imported records c12_k7_low3_mask07_block10_output = true).
{ vm_compute. reflexivity. }
exact (check_selected_microblock_sound
  (c12_k7_low3_instance [true; false; true; false; false; false; false; false; true; false; false; false]) base_ids imported records c12_k7_low3_mask07_block10_output
  Hcheck rho Hbase Himported).
Qed.
