(** Generated by [scripts/generate_ckpath_certificates.py].
    Only the block output is transparent.  Selected base clauses,
    producer imports, replay records, and the transient database
    all remain underneath the opaque soundness theorem. *)

From Stdlib Require Import List.
From Digraph Require Import ckpath_cnf ckpath_drup_microblock ckpath_cert_k7_c12_low3_reduction ckpath_cert_k7_c12_low3_mask06_block00 ckpath_cert_k7_c12_low3_mask06_block02 ckpath_cert_k7_c12_low3_mask06_block03 ckpath_cert_k7_c12_low3_mask06_block04 ckpath_cert_k7_c12_low3_mask06_block05 ckpath_cert_k7_c12_low3_mask06_block06 ckpath_cert_k7_c12_low3_mask06_block07 ckpath_cert_k7_c12_low3_mask06_block08 ckpath_cert_k7_c12_low3_mask06_block10 ckpath_cert_k7_c12_low3_mask06_block12 ckpath_cert_k7_c12_low3_mask06_block13 ckpath_cert_k7_c12_low3_mask06_block14 ckpath_cert_k7_c12_low3_mask06_block16 ckpath_cert_k7_c12_low3_mask06_block17.
Import ListNotations.
Set Warnings "-abstract-large-number".

(** Original retained additions [450, 475); 69 selected base clauses and 48 imported consequences from 14 producer blocks. *)
Definition c12_k7_low3_mask06_block18_output : cnf :=
  [
  [(146,false)];
  [(124,false)];
  [(29,false)];
  [(154,false)];
  [(155,false)];
  [(114,true)];
  [(111,false)];
  [(78,false)];
  [(43,false)];
  [(118,false)];
  [(113,true)];
  [(32,false)];
  [(115,true)];
  [(117,true)];
  [(116,true)];
  [(119,true)];
  [(15,false)];
  [(18,false)];
  [(54,false)];
  [(40,false)];
  [(88,false)];
  [(57,true)];
  [(99,false)];
  [(66,false)];
  [(110,false)]
].

Theorem c12_k7_low3_mask06_block18_sound :
  forall rho, satisfies_cnf rho (c12_k7_low3_instance [true; false; false; true; false; false; true; false; false; false; false; false]) ->
    satisfies_cnf rho c12_k7_low3_mask06_block18_output.
Proof.
intros rho Hbase.
pose (select_cnf c12_k7_low3_mask06_block00_output [0;1;2;3;4;5;6;7;8;9;10;11;24] : cnf)
  as imported_from_block00.
assert (Himported_from_block00 :
  satisfies_cnf rho imported_from_block00).
{
  unfold imported_from_block00.
  apply (satisfies_cnf_select rho c12_k7_low3_mask06_block00_output [0;1;2;3;4;5;6;7;8;9;10;11;24]).
  - exact (c12_k7_low3_mask06_block00_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask06_block02_output [21] : cnf)
  as imported_from_block02.
assert (Himported_from_block02 :
  satisfies_cnf rho imported_from_block02).
{
  unfold imported_from_block02.
  apply (satisfies_cnf_select rho c12_k7_low3_mask06_block02_output [21]).
  - exact (c12_k7_low3_mask06_block02_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask06_block03_output [1] : cnf)
  as imported_from_block03.
assert (Himported_from_block03 :
  satisfies_cnf rho imported_from_block03).
{
  unfold imported_from_block03.
  apply (satisfies_cnf_select rho c12_k7_low3_mask06_block03_output [1]).
  - exact (c12_k7_low3_mask06_block03_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask06_block04_output [14;19] : cnf)
  as imported_from_block04.
assert (Himported_from_block04 :
  satisfies_cnf rho imported_from_block04).
{
  unfold imported_from_block04.
  apply (satisfies_cnf_select rho c12_k7_low3_mask06_block04_output [14;19]).
  - exact (c12_k7_low3_mask06_block04_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask06_block05_output [3;19;18;11] : cnf)
  as imported_from_block05.
assert (Himported_from_block05 :
  satisfies_cnf rho imported_from_block05).
{
  unfold imported_from_block05.
  apply (satisfies_cnf_select rho c12_k7_low3_mask06_block05_output [3;19;18;11]).
  - exact (c12_k7_low3_mask06_block05_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask06_block06_output [15;9;2;18] : cnf)
  as imported_from_block06.
assert (Himported_from_block06 :
  satisfies_cnf rho imported_from_block06).
{
  unfold imported_from_block06.
  apply (satisfies_cnf_select rho c12_k7_low3_mask06_block06_output [15;9;2;18]).
  - exact (c12_k7_low3_mask06_block06_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask06_block07_output [23] : cnf)
  as imported_from_block07.
assert (Himported_from_block07 :
  satisfies_cnf rho imported_from_block07).
{
  unfold imported_from_block07.
  apply (satisfies_cnf_select rho c12_k7_low3_mask06_block07_output [23]).
  - exact (c12_k7_low3_mask06_block07_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask06_block08_output [16;11;6] : cnf)
  as imported_from_block08.
assert (Himported_from_block08 :
  satisfies_cnf rho imported_from_block08).
{
  unfold imported_from_block08.
  apply (satisfies_cnf_select rho c12_k7_low3_mask06_block08_output [16;11;6]).
  - exact (c12_k7_low3_mask06_block08_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask06_block10_output [2] : cnf)
  as imported_from_block10.
assert (Himported_from_block10 :
  satisfies_cnf rho imported_from_block10).
{
  unfold imported_from_block10.
  apply (satisfies_cnf_select rho c12_k7_low3_mask06_block10_output [2]).
  - exact (c12_k7_low3_mask06_block10_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask06_block12_output [10] : cnf)
  as imported_from_block12.
assert (Himported_from_block12 :
  satisfies_cnf rho imported_from_block12).
{
  unfold imported_from_block12.
  apply (satisfies_cnf_select rho c12_k7_low3_mask06_block12_output [10]).
  - exact (c12_k7_low3_mask06_block12_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask06_block13_output [7] : cnf)
  as imported_from_block13.
assert (Himported_from_block13 :
  satisfies_cnf rho imported_from_block13).
{
  unfold imported_from_block13.
  apply (satisfies_cnf_select rho c12_k7_low3_mask06_block13_output [7]).
  - exact (c12_k7_low3_mask06_block13_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask06_block14_output [12] : cnf)
  as imported_from_block14.
assert (Himported_from_block14 :
  satisfies_cnf rho imported_from_block14).
{
  unfold imported_from_block14.
  apply (satisfies_cnf_select rho c12_k7_low3_mask06_block14_output [12]).
  - exact (c12_k7_low3_mask06_block14_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask06_block16_output [15;23;24] : cnf)
  as imported_from_block16.
assert (Himported_from_block16 :
  satisfies_cnf rho imported_from_block16).
{
  unfold imported_from_block16.
  apply (satisfies_cnf_select rho c12_k7_low3_mask06_block16_output [15;23;24]).
  - exact (c12_k7_low3_mask06_block16_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask06_block17_output [13;14;15;16;17;18;19;20;21;22;23;24] : cnf)
  as imported_from_block17.
assert (Himported_from_block17 :
  satisfies_cnf rho imported_from_block17).
{
  unfold imported_from_block17.
  apply (satisfies_cnf_select rho c12_k7_low3_mask06_block17_output [13;14;15;16;17;18;19;20;21;22;23;24]).
  - exact (c12_k7_low3_mask06_block17_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (concat [imported_from_block00;imported_from_block02;imported_from_block03;imported_from_block04;imported_from_block05;imported_from_block06;imported_from_block07;imported_from_block08;imported_from_block10;imported_from_block12;imported_from_block13;imported_from_block14;imported_from_block16;imported_from_block17] : cnf) as imported.
assert (Himported : satisfies_cnf rho imported).
{
  unfold imported.
  apply satisfies_cnf_concat_intro.
  constructor.
  { exact Himported_from_block00. }
  constructor.
  { exact Himported_from_block02. }
  constructor.
  { exact Himported_from_block03. }
  constructor.
  { exact Himported_from_block04. }
  constructor.
  { exact Himported_from_block05. }
  constructor.
  { exact Himported_from_block06. }
  constructor.
  { exact Himported_from_block07. }
  constructor.
  { exact Himported_from_block08. }
  constructor.
  { exact Himported_from_block10. }
  constructor.
  { exact Himported_from_block12. }
  constructor.
  { exact Himported_from_block13. }
  constructor.
  { exact Himported_from_block14. }
  constructor.
  { exact Himported_from_block16. }
  constructor.
  { exact Himported_from_block17. }
  constructor.
}
pose (
  [66;67;68;69;70;71;72;73;74;75;76;77;4152;29;2529;1808;25;4158;4159;9;2521;1088;1803;6;1082;1788;2497;36;2505;2513;2496;2577;2593;2587;2596;2597;3520;3521;28;3532;3536;3535;3533;3537;13;1048;2535;1796;1805;16;2516;1051;2508;2499;2523;43;33;2501;2510;2518;2525;59;1787;62;1793;50;1780;64;1798] : list nat) as base_ids.
pose ([
  ([290],[0;1;2;3;4;5;6;7;8;9;10;11;69;70;71;72;73;74;75;76;77;78;79;80;82;99;102;103;104;105;106;107;108;109;110;111;112;113;114;115;116;12]);
  ([246],[0;1;2;3;4;5;6;7;8;9;10;11;69;70;71;72;73;74;75;76;77;78;79;80;82;99;102;103;104;105;106;107;108;109;110;111;112;113;114;115;116;117;13;14;15;90]);
  ([56],[0;1;2;3;4;5;6;7;8;9;10;11;69;70;71;72;73;74;75;76;77;78;79;80;82;99;102;103;104;105;106;107;108;109;110;111;112;113;114;115;116;117;118;16;95]);
  ([306],[0;1;2;3;4;5;6;7;8;9;10;11;69;70;71;72;73;74;75;76;77;78;79;80;82;99;102;103;104;105;106;107;108;109;110;111;112;113;114;115;116;117;118;119;17]);
  ([308],[0;1;2;3;4;5;6;7;8;9;10;11;69;70;71;72;73;74;75;76;77;78;79;80;82;99;102;103;104;105;106;107;108;109;110;111;112;113;114;115;116;117;118;119;120;18]);
  ([227],[0;1;2;3;4;5;6;7;8;9;10;11;69;70;71;72;73;74;75;76;77;78;79;80;82;99;102;103;104;105;106;107;108;109;110;111;112;113;114;115;116;117;118;119;120;121;98]);
  ([220],[0;1;2;3;4;5;6;7;8;9;10;11;69;70;71;72;73;74;75;76;77;78;79;80;82;99;102;103;104;105;106;107;108;109;110;111;112;113;114;115;116;117;118;119;120;121;122;19;20;21;22;94;96;86]);
  ([154],[0;1;2;3;4;5;6;7;8;9;10;11;69;70;71;72;73;74;75;76;77;78;79;80;82;99;102;103;104;105;106;107;108;109;110;111;112;113;114;115;116;117;118;119;120;121;122;123;23;24;25;26;84]);
  ([84],[0;1;2;3;4;5;6;7;8;9;10;11;69;70;71;72;73;74;75;76;77;78;79;80;82;99;102;103;104;105;106;107;108;109;110;111;112;113;114;115;116;117;118;119;120;121;122;123;124;27]);
  ([234],[0;1;2;3;4;5;6;7;8;9;10;11;69;70;71;72;73;74;75;76;77;78;79;80;82;99;102;103;104;105;106;107;108;109;110;111;112;113;114;115;116;117;118;119;120;121;122;123;124;125;28;29;30;31;32;33;87;88;91;97;34;35]);
  ([225],[0;1;2;3;4;5;6;7;8;9;10;11;69;70;71;72;73;74;75;76;77;78;79;80;82;99;102;103;104;105;106;107;108;109;110;111;112;113;114;115;116;117;118;119;120;121;122;123;124;125;126;36;37]);
  ([62],[0;1;2;3;4;5;6;7;8;9;10;11;69;70;71;72;73;74;75;76;77;78;79;80;82;99;102;103;104;105;106;107;108;109;110;111;112;113;114;115;116;117;118;119;120;121;122;123;124;125;126;127;38]);
  ([229],[0;1;2;3;4;5;6;7;8;9;10;11;69;70;71;72;73;74;75;76;77;78;79;80;82;99;102;103;104;105;106;107;108;109;110;111;112;113;114;115;116;117;118;119;120;121;122;123;124;125;126;127;128;101;92;89]);
  ([233],[0;1;2;3;4;5;6;7;8;9;10;11;69;70;71;72;73;74;75;76;77;78;79;80;82;99;102;103;104;105;106;107;108;109;110;111;112;113;114;115;116;117;118;119;120;121;122;123;124;125;126;127;128;129;100;39;40;41]);
  ([231],[0;1;2;3;4;5;6;7;8;9;10;11;69;70;71;72;73;74;75;76;77;78;79;80;82;99;102;103;104;105;106;107;108;109;110;111;112;113;114;115;116;117;118;119;120;121;122;123;124;125;126;127;128;129;130;42]);
  ([237],[0;1;2;3;4;5;6;7;8;9;10;11;69;70;71;72;73;74;75;76;77;78;79;80;82;99;102;103;104;105;106;107;108;109;110;111;112;113;114;115;116;117;118;119;120;121;122;123;124;125;126;127;128;129;130;131;43]);
  ([28],[0;1;2;3;4;5;6;7;8;9;10;11;69;70;71;72;73;74;75;76;77;78;79;80;82;99;102;103;104;105;106;107;108;109;110;111;112;113;114;115;116;117;118;119;120;121;122;123;124;125;126;127;128;129;130;131;132;44;45;46;47;48]);
  ([34],[0;1;2;3;4;5;6;7;8;9;10;11;69;70;71;72;73;74;75;76;77;78;79;80;82;99;102;103;104;105;106;107;108;109;110;111;112;113;114;115;116;117;118;119;120;121;122;123;124;125;126;127;128;129;130;131;132;133;49;50;51;52;53;81;54]);
  ([106],[0;1;2;3;4;5;6;7;8;9;10;11;69;70;71;72;73;74;75;76;77;78;79;80;82;99;102;103;104;105;106;107;108;109;110;111;112;113;114;115;116;117;118;119;120;121;122;123;124;125;126;127;128;129;130;131;132;133;134;55]);
  ([78],[0;1;2;3;4;5;6;7;8;9;10;11;69;70;71;72;73;74;75;76;77;78;79;80;82;99;102;103;104;105;106;107;108;109;110;111;112;113;114;115;116;117;118;119;120;121;122;123;124;125;126;127;128;129;130;131;132;133;134;135;56;57;58;59;60]);
  ([174],[0;1;2;3;4;5;6;7;8;9;10;11;69;70;71;72;73;74;75;76;77;78;79;80;82;99;102;103;104;105;106;107;108;109;110;111;112;113;114;115;116;117;118;119;120;121;122;123;124;125;126;127;128;129;130;131;132;133;134;135;136;61;62]);
  ([113],[0;1;2;3;4;5;6;7;8;9;10;11;69;70;71;72;73;74;75;76;77;78;79;80;82;99;102;103;104;105;106;107;108;109;110;111;112;113;114;115;116;117;118;119;120;121;122;123;124;125;126;127;128;129;130;131;132;133;134;135;136;137;85;93;83]);
  ([196],[0;1;2;3;4;5;6;7;8;9;10;11;69;70;71;72;73;74;75;76;77;78;79;80;82;99;102;103;104;105;106;107;108;109;110;111;112;113;114;115;116;117;118;119;120;121;122;123;124;125;126;127;128;129;130;131;132;133;134;135;136;137;138;63;64]);
  ([130],[0;1;2;3;4;5;6;7;8;9;10;11;69;70;71;72;73;74;75;76;77;78;79;80;82;99;102;103;104;105;106;107;108;109;110;111;112;113;114;115;116;117;118;119;120;121;122;123;124;125;126;127;128;129;130;131;132;133;134;135;136;137;138;139;65;66]);
  ([218],[0;1;2;3;4;5;6;7;8;9;10;11;69;70;71;72;73;74;75;76;77;78;79;80;82;99;102;103;104;105;106;107;108;109;110;111;112;113;114;115;116;117;118;119;120;121;122;123;124;125;126;127;128;129;130;131;132;133;134;135;136;137;138;139;140;67;68])
] : list (list nat * list nat)) as records.
assert (Hcheck :
  check_selected_microblock (c12_k7_low3_instance [true; false; false; true; false; false; true; false; false; false; false; false]) base_ids
    imported records c12_k7_low3_mask06_block18_output = true).
{ vm_compute. reflexivity. }
exact (check_selected_microblock_sound
  (c12_k7_low3_instance [true; false; false; true; false; false; true; false; false; false; false; false]) base_ids imported records c12_k7_low3_mask06_block18_output
  Hcheck rho Hbase Himported).
Qed.
