(** Generated by [scripts/generate_ckpath_certificates.py].
    Only the block output is transparent.  Selected base clauses,
    producer imports, replay records, and the transient database
    all remain underneath the opaque soundness theorem. *)

From Stdlib Require Import List.
From Digraph Require Import ckpath_cnf ckpath_drup_microblock ckpath_cert_k7_base ckpath_cert_k7_c12_cover4_micro_block003 ckpath_cert_k7_c12_cover4_micro_block004 ckpath_cert_k7_c12_cover4_micro_block005 ckpath_cert_k7_c12_cover4_micro_block006 ckpath_cert_k7_c12_cover4_micro_block007 ckpath_cert_k7_c12_cover4_micro_block008 ckpath_cert_k7_c12_cover4_micro_block009 ckpath_cert_k7_c12_cover4_micro_block010 ckpath_cert_k7_c12_cover4_micro_block011 ckpath_cert_k7_c12_cover4_micro_block013 ckpath_cert_k7_c12_cover4_micro_block017 ckpath_cert_k7_c12_cover4_micro_block018 ckpath_cert_k7_c12_cover4_micro_block019 ckpath_cert_k7_c12_cover4_micro_block032 ckpath_cert_k7_c12_cover4_micro_block033 ckpath_cert_k7_c12_cover4_micro_block037 ckpath_cert_k7_c12_cover4_micro_block038 ckpath_cert_k7_c12_cover4_micro_block040 ckpath_cert_k7_c12_cover4_micro_block041 ckpath_cert_k7_c12_cover4_micro_block042.
Import ListNotations.
Set Warnings "-abstract-large-number".

(** Original retained additions [1075, 1100); 70 selected base clauses and 70 imported consequences from 20 producer blocks. *)
Definition c12_k7_cover4_micro_block043_output : cnf :=
  [
  [(150,false);(154,false);(152,false);(155,false);(156,false)];
  [(150,false);(154,false);(153,false);(155,false);(156,false)];
  [(153,false);(151,false);(152,false);(154,false);(155,false)];
  [(153,false);(151,false);(152,false);(154,false);(156,false)];
  [(153,false);(151,false);(152,false);(155,false);(156,false)];
  [(151,false);(154,false);(152,false);(155,false);(156,false)];
  [(151,false);(154,false);(153,false);(155,false);(156,false)];
  [(152,false);(154,false);(153,false);(155,false);(156,false)];
  [(89,false);(134,true);(144,true);(139,true);(142,true);(143,true);(154,true);(140,false);(136,false)];
  [(144,true);(89,false);(139,true);(142,true);(143,true);(154,true);(140,false);(136,false)];
  [(76,true);(98,true);(139,true);(148,true);(144,false);(30,true);(26,true);(99,true);(141,true);(140,false)];
  [(99,true);(154,true);(136,false);(135,false);(98,true);(139,false)];
  [(137,true);(99,false);(136,true);(140,true);(142,true);(143,true);(154,true);(134,false);(139,false)];
  [(99,false);(136,true);(140,true);(142,true);(143,true);(137,true);(154,true);(139,false);(135,false)];
  [(144,true);(134,true);(154,true);(137,false);(143,true);(139,false);(26,true);(136,true);(140,true);(142,true)];
  [(139,false);(134,true);(136,true);(26,true);(152,false);(154,true);(137,false);(142,true);(143,true);(140,true)];
  [(144,true);(134,true);(139,false);(154,true);(135,false);(98,true);(136,true);(140,true);(142,true);(143,true)];
  [(99,false);(136,true);(140,true);(142,true);(143,true);(154,true);(139,false);(135,false)];
  [(135,false);(134,false);(152,false);(139,false);(143,true);(136,true);(154,true);(142,true)];
  [(144,false);(91,true);(143,true);(135,false);(136,true);(152,false);(139,false);(154,true);(99,true);(98,true)];
  [(99,false);(136,true);(140,true);(142,true);(143,true);(154,true);(134,false);(139,false)];
  [(144,true);(77,false);(140,true);(141,true);(142,true);(143,true);(152,true);(137,false);(136,false)];
  [(152,true);(77,false);(141,true);(142,true);(143,true);(135,false);(136,false);(140,true)];
  [(144,true);(76,false);(140,true);(141,true);(142,true);(143,true);(152,true);(137,false);(136,false)];
  [(77,false);(140,true);(141,true);(142,true);(143,true);(152,true);(137,false);(136,false)]
].

Theorem c12_k7_cover4_micro_block043_sound :
  forall rho, satisfies_cnf rho ((c12_k7_cover_base 4)) ->
    satisfies_cnf rho c12_k7_cover4_micro_block043_output.
Proof.
intros rho Hbase.
pose (select_cnf c12_k7_cover4_micro_block003_output [11;4;24] : cnf)
  as imported_from_block003.
assert (Himported_from_block003 :
  satisfies_cnf rho imported_from_block003).
{
  unfold imported_from_block003.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block003_output [11;4;24]).
  - exact (c12_k7_cover4_micro_block003_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block004_output [3;7;9;1;5;8] : cnf)
  as imported_from_block004.
assert (Himported_from_block004 :
  satisfies_cnf rho imported_from_block004).
{
  unfold imported_from_block004.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block004_output [3;7;9;1;5;8]).
  - exact (c12_k7_cover4_micro_block004_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block005_output [23;24] : cnf)
  as imported_from_block005.
assert (Himported_from_block005 :
  satisfies_cnf rho imported_from_block005).
{
  unfold imported_from_block005.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block005_output [23;24]).
  - exact (c12_k7_cover4_micro_block005_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block006_output [19;3;4] : cnf)
  as imported_from_block006.
assert (Himported_from_block006 :
  satisfies_cnf rho imported_from_block006).
{
  unfold imported_from_block006.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block006_output [19;3;4]).
  - exact (c12_k7_cover4_micro_block006_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block007_output [12;18;24;17;13;15;9;20;22] : cnf)
  as imported_from_block007.
assert (Himported_from_block007 :
  satisfies_cnf rho imported_from_block007).
{
  unfold imported_from_block007.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block007_output [12;18;24;17;13;15;9;20;22]).
  - exact (c12_k7_cover4_micro_block007_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block008_output [1;3] : cnf)
  as imported_from_block008.
assert (Himported_from_block008 :
  satisfies_cnf rho imported_from_block008).
{
  unfold imported_from_block008.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block008_output [1;3]).
  - exact (c12_k7_cover4_micro_block008_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block009_output [8;9] : cnf)
  as imported_from_block009.
assert (Himported_from_block009 :
  satisfies_cnf rho imported_from_block009).
{
  unfold imported_from_block009.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block009_output [8;9]).
  - exact (c12_k7_cover4_micro_block009_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block010_output [23;5;3;21] : cnf)
  as imported_from_block010.
assert (Himported_from_block010 :
  satisfies_cnf rho imported_from_block010).
{
  unfold imported_from_block010.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block010_output [23;5;3;21]).
  - exact (c12_k7_cover4_micro_block010_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block011_output [16;17] : cnf)
  as imported_from_block011.
assert (Himported_from_block011 :
  satisfies_cnf rho imported_from_block011).
{
  unfold imported_from_block011.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block011_output [16;17]).
  - exact (c12_k7_cover4_micro_block011_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block013_output [5] : cnf)
  as imported_from_block013.
assert (Himported_from_block013 :
  satisfies_cnf rho imported_from_block013).
{
  unfold imported_from_block013.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block013_output [5]).
  - exact (c12_k7_cover4_micro_block013_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block017_output [9] : cnf)
  as imported_from_block017.
assert (Himported_from_block017 :
  satisfies_cnf rho imported_from_block017).
{
  unfold imported_from_block017.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block017_output [9]).
  - exact (c12_k7_cover4_micro_block017_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block018_output [9] : cnf)
  as imported_from_block018.
assert (Himported_from_block018 :
  satisfies_cnf rho imported_from_block018).
{
  unfold imported_from_block018.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block018_output [9]).
  - exact (c12_k7_cover4_micro_block018_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block019_output [16;18] : cnf)
  as imported_from_block019.
assert (Himported_from_block019 :
  satisfies_cnf rho imported_from_block019).
{
  unfold imported_from_block019.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block019_output [16;18]).
  - exact (c12_k7_cover4_micro_block019_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block032_output [13;18;17;20] : cnf)
  as imported_from_block032.
assert (Himported_from_block032 :
  satisfies_cnf rho imported_from_block032).
{
  unfold imported_from_block032.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block032_output [13;18;17;20]).
  - exact (c12_k7_cover4_micro_block032_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block033_output [5;1] : cnf)
  as imported_from_block033.
assert (Himported_from_block033 :
  satisfies_cnf rho imported_from_block033).
{
  unfold imported_from_block033.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block033_output [5;1]).
  - exact (c12_k7_cover4_micro_block033_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block037_output [11;14;23;17;20] : cnf)
  as imported_from_block037.
assert (Himported_from_block037 :
  satisfies_cnf rho imported_from_block037).
{
  unfold imported_from_block037.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block037_output [11;14;23;17;20]).
  - exact (c12_k7_cover4_micro_block037_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block038_output [4;1;5] : cnf)
  as imported_from_block038.
assert (Himported_from_block038 :
  satisfies_cnf rho imported_from_block038).
{
  unfold imported_from_block038.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block038_output [4;1;5]).
  - exact (c12_k7_cover4_micro_block038_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block040_output [6;8;12;13;15;18;24] : cnf)
  as imported_from_block040.
assert (Himported_from_block040 :
  satisfies_cnf rho imported_from_block040).
{
  unfold imported_from_block040.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block040_output [6;8;12;13;15;18;24]).
  - exact (c12_k7_cover4_micro_block040_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block041_output [16;23;22] : cnf)
  as imported_from_block041.
assert (Himported_from_block041 :
  satisfies_cnf rho imported_from_block041).
{
  unfold imported_from_block041.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block041_output [16;23;22]).
  - exact (c12_k7_cover4_micro_block041_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block042_output [24;16;11;19;23;13;21;10] : cnf)
  as imported_from_block042.
assert (Himported_from_block042 :
  satisfies_cnf rho imported_from_block042).
{
  unfold imported_from_block042.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block042_output [24;16;11;19;23;13;21;10]).
  - exact (c12_k7_cover4_micro_block042_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (concat [imported_from_block003;imported_from_block004;imported_from_block005;imported_from_block006;imported_from_block007;imported_from_block008;imported_from_block009;imported_from_block010;imported_from_block011;imported_from_block013;imported_from_block017;imported_from_block018;imported_from_block019;imported_from_block032;imported_from_block033;imported_from_block037;imported_from_block038;imported_from_block040;imported_from_block041;imported_from_block042] : cnf) as imported.
assert (Himported : satisfies_cnf rho imported).
{
  unfold imported.
  apply satisfies_cnf_concat_intro.
  constructor.
  { exact Himported_from_block003. }
  constructor.
  { exact Himported_from_block004. }
  constructor.
  { exact Himported_from_block005. }
  constructor.
  { exact Himported_from_block006. }
  constructor.
  { exact Himported_from_block007. }
  constructor.
  { exact Himported_from_block008. }
  constructor.
  { exact Himported_from_block009. }
  constructor.
  { exact Himported_from_block010. }
  constructor.
  { exact Himported_from_block011. }
  constructor.
  { exact Himported_from_block013. }
  constructor.
  { exact Himported_from_block017. }
  constructor.
  { exact Himported_from_block018. }
  constructor.
  { exact Himported_from_block019. }
  constructor.
  { exact Himported_from_block032. }
  constructor.
  { exact Himported_from_block033. }
  constructor.
  { exact Himported_from_block037. }
  constructor.
  { exact Himported_from_block038. }
  constructor.
  { exact Himported_from_block040. }
  constructor.
  { exact Himported_from_block041. }
  constructor.
  { exact Himported_from_block042. }
  constructor.
}
pose (
  [66;67;68;69;70;71;72;73;74;75;76;77;2014;1796;0;11;21;30;38;45;51;56;60;63;65;10;2015;1797;2013;1798;1980;2007;1799;1800;1801;1802;1803;7;4431;2619;2277;5337;5608;2921;434;3827;4086;435;433;300;425;62;2312;2907;4085;3223;3498;2317;313;319;320;471;485;2610;55;2896;3190;2305;54;3483] : list nat) as base_ids.
pose ([
  ([298;306;302;308;310],[0;1;2;3;4;5;6;7;8;9;10;11;12;132;129;133;122;112;114;13;14;15;16;17;18;19;20;21;22;23;24;25;26]);
  ([298;306;304;308;310],[0;1;2;3;4;5;6;7;8;9;10;11;12;134;123;108;135;140;115;27;14;15;16;17;18;19;20;21;22;23;24;25;26]);
  ([304;300;302;306;308],[0;1;2;3;4;5;6;7;8;9;10;11;12;116;109;130;28;29;30;31;14;15;16;17;18;19;20;21;22;23;24;25;26]);
  ([304;300;302;306;310],[0;1;2;3;4;5;6;7;8;9;10;11;12;117;110;131;142;124;136;32;14;15;16;17;18;19;20;21;22;23;24;25;26]);
  ([304;300;302;308;310],[0;1;2;3;4;5;6;7;8;9;10;11;12;143;125;119;137;109;130;33;14;15;16;17;18;19;20;21;22;23;24;25;26]);
  ([300;306;302;308;310],[0;1;2;3;4;5;6;7;8;9;10;11;12;144;138;118;111;139;126;34;14;15;16;17;18;19;20;21;22;23;24;25;26]);
  ([300;306;304;308;310],[0;1;2;3;4;5;6;7;8;9;10;11;12;138;120;113;145;134;127;35;14;15;16;17;18;19;20;21;22;23;24;25;26]);
  ([302;306;304;308;310],[0;1;2;3;4;5;6;7;8;9;10;11;12;139;140;112;121;145;128;36;14;15;16;17;18;19;20;21;22;23;24;25;26]);
  ([176;267;287;277;283;285;307;278;270],[0;1;2;3;4;5;6;7;8;9;10;11;12;37;97;98;38;99]);
  ([287;176;277;283;285;307;278;270],[0;1;2;3;4;5;6;7;8;9;10;11;12;100;97;37;148]);
  ([151;195;277;295;286;59;51;197;281;278],[0;1;2;3;4;5;6;7;8;9;10;11;12;39;101;40;41;42;102]);
  ([197;307;270;268;195;276],[0;1;2;3;4;5;6;7;8;9;10;11;12;84;95;38;43;39;44;45;46;47;104;48;49;50;96]);
  ([273;196;271;279;283;285;307;266;276],[0;1;2;3;4;5;6;7;8;9;10;11;12;51;52;81;85]);
  ([196;271;279;283;285;273;307;276;268],[0;1;2;3;4;5;6;7;8;9;10;11;12;51;52;85;53;54;86]);
  ([287;267;307;272;285;276;51;271;279;283],[0;1;2;3;4;5;6;7;8;9;10;11;12;38;55;70;87;79]);
  ([276;267;271;51;302;307;272;283;285;279],[0;1;2;3;4;5;6;7;8;9;10;11;12;88;154;82]);
  ([287;267;276;307;268;195;271;279;283;285],[0;1;2;3;4;5;6;7;8;9;10;11;12;45;38;39;87;93]);
  ([196;271;279;283;285;307;276;268],[0;1;2;3;4;5;6;7;8;9;10;11;12;51;52;85;53;54;153;56;89;80;90;38;45;39;87]);
  ([268;266;302;276;285;271;307;283],[0;1;2;3;4;5;6;7;8;9;10;11;12;39;88;57;58;59;91;103;60;85;92]);
  ([286;181;285;268;271;302;276;307;197;195],[0;1;2;3;4;5;6;7;8;9;10;11;12;41;61;105;106;107;62;103;94]);
  ([196;271;279;283;285;307;266;276],[0;1;2;3;4;5;6;7;8;9;10;11;12;51;52;54;63;157;38;57;83;152]);
  ([287;152;279;281;283;285;303;272;270],[0;1;2;3;4;5;6;7;8;9;10;11;12;64;73;71;74]);
  ([303;152;281;283;285;268;270;279],[0;1;2;3;4;5;6;7;8;9;10;11;12;45;65;66;67;64;74;75]);
  ([287;150;279;281;283;285;303;272;270],[0;1;2;3;4;5;6;7;8;9;10;11;12;161;68;76;77]);
  ([152;279;281;283;285;303;272;270],[0;1;2;3;4;5;6;7;8;9;10;11;12;64;161;45;66;67;162;55;69;78;72])
] : list (list nat * list nat)) as records.
assert (Hcheck :
  check_selected_microblock ((c12_k7_cover_base 4)) base_ids
    imported records c12_k7_cover4_micro_block043_output = true).
{ vm_compute. reflexivity. }
exact (check_selected_microblock_sound
  ((c12_k7_cover_base 4)) base_ids imported records c12_k7_cover4_micro_block043_output
  Hcheck rho Hbase Himported).
Qed.
