(** Generated by [scripts/generate_ckpath_certificates.py].
    Only the block output is transparent.  Selected base clauses,
    producer imports, replay records, and the transient database
    all remain underneath the opaque soundness theorem. *)

From Stdlib Require Import List.
From Digraph Require Import ckpath_cnf ckpath_drup_microblock ckpath_cert_k7_base ckpath_cert_k7_c12_cover4_micro_block000 ckpath_cert_k7_c12_cover4_micro_block001 ckpath_cert_k7_c12_cover4_micro_block002 ckpath_cert_k7_c12_cover4_micro_block005 ckpath_cert_k7_c12_cover4_micro_block008 ckpath_cert_k7_c12_cover4_micro_block019 ckpath_cert_k7_c12_cover4_micro_block021 ckpath_cert_k7_c12_cover4_micro_block023 ckpath_cert_k7_c12_cover4_micro_block024 ckpath_cert_k7_c12_cover4_micro_block025 ckpath_cert_k7_c12_cover4_micro_block027 ckpath_cert_k7_c12_cover4_micro_block028 ckpath_cert_k7_c12_cover4_micro_block029 ckpath_cert_k7_c12_cover4_micro_block030 ckpath_cert_k7_c12_cover4_micro_block031 ckpath_cert_k7_c12_cover4_micro_block032 ckpath_cert_k7_c12_cover4_micro_block033 ckpath_cert_k7_c12_cover4_micro_block034 ckpath_cert_k7_c12_cover4_micro_block035 ckpath_cert_k7_c12_cover4_micro_block036 ckpath_cert_k7_c12_cover4_micro_block037 ckpath_cert_k7_c12_cover4_micro_block038 ckpath_cert_k7_c12_cover4_micro_block039 ckpath_cert_k7_c12_cover4_micro_block040 ckpath_cert_k7_c12_cover4_micro_block041 ckpath_cert_k7_c12_cover4_micro_block042 ckpath_cert_k7_c12_cover4_micro_block044 ckpath_cert_k7_c12_cover4_micro_block045 ckpath_cert_k7_c12_cover4_micro_block048 ckpath_cert_k7_c12_cover4_micro_block049 ckpath_cert_k7_c12_cover4_micro_block050 ckpath_cert_k7_c12_cover4_micro_block051 ckpath_cert_k7_c12_cover4_micro_block052 ckpath_cert_k7_c12_cover4_micro_block053 ckpath_cert_k7_c12_cover4_micro_block054 ckpath_cert_k7_c12_cover4_micro_block059 ckpath_cert_k7_c12_cover4_micro_block063 ckpath_cert_k7_c12_cover4_micro_block064.
Import ListNotations.
Set Warnings "-abstract-large-number".

(** Original retained additions [1625, 1650); 175 selected base clauses and 111 imported consequences from 38 producer blocks. *)
Definition c12_k7_cover4_micro_block065_output : cnf :=
  [
  [(140,false);(152,true);(154,true);(137,true);(136,true);(142,false);(135,false)];
  [(144,true);(152,true);(137,true);(136,true);(138,true);(142,false);(154,true)];
  [(152,true);(142,false);(137,true);(135,false);(136,true);(138,true);(154,true);(150,false)];
  [(142,false);(138,true);(136,true);(139,true);(137,true);(154,true)];
  [(153,false);(152,true);(154,true);(136,true);(137,true);(142,true);(143,false);(150,false);(148,false)];
  [(147,false);(152,true);(154,true);(136,true);(137,true);(142,true);(143,false);(150,false);(148,false)];
  [(152,true);(143,false);(136,true);(137,true);(154,true);(138,true)];
  [(143,false);(138,true);(136,true);(139,true);(137,true);(154,true)];
  [(147,false);(140,false);(154,true);(152,true);(137,true);(136,true);(142,true);(150,false);(148,false)];
  [(140,false);(152,true);(154,true);(137,true);(136,true);(138,true)];
  [(152,true);(138,true);(136,true);(137,true);(154,true)];
  [(153,false);(143,true);(136,true);(139,true);(141,true);(137,true);(138,true);(142,true);(150,false);(152,false);(148,false)];
  [(138,true);(139,true);(154,true);(137,true);(136,true)];
  [(143,false);(142,false);(138,false);(137,true);(154,true);(150,false)];
  [(140,false);(152,true);(138,false);(142,false);(137,true);(154,true);(150,false)];
  [(153,false);(134,true);(137,true);(140,true);(139,true);(141,true);(136,true);(143,true);(150,false);(155,false);(151,false)];
  [(144,false);(152,true);(138,false);(142,false);(137,true);(154,true);(150,false)];
  [(92,true);(98,true);(126,true);(138,false);(154,true);(144,true);(93,true)];
  [(89,false);(126,true);(144,true);(135,false);(154,true);(138,false)];
  [(98,true);(135,false);(154,true);(138,false);(147,true);(89,true);(93,true)];
  [(99,true);(20,true);(134,true);(135,false);(154,true);(138,false);(89,true);(93,true)];
  [(134,true);(152,true);(142,false);(137,true);(154,true);(136,true)];
  [(152,true);(142,false);(138,false);(137,true);(154,true);(150,false);(136,true)];
  [(142,false);(139,true);(137,true);(136,true);(154,true)];
  [(140,true);(134,true);(137,true);(136,true);(143,true);(152,true);(154,true)]
].

Theorem c12_k7_cover4_micro_block065_sound :
  forall rho, satisfies_cnf rho ((c12_k7_cover_base 4)) ->
    satisfies_cnf rho c12_k7_cover4_micro_block065_output.
Proof.
intros rho Hbase.
pose (select_cnf c12_k7_cover4_micro_block000_output [22] : cnf)
  as imported_from_block000.
assert (Himported_from_block000 :
  satisfies_cnf rho imported_from_block000).
{
  unfold imported_from_block000.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block000_output [22]).
  - exact (c12_k7_cover4_micro_block000_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block001_output [9;20] : cnf)
  as imported_from_block001.
assert (Himported_from_block001 :
  satisfies_cnf rho imported_from_block001).
{
  unfold imported_from_block001.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block001_output [9;20]).
  - exact (c12_k7_cover4_micro_block001_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block002_output [5;24;20;2;22;21] : cnf)
  as imported_from_block002.
assert (Himported_from_block002 :
  satisfies_cnf rho imported_from_block002).
{
  unfold imported_from_block002.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block002_output [5;24;20;2;22;21]).
  - exact (c12_k7_cover4_micro_block002_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block005_output [18] : cnf)
  as imported_from_block005.
assert (Himported_from_block005 :
  satisfies_cnf rho imported_from_block005).
{
  unfold imported_from_block005.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block005_output [18]).
  - exact (c12_k7_cover4_micro_block005_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block008_output [0;14;15] : cnf)
  as imported_from_block008.
assert (Himported_from_block008 :
  satisfies_cnf rho imported_from_block008).
{
  unfold imported_from_block008.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block008_output [0;14;15]).
  - exact (c12_k7_cover4_micro_block008_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block019_output [11;1;8] : cnf)
  as imported_from_block019.
assert (Himported_from_block019 :
  satisfies_cnf rho imported_from_block019).
{
  unfold imported_from_block019.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block019_output [11;1;8]).
  - exact (c12_k7_cover4_micro_block019_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block021_output [5;12] : cnf)
  as imported_from_block021.
assert (Himported_from_block021 :
  satisfies_cnf rho imported_from_block021).
{
  unfold imported_from_block021.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block021_output [5;12]).
  - exact (c12_k7_cover4_micro_block021_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block023_output [24] : cnf)
  as imported_from_block023.
assert (Himported_from_block023 :
  satisfies_cnf rho imported_from_block023).
{
  unfold imported_from_block023.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block023_output [24]).
  - exact (c12_k7_cover4_micro_block023_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block024_output [8;11;6;9;0] : cnf)
  as imported_from_block024.
assert (Himported_from_block024 :
  satisfies_cnf rho imported_from_block024).
{
  unfold imported_from_block024.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block024_output [8;11;6;9;0]).
  - exact (c12_k7_cover4_micro_block024_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block025_output [13;14;11] : cnf)
  as imported_from_block025.
assert (Himported_from_block025 :
  satisfies_cnf rho imported_from_block025).
{
  unfold imported_from_block025.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block025_output [13;14;11]).
  - exact (c12_k7_cover4_micro_block025_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block027_output [2] : cnf)
  as imported_from_block027.
assert (Himported_from_block027 :
  satisfies_cnf rho imported_from_block027).
{
  unfold imported_from_block027.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block027_output [2]).
  - exact (c12_k7_cover4_micro_block027_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block028_output [12;13] : cnf)
  as imported_from_block028.
assert (Himported_from_block028 :
  satisfies_cnf rho imported_from_block028).
{
  unfold imported_from_block028.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block028_output [12;13]).
  - exact (c12_k7_cover4_micro_block028_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block029_output [14;18;7;11;15;8;9;5] : cnf)
  as imported_from_block029.
assert (Himported_from_block029 :
  satisfies_cnf rho imported_from_block029).
{
  unfold imported_from_block029.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block029_output [14;18;7;11;15;8;9;5]).
  - exact (c12_k7_cover4_micro_block029_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block030_output [15] : cnf)
  as imported_from_block030.
assert (Himported_from_block030 :
  satisfies_cnf rho imported_from_block030).
{
  unfold imported_from_block030.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block030_output [15]).
  - exact (c12_k7_cover4_micro_block030_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block031_output [24] : cnf)
  as imported_from_block031.
assert (Himported_from_block031 :
  satisfies_cnf rho imported_from_block031).
{
  unfold imported_from_block031.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block031_output [24]).
  - exact (c12_k7_cover4_micro_block031_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block032_output [6;2;3] : cnf)
  as imported_from_block032.
assert (Himported_from_block032 :
  satisfies_cnf rho imported_from_block032).
{
  unfold imported_from_block032.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block032_output [6;2;3]).
  - exact (c12_k7_cover4_micro_block032_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block033_output [9] : cnf)
  as imported_from_block033.
assert (Himported_from_block033 :
  satisfies_cnf rho imported_from_block033).
{
  unfold imported_from_block033.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block033_output [9]).
  - exact (c12_k7_cover4_micro_block033_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block034_output [10;17;7;13;4;14;8;6] : cnf)
  as imported_from_block034.
assert (Himported_from_block034 :
  satisfies_cnf rho imported_from_block034).
{
  unfold imported_from_block034.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block034_output [10;17;7;13;4;14;8;6]).
  - exact (c12_k7_cover4_micro_block034_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block035_output [15] : cnf)
  as imported_from_block035.
assert (Himported_from_block035 :
  satisfies_cnf rho imported_from_block035).
{
  unfold imported_from_block035.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block035_output [15]).
  - exact (c12_k7_cover4_micro_block035_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block036_output [24] : cnf)
  as imported_from_block036.
assert (Himported_from_block036 :
  satisfies_cnf rho imported_from_block036).
{
  unfold imported_from_block036.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block036_output [24]).
  - exact (c12_k7_cover4_micro_block036_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block037_output [6;2] : cnf)
  as imported_from_block037.
assert (Himported_from_block037 :
  satisfies_cnf rho imported_from_block037).
{
  unfold imported_from_block037.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block037_output [6;2]).
  - exact (c12_k7_cover4_micro_block037_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block038_output [17;14;18;12;10] : cnf)
  as imported_from_block038.
assert (Himported_from_block038 :
  satisfies_cnf rho imported_from_block038).
{
  unfold imported_from_block038.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block038_output [17;14;18;12;10]).
  - exact (c12_k7_cover4_micro_block038_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block039_output [22;19;23;17] : cnf)
  as imported_from_block039.
assert (Himported_from_block039 :
  satisfies_cnf rho imported_from_block039).
{
  unfold imported_from_block039.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block039_output [22;19;23;17]).
  - exact (c12_k7_cover4_micro_block039_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block040_output [10;3;7;4;2;1] : cnf)
  as imported_from_block040.
assert (Himported_from_block040 :
  satisfies_cnf rho imported_from_block040).
{
  unfold imported_from_block040.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block040_output [10;3;7;4;2;1]).
  - exact (c12_k7_cover4_micro_block040_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block041_output [11;7;4] : cnf)
  as imported_from_block041.
assert (Himported_from_block041 :
  satisfies_cnf rho imported_from_block041).
{
  unfold imported_from_block041.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block041_output [11;7;4]).
  - exact (c12_k7_cover4_micro_block041_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block042_output [20;17;13;18] : cnf)
  as imported_from_block042.
assert (Himported_from_block042 :
  satisfies_cnf rho imported_from_block042).
{
  unfold imported_from_block042.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block042_output [20;17;13;18]).
  - exact (c12_k7_cover4_micro_block042_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block044_output [10] : cnf)
  as imported_from_block044.
assert (Himported_from_block044 :
  satisfies_cnf rho imported_from_block044).
{
  unfold imported_from_block044.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block044_output [10]).
  - exact (c12_k7_cover4_micro_block044_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block045_output [19] : cnf)
  as imported_from_block045.
assert (Himported_from_block045 :
  satisfies_cnf rho imported_from_block045).
{
  unfold imported_from_block045.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block045_output [19]).
  - exact (c12_k7_cover4_micro_block045_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block048_output [20;19] : cnf)
  as imported_from_block048.
assert (Himported_from_block048 :
  satisfies_cnf rho imported_from_block048).
{
  unfold imported_from_block048.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block048_output [20;19]).
  - exact (c12_k7_cover4_micro_block048_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block049_output [16;21;22] : cnf)
  as imported_from_block049.
assert (Himported_from_block049 :
  satisfies_cnf rho imported_from_block049).
{
  unfold imported_from_block049.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block049_output [16;21;22]).
  - exact (c12_k7_cover4_micro_block049_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block050_output [22] : cnf)
  as imported_from_block050.
assert (Himported_from_block050 :
  satisfies_cnf rho imported_from_block050).
{
  unfold imported_from_block050.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block050_output [22]).
  - exact (c12_k7_cover4_micro_block050_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block051_output [7;18;15;9] : cnf)
  as imported_from_block051.
assert (Himported_from_block051 :
  satisfies_cnf rho imported_from_block051).
{
  unfold imported_from_block051.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block051_output [7;18;15;9]).
  - exact (c12_k7_cover4_micro_block051_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block052_output [21;16;0] : cnf)
  as imported_from_block052.
assert (Himported_from_block052 :
  satisfies_cnf rho imported_from_block052).
{
  unfold imported_from_block052.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block052_output [21;16;0]).
  - exact (c12_k7_cover4_micro_block052_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block053_output [15;1;13;14] : cnf)
  as imported_from_block053.
assert (Himported_from_block053 :
  satisfies_cnf rho imported_from_block053).
{
  unfold imported_from_block053.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block053_output [15;1;13;14]).
  - exact (c12_k7_cover4_micro_block053_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block054_output [1;22] : cnf)
  as imported_from_block054.
assert (Himported_from_block054 :
  satisfies_cnf rho imported_from_block054).
{
  unfold imported_from_block054.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block054_output [1;22]).
  - exact (c12_k7_cover4_micro_block054_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block059_output [19;8] : cnf)
  as imported_from_block059.
assert (Himported_from_block059 :
  satisfies_cnf rho imported_from_block059).
{
  unfold imported_from_block059.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block059_output [19;8]).
  - exact (c12_k7_cover4_micro_block059_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block063_output [20;8] : cnf)
  as imported_from_block063.
assert (Himported_from_block063 :
  satisfies_cnf rho imported_from_block063).
{
  unfold imported_from_block063.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block063_output [20;8]).
  - exact (c12_k7_cover4_micro_block063_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_cover4_micro_block064_output [7;15;24;17;5;18;23;6] : cnf)
  as imported_from_block064.
assert (Himported_from_block064 :
  satisfies_cnf rho imported_from_block064).
{
  unfold imported_from_block064.
  apply (satisfies_cnf_select rho c12_k7_cover4_micro_block064_output [7;15;24;17;5;18;23;6]).
  - exact (c12_k7_cover4_micro_block064_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (concat [imported_from_block000;imported_from_block001;imported_from_block002;imported_from_block005;imported_from_block008;imported_from_block019;imported_from_block021;imported_from_block023;imported_from_block024;imported_from_block025;imported_from_block027;imported_from_block028;imported_from_block029;imported_from_block030;imported_from_block031;imported_from_block032;imported_from_block033;imported_from_block034;imported_from_block035;imported_from_block036;imported_from_block037;imported_from_block038;imported_from_block039;imported_from_block040;imported_from_block041;imported_from_block042;imported_from_block044;imported_from_block045;imported_from_block048;imported_from_block049;imported_from_block050;imported_from_block051;imported_from_block052;imported_from_block053;imported_from_block054;imported_from_block059;imported_from_block063;imported_from_block064] : cnf) as imported.
assert (Himported : satisfies_cnf rho imported).
{
  unfold imported.
  apply satisfies_cnf_concat_intro.
  constructor.
  { exact Himported_from_block000. }
  constructor.
  { exact Himported_from_block001. }
  constructor.
  { exact Himported_from_block002. }
  constructor.
  { exact Himported_from_block005. }
  constructor.
  { exact Himported_from_block008. }
  constructor.
  { exact Himported_from_block019. }
  constructor.
  { exact Himported_from_block021. }
  constructor.
  { exact Himported_from_block023. }
  constructor.
  { exact Himported_from_block024. }
  constructor.
  { exact Himported_from_block025. }
  constructor.
  { exact Himported_from_block027. }
  constructor.
  { exact Himported_from_block028. }
  constructor.
  { exact Himported_from_block029. }
  constructor.
  { exact Himported_from_block030. }
  constructor.
  { exact Himported_from_block031. }
  constructor.
  { exact Himported_from_block032. }
  constructor.
  { exact Himported_from_block033. }
  constructor.
  { exact Himported_from_block034. }
  constructor.
  { exact Himported_from_block035. }
  constructor.
  { exact Himported_from_block036. }
  constructor.
  { exact Himported_from_block037. }
  constructor.
  { exact Himported_from_block038. }
  constructor.
  { exact Himported_from_block039. }
  constructor.
  { exact Himported_from_block040. }
  constructor.
  { exact Himported_from_block041. }
  constructor.
  { exact Himported_from_block042. }
  constructor.
  { exact Himported_from_block044. }
  constructor.
  { exact Himported_from_block045. }
  constructor.
  { exact Himported_from_block048. }
  constructor.
  { exact Himported_from_block049. }
  constructor.
  { exact Himported_from_block050. }
  constructor.
  { exact Himported_from_block051. }
  constructor.
  { exact Himported_from_block052. }
  constructor.
  { exact Himported_from_block053. }
  constructor.
  { exact Himported_from_block054. }
  constructor.
  { exact Himported_from_block059. }
  constructor.
  { exact Himported_from_block063. }
  constructor.
  { exact Himported_from_block064. }
  constructor.
}
pose (
  [66;67;68;69;70;71;72;73;74;75;76;77;2014;4129;496;4431;4733;2619;325;0;11;21;30;38;45;51;56;60;63;65;10;2015;1583;3827;281;2317;1587;1576;1556;2574;31;2281;5020;3290;3228;3292;3287;3294;3283;41;3;42;40;48;5031;2298;2887;5337;332;5611;3233;3240;3237;3242;3244;39;22;44;5626;4514;4516;4445;5035;5316;3525;1557;280;1686;1716;1203;1581;283;1205;1176;1196;279;479;395;535;3826;3313;3314;3304;389;594;607;473;606;603;4425;3306;3300;260;396;4544;4470;4548;4525;4546;4505;47;3798;7;3793;2313;62;2312;3792;26;3795;52;17;3794;5434;5414;5379;2908;5360;4479;4483;4460;4481;2909;2268;2907;2910;34;3796;2429;2435;2325;2358;4480;4446;4482;4461;4471;61;2311;3791;2906;2413;3302;3297;5013;5033;5034;4998;5024;5418;5458;5383;5438;5454;5457;5046;5126;5121;5105;5115;316;1652;3284;285;258] : list nat) as base_ids.
pose ([
  ([278;303;307;273;271;282;268],[0;1;2;3;4;5;6;7;8;9;10;11;12;13;14;188;274;15;16;278;17;189;18;19;20;21;22;23;24;25;26;27;28;29;30;31;236;32;205;257;240;231;265;261]);
  ([287;303;273;271;275;282;307],[0;1;2;3;4;5;6;7;8;9;10;11;12;275;33;279;286;16;280;15;19;20;21;22;23;24;25;26;27;28;29;30;31;17;34;35;36;32;37;199;38;262;268;39;40;41;42;43;44;45;46;258;47;48;49;50;51;52;53;54;55;56;259]);
  ([303;282;273;268;271;275;307;298],[0;1;2;3;4;5;6;7;8;9;10;11;12;33;286;287;16;280;17;15;19;20;21;22;23;24;25;26;27;28;29;30;31;57;58;203;205;199;206;207;262;268;59;40;41;42;60;61;62;63;44;64;258;65;49;52;51;66;67;53;54;55;56;68;69;70;71]);
  ([282;275;271;277;273;307],[0;1;2;3;4;5;6;7;8;9;10;11;12;16;281;282;15;19;20;21;22;23;24;25;26;27;28;29;30;31;17;280;288;241;242;232;208;237;219;13;57;35;34]);
  ([304;303;307;271;273;283;284;298;294],[0;1;2;3;4;5;6;7;8;9;10;11;12;33;15;283;72;19;20;21;22;23;24;25;26;27;28;29;30;31;35;240;233;238;209;266;73;74;255;263]);
  ([292;303;307;271;273;283;284;298;294],[0;1;2;3;4;5;6;7;8;9;10;11;12;33;290;15;72;19;20;21;22;23;24;25;26;27;28;29;30;31;13;220;75;200;221;266;73;57;74;255;263]);
  ([303;284;271;273;307;275],[0;1;2;3;4;5;6;7;8;9;10;11;12;33;274;72;15;284;289;19;20;21;22;23;24;25;26;27;28;29;30;31;17;290;291;13;35;76;57;206;204;210;266;73;59;255;263]);
  ([284;275;271;277;273;307],[0;1;2;3;4;5;6;7;8;9;10;11;12;72;276;292;284;289;15;19;20;21;22;23;24;25;26;27;28;29;30;31;17;242;243;77;78;79;80;13;57;35;76]);
  ([292;278;307;303;273;271;283;298;294],[0;1;2;3;4;5;6;7;8;9;10;11;12;13;15;33;291;19;20;21;22;23;24;25;26;27;28;29;30;31;222;223;201;224;218;272;74;261;256;255]);
  ([278;303;307;273;271;275],[0;1;2;3;4;5;6;7;8;9;10;11;12;13;33;274;15;284;289;293;19;20;21;22;23;24;25;26;27;28;29;30;31;17;294;35;81;57;209;82;83;84;269;260;59;261;256;255]);
  ([303;275;271;273;307],[0;1;2;3;4;5;6;7;8;9;10;11;12;33;274;295;284;289;293;15;19;20;21;22;23;24;25;26;27;28;29;30;31;178;175;85;17;179;57;180]);
  ([304;285;271;277;281;273;275;283;298;302;294],[0;1;2;3;4;5;6;7;8;9;10;11;12;243;234;211;239;241;244;225;19;20;21;22;23;24;25;26;27;28;29;30;31;57;176;284;35;81]);
  ([275;277;307;273;271],[0;1;2;3;4;5;6;7;8;9;10;11;12;282;289;293;296;15;284;19;20;21;22;23;24;25;26;27;28;29;30;31;17;297;13;175;85;277;253]);
  ([284;282;274;273;307;298],[0;1;2;3;4;5;6;7;8;9;10;11;12;72;16;278;74;86;87;88;194;195;193;19;20;21;22;23;24;25;26;27;28;29;30;31;249;229;215;246;250;245;267;264;273;40;41;89;42;73;90;91;60;92]);
  ([278;303;274;282;273;307;298],[0;1;2;3;4;5;6;7;8;9;10;11;12;13;93;191;94;95;74;96;97;98;16;19;20;21;22;23;24;25;26;27;28;29;30;31;230;216;247;236;249;268;99;40;41;89;42;100;101]);
  ([304;267;273;279;277;281;271;285;298;308;300],[0;1;2;3;4;5;6;7;8;9;10;11;12;230;216;247;236;249;251;252;19;20;21;22;23;24;25;26;27;28;29;30;31;57;17;296;178;272;102]);
  ([286;303;274;282;273;307;298],[0;1;2;3;4;5;6;7;8;9;10;11;12;57;196;197;198;270;190;74;192;195;103;16;19;20;21;22;23;24;25;26;27;28;29;30;31;216;215;202;207;213;268;271;40;41;89;42;59;101;60]);
  ([183;195;251;274;307;287;185],[0;1;2;3;4;5;6;7;8;9;10;11;12;74;15;19;20;21;22;23;24;25;26;27;28;29;30;31;104;105;106;107;108;109;110;111;112;113;114;115;116;117;118;119;120;121;122;123;124;125]);
  ([176;251;287;268;307;274],[0;1;2;3;4;5;6;7;8;9;10;11;12;112;113;114;17;181;185;126;15;74;19;20;21;22;23;24;25;26;27;28;29;30;31;127]);
  ([195;268;307;274;293;177;185],[0;1;2;3;4;5;6;7;8;9;10;11;12;17;15;74;35;128;71;129;130;131;19;20;21;22;23;24;25;26;27;28;29;30;31;105;110;111;121;122;132;133;115;116;117;134;118;119;135;120;136;137;138;139;254;184;140;141]);
  ([197;39;267;268;307;274;177;185],[0;1;2;3;4;5;6;7;8;9;10;11;12;17;15;74;142;143;144;145;19;20;21;22;23;24;25;26;27;28;29;30;31;129;146;110;111;121;122;132;120;118;119;135;254;147;148;149;150;136;137;138;139;151;140;141]);
  ([267;303;282;273;307;271],[0;1;2;3;4;5;6;7;8;9;10;11;12;33;274;296;300;302;16;299;15;19;20;21;22;23;24;25;26;27;28;29;30;31;102;74;301;17;245;226;207;235;268;40;41;89;42;101;60;92;152;153;48;49;50;67;51;52;66;304;305;147;148;149;150;154;155;156;157;158;306;115;116;117;134;159;160;161;162;163;164;165;166;167;168;169]);
  ([303;282;274;273;307;298;271],[0;1;2;3;4;5;6;7;8;9;10;11;12;33;300;302;307;16;299;74;15;19;20;21;22;23;24;25;26;27;28;29;30;31;35;170;230;37;171;202;227;268;39;40;41;89;42;43;44;45;46;172;48]);
  ([282;277;273;271;307],[0;1;2;3;4;5;6;7;8;9;10;11;12;16;289;285;15;19;20;21;22;23;24;25;26;27;28;29;30;31;74;299;308;250;228;214;248;251;237;35;57;13;17;102]);
  ([279;267;273;271;285;303;307],[0;1;2;3;4;5;6;7;8;9;10;11;12;33;274;296;307;15;19;20;21;22;23;24;25;26;27;28;29;30;31;177;173;174;179;182;57;183;186;187;17;217;301;212])
] : list (list nat * list nat)) as records.
assert (Hcheck :
  check_selected_microblock ((c12_k7_cover_base 4)) base_ids
    imported records c12_k7_cover4_micro_block065_output = true).
{ vm_compute. reflexivity. }
exact (check_selected_microblock_sound
  ((c12_k7_cover_base 4)) base_ids imported records c12_k7_cover4_micro_block065_output
  Hcheck rho Hbase Himported).
Qed.
