(** Generated by [scripts/generate_ckpath_certificates.py].
    Only the block output is transparent.  Selected base clauses,
    producer imports, replay records, and the transient database
    all remain underneath the opaque soundness theorem. *)

From Stdlib Require Import List.
From Digraph Require Import ckpath_cnf ckpath_drup_microblock ckpath_cert_k7_c12_low3_reduction ckpath_cert_k7_c12_low3_mask04_block00 ckpath_cert_k7_c12_low3_mask04_block01 ckpath_cert_k7_c12_low3_mask04_block02 ckpath_cert_k7_c12_low3_mask04_block03 ckpath_cert_k7_c12_low3_mask04_block04 ckpath_cert_k7_c12_low3_mask04_block05 ckpath_cert_k7_c12_low3_mask04_block06 ckpath_cert_k7_c12_low3_mask04_block07 ckpath_cert_k7_c12_low3_mask04_block08 ckpath_cert_k7_c12_low3_mask04_block09 ckpath_cert_k7_c12_low3_mask04_block10 ckpath_cert_k7_c12_low3_mask04_block11.
Import ListNotations.
Set Warnings "-abstract-large-number".

(** Original retained additions [300, 325); 324 selected base clauses and 63 imported consequences from 12 producer blocks. *)
Definition c12_k7_low3_mask04_block12_output : cnf :=
  [
  [(31,true);(110,true);(27,true);(138,false);(135,false);(29,true);(142,false)];
  [(101,true);(123,true);(102,true);(110,true);(138,false);(144,false);(136,false)];
  [(140,true);(138,false);(135,false);(144,false);(136,false)];
  [(32,true);(27,true);(138,false);(135,false);(144,false);(136,false)];
  [(42,true);(64,true);(136,false);(138,false);(62,true);(144,false)];
  [(100,true);(62,true);(101,true);(102,true);(138,false);(144,false);(136,false)];
  [(100,false);(101,true);(102,true);(138,false);(144,false);(136,false)];
  [(101,true);(102,true);(138,false);(144,false);(136,false)];
  [(62,false);(101,false);(135,false);(144,false);(136,false)];
  [(101,false);(138,false);(135,false);(144,false);(136,false)];
  [(138,false);(135,false);(144,false);(136,false)];
  [(62,false);(135,false);(144,false);(136,false)];
  [(27,true);(28,true);(101,true);(140,false);(135,false);(110,true);(29,true);(142,false)];
  [(27,false);(101,true);(110,true);(137,false);(135,false);(142,false)];
  [(101,true);(135,false);(144,false);(136,false)];
  [(27,true);(123,true);(135,false);(144,false);(136,false)];
  [(27,false);(54,true);(137,false);(135,false)];
  [(135,false);(144,false);(136,false)];
  [(53,false);(141,false);(89,true);(143,false);(137,false)];
  [(138,true);(137,false);(54,true);(123,false);(135,true);(113,true)];
  [(143,false);(141,false);(137,false);(54,true);(112,true);(123,false);(113,true)];
  [(51,false);(140,false);(87,true);(78,true)];
  [(51,true);(138,false);(56,true);(137,false);(45,true);(54,true);(142,false)];
  [(137,false);(101,false);(123,false);(135,true);(136,false)];
  [(101,false);(123,false);(144,false);(136,false)]
].

Theorem c12_k7_low3_mask04_block12_sound :
  forall rho, satisfies_cnf rho (c12_k7_low3_instance [true; true; false; false; false; false; true; false; false; false; false; false]) ->
    satisfies_cnf rho c12_k7_low3_mask04_block12_output.
Proof.
intros rho Hbase.
pose (select_cnf c12_k7_low3_mask04_block00_output [0;1;2;3;4;5;6;7;8;9;10;11;19] : cnf)
  as imported_from_block00.
assert (Himported_from_block00 :
  satisfies_cnf rho imported_from_block00).
{
  unfold imported_from_block00.
  apply (satisfies_cnf_select rho c12_k7_low3_mask04_block00_output [0;1;2;3;4;5;6;7;8;9;10;11;19]).
  - exact (c12_k7_low3_mask04_block00_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask04_block01_output [0] : cnf)
  as imported_from_block01.
assert (Himported_from_block01 :
  satisfies_cnf rho imported_from_block01).
{
  unfold imported_from_block01.
  apply (satisfies_cnf_select rho c12_k7_low3_mask04_block01_output [0]).
  - exact (c12_k7_low3_mask04_block01_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask04_block02_output [12;18] : cnf)
  as imported_from_block02.
assert (Himported_from_block02 :
  satisfies_cnf rho imported_from_block02).
{
  unfold imported_from_block02.
  apply (satisfies_cnf_select rho c12_k7_low3_mask04_block02_output [12;18]).
  - exact (c12_k7_low3_mask04_block02_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask04_block03_output [5;12;8;4;16] : cnf)
  as imported_from_block03.
assert (Himported_from_block03 :
  satisfies_cnf rho imported_from_block03).
{
  unfold imported_from_block03.
  apply (satisfies_cnf_select rho c12_k7_low3_mask04_block03_output [5;12;8;4;16]).
  - exact (c12_k7_low3_mask04_block03_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask04_block04_output [21] : cnf)
  as imported_from_block04.
assert (Himported_from_block04 :
  satisfies_cnf rho imported_from_block04).
{
  unfold imported_from_block04.
  apply (satisfies_cnf_select rho c12_k7_low3_mask04_block04_output [21]).
  - exact (c12_k7_low3_mask04_block04_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask04_block05_output [11;9;10;7;1] : cnf)
  as imported_from_block05.
assert (Himported_from_block05 :
  satisfies_cnf rho imported_from_block05).
{
  unfold imported_from_block05.
  apply (satisfies_cnf_select rho c12_k7_low3_mask04_block05_output [11;9;10;7;1]).
  - exact (c12_k7_low3_mask04_block05_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask04_block06_output [0;8;12;6;7] : cnf)
  as imported_from_block06.
assert (Himported_from_block06 :
  satisfies_cnf rho imported_from_block06).
{
  unfold imported_from_block06.
  apply (satisfies_cnf_select rho c12_k7_low3_mask04_block06_output [0;8;12;6;7]).
  - exact (c12_k7_low3_mask04_block06_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask04_block07_output [11;10;16;13;20;22;14] : cnf)
  as imported_from_block07.
assert (Himported_from_block07 :
  satisfies_cnf rho imported_from_block07).
{
  unfold imported_from_block07.
  apply (satisfies_cnf_select rho c12_k7_low3_mask04_block07_output [11;10;16;13;20;22;14]).
  - exact (c12_k7_low3_mask04_block07_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask04_block08_output [14;17;4;5;3] : cnf)
  as imported_from_block08.
assert (Himported_from_block08 :
  satisfies_cnf rho imported_from_block08).
{
  unfold imported_from_block08.
  apply (satisfies_cnf_select rho c12_k7_low3_mask04_block08_output [14;17;4;5;3]).
  - exact (c12_k7_low3_mask04_block08_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask04_block09_output [19;23;18;8;12] : cnf)
  as imported_from_block09.
assert (Himported_from_block09 :
  satisfies_cnf rho imported_from_block09).
{
  unfold imported_from_block09.
  apply (satisfies_cnf_select rho c12_k7_low3_mask04_block09_output [19;23;18;8;12]).
  - exact (c12_k7_low3_mask04_block09_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask04_block10_output [17;14;22;7;24] : cnf)
  as imported_from_block10.
assert (Himported_from_block10 :
  satisfies_cnf rho imported_from_block10).
{
  unfold imported_from_block10.
  apply (satisfies_cnf_select rho c12_k7_low3_mask04_block10_output [17;14;22;7;24]).
  - exact (c12_k7_low3_mask04_block10_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (select_cnf c12_k7_low3_mask04_block11_output [24;17;12;16;23;11;20;22;2] : cnf)
  as imported_from_block11.
assert (Himported_from_block11 :
  satisfies_cnf rho imported_from_block11).
{
  unfold imported_from_block11.
  apply (satisfies_cnf_select rho c12_k7_low3_mask04_block11_output [24;17;12;16;23;11;20;22;2]).
  - exact (c12_k7_low3_mask04_block11_sound rho Hbase).
  - vm_compute. reflexivity.
}
pose (concat [imported_from_block00;imported_from_block01;imported_from_block02;imported_from_block03;imported_from_block04;imported_from_block05;imported_from_block06;imported_from_block07;imported_from_block08;imported_from_block09;imported_from_block10;imported_from_block11] : cnf) as imported.
assert (Himported : satisfies_cnf rho imported).
{
  unfold imported.
  apply satisfies_cnf_concat_intro.
  constructor.
  { exact Himported_from_block00. }
  constructor.
  { exact Himported_from_block01. }
  constructor.
  { exact Himported_from_block02. }
  constructor.
  { exact Himported_from_block03. }
  constructor.
  { exact Himported_from_block04. }
  constructor.
  { exact Himported_from_block05. }
  constructor.
  { exact Himported_from_block06. }
  constructor.
  { exact Himported_from_block07. }
  constructor.
  { exact Himported_from_block08. }
  constructor.
  { exact Himported_from_block09. }
  constructor.
  { exact Himported_from_block10. }
  constructor.
  { exact Himported_from_block11. }
  constructor.
}
pose (
  [66;67;68;69;70;71;72;73;74;75;76;77;1276;1277;1273;1199;1264;1234;4155;4152;4158;28;1053;29;1054;26;1051;1127;1;1055;24;1049;1125;2548;22;1047;2546;3268;3271;3270;3206;3265;3261;2211;2213;2206;2212;2214;4;48;4153;2531;57;53;2532;8;1167;2526;42;2530;35;2529;3841;3850;3856;3853;3846;37;50;62;55;44;32;1057;1134;274;233;4159;4154;1052;18;1061;1168;2527;1074;1068;1278;1200;1274;1235;1265;1931;1937;1925;1934;1860;1895;1574;1583;1514;1585;1587;1564;4156;47;31;3189;49;1502;1557;1562;1563;1565;3262;3203;3258;3266;3849;3844;3839;3851;3852;3587;3267;2;34;2162;2234;3201;3205;3202;3204;64;1084;2525;1085;46;1071;1150;2545;2550;1288;1210;1245;1284;1286;23;1048;1124;2547;27;1889;3855;3854;3840;3845;1575;1579;1572;1507;1078;2243;2178;2254;2256;2252;1076;1155;1073;1075;1072;1151;14;1560;1597;1594;1601;1599;1525;2622;2611;2556;2615;2620;2618;12;1129;1153;2528;1138;1158;1221;1293;1256;1296;253;219;258;2551;2539;3220;3280;3291;3289;1193;1228;1263;1266;2507;1890;1888;1828;1067;1145;39;1064;1069;43;1146;41;1066;1144;3;1070;1148;3275;3230;3307;3306;2453;3161;1606;1551;1586;1623;1616;2408;2417;2415;2362;1951;1932;1912;1942;1949;1877;36;3589;3584;3591;3580;3525;59;2438;40;3191;20;4157;85;129;127;130;128;131;1063;1080;1086;1083;1171;2540;1882;1845;1876;1879;1870;1133;13;1065;1143;2538;2544;2523;2514;1142;3523;3521;3522;3526;3524;2563;2578;2590;2603;2601;2599;1855;1878;1840;1874;1865;1147;1149;2549;1529;1534;1536;1505;1532;33;1060;1137;1059;1136;106;113;115;112;1081;2537;2517;2508;54;1613;1539] : list nat) as base_ids.
pose ([
  ([61;219;53;274;268;57;282],[0;1;2;3;4;5;6;7;8;9;10;11;324;325;326;327;328;329;330;331;332;333;334;335;338;12;13;14;15;16;17;378;18;19;20;21;22;23;24;25;26;27;28;29;30;31;32;33;346;34;35;36;37;38;39;40;41;42;43;44;45;46;47;48;49]);
  ([201;245;203;219;274;286;270],[0;1;2;3;4;5;6;7;8;9;10;11;324;325;326;327;328;329;330;331;332;333;334;335;338;18;50;356;368;20;37;38;39;40;41;42;49;51;52;53;54;55;56;57;373;58;59;60;61;62;63;64;65;66;340;67;68;69;70;71;72;73;74;363]);
  ([279;274;268;286;270],[0;1;2;3;4;5;6;7;8;9;10;11;324;325;326;327;328;329;330;331;332;333;334;335;338;357;379;18;19;380;381;50;368;75;76;20;77;369;347;348;78;58;59;370;378;387;388;79;80;81;82;83;22;84;85;86;87;88;89;90;23;24;26;27;34;35;30;31;32;33;346;351;358;91;92;93;94;95;96;97;98;99;100;101;102;43;44]);
  ([63;53;274;268;286;270],[0;1;2;3;4;5;6;7;8;9;10;11;324;325;326;327;328;329;330;331;332;333;334;335;338;18;389;19;382;380;381;50;356;368;103;86;87;12;88;89;339;90;378;20;23;24;28;29;26;27;34;35;36;30;31;32;33;346;341;43;45;46;47;44;48;104;105;49;106;68;107;84;108;109;110;111;102;112;113;114;115;116;117;118;63;119;120;121;122;388;123;124;72;125;60]);
  ([83;127;270;274;123;286],[0;1;2;3;4;5;6;7;8;9;10;11;324;325;326;327;328;329;330;331;332;333;334;335;338;342;50;356;368;18;72;73;74;363;20;126;43;45;343;127;46]);
  ([199;123;201;203;274;286;270],[0;1;2;3;4;5;6;7;8;9;10;11;324;325;326;327;328;329;330;331;332;333;334;335;338;18;50;356;368;20;128;40;129;130;114;131;60;61;132;133;134;347;52;58;59;49;51;53;342;391]);
  ([198;201;203;274;286;270],[0;1;2;3;4;5;6;7;8;9;10;11;324;325;326;327;328;329;330;331;332;333;334;335;338;55;18;50;356;368;20;135;56;57;349;373;388;383;62;63;64;65;66;58;59;132]);
  ([201;203;274;286;270],[0;1;2;3;4;5;6;7;8;9;10;11;324;325;326;327;328;329;330;331;332;333;334;335;338;393;18;50;356;368;392;128;40;129;130;114;131;20;136;137;138;139;140;54]);
  ([122;200;268;286;270],[0;1;2;3;4;5;6;7;8;9;10;11;324;325;326;327;328;329;330;331;332;333;334;335;338;136;139;140;80;81;22;19;382;380;381;33;50;356;368;374;90;141;142;143;144;145;20;54;345;82;83;146;147;148;149;24;29;35;36;26;27;150;79;58;151;152;65;153;154;155;117;156;157;158;159;97]);
  ([200;274;268;286;270],[0;1;2;3;4;5;6;7;8;9;10;11;324;325;326;327;328;329;330;331;332;333;334;335;338;80;81;22;395;18;84;389;390;19;382;380;381;50;356;368;350;103;160;146;147;148;149;20;82;83;161;162;163;164;165;44;105;48;166;167;49;168;68;169;104;170;171;172;73;31;173;174;175;176;177;178;351;117;118;119;120;121;341;179;180;181;182;183;184;141;142;143;144;145;185;35]);
  ([274;268;286;270],[0;1;2;3;4;5;6;7;8;9;10;11;324;325;326;327;328;329;330;331;332;333;334;335;338;18;389;396;19;382;380;381;50;356;368;103;394;20;150;186;378;187;350;188;189;190;191;192;145;193;194;146;147;148;149;136;139;140;137;138;33]);
  ([122;268;286;270],[0;1;2;3;4;5;6;7;8;9;10;11;324;325;326;327;328;329;330;331;332;333;334;335;338;136;139;140;395;33;19;382;380;381;397;50;356;368;374;195;196;197;20;54;345;103;78;198;375;77;347;199;200;201;202;58;59;371;152;65;153;154;155;117;203;39;55;57]);
  ([53;55;201;278;268;219;57;282],[0;1;2;3;4;5;6;7;8;9;10;11;324;325;326;327;328;329;330;331;332;333;334;335;338;90;378;372;204;16;205;206;207;376;374;103;19;38;40;41;42;20;21;39;37;28;29;79;34;35;36;26;24;52;208;55;57;58;60;53;54;49;51;341;179;180;181;182;183]);
  ([52;201;219;272;268;282],[0;1;2;3;4;5;6;7;8;9;10;11;324;325;326;327;328;329;330;331;332;333;334;335;338;146;147;148;149;370;371;364;78;19;20;352;209;210;211;58;212;213;214;215;198;71;216;217;218;219;220;221;222;223;224;225;226;227;228;41]);
  ([201;268;286;270],[0;1;2;3;4;5;6;7;8;9;10;11;324;325;326;327;328;329;330;331;332;333;334;335;338;19;380;397;398;382;381;50;356;368;195;196;197;20;103;78;77;347;400;378;399;39;37;38;40;41;42;377;30;31;32;229;53;49;51;52;208;55;56;57;373;58;59;60;62;63;64;65;66;230;67;68;69;70;71;353;231;232;233;234;235;236;237;238;239;240;241;242;243;244;245;246;105]);
  ([53;245;268;286;270],[0;1;2;3;4;5;6;7;8;9;10;11;324;325;326;327;328;329;330;331;332;333;334;335;338;19;401;380;397;398;382;381;50;356;368;80;81;22;82;83;195;196;197;378;20;90;86;87;12;88;89;339;103;160;78;85;77;347;30;31;32;23;24;26;27;34;35;36;341;179;180;181;182;184;183;97;98;99;101;102;100;247;248;249;250;251;122;252;253;384;254;52;255;72;125;124;67]);
  ([52;107;272;268],[0;1;2;3;4;5;6;7;8;9;10;11;324;325;326;327;328;329;330;331;332;333;334;335;338;146;147;148;149;370;371;364;78;19;352;209]);
  ([268;286;270],[0;1;2;3;4;5;6;7;8;9;10;11;324;325;326;327;328;329;330;331;332;333;334;335;338;19;380;397;398;382;381;401;50;356;368;195;196;197;80;81;22;82;83;20;103;160;78;85;77;347;403;402;378;90;86;87;12;88;89;339;256;29]);
  ([104;280;177;284;272],[0;1;2;3;4;5;6;7;8;9;10;11;324;325;326;327;328;329;330;331;332;333;334;335;338;58;212;213;257;336]);
  ([275;272;107;244;269;225],[0;1;2;3;4;5;6;7;8;9;10;11;324;325;326;327;328;329;330;331;332;333;334;335;338;78;256;223;258;259;260;261;262;263;50;264;20;135;103;385;265;77;347;266;257;344;267;405;268;269;270;95;271;272;273;274;71;216;34;275;276;254;277;278;279;280;281;282;51;219;220;221;214;215;283;198;365;284]);
  ([284;280;272;107;223;244;225],[0;1;2;3;4;5;6;7;8;9;10;11;324;325;326;327;328;329;330;331;332;333;334;335;338;77;266;257;267;405;78;284;285;286;251;287;288;256;366;223;270;95;271;272;273;274;107;279]);
  ([100;278;173;155],[0;1;2;3;4;5;6;7;8;9;10;11;324;325;326;327;328;329;330;331;332;333;334;335;338;254;282;103;289;290;291;292;293;294]);
  ([101;274;111;272;89;107;282],[0;1;2;3;4;5;6;7;8;9;10;11;324;325;326;327;328;329;330;331;332;333;334;335;338;295;272;296;297;298;299;18;78;20;34;58;212;213;71;216;300;276;301;219;220;221;214;215;283;198;337]);
  ([272;200;244;269;270],[0;1;2;3;4;5;6;7;8;9;10;11;324;325;326;327;328;329;330;331;332;333;334;335;338;78;85;80;81;256;223;50;356;368;264;406;20;82;83;135;18;166;409;84;254;277;278;51;302;354;178;303;304;305;306;307;72;73;74;140;363;308;59;60;309;310;67;185;125;311;312;359;44]);
  ([200;244;286;270],[0;1;2;3;4;5;6;7;8;9;10;11;324;325;326;327;328;329;330;331;332;333;334;335;338;80;81;256;404;268;269;50;356;368;264;410;20;135;313;314;315;316;18;166;84;257;267;317;77;266;355;284;285;286;251;287;288;347;348;103;265;160;360;385;279;217;318;319;361;320;321;199;386;58;362;367;97;322;323])
] : list (list nat * list nat)) as records.
assert (Hcheck :
  check_selected_microblock (c12_k7_low3_instance [true; true; false; false; false; false; true; false; false; false; false; false]) base_ids
    imported records c12_k7_low3_mask04_block12_output = true).
{ vm_compute. reflexivity. }
exact (check_selected_microblock_sound
  (c12_k7_low3_instance [true; true; false; false; false; false; true; false; false; false; false; false]) base_ids imported records c12_k7_low3_mask04_block12_output
  Hcheck rho Hbase Himported).
Qed.
